### ISSUE TITLE
Calendar: Typing incorrect for SohoCalendarOptions - dayLegend

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise-ng#1001]
**Describe the bug**
dayLegend on SohoCalendarOptions  should be an optional array instead of just an object.

Array<SohoDatePickerLegend>

**Comment by tmcconechy** [comment]
Right now its this
```
  dayLegend?: SohoDatePickerLegend;
```

Actually SohoDatePickerLegend is undefined... Think we should maybe make it an array of a specific objects...

```
        dayLegend: [
          { name: 'Public Holiday', color: 'emerald02', dates: ['7/7/2020', '7/8/2020']} ,
          { name: 'Other', color: 'amethyst02', dates: ['7/22/2020', '7/23/2020'] }
        ]
```

**Comment by marknolaninfor** [comment]
@tmcconechy 

This is based on the datePickers legend with the typing of

` legend?: Array<SohoDatePickerLegend>;`

compared to the calendar with 

`dayLegend?: SohoDatePickerLegend;`

It is coded to accept an array, but with strict typing only the following can be set and will error

`dayLegend: { name: 'Public Holiday', color: 'emerald02', dates: ['7/7/2020', '7/8/2020']}`

**Comment by tmcconechy** [comment]
looks good @marknolaninfor  ? https://github.com/infor-design/enterprise-ng/pull/1004
