### ISSUE TITLE
Datagrid: Unable to copy a data value from Excel and paste into editable cell

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#1002]
Describe the bug:
Unable to copy a cell in Excel and paste the copied value into an editable datagrid cell.

1. Go to 'DataGrid - Angular Editors'
2. Open Excel and enter a numeric value into a cell
3. Copy the cell value from Excel
4. Attempt to paste into a cell in the Quantity column

Expected behavior
Be able to cut and paste into an editable cell

Version
- ids-enterprise: v4.38.0-dev

**Comment by claudenbach** [comment]
![GitNT-1002](https://user-images.githubusercontent.com/39804038/109980936-0d185780-7cc6-11eb-8154-b18b2fd3b199.gif)

**Comment by tmcconechy** [comment]
This seems to work in EP https://drive.google.com/file/d/15SZNyVvBMrfwxjbeTIYQ7uQFztzaYL3r/view
Is this maybe an angular only issue?

**Comment by claudenbach** [comment]
I have a similar issue, were the user is attempting to copy bulleted items with a .pdf file and they are unable to paste the copied value into a list cell.   This did work in 3.5.

Do you need a different ticket for this issue?

**Comment by tmcconechy** [comment]
@claudenbach no thats ok. I think its going to be the same issue - the issue is around this area https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L6266 where it tries to detect new lines in the data and create/copy the data to neighbouring cells. I'm not sure what the fix would be....

**Comment by claudenbach** [comment]
This is the Landmark example:

**Comment by claudenbach** [comment]
Landmark example in 3.5:

![LMCLIENT-34572-3 5](https://user-images.githubusercontent.com/39804038/112179969-21ff5100-8bc9-11eb-99b8-bd2029c46cbd.gif)

**Comment by tmcconechy** [comment]
Did paste from excel to create rows work in 3.5?

**Comment by claudenbach** [comment]
Yes.

**Comment by tmcconechy** [comment]
This was fixed in https://github.com/infor-design/enterprise/pull/5071

**Comment by janahintal** [comment]
The issue still exists in https://main-enterprise.demo.design.infor.com/components/datagrid/test-copy-paste-from-excel.html

**Comment by tmcconechy** [comment]
@janahintal that is covered by https://github.com/infor-design/enterprise/issues/5072 as we made this a setting but that half wasnt important so we left it. For this just test on  https://main-enterprise.demo.design.infor.com/components/datagrid/example-index

And we will fix that setting "on" at a later date.

**Comment by janahintal** [comment]
Noted on this. As per checking, https://main-enterprise.demo.design.infor.com/components/datagrid/example-index is working as expected. 

Also tried it in https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html and I was now able to copy and paste form excel.
