### ISSUE TITLE
Multi-select: test id prefix missing after search with reload typeahead

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise-ng#1005]
**Describe the bug**
The custom id attributes specified via the attributes option are missing after a search occurs on a multiselect

**To Reproduce**
1. Unzip [test-id-from-attr.zip](https://github.com/infor-design/enterprise-ng/files/6093792/test-id-from-attr.zip) into 'app/view/components/multiselect'
2. Navigate to 'components/multiselect/test-id-from-attr.html'
3. Open the Towns field, then press F12 and find the first option in the dom. It should have an id of "towns-option-0" on it's a
4. Search for "wr" in the field, then press F12 and find the first option in the dom. It will not have a id which includes "towns"

**Expected behavior**
Ids should be on the anchors after the search. Without the correct id on the value, we can not easily find the option to click in automated tests

**Version**
- ids-enterprise-ng: v4.38.0-dev

**Screenshots**
Before search:
![image](https://user-images.githubusercontent.com/22107636/110180887-44732b00-7dd0-11eb-928e-ec722e6c0226.png)

After Search:
![image](https://user-images.githubusercontent.com/22107636/110180988-75536000-7dd0-11eb-9435-7bbebfeffee8.png)

**Platform**
 - All

**Additional context**

**Comment by ericangeles** [comment]
Looks like this is related on this issue https://github.com/infor-design/enterprise/issues/5053 and the fix is here https://github.com/infor-design/enterprise/pull/5213

Maybe need a test page in NG to make sure it also works? @tjamesallen15 @tmcconechy

**Comment by janahintal** [comment]
QA Passed. Thank you. 
Working as expected. 
![image](https://user-images.githubusercontent.com/45757016/123646292-a95c0080-d859-11eb-99f6-a21f7793b39c.png)
