### ISSUE TITLE
Datagrid and popup menu: when opening a context menu via keyboard, the beforeopen event is not getting triggered

### ISSUE THREAD

**Issue by JBismonte** [infor-design/enterprise-ng#1021]
**Describe the bug**
Datagrid and popup menu: when opening a context menu via keyboard, the beforeopen event is not getting triggered

**To Reproduce**

1. Go to: http://localhost:4200/ids-enterprise-ng-demo/datagrid-dynamic , also open the browser's dev tools 
2. focus on any cell, then click shift+f10
3. the soho popup menu's beforeopen event is not getting triggered

**Expected behavior**
When you open the context menu, it should trigger the beforeopen function that logs the message: "onBeforeContextMenuOpen()"
**Version**

- enterprise-ng: 9.3.1

**Screenshots**

**Platform**
 - Infor Application/Team Name: Landmark
 - Device: (if applicable): NA
 - OS Version: Windows 10
 - Browser Name: Firefox
 - Browser Version: v85.0

**Additional context**

https://github.com/infor-design/enterprise/issues/4614
https://jira.lawson.com/browse/LMCLIENT-31984

**Comment by tmcconechy** [comment]
I had fixed this yesterday. The example in master will fire the beforeOpen now. It has an example but its commented out because if you don't use the response and return logic it wont open. But you can uncomment and work in the logic 

I didn't have time to update the example to use it but at least it fires now.

**Comment by tmcconechy** [comment]
This is what was added / missing https://github.com/infor-design/enterprise-ng/blob/master/projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.component.ts#L511

In the example if you comment this back in and remove the other you can watch it fire here: https://github.com/infor-design/enterprise-ng/blob/master/src/app/datagrid/datagrid-dynamic.demo.html#L29
