### ISSUE TITLE
Lookup: Disabled attribute added even though it is false

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise-ng#1023]
**Describe the bug**
When you set `[isDisabled]="false"` on the SohoLookupComponent, the attribute `disabled=""` will be added to the input, which will disable it (when it really shouldn't be).

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-931-vhcxbj?file=src/app/lookup-demo/lookup-demo.component.html
2. The `[isDisabled]="false"` is added to the markup
3. See the disabled field.

**Expected behavior**
The field should not be disabled when you pass `false` to `isDisabled`.

**Version**
- ids-enterprise-ng: 9.3.1

**Screenshots**
![Screenshot 2021-04-05 at 12 21 14](https://user-images.githubusercontent.com/73601152/113564297-6e0ab680-9609-11eb-861b-aa2a2d674336.png)

**Platform**
 - OS Version: macOS 10.15.7
 - Browser Name: Chrome
 - Browser Version: 89.0.4389.114 (Official Build) (x86_64)

**Additional context**
Changing the HostBinding on line 352 in soho-lookup.component.ts from to be a getter in some way instead is probably the way to go, e.g.

```typescript
@HostBinding('attr.disabled') get disabledState(): boolean | null {
    return this.isDisabled || null;
}
```

**Comment by tmcconechy** [comment]
i think if the host binding works - that seems to me like the right solution. would you want to try and do a pull request?

**Comment by whernebrink** [comment]
@tmcconechy, I could definitely try to do that when I get some time to, although cannot promise anything for these next two weeks.
