### ISSUE TITLE
Popdown: Does Not close when opening a dropdown

### ISSUE THREAD

**Issue by manel-abbes** [infor-design/enterprise-ng#1026]
**Describe the bug**
Hello, team, I am working with the Soho drop-down and pop-down, when I open the pop-down a list will be displayed, I open in the same time the drop-down list and I select an item. the pop-down still open, it should be collapsed automatically when I select an item from the drop-down I need some help to achieve my work and fix the behavior of the pop-down, it works correctly when I click on input text, button, or checkbox. I cloned this example, and I added the example that I worked on, you can find on [this link]( https://stackblitz.com/edit/ids-quick-start-910-4x8s7v?file=src%2Fapp%2Fapp.component.html)

**To Reproduce**
1.open pop-down list
2. open the drop-down list
3. select an item from the drop-down list 
4. the pop-down still open 

**Expected behavior**
the pop down should be collapsed when I choose an item from the dropdown 

**Version**
- ids-enterprise-ng: [ v7.9.0 ]

**Platform**

 - OS Version: [Windows 10]
 - Browser Name [chrome]
 - Browser Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Yes it maybe should close when opening dropdowns. One workaround you could attempt is to 

- use the `listopened `event of the dropdown
- call `destroy` or `close` the popdown

**Comment by manel-abbes** [comment]
Hey, I use many dropdown lists on my screen, so when l apply the event for each dropdown,  that will affect on optimization of the code.

**Comment by tmcconechy** [comment]
Ok, But it might work if you need an immediate fix.
