### ISSUE TITLE
SohoStandalonePager: Event Typings Missing

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#1028]
**Describe the bug**

The `SohoStandalonePagerComponent` does not expose typings for the exposed events, e.g:

```typescript
@Output() firstPage: EventEmitter<Object> = new EventEmitter<Object>();
@Output() lastPage: EventEmitter<Object> = new EventEmitter<Object>();
@Output() previousPage: EventEmitter<Object> = new EventEmitter<Object>();
@Output() nextPage: EventEmitter<Object> = new EventEmitter<Object>();
@Output() pageSizeChange: EventEmitter<Object> = new EventEmitter<Object>();
```

**To Reproduce**

Create component with the following:

```html
<div soho-standalone-pager  (pageSizeChange)="onPageSizeChange($event)"></div>
```

```typescript
class MyComponent {
  ...
  onPageSizeChange(args: object[]) {
    this.store.dispatch(new AuditSetPageSize(args[1].pagesize));
  }
  ...
}
```

This causes compilation failures when using the strict compiler (an eslint) where any is not allowed.

**Expected behavior**

The standalone pager should defined concrete typings for the events.

**Version**
- ids-enterprise-ng: v9.4.0

**Screenshots**

![image](https://user-images.githubusercontent.com/8340092/114212390-b0a9f700-9959-11eb-941c-4290a24a1181.png)

**Platform**

N/A

**Additional context**

None

**Comment by bthharper** [comment]
I'll try to get around to defining these, but if someone else gets in first even better!

**Comment by tjamesallen15** [comment]
Hello @tmcconechy ,

Upon checking, the typings for the exposed events are already there and it's working. I didn't change anything.

Thanks!
James

**Comment by tmcconechy** [comment]
Yes i see them here https://github.com/infor-design/enterprise-ng/blob/main/projects/ids-enterprise-ng/src/lib/pager/soho-standalone-pager.component.ts#L135-L139

I guess they have been added since this issue was reported? @bthharper ?
