### ISSUE TITLE
SohoDataGrid: SohoDataGridOptions missing treeDepth property

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#1029]
**Describe the bug**

The typings for the datagrid option (SohoDataGridOptions) is missing the `treeDepth` property.

This requires the use of any in the code, which violates the eslint rules.

**To Reproduce**

```typescript
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const settings = api.settings as any;
  const depth = settings.treeDepth && settings.treeDepth && settings.treeDepth[row]
    ? settings.treeDepth[row].depth
    : 0;
```

**Expected behavior**

```typescript
  const settings = api.settings;
  const depth = settings.treeDepth && settings.treeDepth && settings.treeDepth[row]
    ? settings.treeDepth[row].depth
    : 0;
```

**Version**
- ids-enterprise-ng: v9.4.0

**Screenshots**

N/A

**Platform**

All

**Additional context**

**Comment by tmcconechy** [comment]
Would be a great issue for a PR 👍🏻
