### ISSUE TITLE
Soho Chart Component runs script on ellipsis mode

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-ng#1030]
**Describe the bug**
Soho chart runs the onerror script on ellipsis mode

**To Reproduce**
1. Open enterprise-ng
2. Change a data item name in chart-demo.service.ts to '"><img src=x onerror=prompt(1)>'
![image](https://user-images.githubusercontent.com/53523076/114345057-95c2c700-9b93-11eb-9456-5518a08b9119.png)
3. Compile and open page
4. Go to http://localhost:4200/ids-enterprise-ng-demo/chart
5. Minimize the window to enable ellipsis on name
![image](https://user-images.githubusercontent.com/53523076/114345029-88a5d800-9b93-11eb-9fa3-2e195312b72e.png)

**Expected behavior**
Script should not execute

**Version**
- ids-enterprise-ng: 4.50

**Screenshots**
See above

**Platform**
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name Chrome
 - Browser Version 89.0.4389.114 

**Additional context**

**Comment by tmcconechy** [comment]
This could be an enterprise issue - will have to try and make an example in the core EP components - but we are trying to prevent this thing so adding this with priority to backlog

**Comment by jbrcna** [comment]
QA Passed
v4.52.0-beta0
https://4520-beta0-enterprise.demo.design.infor.com/components/bar-grouped/test-execute-script.html
![image](https://user-images.githubusercontent.com/56722184/120606380-b6b3e400-c481-11eb-8d60-7b70ce7736c0.png)
