### ISSUE TITLE
SohoDataGrid: activePage type in SohoDataGridSettingsChangedEvent has wrong type

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#1031]
**Describe the bug**

The type of `activePage` at https://github.com/infor-design/enterprise-ng/blob/28476ce4d4268fcaa92d5271797f074e1ad9c515/projects/ids-enterprise-typings/lib/datagrid/soho-datagrid.d.ts#L1372 is wrong, it should be number like https://github.com/infor-design/enterprise-ng/blob/28476ce4d4268fcaa92d5271797f074e1ad9c515/projects/ids-enterprise-typings/lib/pager/soho-pager.d.ts#L131

**To Reproduce**
1. Go to datagrid example of the example app in this repository
2. Listen to `settingsChanged` event and add `console.log('activePage type', typof event.activePage)` and observe that the console will say it is number while type definition says string

**Expected behavior**

The type should be `number`

**Version**
- ids-enterprise-ng: latest

**Screenshots**

**N.A.**

**Platform**

**N.A.**

**Additional context**

**N.A.**

**Comment by tmcconechy** [comment]
This would be a good one for a PR 👍🏻  But perhaps we can make it `activePage?: number|string;` so it doesnt break.

**Comment by tmcconechy** [comment]
Wasnt a breaking change to fix 👍🏻

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
