### ISSUE TITLE
SohoDataGrid: expose `updateDataset` API

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#1032]
**Is your feature request related to a problem? Please describe.**

Comparing between https://github.com/infor-design/enterprise-ng/blob/28476ce4d4268fcaa92d5271797f074e1ad9c515/projects/ids-enterprise-typings/lib/datagrid/soho-datagrid.d.ts#L1002 vs https://github.com/infor-design/enterprise-ng/blob/28476ce4d4268fcaa92d5271797f074e1ad9c515/projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.component.ts#L143 , `updateDataset` API is not exposed for `SohoDatagridComponent`, hence it is not possible to get IDE suggestion to use it.

**Describe the solution you'd like**

Expose `updateDataset` API for `SohoDatagridComponent` in `ids-enterprise-ng`.

**Describe alternatives you've considered**

I don't know any workarounds

**Additional context**

I'm not sure if any other APIs are missing for `SohoDatagridComponent` or not but perhaps all APIs should be checked to see if anything is missing.

**Comment by tmcconechy** [comment]
Ok i see what you mean in the thread now. I think the person that setup SohoDatagrid just called it data.

https://github.com/infor-design/enterprise-ng/blob/28476ce4d4268fcaa92d5271797f074e1ad9c515/projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.component.ts#L961

So you can use it there. Wonder if there is value in exposing the other one too so its a one to one mapping.

**Comment by ahnpnl** [comment]
I find it quite convenient to have 1-1 mapping from design.infor.com to ng wrapper. That makes it easier to use :) I myself often doing that way, first going to design.infor.com to find the API I need and then i look into the ng wrapper to find, straight forward.

**Comment by tmcconechy** [comment]
Agreed - if you wanted to PR it i'd accept it - otherwise will get to this when i can
