### ISSUE TITLE
Autocomplete: Attributes are not added correctly in ng

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise-ng#1035]
**Describe the bug**
In https://main-enterprise.demo.design.infor.com/components/autocomplete/example-index.html I can see that the data-automation-id is applied both to the field and to the results. But with the components I cannot get the data attribute to be added to the results. The attributes are only added to the input field as attributes="[object Object]" 

**To Reproduce**
1. Go to http://localhost:4200/ids-enterprise-ng-demo/autocomplete
2. Open Dev tools
3. In dev tools Elements locate the first autocomplete field
4. Notice that "[attr.data-autocomplete]="url"" that is in the html is not available.
5. Update the html by adding [attr.attributes]="[{name: 'data-automation', value: 'my-custom-1'}]" to the first auto [complete] so that the full file is 
 `<div class="row top-padding">
  <div class="twelve columns">
    <div class="field">
      <label for="autocomplete-default">Set source as string, update from cities to states</label>
      <input id="autocomplete-default" soho-autocomplete soho-mask [sohoPattern]="'********************'" [attr.attributes]="[{name: 'data-automation', value: 'my-custom-1'}]" [attr.data-autocomplete]="url" type="text"  (selected)="onSelected($event)">
    </div>
    <div class="field">
      <label for="autocomplete-source">Set source as a function</label>
      <input id="autocomplete-source" soho-autocomplete [source]="source" [autoSelectFirstItem]="true" type="text">
    </div>
      <div class="field">
      <label for="autocomplete-filtermode">Set filterMode as contains</label>
      <input id="autocomplete-filtermode" soho-autocomplete [source]="statesUrl" filterMode="contains" type="text">
    </div>
    <div class="field">
      <label for="autocomplete-selected-event">Selected event fires</label>
      <input id="autocomplete-selected-event" soho-autocomplete [source]="statesUrl" filterMode="contains" (selected)="onSelected($event)" type="text">
    </div>
    <div class="field">
      <label soho-label>Model: {{selected}}</label>
      <input soho-autocomplete [source]="xssSource" filterMode="contains" [(ngModel)]="selected" placeholder="Search for <script">
    </div>
  </div>
</div>`
6. in http://localhost:4200/ids-enterprise-ng-demo/autocomplete notice that the attributes are only added as 
attributes="[object Object]"
7. Search for 'A'
8. Inspect the Alaska item
9. Notice that the data-automation attribute is not available

**Expected behavior**
6. The attribute is added as data-automation="my-custom-1"
9. The data-automation="my-custom-1-list-option1" should be available on the first result option

**Version**
- ids-enterprise-ng: 9.3.1

**Screenshots**
In IDS-enterprise it works:
![image](https://user-images.githubusercontent.com/8664975/116758985-8c4db180-aa11-11eb-8a88-82b9a3178d95.png)

not in IDS-enterprise-ng:
![image](https://user-images.githubusercontent.com/8664975/116759084-c61eb800-aa11-11eb-8fd4-8a4dd418ece7.png)

![image](https://user-images.githubusercontent.com/8664975/116759110-ddf63c00-aa11-11eb-97d9-b4d46ceb7fc4.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 90.0.4430.93 (Official Build) (64-bit)

**Additional context**

**Comment by SofiK** [comment]
I noticed that for Lookup this was fixed if I changed [attr.attributes] to [attributes], but I cannot do that for autocomplete cause [attributes] isn't allowed there. So maybe it should just be added to the component?

**Comment by SofiK** [comment]
It also seems that it has to be added as an array. [attributes]="[{ name: 'data-automation-id', value: 'value' }]" works but not [attributes]="{ name: 'data-automation-id', value: 'value' }"

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
