### ISSUE TITLE
Card: Add component and include expandable cards

### ISSUE THREAD

**Issue by anton-kurilov** [infor-design/enterprise-ng#1036]
**Is your feature request related to a problem? Please describe.**
The ids card component does not expand out of the box for enterprise-ng.

**Describe the solution you'd like**
Provide card expansion out of the box, and a card angular component.

**Describe alternatives you've considered**
We have implemented our own card expansion in our angular component but still using the card styling

**Additional context**
As per @tmcconechy 

"The idea around card is its mostly markup so we figured we never need a wrapper. What happens if you just directly use the markup in an angular app https://github.com/infor-design/enterprise/blob/master/app/views/components/cards/example-expandable.html#L13
 
The problem with this example i think is that this integrates with the expandable area component. So i think you maybe uncovered a case where we might have to create a card wrapper with an expandable option. Its a bit of work i think to do that."

**Comment by LilBiggs** [comment]
**Platform**

Infor Application/Team Name: **Infor WFM**

**Comment by tmcconechy** [comment]
@ericangeles found this issue and noted that you were working on this already

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
