### ISSUE TITLE
SohoBusyIndicatorDirective - Options property should be public

### ISSUE THREAD

**Issue by LucasLund** [infor-design/enterprise-ng#1038]
**Is your feature request related to a problem? Please describe.**
SohoBusyIndicatorDirective's property "options" are private.

**Describe the solution you'd like**
I feel like SohoBusyIndicatorDirective's options property should be public, as it allows you to fill out attributes on the component and get a specific one dependent on f.x. ID. 

This is extremely useful when you have more than 1 busy indicator on the same page and want to activate them depending on the value in their attributes.
You can currently access a SohoBusyIndicatorDirective's "attributes" via SohoBusyIndicatorDirective.attributes, but this is always "undefined" when the attributes are specified in the HTML.

**Describe alternatives you've considered**
Only other alternative I see is getting the busy indicators based on index, but this doesn't seem "safe" or at least not super developer-friendly, as this could be changed in the future, and a lot of indexes would have to be switched around.

For a code example, this is what I'm attempting to do:
```HTML
<form soho-busyindicator [attributes]="{ id: 'purchaseOrderDataForm' }" value="test" [displayDelay]="0" [formGroup]="purchaseOrderDataForm">
```

```Typescript
@ViewChildren(SohoBusyIndicatorDirective) busyIndicators: QueryList<SohoBusyIndicatorDirective>;

this.busyIndicators.forEach(item => {
    console.log(item.options.attributes.id);
});
```

**Comment by LucasLund** [comment]
I don't see how option C would be possible, as the ID wouldn't reflect on the SohoBusyIndicatorDirective.
In terms of A) You are able to put options on it, the issue comes when reading them from the component.ts file.

A use case could be having multiple busy indicators on the same page (in my case, multiple data grids), and having to activate / deactivate them depending on when data gets returned from API's.
Currently I have one busy indicator filling the whole component, but I'd like to make it more user friendly with having UI elements responsive as soon as possible.

**Comment by tmcconechy** [comment]
I mean the id could be on the "parent" and you could drill in to what you want there. BUt other than that I'm not picture what a fix might look like.

Would you want to propose a PR to fix this?
