### ISSUE TITLE
Angular 12 

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#1040]
**Is your feature request related to a problem? Please describe.**

Support for Angular 12. 

**Describe the solution you'd like**

Either upgrade the component library to use version 12 or allow a version tolerance in the peer dependencies.

**Describe alternatives you've considered**

N/A

**Additional context**

See [Announcement](https://blog.angular.io/angular-v12-is-now-available-32ed51fbfd49)

Other useful links:

* https://update.angular.io/?l=2&v=11.0-12.0..
* https://github.com/angular/angular/blob/master/CHANGELOG.md

**Comment by tmcconechy** [comment]
@bthharper is this something you plan to look at or should we consider it for our backlog

**Comment by tmcconechy** [comment]
Seeing this...

```
tmcconechy@usmvtmcconechy enterprise-ng % ng update @angular/core@12 @angular/cli@12
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 70 dependencies.
Fetching dependency metadata from registry...
                  Package "@angular-eslint/builder" has an incompatible peer dependency to "@angular/cli" (requires ">= 11.2.0 < 12.0.0", would install "12.0.0").
✖ Migration failed: Incompatible peer dependencies found.
```

Is this something on our end or is it "not ready"

**Comment by bthharper** [comment]
@tmcconechy  - when I get a minute I will try, surprised this is not upgraded.

**Comment by tmcconechy** [comment]
Got it working with force for now https://github.com/infor-design/enterprise-ng/pull/1041
