### ISSUE TITLE
Datepicker: Attributes aren't added correctly to datepicker in ng

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise-ng#1044]
**Describe the bug**
A clear and concise description of what the bug is. in https://main-enterprise.demo.design.infor.com/components/datepicker/example-index.html we can see that there are a data-automation-id in the datepicker that is also used in the modal (for some reason not in the datepicker button thoug, but that's probably a bug)
But when I try to add the same attribute to a datepicker in enterprise-ng nothing happens.

**To Reproduce**
1. Go to http://localhost:4200/ids-enterprise-ng-demo/datepicker
2. In the src\app\datepicker change the first  Standard Date input to 
`<input soho-datepicker id="standard" name="standard" dateFormat="MM/dd/yyyy" mode="standard" placeholder="MM/dd/yyyy" [(ngModel)]="model.standard" (change)="onChange($event)" [attributes]="[{ name: 'data-automation-id', value: 'my-custom-dp1' }]"/>`
3. Reload the page from step 1
4. use the inspector to locate the Standard Date date picker element in dev tools.
5. Notice that the 'data-automation-id' attribute is **not** available on the datepicker.
6. Click the datepicker button (note that it also does not have the data-automation-id attribute)
7. Notice that the data-automation-id is available in the dialog elements (in ng 9.4.4 not in 9.3.1)!

**Expected behavior**
The datepicker and the datepicker svg shpuld also have the data-automation-id when it has been added as an attribute to the datepicker.

**Version**
- ids-enterprise-ng: 9.4.4

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/118841413-97855600-b8c8-11eb-979b-9701e575e797.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 90.0.4430.212 (Official Build) (64-bit)

**Additional context**
Related issues: 
https://github.com/infor-design/enterprise/issues/5082
https://github.com/infor-design/enterprise-ng/issues/1035

**Comment by tmcconechy** [comment]
Yes i think the id not on the trigger button is a bug - probably from when we changed the triggers to buttons somewhat recently

**Comment by janahintal** [comment]
Working as expected in https://main-enterprise.demo.design.infor.com/components/datepicker/example-index

![image](https://user-images.githubusercontent.com/45757016/120961702-e53b0300-c790-11eb-84a4-01331137874f.png)
![image](https://user-images.githubusercontent.com/45757016/120961789-0bf93980-c791-11eb-83f5-19084d295fd9.png)
