### ISSUE TITLE
CAP: Title not possible to set with modalSettings

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise-ng#1048]
**Describe the bug**
When trying to set the title with `.modalSettings({ title: 'Test'})` it gets the default `Contextual Action Panel` title.
Setting title works for: `.title('Test')` and `.options({ title: 'Test'})`.

_Additionally, `.beforeClose()` is missing from the API (enterprise and ng-enterprise). It would be great if this could be added at the same time._

_Additionally 2, `buttonsetAPI` is also missing. Please add typings, and to enterprise API if it is missing there, which I suspect it is since I get undefined when trying to access that prop:_
```typescript
const ref = dialogRef as any;
console.log('buttonsetAPI', ref.buttonsetAPI);
```
_and verify it is working for CAPs too._

**To Reproduce**
1. https://stackblitz.com/edit/ids-quick-start-950-1rcodi?file=src%2Fapp%2Fapp.component.ts
2. On line 64 in `app.component.ts` the `.modalSettings({ title: 'Test' })` is set.
3. Click the button "Show CAP Dialog" in the UI.
4. See the CAP dialog with "Contextual Action Panel" for title instead of the "Test", which should have been applied. 

**Expected behavior**
The title of the CAP dialog should be the title from the modalSettings.

**Version**
- ids-enterprise-ng: 9.5

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: Mac OSX
 - Browser Name: Firefox
 - Browser Version: 88.0.1

**Additional context**

**Comment by whernebrink** [comment]
@tmcconechy, did you note `Additionally, .beforeClose() is missing from the API (enterprise and ng-enterprise). It would be great if this could be added at the same time.` which I added after discussion in teams, just as a FYI. All of our application configuration will be done with CAP dialog windows, so would be really good to have in the somewhat nearest future.

**Comment by whernebrink** [comment]
Also, types are missing for the `buttonsetAPI` for the CAP dialog, would be nice to have that too (also verify that the buttonsetAPI is present and working on CAP, please). :) 
![Screenshot 2021-06-17 at 16 17 00](https://user-images.githubusercontent.com/73601152/122414459-74ad9680-cf87-11eb-9db4-8fa524d4fd64.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by whernebrink** [comment]
Hey @ericangeles, What about the missing buttonsetAPI that also was missing? :) (See Additionally 2 and the comment quoted comment below) 

> Also, types are missing for the `buttonsetAPI` for the CAP dialog, would be nice to have that too (also verify that the buttonsetAPI is present and working on CAP, please). :)
> ![Screenshot 2021-06-17 at 16 17 00](https://user-images.githubusercontent.com/73601152/122414459-74ad9680-cf87-11eb-9db4-8fa524d4fd64.png)
