### ISSUE TITLE
Lookup: Example request for lookup with autocomplete

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise-ng#1049]
We have the need for a lookup with autocomplete, just like this enterprise example:

https://main-enterprise.demo.design.infor.com/components/lookup/test-autocomplete-and-lookup.html

I'd like to request having that as an example in enterprise-ng too, thanks!

**Comment by tmcconechy** [comment]
The problem here is i dont think you can have two NG components on the same field. Maybe have to introduce a set of settings on lookup so you can invoke an autocomplete. Or make a new directive.

https://main-enterprise.demo.design.infor.com/components/lookup/test-autocomplete-and-lookup.html

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
