### ISSUE TITLE
Datagrid: Using disable/isDisabled on a SohoDataGridColumn does not work

### ISSUE THREAD

**Issue by arturchilangwa-infor** [infor-design/enterprise-ng#1052]
**Describe the bug**
When using `disabled` property on a `SohoDataGirdColumn` with the `editor` set to `Soho.Editor.Input`it is not disabled. 
Also Tim mentioned that `isDisabled` should be working that but does not compile.

**To Reproduce**

1. Make a component that uses SohoDataGrid as a viewchild
2. Use code below

```typescript
const columns: SohoDataGridColumn[] = [];
... 
columns.push({
    width: this.isInput ? "30%" : "50%",
    id: "key",
    name: Soho.Locale.translate("Name"),
    field: "key",
    sortable: false,
    resizable: false,
    editor: Soho.Editors.Input,
    disabled: () => true
    // isDisabled: ... // does not compile
});
```

**Expected behavior**
The column should be disabled and the user should not be able to edit the cell

**Version**
- ids-enterprise-ng: 9.4.4

**Screenshots**

**Platform**

- OS Version: Windows 10 or iOS 8
- Browser Name: Chrome
- Browser Version: 91.0.4472.77

**Comment by tmcconechy** [comment]
@arturchilangwa-infor my mistake i made an error in explaining this. The function is isEditable and it works and is there. Try this please

```
 isEditable: () => { return false },
```
