### ISSUE TITLE
Soho Message :  SohoMessageService returns undefined from message

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#1061]
**Describe the bug**

The `message` method should not return undefined from the message method, otherwise this causes addition checks when the strict compiler is enabled in typescript.

```typescript
message(options?: SohoMessageOptions): SohoMessageRef | undefined {
  return new SohoMessageRef().options(options);
}
```

For example:

```typescript
const buttons: SohoModalButton[] = [];

this.messageService.message()
  .buttons(buttons)
  .open();
```
**To Reproduce**

In a project, e.g. `ids-enterprise-quickstart-ng`, add the above code and enable the strict compiler. 

**Expected behavior**

There should no be need to include/add an `undefined` check.

**Version**
- ids-enterprise-ng: 10.1.0

**Screenshots**

![image](https://user-images.githubusercontent.com/8340092/122921727-c163e980-d35a-11eb-9201-1358ea770239.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
