### ISSUE TITLE
CAP: Add example showing a vertical tab

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#1065]
**Is your feature request related to a problem? Please describe.**
Add an example once https://github.com/infor-design/enterprise/pull/5355 is merged that shows the same in angular.
I.E. an example with a working vertical tabs on a CAP

**Describe the solution you'd like**
Example similar to EP

**Describe alternatives you've considered**
NA - is needed for 

**Additional context**
https://github.com/infor-design/enterprise/pull/5355

**Comment by janahintal** [comment]
QA Passed. Thank you. 

![image](https://user-images.githubusercontent.com/45757016/126482258-0301a7a2-facc-42d4-afee-ac5926c757de.png)
![image](https://user-images.githubusercontent.com/45757016/126482297-a79f4e99-168f-4c2b-ad42-6bd33e04f380.png)
