### ISSUE TITLE
Lookup: When the control is initially disabled, it cannot be properly enabled.

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-ng#1069]
**Describe the bug**
When a `soho-lookup` is initially disabled, for instance with the `[isDisabled]="true"` input, or when calling `setDisabledState(true)` when the host component is initiated, the component cannot be enabled again. The input field looks enabled, but it keeps the `is-disabled` class and the button has the `disabled` attribute forever.

**To Reproduce**
1. Go to https://anhallbe.github.io/ids-repro/lookup-disabled
2. Click on 'Enable'
3. Press the button in the "Initially Disabled" lookup field
4. Nothing happens

Code here: https://github.com/anhallbe/ids-repro/blob/master/src/app/lookup-disabled/lookup-disabled.component.html

**Expected behavior**
The lookup button and field should no longer be disabled.

**Version**
- ids-enterprise-ng: 9.5.0
- ids-enterprise: 4.51.1

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 93

**Additional context**

Issue observed in Homepages widget.

**NOTE:** If possible, we would like a patch for ng@9.5.0 and/or core@4.51.1 since Angular 12 is stopping us from upgrading to the latest version

**Comment by tmcconechy** [comment]
@ericangeles can you or someone in manilla please prioritize this fix to main branch. After will have to patch 4.51

**Comment by ericangeles** [comment]
I can take a look if it's urgent @tmcconechy

**Comment by tmcconechy** [comment]
Yes it is thanks @ericangeles

**Comment by anhallbe** [comment]
Thanks @bthharper @tmcconechy & team!
The fix #1076 appears to have solved our issue.

I created a manual patch for our project (on 9.5.0) with the changes so I don't think we need an upstream patch.

**Comment by tmcconechy** [comment]
Awesome, thanks for the update. I had forgotten about the patch. So glad its resolved

**Comment by janahintal** [comment]
QA Passed. Thanks!
![image](https://user-images.githubusercontent.com/45757016/126639817-dc4b18b2-1635-4393-9ae5-3e17c8c95b6b.png)
![image](https://user-images.githubusercontent.com/45757016/126639965-7debc0d9-2d73-4b61-acc4-c76923e7fbbc.png)
![image](https://user-images.githubusercontent.com/45757016/126639883-c3b37bf5-5c09-4ee1-a780-23fa57427fa5.png)
