### ISSUE TITLE
SOHO-8134 - Release-it places index.d.ts in 'publish' directory not root

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#107]
**Describe the bug**

The npm build package infor-design/enterprise-ng has changed the location of the index.d.ts. It is now in the publish folder and not in the root folder. I believe it should be in the root folder.

From http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html: Also note that if your main declaration file is named index.d.ts and lives at the root of the package

**Comment by tmcconechy** [comment]
@clepore what do you think about this one?

**Comment by clepore** [comment]
The only way to achieve this is if we build it to the root folder when we run the build cmd and add it to the `files: ['publish/', 'index.d.ts']` property.

**Comment by clepore** [comment]
Upon further inspection, we'd probably need to edit the paths inside fo these files so they all correspond to each other. The reason we don't have `index.d.ts` in root, is because it's not actually used in root, but in our `src/` folder.
