### ISSUE TITLE
Using soho-popdown gives a deprecation warning

### ISSUE THREAD

**Issue by ablomq** [infor-design/enterprise-ng#1070]
**Describe the bug**
A deprecation warning is given in the console when using soho-popdown.

**To Reproduce**
1. Run Enterprise-ng demo application
2. Go to Popdown
3. A deprecation warning is given in the console.

**Expected behavior**
Using soho-popdown should not give a deprecation warning in the console. Is there an alternative to soho-popdown, with the same functionality,  that could be used instead?

**Version**
- ids-enterprise-ng: 9.5.0
- ids-enterprise: 4.51.0

**Screenshots**
![image](https://user-images.githubusercontent.com/42343009/124485548-fa657a80-ddac-11eb-93fe-904eaf35eba5.png)

**Comment by tmcconechy** [comment]
Will remove this warning for now. The idea is to use the popover component instead as we have several "pop" components but the angular wrappers example work around the popdown so this is tricky in practice. WIll remove the warning as its safe to use until 5.0 is done.
