### ISSUE TITLE
Tree: Missing "badge" property in SohoTreeNode-type

### ISSUE THREAD

**Issue by kels0** [infor-design/enterprise-ng#1079]
**Describe the bug**
The SohoTreeNode should have the Badge-property in its type but it is not there.

**Expected behavior**
The Badge-property should be there.

**Version**
- ids-enterprise-ng: 10.1.0,

**Comment by tmcconechy** [comment]
Badge type should have this https://github.com/infor-design/enterprise/blob/main/app/views/components/tree/example-badges.html#L63
