### ISSUE TITLE
Soho Splitter: `splitter` property is `undefined`

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#1098]
**Describe the bug**

This line https://github.com/infor-design/enterprise-ng/blob/main/projects/ids-enterprise-ng/src/lib/splitter/soho-splitter.component.ts#L140 is wrong. It makes `splitter` become `undefined`.

**To Reproduce**

1. Add a console log to `soho-splitter.component.ts` as `console.log(this.splitter)`
2. Build the lib and launch the example app
3. Go to splitter demo example
4. Observe that console log print out `undefined`

**Expected behavior**
The value of `this.splitter` should not be `undefined`. It should be the `Splitter` object https://github.com/infor-design/enterprise/blob/main/src/components/splitter/splitter.js#L46

**Version**
- ids-enterprise-ng: latest

**Screenshots**
**N.A.**

**Platform**
 **N.A.**

**Additional context**
**N.A.**

**Comment by ahnpnl** [comment]
would be good if this bug can be patched into **10.2.x** release. I'm using **10.2.1**

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
