### ISSUE TITLE
Soho Splitter: missing input `maxWidth` for splitter settings

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#1100]
**Describe the bug**
Looking at splitter documentation at https://design.infor.com/code/ids-enterprise/latest/splitter, splitter has a property `maxWidth` in settings. This property is not in Angular component which makes it not possible to limit the width of draggable content.

**To Reproduce**
1. Go to https://github.com/infor-design/enterprise-ng/blob/main/projects/ids-enterprise-ng/src/lib/splitter/soho-splitter.component.ts
2. Observe in the file there is no input for `maxWidth`

**Expected behavior**

There should be something like
```
@Input() set maxWidth(maxWidthOption: { left: string | number, right: string | number }) {
    this.options.maxWidth = maxWidthOption;
    if (this.splitter) {
      this.splitter.settings.maxWidth = maxWidthOption;
      this.splitter.updated();
    }
}
```

**Version**
- ids-enterprise-ng: latest

**Screenshots**
**N.A.**

**Platform**
 **N.A.**

**Additional context**
**N.A.**

**Comment by tmcconechy** [comment]
Feel free to PR this is you want @ahnpnl 👍🏻

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
