### ISSUE TITLE
CAP: Add buttonsetAPI to dialog

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise-ng#1101]
**Is your feature request related to a problem? Please describe.**
Missing buttonsetAPI for CAP dialog (should have it just like standard dialog).

**Describe the solution you'd like**
I want the buttonsetAPI to be available for CAP dialog, i.e. added to the enterprise project (don't think it is), and typings added to this enterprise-ng project.

**Additional context**
This issue/feature request was mentioned in #1048 but was not addressed. We need this for new UI of M3 where we heavily rely on the CAP dialog, and need to be able to disable dialog buttons when forms are not valid etc.

We will need these types in Angular as well

**Comment by tmcconechy** [comment]
I dont know how tricky this is going to be as the buttonsetAPI is for the modal and the CAP has a toolbar. So maybe its something else. Will have to look

**Comment by whernebrink** [comment]
@tmcconechy, alright, didn't know that. Basically, I think we just need a way (API) to enable/disable the buttons, users should not be able to press save when a form is invalid etc. Preventing the dialog from closing we can do in the newly added/exposed beforeClose (previously lacking from CAP) I assume.

**Comment by whernebrink** [comment]
If this is to any help, this is what one would have to do today:
<img width="824" alt="image" src="https://user-images.githubusercontent.com/73601152/129893478-6a245268-605d-4ac3-b05b-a1fddb25e2ce.png">

**Comment by tmcconechy** [comment]
That doesn't seem too bad maybe we can just map this to one thing (buttonSetAPI)

**Comment by whernebrink** [comment]
Although, not sure if there can be other elements in the toolbar? Will it always be buttons? Searchfields? Also, if there will be a map to buttonsetAPI, just make sure the name is `buttonsetAPI`, not camelCase. :) 
![image](https://user-images.githubusercontent.com/73601152/129916675-a8cc066d-2ed3-4813-828e-cf378db6166e.png)

**Comment by whernebrink** [comment]
There is an example with dropdown and searchfield, would be nice to know how this is incorporated in the buttonsetAPI etc (how do disable a option in dropdown based on something etc).

![image](https://user-images.githubusercontent.com/73601152/131473548-fa1e6bae-bbd4-4ade-8b0a-d652c5048b2b.png)

**Comment by tmcconechy** [comment]
Its possible without angular (or maybe this is a usable way as well) if you make the toolbar use all HTML like this example https://github.com/infor-design/enterprise/blob/main/app/views/components/contextualactionpanel/test-complex-toolbar.html#L14 and dont use the button setting https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/test-complex-toolbar.html (use flex toolbar instead tho).

There is no way to do it in angular with the button settings. I would make a new feature request and we could add the ability to set the button type to `menubutton` and the ability to reference a `menuID` to use if the other suggestion doesnt work.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
