### ISSUE TITLE
Dropdown: Selecting the first element in a drop down does not populate the selected element.

### ISSUE THREAD

**Issue by petercullen68** [infor-design/enterprise-ng#1102]
**Describe the bug**
We have a drop down with two options, dock and Dock1.  If you select dock, the selected property is not populated.  If you select the second element, the selected property is correctly populated.  Selected the first element again, the property is populated.

**To Reproduce**
1. Add a dropdown
2. Populate with at least two elements.
3. Bind the dropdown to a property for the selected element
4. Select the first element in the dropdown and observe the 

**Expected behavior**
When you select the value in the dropdown the bound property should reflect that.

**Version**
- "ids-enterprise-ng": "^10.3.0" (Did NOT happen in 10.1.0)

**Screenshots**
![Capture1](https://user-images.githubusercontent.com/42790047/128881593-86dc9f71-5c7b-49bb-a9ec-69e7771b4d4e.PNG)
![Capture2](https://user-images.githubusercontent.com/42790047/128881606-bf517b25-1f10-45bc-9e8b-0e13193259f0.PNG)

**Platform**
 - Device: PC
 - OS Version: Windows 10
 - Browser Name: Chrome and Edge
 - Browser Version: Chrome [92.0.4515.131 (Official Build) (64-bit)], Edge [92.0.902.67 (Official build) (64-bit)

**Additional context**
Project showing issue.
[enterprise-ng-quickstart-main.zip](https://github.com/infor-design/enterprise-ng/files/6962305/enterprise-ng-quickstart-main.zip)

**Comment by jbrcna** [comment]
this issue is now resolved.
 v4.56.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/dropdown/test-first-selected-on-list
![image](https://user-images.githubusercontent.com/56722184/134479786-cccd852a-f5fd-4dc9-878b-e42896261010.png)
