### ISSUE TITLE
Searchfield: Add getCategoryData method

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise-ng#1107]
Expose `getCategoryData(onlyReturnSelected)` on the searchfield component.

Enterprise has [method](https://github.com/infor-design/enterprise/blob/6368aa74b9dd876091d7bb09e4c36b8f9a4e9258/src/components/searchfield/searchfield.js#L1587) we'd like to call:

We have tried the `getSelectedCategories()` but that returns jQuery list so a bit cumbersome to use.

**Comment by tmcconechy** [comment]
Feel free to do a PR if we arent able to get to this soon
