### ISSUE TITLE
Searchfield: Add 'cleared' event emitter

### ISSUE THREAD

**Issue by mgdfgodoy** [infor-design/enterprise-ng#1109]
Add `cleared` event for the searchfield component.

Have a cleared event that will trigger when the clear button (x) is clicked or when `clear()` method is called.
This event is currently available on the toolbar flex searchfield but not on the standard searchfield component.

**Comment by tmcconechy** [comment]
thanks @mgdfgodoy - your welcome to do a pull request for it. we encourage contributions like this 👍🏻
