### ISSUE TITLE
Alert: set empty string value for `message` doesn't remove the existing validation message

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#1110]
**Describe the bug**

When using `message` input property of `soho-alert`, if setting `message` with an empty string value, the current validation message doesn't go away.

**To Reproduce**
1. Go to https://github.com/infor-design/enterprise-ng/tree/main/projects/ids-enterprise-ng/src/lib/alert
2. Create a new file `soho-alert-directive.spec.ts`
3. Add this content in
```
import { Component, DebugElement, ViewChild } from '@angular/core';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { By } from '@angular/platform-browser';
import { SohoAlertDirective } from './soho-alert.directive';
import { SohoAlertModule } from './soho-alert.module';

@Component({
  template: `
    <div class="field">
      <input soho-alert [message]="errorMsg">
    </div>
    `
})
class SohoAlertDirectiveTestComponent {
  @ViewChild(SohoAlertDirective) alert?: SohoAlertDirective | null;
  errorMsg = '';
}

describe('Soho Alert Directive Render', () => {
  let alert: SohoAlertDirective;
  let comp: SohoAlertDirectiveTestComponent;
  let fixture: ComponentFixture<SohoAlertDirectiveTestComponent>;
  let de: DebugElement;
  let el: HTMLElement;

  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [SohoAlertDirectiveTestComponent],
      imports: [SohoAlertModule],
    });

    fixture = TestBed.createComponent(SohoAlertDirectiveTestComponent);
    comp = fixture.componentInstance;

    de = fixture.debugElement;
    el = de.query(By.css('input[soho-alert]')).nativeElement;

    fixture.detectChanges();
    alert = (comp.alert as any);
  });

  it('Check splitter element', () => {
    fixture.detectChanges();
    expect((alert as any)._options.message).toEqual('');
    expect(de.query(By.css('.message-text'))).toBeNull();

    comp.errorMsg = 'foo';
    fixture.detectChanges();

    expect((alert as any)._options.message).toEqual('foo');
    expect(de.query(By.css('.message-text')).nativeElement.innerText).toEqual('foo');

    comp.errorMsg = '';
    fixture.detectChanges();

    expect((alert as any)._options.message).toEqual('');
    expect(de.query(By.css('.message-text'))).toBeNull();
  });
});
```
4. Run the tests and observe the error
```
Error: Expected DebugElement__POST_R3__({ nativeNode: <p class="message-text">...</p> }) to be null.
	    at <Jasmine>
	    at UserContext.<anonymous> (projects/ids-enterprise-ng/src/lib/alert/soho-alert-directive.spec.ts:57:47)
	    at ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:372:1)
	    at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:287:1)
```

I encountered this bug in my application but I'm not quite sure so I tried with unit test and unit test failed as expected, similar to what I observed in my application.

**Expected behavior**

The current validation message should be removed when setting `message` with empty string value.

**Version**
- ids-enterprise-ng: latest

**Screenshots**
**N.A.**

**Platform**
 - OS Version: Windows and MacOS
 - Browser Name: all browsers

**Additional context**
**N.A.**

**Comment by tmcconechy** [comment]
The test is nice but i'm wondering if we can test this functionally? Isnt this the same as https://main-enterprise.demo.design.infor.com/components/validation/example-index.html ?

if you try:
http://localhost:4200/ids-enterprise-ng-demo/alert

basically the idea of the alert vs validation is you are manually setting the error message. so i feel like it doesnt relate to whatever the string is. you do that and call removeMessage as needed

**Comment by ahnpnl** [comment]
I actually tested with my application which set the value for `message`. When the value is not empty string, `soho-alert` displays the message correctly, but when it is empty string, the previous error message doesn't go away even though the internal codes call `removeMessage` https://github.com/infor-design/enterprise-ng/blob/main/projects/ids-enterprise-ng/src/lib/alert/soho-alert.directive.ts#L31 

I did debug and I saw my breakpoint hit that line but the message doesn't disappear so I think that is definitely a bug.

Workaround is: I call `removeAllMessage`

**Comment by tmcconechy** [comment]
Ok i wasnt aware that you could set message('') i guess the logic is there so not sure why it wouldnt work https://github.com/infor-design/enterprise-ng/blob/main/projects/ids-enterprise-ng/src/lib/alert/soho-alert.directive.ts#L28 but we can try and take a look. I feel like calling `removeAllMessage` is correct tho.

If you want real validation on value you can use the validation functions. message is just on/off but since the line is there will take a look

**Comment by yohannahbautista** [comment]
Hello! I think I've figured out why message isn't removed. If I add `(alert as any)._options.type = 'error'` (or any of the valid message types) in beforeEach, the tests pass. 

I've tried replicating the empty message in http://localhost:4200/ids-enterprise-ng-demo/alert (adding an additional call in changing the message to "") and removeMessage is called and seems to work fine. If the bug is still there, can I ask for another example so I can try again?

**Comment by ericangeles** [comment]
@ahnpnl any comment about @yohannahbautista findings?

**Comment by ahnpnl** [comment]
If adding `(alert as any)._options.type = 'error'` makes the test pass, I think that should be the fix :)

**Comment by ericangeles** [comment]
@ahnpnl thanks! @yohannahbautista you can proceed now.

**Comment by ahnpnl** [comment]
Hi @yohannahbautista , pls check out this repo https://github.com/ahnpnl/soho-bug-repo/tree/alert-bug (branch `alert-bug`) to see the reproducible issue.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
