### ISSUE TITLE
Flex Toolbar - deprecation warning when setting moreMenuBeforeOpenFunction

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise-ng#1118]
**Describe the bug**
A deprecation warning is seen in the browser console when the moreMenuBeforeOpenFunction is set on a flex toolbar.

**To Reproduce**
1. In the demo app, navigate to T -> Toolbar Flex - More Actions Ajax
2. Open the browser dev tools, look at the console with warnings on
4. See message

**Expected behavior**
The component is updated so we don't see the deprecated message anymore

**Version**
- ids-enterprise-ng: 10.1.1

**Screenshots**
![image](https://user-images.githubusercontent.com/22107636/131167994-088730af-f879-4450-b3e9-d05324c1fc73.png)

**Platform**
 - All

**Additional context**
I think we just need to change the function [moreMenuBeforeOpenFunction](https://github.com/infor-design/enterprise-ng/blob/main/projects/ids-enterprise-ng/src/lib/toolbar-flex/soho-toolbar-flex.component.ts#L293)
 to be using settings.moreMenuSettings.beforeOpen instead of settings.beforeMoreMenuOpen

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
