### ISSUE TITLE
After upgrading from Angular 5 to 6 and install ids-enterprise-ng, app can't start

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#112]
**Describe the bug**
Development server can't start after upgrading a project from Angular 5 to 6 and install `ids-enterprise-ng`

**To Reproduce**
- Generate a project with `@angular/cli` 1.7.4
- Run `yarn global add @angular/cli`
- Run `yarn add @angular/cli`
- Run `ng update @angular/cli`
- Run `ng update @angular/core`
- Run `ng update rxjs`
- Run `yarn add ids-enterprise-ng`
-  In `angular.json` add this to scripts array
`
"./node_modules/jquery/dist/jquery.js",
"./node_modules/ids-enterprise/dist/js/sohoxi.js",
"./node_modules/ids-enterprise/dist/js/cultures/en-US.js",
 "./node_modules/ids-enterprise/dist/js/d3.v4.js"
`
- Add this code to assets array
`
{
     "glob": "**/*",
     "input": "./node_modules/ids-enterprise/dist/css",
     "output": "./assets/ids-enterprise/css"
},
`
- Run `ng serve` and error occurs

**Expected behavior**
A guide to upgrade from `@infor/sohoxi-angular` to `ids-enterprise-ng` together with Angular 5 to 6

**Screenshots**
![image](https://user-images.githubusercontent.com/27772165/41896971-4f687238-7926-11e8-84c4-d9df99512258.png)

**Platform**
 - Device: laptop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 67.0.3396.87 (Official Build) (64-bit)

**Additional context**
**N.A.**

**Comment by ahnpnl** [comment]
**UPDATED**
I managed to start dev server now but we do need a migration guide from `@infor/sohoxi-angular` to `ids-enterprise-ng`

**Comment by tmcconechy** [comment]
All you should have to do is change the references in the pacakge.json. It was only a name and version change. You can take a look at the Quick Start to see it working on a simple project.

https://github.com/infor-design/enterprise-ng-quickstart

The other change from Angular 5 to 6 was previous to the name change. it may help to look at the pull request where we changed the Angular 6 dependencies (Although some if it is newer now).

https://github.com/infor-design/enterprise-ng/pull/11/files

What solved your issue?

**Comment by ahnpnl** [comment]
I think I did some adjustments on `tsconfig.json`, `tsconfig.app.json` and `tsconfig.spec.json` extra to make a successful build. But I think in general you are right, enterprise-ng-quickstart does help.

**Comment by tmcconechy** [comment]
OK, Sounds like you are good here now 👍
