### ISSUE TITLE
Calendar modal is converted to jQuery element and lost Angular context

### ISSUE THREAD

**Issue by edinfor** [infor-design/enterprise-ng#1120]
**Describe the bug**

The angular wrapper passes the angular html to jQuery as a jQuery element and loses angular context, so once the html is generated, we can only use jQuery to manipulate the dom.
https://github.com/infor-design/enterprise-ng/blob/051542659af570393fa0a35dc1d5e914492b8107/projects/ids-enterprise-ng/src/lib/calendar/soho-calendar.component.ts#L611

This is where angular element is converted to jQuery
https://github.com/infor-design/enterprise/blob/main/src/components/calendar/calendar.js#L1390

**To Reproduce**
1. Create any modals in angular calendar component
2. Write any angular *ngIf or angular input that changes dynamically on user actions
3. Modal content doesn't change after angular updates the values
4. Modal content is already converted to jQuery and angular has no control over them.

**Expected behavior**

Angular should continue to have context in the modal and allow us to modify dom.

**Version**
- ids-enterprise-ng: [e.g. v4.9.0 or v4.10.0]
- 
10.4.0-dev.20210831

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Since the underlying component uses jQuery some of the things it returns will be jQuery. Im not sure i can picture anyway to solve this except during the rewrite we are doing to use web components.

Can you work with the jQuery element?
Can you suggest an alternate solution that will work? (thats not a breaking change?)
