### ISSUE TITLE
Datagrid: Expose filterMask for a SohoDataGridColumn

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#1121]
Describe the bug:
The newly created filterMask is not exposed in enterprise-ng.  A better name for filterMask would be filterMaskOptions.

Expected behavior:
Expect to see the following in SohoDataGridColumn...

filterMask?: SohoMaskOptions;

Version:
- ids-enterprise-ng: 10.3.1 (using ids-enterprise 4.54.1)

Additional context:
Landmark will require a patch to 10.3.1

**Comment by tmcconechy** [comment]
As discussed i added the type to main for now but can patch if still requested https://github.com/infor-design/enterprise-ng/commit/2181e91251aa1955e3a25b48b00e98ba8e392cc2

There is two types `mask/filterMask` which is the old string style mask and.
There is two types `maskOptions/filterMaskOptions` which is the new object style mask and.

So please try to use (as any) on filterMaskOptions and if that doesnt work as workaround let me know.
