### ISSUE TITLE
Switching style on soho-button does not retain the styling due to that class "btn-" is appended last in classList

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-ng#1123]
**Describe the bug**
Switching style on soho-button does not retain the styling due to that class "btn-" is appended last in classList

Look in the thumbnails below

Before
![image](https://user-images.githubusercontent.com/542598/132361383-174c7958-e064-47a8-a248-bf2a03ecc2c2.png)

After
![image](https://user-images.githubusercontent.com/542598/132361228-4896f57b-ce9b-44f5-8aed-f7c387d58283.png)

**To Reproduce**
1. Create a button or go to the button page
2. Change `soho-button="primary` to `soho-button="secondary"` 
3. notice the styles didnt work because the btn rule is not first in the class list

**Expected behavior**
Size, and font size should retain.

**Version**
- ids-enterprise-ng: 10.3.1

**Screenshots**
Look thumbnails

**Comment by tmcconechy** [comment]
Just to clarify your changing the `soho-button` property to change the button type right?
https://github.com/infor-design/enterprise-ng/blob/main/src/app/button/button.demo.html#L11

**Comment by guoliang** [comment]
> Just to clarify your changing the `soho-button` property to change the button type right?
> https://github.com/infor-design/enterprise-ng/blob/main/src/app/button/button.demo.html#L11

that's right, it is about using `<button soho-button="<name-of-style>">`

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
