### ISSUE TITLE
About dialog: missing `beforeOpen`/`close`/`afterClose` events

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#1124]
**Describe the bug**

Currently the [SohoAboutRef](https://github.com/infor-design/enterprise-ng/blob/main/projects/ids-enterprise-ng/src/lib/about/soho-about.ref.ts) doesn't have `beforeOpen`/`close`/`afterClose` events while https://design.infor.com/code/ids-enterprise/latest/about mentions there should be.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/about and check **Events** section
2. Go to https://github.com/infor-design/enterprise-ng/blob/main/projects/ids-enterprise-ng/src/lib/about/soho-about.ref.ts and read through the file but cannot find `beforeOpen`/`close`/`afterClose` events

**Expected behavior**
There should be `beforeOpen`/`close`/`afterClose` events, similar to https://github.com/infor-design/enterprise-ng/blob/main/projects/ids-enterprise-ng/src/lib/message/soho-message.ref.ts#L230

**Version**
- ids-enterprise-ng: latest

**Screenshots**
**N.A.**

**Platform**
 - Device (if applicable) **N.A.**
 - OS Version: **N.A.**
 - Browser Name **N.A.**
 - Browser Version **N.A.**

**Additional context**
**N.A.**

**Comment by tmcconechy** [comment]
The events are on the underlying modal. We might need to expose them both in the about component and in the NG wrapper.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
