### ISSUE TITLE
Lookup: Selection is not reflected in dialog when using multiselect and source

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-ng#1132]
**Describe the bug**
When a multiselect-lookup gets its data using the [source] input, the selected items are not "checked" in the lookup dialog.

**To Reproduce**
1. Go to https://anhallbe.github.io/ids-repro/lookup-source
2. Open the "Lookup with dataset"
3. Notice that the correct items are selected in the dialog
4. Open the "Lookup with source"
5. Notice that no items are selected in the dialog

Repro code here: https://github.com/anhallbe/ids-repro/blob/master/src/app/lookup-source/lookup-source.component.html

**Expected behavior**
The "source" lookup should work the same way as the "dataset" lookup.

**Version**
- ids-enterprise-ng: 10.6.2 (also reproducible with 9.5.0)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 96

**Additional context**
https://jira.infor.com/browse/LIME-7085

**Comment by tmcconechy** [comment]
For what it is worth it is working with source here https://main-enterprise.demo.design.infor.com/components/lookup/example-multiselect-paging-serverside.html but i didnt test what happens if the value is initially populated. 

Maybe this helps you debug while you wait for us to check this out.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
