### ISSUE TITLE
Radar Chart Legend "bottom" visually wrong in demo

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#114]
**Describe the bug**
If you have a radar chart with the `legendPlacement` set to "bottom", the example will show a thin strip of white and you will not see the actual legend due to:
```
.widget-content, .card-content {
  height: 318px;
  ...
```

**To Reproduce**
1. `npm start`
1. Go to `radar.demo.html` and add `[legendPlacement]="'bottom'"` to `<soho-radar>`
1. See that the legend is a thin white line
1. Inspect the chart and click on `<div class="widget-content"> and toggle the checkbox the css of `height: 318px` to see it hide/show the legend (see screenshots below)

**Expected behavior**
The legend should be perfectly viewable and not cut off (like seen in the 2nd screenshot)

**Screenshots**
Height is set:
<img width="993" alt="height-set" src="https://user-images.githubusercontent.com/742319/41939768-bdfce4f2-7964-11e8-9ad8-956926b3f18c.png">

Height is not set:
<img width="411" alt="height-not-set" src="https://user-images.githubusercontent.com/742319/41939779-c6e74bf2-7964-11e8-935e-4460a888ea84.png">

**Platform**
 - OS Version: OS X
 - Browser Name: chrome
 - Browser Version: latest

**Comment by tmcconechy** [comment]
Just noting that the widgets have a fixed size due to the homepage algorithm. But the way the chart works you can set the parent width and height. This will effect the height and width of the chart.

So to make this work can probably move it out of the widget class and make a new custom div with a better size for the lower legend that works.

**Comment by tmcconechy** [comment]
Are you working on this one still @krahs1 ?

**Comment by tmcconechy** [comment]
This is probably fixed by https://github.com/infor-design/enterprise/pull/3739 and related issues on that chain.
