### ISSUE TITLE
SohoTag does not emit events (beforeTagRemove event)

### ISSUE THREAD

**Issue by pgrochowski-infor** [infor-design/enterprise-ng#1150]
**Describe the bug**
SohoTag does not emit events (beforeTagRemove event).
The issue was originally reported at: https://github.com/infor-design/enterprise-ng/issues/1063
However it seems that the problem was fixed only for "soho-tag-list".
Might have been caused by the fact that "soho-tag" attribute directive is not rendered on jQuery element, as seen below:

![obraz](https://user-images.githubusercontent.com/90457153/137334558-77d4d931-ea36-4328-bf9a-4d8f7e7c9fb4.png)

**To Reproduce**
1. Add "beforeTagRemove" on any "soho-tag" on  tag demo.
2. Observe that "beforeTagRemove" event is not emited.

**Expected behavior**
The event is emited.

**Version**
- ids-enterprise-ng: 10.6.0

**Platform**
 - Device: Desktop
 - OS Version: Windows 10
 - Browser Name: Google Chrome
 - Infor Application/Team Name: WFM

**Comment by pgrochowski-infor** [comment]
How can I know which tag has been removed if I cannot listen on specific tag?
Right now we have an ugly workaround that iterates through all tags to find which one has been erased.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
