### ISSUE TITLE
Date Picker - When trying to change year by using laptop touchpad 10 years get skipped.

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise-ng#1156]
**Describe the bug**
In Date picker when we tried to change the year by using laptop's touchpad we observed 10 years records get skipped from list. 
This issue is observed when we use laptop touchpad to change the years. 

**To Reproduce**
1. Go to 'http://localhost:4200/ids-enterprise-ng-demo/datepicker.'
2. Click on 'Click on "Calendar Icon button to pen calendar"'
3. Click on 'October 2021 to change the year by using touchpad'
4. Click on 'Up Arrow in year section to change the years data by using touchpad'
4. See it was showing data from 2017 to 2026 after clicking on up arrow now it is showing years from 1997 to 2006

**Expected behavior**
It should show years from 2007 to 2016.

**Version**
- ids-enterprise-ng: [ v4.56.0]

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Im not sure if i can reproduce this or not?

a) By touchpad you mean the mac touch pad right?
b) Be aware if you hold down the mouse it scrolls this menu faster so you want to tap not hold?

Can you see any of this on https://main-enterprise.demo.design.infor.com/components/datepicker/example-index.html
Do you think it would be better to not increase this menu and have to type each time to scroll 10 years?

**Comment by tmcconechy** [comment]
I mean now if you press the mouse down it scrolls more then 10? Im thinking we should just remove that so you have to tap each time....? Sound good?

**Comment by dhumalkishor** [comment]
> I mean now if you press the mouse down it scrolls more then 10? Im thinking we should just remove that so you have to tap each time....? Sound good?

Yes. we can go with this option.

**Comment by dhumalkishor** [comment]
Hi Tim,

Can you please update when we can expect fix for this JT.

Regards,
Kishor

**Comment by tmcconechy** [comment]
Put this in for next sprint planning

**Comment by tmcconechy** [comment]
To the Developer:

1. Change to one per click
2. We missed this design on https://www.figma.com/file/y1oT4NPGJA78EzUNssZYsG/Calendar?node-id=1%3A2269&viewport=-288%2C2528%2C0.32999536395072937 so it should look like this with bigger hit point sin particular


<img width="359" alt="Screen Shot 2022-03-30 at 12 12 34 PM" src="https://user-images.githubusercontent.com/814283/160881735-f1eaf6bf-98c1-44c4-aa7b-792a25d313e7.png">

**Comment by janahintal** [comment]
Failing in years. It's skipping double in years drop down. Kindly see below video.
https://user-images.githubusercontent.com/45757016/167853614-78a17d7f-fac8-4c07-b26a-a970ccdc755e.mp4

**Comment by tmcconechy** [comment]
@janahintal should this be moved to failed then? Can you add steps if so as im not certain i'm seeing the same thing and the video doesnt seem to show me as i cant see how you are clicking

**Comment by janahintal** [comment]
Hi @tmcconechy. Its failing in https://main-enterprise.demo.design.infor.com/components/datepicker/example-index.html

Steps: 
1. Go to https://main-enterprise.demo.design.infor.com/components/datepicker/example-index.html 
2. Open the Month Year Dropdown 
3. Navigate in Year 

Notice it skips another year.

**Comment by tmcconechy** [comment]
Not seeing it @janahintal but do note that if you hold the mouse down it will move more than one year - so maybe thats happening?

**Comment by yohannahbautista** [comment]
@janahintal @tmcconechy 
Hi, I checked the page and tried it. The only times I'm able to get it to skip is when I long click

**Comment by tmcconechy** [comment]
Yeah agreed - i think this is working as expected.
