### ISSUE TITLE
Implement Swipe Action component wrapper

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-ng#1164]
**Is your feature request related to a problem? Please describe.**
Need to support Card Swipe Actions in NG:  https://main-enterprise.demo.design.infor.com/components/swipe-action/example-index.html

- [x] Add Swipe Action component wrapper
- [x] Add Types
- [x] Add Example (can be done against cards similar to EP example)
- [x] Add Tests?

**Additional context**
- Original EP Issue: infor-design/enterprise#5254
- EP Component source: https://github.com/infor-design/enterprise/blob/main/src/components/swipe-action/swipe-action.js
- Discussed in [MS Teams](https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1635279099533?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1635279099533&teamName=IDS%20Enterprise%20Development&channelName=General&createdTime=1635279099533)

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.58.0-dev.

https://main-enterprise.demo.design.infor.com/components/swipe-action/example-index.html
![Video 20](https://user-images.githubusercontent.com/84306838/142083183-7379bf40-5f3b-44aa-ba29-fb7db6bc8704.gif)

Moving this ticket to Done.

Thanks!
