### ISSUE TITLE
Datagrid: Filter problems

### ISSUE THREAD

**Issue by Thomas-Sparber** [infor-design/enterprise-ng#1166]
**Describe the bug**

Actually there are two problems with filters in DataGrid:

 - If a user manually applies a filter in a DataGrid I have no possibility to get the filtered rows. e.g. Full dataset is 100 lines, user applies filter so that only 2 lines are visible. There is no possibility to get those two lines
 - Multiselect is enabled for DataGrid. If a user selects one line, then manually applies a filter which EXCLUDES the previously selected line. Then again selects a line, the first selected line still appears in `dataGrid.selectedRows()` although it is not visible in the datagrid (anymore)

Thanks for your help!

**Comment by tmcconechy** [comment]
Hi. For 

1) you could look at the attached array and if the property `_isFilteredOut` is set its filtered else it isn't. But i think that a new function like `getFIlteredRows()` could be a good addition
2) Im not sure what you mean? How can i reproduce that on our examples?

**Comment by Thomas-Sparber** [comment]
Hi Tim,

thanks a lot for your answer! `_isFilteredOut` is totally what I was looking for - thank you! Yes, I agreen `getFilteredRows` would be a great feature.
Problem 2 is fixed with `_isFilteredOut` too, thanks!

**Comment by tmcconechy** [comment]
Could also make `getUnfilteredRows()` ...
