### ISSUE TITLE
Notification Badge: Update notification badge wrapper and implement in button and appmenu

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise-ng#1169]
**Is your feature request related to a problem? Please describe.**
Update the notification badge wrapper and apply the component to the button and app menu as we did in EP.

**Describe the solution you'd like**
- [ ] Update the example page of Notification Badge
- [ ] Update the typings (including for button and in app menu)
- [ ] Add the methods (enable & disable)
- [ ] Add tests

**Describe alternatives you've considered**
N/A

**Additional context**
- Related EP issue - https://github.com/infor-design/enterprise/issues/5594
- PR merged (for reference) - https://github.com/infor-design/enterprise/pull/5790

**Comment by CindyMercadoReyes** [comment]
This issue is not resolved.
