### ISSUE TITLE
Angular 13 Support

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#1170]
**Is your feature request related to a problem? Please describe.**

Angular 13 has been released.

**Describe the solution you'd like**

IDS Enterprise component wrappers upgraded to use Angular 13.

**Describe alternatives you've considered**

N/A

**Additional context**

https://blog.angular.io/angular-v13-is-now-available-cce66f7bc296

**Comment by tmcconechy** [comment]
@bthharper is this something you plan to look at or should we?

**Comment by bthharper** [comment]
@tmcconechy - I wont have the capacity for a few days, but if you've not gotten around to it when thing ease up a bit I'll take a look.  Is anyone else requesting this yet?

**Comment by tmcconechy** [comment]
Not yet but im sure they will.

**Comment by tmcconechy** [comment]
Gave it a quick try but ran into this
```
Package "@angular-eslint/builder" has an incompatible peer dependency to "@angular/cli" (requires ">= 12.0.0 < 13.0.0", would install "13.0.1").
```

So can retry when @angular-eslint/builder is updated with a patch seems 13.0.0 and 13.0.1 are currently out of sync.

We should also add the caching https://blog.angular.io/angular-v13-is-now-available-cce66f7bc296 as the build is pretty slow..

Feel free to check it out too but will plan on this for 10.11.0 in one month from today

**Comment by tmcconechy** [comment]
Still some issues in the dependency chain..

```
tmcconechy@USROMTMCCONEC01 enterprise-ng % npx @angular/cli@13 update @angular/core@13 @angular/cli@13
Using package manager: 'npm'
Collecting installed dependencies...
Found 70 dependencies.
Fetching dependency metadata from registry...
                  Package "@angular-eslint/builder" has an incompatible peer dependency to "@angular/cli" (requires ">= 12.0.0 < 13.0.0", would install "13.0.3").
✖ Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "/private/var/folders/h_/11z2j1h550scclvkw5fm0ny81847w_/T/ng-0yZqX2/angular-errors.log" for further details.
```

**Comment by whernebrink** [comment]
So we are waiting for Angular on this? Would be great to have this soon so that we can do a migrate on our workspace to latest lib versions etc. 👍

**Comment by tmcconechy** [comment]
I was working on this Friday actually. Should have a PR soon

**Comment by tmcconechy** [comment]
PR is IN https://github.com/infor-design/enterprise-ng/pull/1190
Also made a dev build for testing `11.0.0-dev.20211206` using 4.59-dev
