### ISSUE TITLE
LineChart: Throws error when empty array is supplied to data property

### ISSUE THREAD

**Issue by dohjon** [infor-design/enterprise-ng#1172]
**Describe the bug**

When using `SohoLineComponent` (line chart) and an empty array `[]` is used/supplied as input to the `data` property. 

```ts
    {
      data: [], // <--- Empty array, error
      name: "...",
      id: "...",
    },
```

The following error is thrown:

```ts
ERROR TypeError: Cannot read properties of null (reading 'getBBox')
    at Line.setTextValues (sohoxi.js:34619)
    at Line.build (sohoxi.js:34531)
    at Line.init (sohoxi.js:33830)
    at new Line (sohoxi.js:33810)
    at jQuery.fn.init.$.fn.chart (sohoxi.js:39472)
    at soho-line.component.ts:184
    at ZoneDelegate.invoke (zone.js:372)
    at Zone.run (zone.js:134)
    at NgZone.runOutsideAngular (core.js:28571)
    at SohoLineComponent.ngAfterViewInit (soho-line.component.ts:179)
```

**To Reproduce**

1. Open `src/app/line/line.demo.ts`.
2.  Use empty array `[]` as input to (all) the `data` property. 
```ts
  public lineData = [
    {
      data: [], // <--- empty array
      name: "Component A",
      id: "1",
    },
  ];
```
3.  See error

**Expected behavior**
Empty array as input to `data` property should not throw an error or be handled.

**Version**
- ids-enterprise-ng: 10.9.0

**Screenshots**
null

**Platform**
 - Device: Desktop
 - OS Version: macOS Big Sur 11.6.1
 - Browser Name: Google Chrome
 - Browser Version: Version 95.0.4638.69 (Official Build) (x86_64)

**Additional context**
When this error is thrown in a homepage widget it causes homepages to bug out and not be able to display data when clicking on widget About or Configure button(s) etc.

The exact same bug happens for the `area chart` (`src/app/area/area.demo.ts`) and can be reproduced with above steps as well.

**Comment by tmcconechy** [comment]
Yeah probably shouldn't error but wondering what we would show here? We have an example that shows an empty message when the data is empty and we used a straight up empty array for the whole property. This could be a work around/option for you for now

https://github.com/infor-design/enterprise/blob/main/app/views/components/line/test-empty.html#L18

**Comment by dohjon** [comment]
@tmcconechy Unsure as well. Below you can see what happens to homepage(s) after a widget encounters this error, no text is shown etc. Hopefully when the error is handled the below side-effect of the error will be gone as well.

Do you want me to create the same bug report for the area chart as well? (as noted above the exact same bug happens for the area chart as well) 

<img width="1514" alt="bug" src="https://user-images.githubusercontent.com/14950480/141132812-d903aed6-db63-4827-b2b2-45c410353be1.png">

**Comment by yohannahbautista** [comment]
@dohjon Hello, the mentioned PR above should fix the bug, just use the latest ids-enterprise and build and run again. 

@tmcconechy @ericangeles Should I make an example page?

**Comment by ericangeles** [comment]
@yohannahbautista that would be great. Thanks!

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
