### ISSUE TITLE
Datagrid: Expose the maskOptions and filterMaskOptions function

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#1175]
**Describe the bug**
Need to expose the maskOptions and filterMaskOptions functions in enterprise-ng.

**Expected behavior**
Need something like the following to be added to soho-datagrid.d.ts...

```
maskOptions?: SohoMaskOptions | SohoDataGridColumnMaskOptionsFunction;
filterMaskOptions?: SohoMaskOptions | SohoDataGridColumnMaskOptionsFunction;

type SohoDataGridColumnMaskOptionsFunction = (
    row: number,
    cell: any,
    fieldValue: any,
    columnDef: SohoDataGridColumn,
    rowData: Object
) => SohoMaskOptions;
```

**Version**
- ids-enterprise-ng: v10.10.0

**Additional context**
Is related to https://github.com/infor-design/enterprise/issues/5847

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
