### ISSUE TITLE
Datepicker: Set to required does not validate data

### ISSUE THREAD

**Issue by dmcodrum** [infor-design/enterprise-ng#1181]
**Describe the bug**
In IDS Angular, when a datepicker is set to 'required' the value validation is skipped - it allows an invalid date.

**To Reproduce**
1. Start IDS NG demo.
2. Open the 'Date Picker' app. http://localhost:4200/ids-enterprise-ng-demo/datepicker
3. In the first date field, 'Standard Date', enter an invalid date value and tab away - note the error message about an invalid value. This is correct behavior.
4. Modify the file '.\src\app\datepicker\datepicker.demo.html' to make that field required - see attached doc for instructions.
5. Re-visit the datepicker app.
6. Enter an invalid value in the Standard Date field again and tab away - note no error message, validation is skipped.
7. The 'required' validation does work.

**Expected behavior**
At step 6 the field should correctly identify the error - an invalid date but it only errors if the field is empty.

**Version**
- ids-enterprise-ng: 10.9.x

**Screenshots**

**Platform**

 - OS Version: Windows 10 
 - Browser Name chrome
 - Browser Version 96.0.4664.45

**Additional context**
Add any other context about the problem here

![datepicker](https://user-images.githubusercontent.com/39279254/143095543-abd8d1e8-969c-4c01-9368-a87d16ced0a8.JPG)
.

**Comment by tmcconechy** [comment]
If you override the validation you will need to add the full set of things you want to validate. I.E. `data-validate="required date"` should check both required and the valid date.

I think that is the issue here... Does that work?

**Comment by dmcodrum** [comment]
No, that's not really the issue. The issue is that it allows you to manually enter a completely invalid date, '11/39/2021' for example. I think it should always validate for an invalid date value. If that's not the case then I'll have to add date value validation manually in every instance where a date is required.

**Comment by tmcconechy** [comment]
Yeah i made that change a few years ago. If you set any validation you need to add some of the defaults back in (made it easier so you can specify exactly which ones you want if you set it).

**Comment by dmcodrum** [comment]
Ok. Not the answer I wanted but thinking more about it, it makes sense. The fix is actually simple enough - make it data-validate="required date" and it works as I would expect. You can close this. Thanks Tim.

**Comment by tmcconechy** [comment]
yeah sorry 👎🏻 I forget why but i think it was a lot simpler this way as there is more than one default depending on the types (i.e. time/date ect) and the need to entirely disable the validation for some strange date formats
