### ISSUE TITLE
Tabs: Not usable within Contextual Action Panel

### ISSUE THREAD

**Issue by lbursey-infor** [infor-design/enterprise-ng#1183]
**Describe the bug**
Tabs within Contextual Action Panel are not usable, instead the browser is redirected to the href of the clicked tab

**To Reproduce**
1. Go to http://localhost:4200/ids-enterprise-ng-demo/contextual-action-panel
2. Click on "CAP - Tabs Vertical" or "Panel with form validation / buttonsetAPI"
3. Click on any tab
4. Browser refreshes and is redirected to http://localhost:4200/ids-enterprise-ng-demo/#<tab-id> instead of opening tab. CAP is closed.

**Expected behavior**
Tab should open without reloading page

**Version**
- ids-enterprise-ng: main, 10.10.x

**Platform**
 - Device: Desktop
 - OS Version: Windows 10
 - Browser Name: Chrome, Firefox
 - Browser Version: Chrome Version 96.0.4664.45 (Official Build) (64-bit)

**Additional context**

The issue I am encountering in our application is that we get the following error message when clicking tabs in CAP:
![image](https://user-images.githubusercontent.com/92546088/143096917-7b0f9cef-727d-4bbf-b945-71ce0fc41d5b.png)
No changes are seen on the page, the page does not reload and the clicked tab is not switched to. This seems related given that the demo app is routing unexpectedly.

**Comment by lbursey-infor** [comment]
Hi Tim, just found the following ticket in the JQuery project, seems related? https://github.com/infor-design/enterprise/issues/5867

Note by the way that disabling hashing did not unblock the issue for us

**Comment by yohannahbautista** [comment]
@tmcconechy @ericangeles @lbursey-infor 
Hello, the tabs seem to work in my end if I use the latest ids-enterprise. Could you build with the latest version and see if the error occurs again?

**Comment by tmcconechy** [comment]
yeah I'm also not seeing this. Can you test on 11.3.0-beta.0 @lbursey-infor 
for now will close unless we get further information as the steps are working
