### ISSUE TITLE
DataGrid Context menu onSelected not fired

### ISSUE THREAD

**Issue by Thomas-Sparber** [infor-design/enterprise-ng#1184]
**Describe the bug**
I created a data-grid and I'm trying to set up a context menu. I created it similar to the example `datagrid-dynamic.demo`. When I click on a menu entry, no event is fired.

Additinal note: I am currently developing in Homepages widget SDK and tried to reproduce this error in a new simple project but I was not able to get it up and running. I tried to clone this repo but as soon as I run `npm start` I get a ton of errors. Also I tried to create a new project with `ng new ...`, then install ids-enterprise-ng, jquery etc. but eventuelly I also got many errors. It would be great if you could add a setup section in `Readme.md` which describes how to properly setup a project to use ids-enterprise-ng so I could create better bug reports.

**To Reproduce**

This is the relevant section of the html code:

    <div soho-datagrid *ngIf="itemGridOptions" [gridOptions]="itemGridOptions" id="itemGrid" #itemGrid
						(filtered)="itemsFiltered($event)" (selected)="itemSelected($event)" menuId="grid-context-menu"></div>

				<ul soho-popupmenu id="grid-context-menu" [attachToBody]="true" (selected)="showInContext($event)">
					<li soho-popupmenu-item>
						<a soho-popupmenu-label href="#">Show In-Context</a>
					</li>
				</ul>

The function `showInContext` is not executed when I click on the menu entry

Thanks for any help!

**Comment by tmcconechy** [comment]
Can you use the stack blitz to reproduce this issue? https://stackblitz.com/edit/ids-enterprise-10100
I think we are going to need that to look at this issue.

BTW this is based on https://github.com/infor-design/enterprise-ng-quickstart which works. I can take a look when you get the reproduction working 👍🏻
