### ISSUE TITLE
DataGrid programmatic selection not working

### ISSUE THREAD

**Issue by Thomas-Sparber** [infor-design/enterprise-ng#1185]
**Describe the bug**
I use data-grid and would like to implement two features `select all` and `unselect all`. Unselect all is working as expected but select all  does not select all rows but just fires the select event.

**To Reproduce**

Here is my relevant html code

    <div soho-datagrid *ngIf="itemGridOptions" [gridOptions]="itemGridOptions" id="itemGrid" #itemGrid
						(filtered)="itemsFiltered($event)" (selected)="itemSelected($event)"></div>
    <button soho-button (click)="selectAll()">Select all</button>

And here my relevant ts code

    ...
    this.itemGridOptions = {
				columns: this.itemColumns,
				selectable: "multi",
				idProperty: "MMITNO",
				editable: false,
				isList: true,
				filterable: true,
				paging: false,
				// pagesize: 20,
				dataset: response
			};
    ...
    selectAll() {
		this.dataGrid.selectAllRows();
	}

	unselectAll() {
		this.dataGrid.unSelectAllRows();
	}
    itemSelected(event: any) {
		console.log(event);
	}

`itemSelected` is correctly triggered but the selection on the datagrid remains the same.

Thanks for any help!

**Comment by tmcconechy** [comment]
Im not 100% clear on this maybe we need an example like in stack blitz https://stackblitz.com/edit/ids-enterprise-10100
The selectAllRows and unSelectAllRows do seem to work when i try them on my side.

Try https://main-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html
```
$('#datagrid').data('datagrid').selectAllRows()
$('#datagrid').data('datagrid').deSelectAllRows()
```

Or could you just use the selection checkbox on the header?

**Comment by kimanderssonm3cs** [comment]
I can confirm that this still is an issue, selectall is triggered but doesn't do any action.

I have tried both [dataset] and [data], there's no difference.
I am pretty certain that the underlying "idx" values doesn't correctly sync. 

`<div soho-datagrid #parserDatagrid selectable="multiple" [dataset]="data | async"
   indeterminate="false" treeGrid="true" [gridOptions]="parserGridOptions"
   style="height: calc(100% - 45px)" (selected)="onDatagridSelect($event)">
</div>`

A workaround is to do something like: 
`onDatagridSelect(event: SohoDataGridSelectedEvent) {
  if (event.type == 'selectall') {
	 const _ = (this.parserDatagrid as SohoDataGridComponent).selectAllCurrentPage = true;
  }
}`
However, the selection doesn't work the first time, you need to selectall => deselectall => selectall and then it will re-render.
I need some way of calling a reRender on the datagrid in order for this to work.

**Comment by kimanderssonm3cs** [comment]
I can also confirm that "this.parserDatagrid.selectRows[i]" wont trigger any event.
