### ISSUE TITLE
SohoDropdown: Readonly prop not working

### ISSUE THREAD

**Issue by ayoayco** [infor-design/enterprise-ng#1189]
**Describe the bug**
The angular way of setting dropdown fields to readonly is not working.

**To Reproduce**
1. Go to StackBlitz ['SohoDropdown Readonly Bug'](https://stackblitz.com/edit/ids-quick-start-930-3gc2wi?file=src%2Fapp%2Fdropdown-readonly%2Fdropdown-readonly.component.html)
2. See Text and Lookup readonly input property properly makes the fields readonly
3. See Dropdown field not made readonly

**Expected behavior**
Assigning `readonly` to true should make the dropdown readonly.

**Version**

- StackBlitz version: "ids-enterprise-ng": "9.3.0", and
- also encountered in our workspace using "ids-enterprise-ng": "^10.6.0",

**Screenshots**
![screencapture-stackblitz-edit-ids-quick-start-930-3gc2wi-2021-12-06-13_13_43](https://user-images.githubusercontent.com/4262489/144791125-c78bc0f0-8117-4595-8b9e-76fc3333373a.png)

**Comment by tmcconechy** [comment]
I think this is becuase the dropdown has special functionality around this https://github.com/infor-design/enterprise-ng/blob/main/projects/ids-enterprise-ng/src/lib/dropdown/soho-dropdown.component.ts#L635 to disable more than one item.

One way to fix it is to use `<select soho-dropdown readonly="true">` but we can take a look

**Comment by ayoayco** [comment]
Okay, I'll also try this in our workspace! Thanks!

**Comment by ayoayco** [comment]
The suggested workaround readonly="true" doesn't take a boolean since the true there is a string "true" (it will also work with readonly="readonly").

To make this work in our angular workspace I had to do:

```
    [attr.readonly]="controlConfig.readonly ? 'readonly' : null"
```

Would be nice to have the `[readonly]` angular input implemented to make it consistent with other controls.

**Comment by tmcconechy** [comment]
ok we will have a look when we can 👍🏻

**Comment by ayoayco** [comment]
@whernebrink @carlerikjohan

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by inforrpunay** [comment]
Hello! We have tested this in ids-enterprise-ng@13.1.1 and having [readonly]="false" still makes the dropdown field disabled. [See StackBlitz](https://stackblitz.com/edit/ids-quick-start-1311-rkql11?file=src%2Fapp%2Fapp.component.html)

**Comment by tmcconechy** [comment]
This is actually normal. If you use it the readonly attribute its presense means readonly. You probably need

```
[attr.readonly]': 'isReadonly ? '' : null'
```

So in the false case you want to remove it.

**Comment by whernebrink** [comment]
@tmcconechy hmm, that does not seem to work:

![image](https://user-images.githubusercontent.com/73601152/156221555-d5cb7309-2846-42ca-898e-df381390f83b.png)
