### ISSUE TITLE
SohoTextArea: Unable to change options after component was initialized

### ISSUE THREAD

**Issue by ptomanek-infor** [infor-design/enterprise-ng#1193]
**Describe the bug**
Paramenters such as maxLength, characterCounter, charRemainingText, charMaxText cannot be changed once the component is initialized.

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-enterprise-10100-6q4j7y?file=src/app/app.component.html
2. See component is initialized with maxLenght=5 and Remaining characters: text.
3. Click on change text/change length/toggle counter and observe that nothing changed

**Expected behavior**
New options should be reflected in 

**Version**
- ids-enterprise-ng: [v10.10.0]

**Screenshots**
![image](https://user-images.githubusercontent.com/59701582/145773179-44edfbfd-9bb9-4b8b-bd2c-eb06c55a687b.png)
The text bellow text area should be "Max extra" and length should be 10 instead of 5 and counter should be disabled.

Second textarea that is configured in ngAfterInit method is not working at all.

**Comment by edgarinfor** [comment]
@tmcconechy , any chance that this might get on your queue any time soon?
I've seen some upcoming **WFM** designs that might require full advantage of the IDS textarea which we cannot adopt due to this issue.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
