### ISSUE TITLE
Popupmenu: Issues with CAP & emptymessage

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-ng#1194]
**Describe the bug**
Multiple (related) issues:

1. When a `soho-emptymessage` component is created, its button gets an `id="undefined"`.
2. When there is an element with `id="undefined"` and a CAP is opened, the element will be moved to the "more" menu of the CAP.

**To Reproduce**
(optional: check out the "10.11.1" tag in the repo)

Add the following to the top of `popupmenu.demo.html`:
```html
<!-- Uncomment below to show issue with emptymessage specifically -->
<!-- <div soho-emptymessage title="Hello" [button]="{ text: 'Hello Button' }"></div> -->
<button id="undefined" style="color: red">
  <ng-container *ngIf="isCap">The button under the dialog is now moved to the "more" menu</ng-container>
  <ng-container *ngIf="!isCap">This will be moved to the "more" menu in the CAP</ng-container>
</button>
```

..and the following to `popupmenu.demo.ts`:
```typescript
  constructor(private capService: SohoContextualActionPanelService, private viewRef: ViewContainerRef) { }
  
  isCap = false;
  ngOnInit() {
    if (!this.isCap) {
      setTimeout(() => {
        this.capService
          .contextualactionpanel(PopupMenuDemoComponent, this.viewRef)
          .apply(c => c.isCap = true)
          .buttons([
            { text: "Hello" },
            { text: "Hello" },
            { text: "Hello" },
            { text: "Hello" },
            { text: "Hello" },
            { text: "Hello" },
          ])
          .open();
      }, 5000);
    }
  }
```

1. Serve the demo project and go to 'http://localhost:4200/ids-enterprise-ng-demo/popupmenu'
2. Notice the red text at the top
3. Wait for 5 seconds
4. Notice that the red text has disappeared
5. Open the "more" menu in the cap header
6. Notice that the red text is in there.

**Expected behavior**
1. Elements with id "undefined" should not be moved to the menu
2. emptymessage button should not have the id "undefined"

**Version**
- ids-enterprise-ng: 10.11.1

**Screenshots**
![image](https://user-images.githubusercontent.com/4991954/146033088-d369620e-87f2-4bb2-90a0-8c74e6da7b24.png)

**Additional context**
This has some pretty major effects:
https://jira.infor.com/browse/LIME-7489
https://jira.infor.com/browse/LIME-7488

**Comment by tmcconechy** [comment]
Would it be a workaround to always set an id on it? Technically i guess `undefined` is a valid ID. But also anything internal should probably default a better id...

**Comment by tmcconechy** [comment]
Need to patch to 4.58 once done. Do you or anyone in manilla have bandwidth for this one @ericangeles ? If not let me know and i can also try and look.

**Comment by volante007** [comment]
Can be reproduced here as well:
https://design.infor.com/code/ids-enterprise/latest/demo/components/contextualactionpanel/example-markup?theme=uplift&variant=light
Modify the button id from `trigger-1` to `undefined` -> open CAP -> button disappears

Interestingly, it can't be reproduced in this one
https://design.infor.com/code/ids-enterprise/latest/demo/components/contextualactionpanel/example-index?theme=uplift&variant=light

**Comment by anhallbe** [comment]
@tmcconechy the `"undefined"` id is not something that we intentionally do.

But if an element accidentally gets the `"undefined"` id (e.g soho-emptymessage in this case, but it can be any component, from any library, and in the Homepages case any widget), then things break.

**Comment by tmcconechy** [comment]
I see the issue here... https://github.com/infor-design/enterprise/blob/main/src/components/toolbar/toolbar.js#L222 looking for a fix...

**Comment by anhallbe** [comment]
The `SohoEmptyMessageButtonOptions.id` property is typed as optional. It can be removed from the `emptymessage.demo.ts` sample:

![image](https://user-images.githubusercontent.com/4991954/146055341-e557ceb8-1836-4cad-8964-7fd421982ab6.png)

I'm not sure if it's causing any major issues as long as the toolbar/popupmenu thing is fixed. But I'd add an `undefined` check to whatever it is turning `undefined` into the string `"undefined"` just to be safe. I haven't looked at the code yet so I'm not sure where.

**Comment by anhallbe** [comment]
@tmcconechy Looks like this is it: https://github.com/infor-design/enterprise/blob/main/src/components/emptymessage/emptymessage.js#L84

**Comment by tmcconechy** [comment]
yep found it too 👍🏻  adding that fix as well https://github.com/infor-design/enterprise/pull/5949/files#diff-712effdbbe8be22ff6f9c7933b63935339497f66affeb4fb501ac2b2635f6c9aR84

Waiting on reviewers for a patch

**Comment by tmcconechy** [comment]
@anhallbe @volante007 
I added a patch for this its NG - 10.11.2 and its using 4.58.2 inside.
