### ISSUE TITLE
DatePicker: Issue with range 

### ISSUE THREAD

**Issue by manel-abbes** [infor-design/enterprise-ng#1200]
**Describe the bug**
Hello Team, I am working with the Soho date picker, I used the range options to display an interval in my date picker for example 
  range: "1/12/2017 - 1/16/2017",  the date picker shows always only one date: the start date instead of the start and end date, I tried to change the locale and I get the same issue. the value of the range takes always the start date.

**To Reproduce**
1. upgrading angular version to 12 
2. upgrading ids-enterprise-ng to 10.10.1 
3. go to the date-picker: a date with a range 
4. the range shows one date (start date) , instead of two dates 

**Expected behavior**
the date picker must display the range with start and end dates.

**Version**
- ids-enterprise-ng: 10.10.1

**Screenshots**
![datepicker range](https://user-images.githubusercontent.com/82028679/146933761-9368cba5-5eda-4a54-ba01-cc76c9ec5773.PNG)

**Comment by tmcconechy** [comment]
I can also see the issue more simply:

- if i go to http://localhost:4200/ids-enterprise-ng-demo/datepicker and open the range picker 
- Click the trigger on "Date with Range (set via mode)"
- Only one date is shown on the range.. 

I do think this did work ok at one point

**Comment by janahintal** [comment]
QA Passed. Verified in http://localhost:4000/components/datepicker/example-range.html
![image](https://user-images.githubusercontent.com/45757016/152982290-a17e4f35-7151-429c-a25a-7c876e82402d.png)
