### ISSUE TITLE
Notification: Match the close method

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise-ng#1201]
**Describe the bug**
Match the method `close` in the notification component.

**Additional context**
See below

hide vs close

https://github.com/infor-design/enterprise/blob/main/src/components/notification/notification.js#L153

https://github.com/infor-design/enterprise-ng/commit/a650893794ff441cb4cfcfdc308bdc17de83a4d6#diff-440838bb0da172a7e5e430783e31865910270df3d133cfc95df528aa3a90d1a9R24

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
