### ISSUE TITLE
General: Passive Events Errors in the console

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#1207]
**Describe the bug**
Jquery/NG is reporting some errors in the console that would be good to get rid of.

**To Reproduce**
-Visit http://localhost:4200/ids-enterprise-ng-demo/context-menu-nested and open developer tools in and emulate a responsive environment at mobile size (I used iPhone 5/SE).
- Long press inside the parent container and the child container and notice the appropriate context menu is opened in each case. 
- See the error (attached) in the console

**Expected behavior**
No warnings/errors 

**Screenshots**

<img width="1153" alt="146410923-e22ea0c5-4e81-4e51-9d50-5fe69328eccb" src="https://user-images.githubusercontent.com/814283/148243968-189fd017-63cc-4bad-a99f-b6373b5036a8.png">

**Platform**
 - Browser Name (chrome)

**Additional context**
See info on https://github.com/infor-design/enterprise-ng/pull/1196

**Comment by davidcarlsonberg** [comment]
Hi @tmcconechy I'm finding it difficult to locate where the long press or click event is located in `enterprise-ng` so I can play around with overcoming this error. Could I ask if you have a good starting point?

**Comment by tmcconechy** [comment]
@davidcarlsonberg the code doing the long press is going to be in the EP code actually not the angular wrapper. Probably someplace in the longpress behavior API https://github.com/infor-design/enterprise/tree/main/src/behaviors/longpress

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
