### ISSUE TITLE
Datagrid: add verticalScrollToEnd event

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise-ng#1208]
A while back support for knowing if the datagrid is at the end of the list was added.

I would like to have this available for the enterprise-ng.

**Additional context**
Here is the [Enterprise issue](https://github.com/infor-design/enterprise/pull/5539).

Tagging @ericangeles, as requested. 

Thanks!

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
