### ISSUE TITLE
Tab contents remain disabled when switching tabs in Contextual Action Panel

### ISSUE THREAD

**Issue by lbursey-infor** [infor-design/enterprise-ng#1210]
**Describe the bug**
Tab contents remain disabled when switching tabs in Contextual Action Panel

**To Reproduce**
1. Add button, input, etc. to a soho-tab-panel inside of a Contextual Action Panel (not the panel open by default)
2. Open the panel
4. See that button, input, etc. remains disabled

**Expected behavior**
Disabled elements enabled when their tab is active

**Version**
- ids-enterprise-ng: 13.0.x, 13.1.

**Screenshots**
![image](https://user-images.githubusercontent.com/92546088/149423078-33fdfb4d-4b1d-4a7c-bfc4-8bedc04b69e6.png).

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome, Firefox

**Comment by tmcconechy** [comment]
@lbursey-infor do you have the code for what you tested you could add (or a stackblitz) - this would save a lot of time. Thanks

**Comment by lbursey-infor** [comment]
Hi @tmcconechy , the file contextual-action-panel-tabs-vertical.component.html can be replaced with the following:
```
<div soho-tabs vertical="true" (activated)="onTabActivated($event)">
  <div soho-tab-list-container [verticalScrolling]="true">
    <ul soho-tab-list>
      <li soho-tab><a soho-tab-title tabId="tabs-vertical-1">Test Information</a></li>
      <li soho-tab selected="true"><a soho-tab-title tabId="tabs-vertical-2">Contacts</a></li>
    </ul>
  </div>
</div>

<div soho-tab-panel-container [verticalScrolling]="true">
  <div soho-tab-panel tabId="tabs-vertical-1">
    <input soho-toolbar-flex-searchfield [collapsible]="true" [clearable]="true" />
    <button type="button"  class="btn-primary">
      <span>Test</span>
    </button>
  </div>
  <div soho-tab-panel tabId="tabs-vertical-2">
  </div>
</div>
```

**Comment by lbursey-infor** [comment]
@tmcconechy Just FYI, this is blocking core functionality for WFM and will be a release blocker for our CU code cutoff on Jan 25th

**Comment by tmcconechy** [comment]
Did this work in the past and broke? I’ll do a quick investigation next week

**Comment by lbursey-infor** [comment]
@tmcconechy This did work at one point yes. It worked as late as 10.3.0 for sure

**Comment by tmcconechy** [comment]
Double assigning this in case @ericangeles can look before me but if next will debug more next Tuesday

**Comment by ericangeles** [comment]
@tmcconechy it looks like an EP issue. I was able to replicate it in EP.

**Comment by tmcconechy** [comment]
@lbursey-infor this issue is fixed now. Would you need a patch? If so you have three choices:

1) Wait for 13.1.0 in early feb
2) On top of 13.0.1 as 13.0.2  (NG 13)
3) On top of 10.12.0  as 10.13.0 (NG 12)

**Comment by lbursey-infor** [comment]
@tmcconechy A patch for 13.0.x would be appreciated. Thanks for the quick turnaround!

**Comment by tmcconechy** [comment]
Ok Its done 13.0.2 -> https://www.npmjs.com/package/ids-enterprise-ng/v/13.0.2

**Comment by janahintal** [comment]
QA Passed. 
Verified in https://main-enterprise.demo.design.infor.com/components/modal/example-hidden-field.html & https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/example-cap-tabs-vertical-scroll.html?theme=classic&mode=light&colors=2578a9

![image](https://user-images.githubusercontent.com/45757016/150264007-6375c444-db7f-4e9a-aee3-897109d76c0d.png)
![image](https://user-images.githubusercontent.com/45757016/150264150-e3e8d61a-f930-4a3b-9cae-fa0fd07028b7.png)


![image](https://user-images.githubusercontent.com/45757016/150264517-91f38499-a45b-472f-b1f3-3b614385378f.png)
