### ISSUE TITLE
CAP: cssClass not added to modal element

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise-ng#1215]
**Describe the bug**
Not able to apply cssClass to CAP modal.

**To Reproduce**
1. Go to this [this stackblitz](https://stackblitz.com/edit/ids-quick-start-1301-nwg4ig?file=src%2Fapp%2Fapp.component.html)
2. Click on the "Show Cap Dialog" button
3. Inspect the DOM
4. You will see that there is no added class to the element:
![image](https://user-images.githubusercontent.com/73601152/150152614-a215a795-3844-4d8b-b51e-5e2558df7f10.png)

5. Close the modal and click the "Open Standard Soho Modal"
6. Inspect the DOM and you will see the added class name:
![image](https://user-images.githubusercontent.com/73601152/150153244-020789aa-cfc5-4c72-9d80-c39309ff4214.png)

**Expected behavior**
Using the `.cssClass('my-custom-class')` or `.modalSettings({ cssClass: 'my-custom-class'})` should be applied to the element with the `.modal` class.

**Version**
- ids-enterprise-ng: 13.0.0

**Platform**
 - OS Version: Mac OSX
 - Browser Name: n/a
 - Browser Version n/a

**Comment by whernebrink** [comment]
Some additional details to this.

This works (first opening the modal, then apply the cssClass do the dialogRef), which is kinda weird and differs from how we usually use the soho modal one:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/73601152/150412246-f062c440-ed03-49a5-b1c3-1ce43b980bf6.png">

Seems to be because of the following code in `soho-contextual-action-panel.ref.ts` wich checks to see that the dialog is open:
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/73601152/150412535-a42dde49-3cdc-40ae-971b-5ba225fd9308.png">

**Comment by jbrcna** [comment]
this issue is now resolved.
verified in https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/test-css-settings.html
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/56722184/156337141-17855e4b-b1c0-454a-bacd-05b9fedda372.png">
