### ISSUE TITLE
Homepage - Widget height includes overflow when dragging in edit mode

### ISSUE THREAD

**Issue by xqses** [infor-design/enterprise-ng#1216]
**Describe the bug**
Dragging a widget with widget height overflow (such as a listview with many items) while editing will include the overflow. This causes the widget(s) below the current widget to be visible as part of the currently dragged widget.  

**To Reproduce**
1. Create an editable homepage and include enough widgets to fill at least two rows.
2. Add enough content to a widget on the first row so it will overflow.
3. Enter the edit mode and drag the widget horizontally.

**Expected behavior**
The widget overflow should not be part of the widget height when the widget is being dragged.

**Version**
- ids-enterprise: 4.55.2 | ids-enterprise-ng: 10.6.2 (observed in 10.9 as well)

**Screenshots**
https://i.imgur.com/XmsjV0z.png
Can be reproduced here.
https://anhallbe.github.io/ids-repro/homepage-editing

**Comment by tmcconechy** [comment]
Maybe as a fix we need to set overflow off on the draggable element or set the height.

**Comment by jbrcna** [comment]
This has been QA tested and passed on v4.62.0-dev.
https://main-enterprise.demo.design.infor.com/components/homepage/example-filled-widget
<img width="1531" alt="image" src="https://user-images.githubusercontent.com/56722184/160050441-98da6536-dfa9-4b63-ae1b-e9f7013053c3.png">
