### ISSUE TITLE
Notification: Styling is off/broken?

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#1217]
**Describe the bug**

**To Reproduce**
1. Go to  http://localhost:4200/ids-enterprise-ng-demo/notification
2. Click on show notification
3. See error

**Expected behavior**
Should look like https://main-enterprise.demo.design.infor.com/components/notification/example-index.html and go all the way across.. (pick one status color)

Also please change the text to "This is a notification Message" or make the text like the EP example..

**Screenshots**
<img width="389" alt="Screen Shot 2022-01-26 at 9 42 22 AM" src="https://user-images.githubusercontent.com/814283/151184084-fd4d0d1c-b126-4e3f-88d4-9a560ba9dd3e.png">

**Comment by tmcconechy** [comment]
Also check if the parentElement should be optional or not in the types...

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
