### ISSUE TITLE
Datagrid: not able to style row template when using rowTemplateComponent

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise-ng#1224]
**Describe the bug**
When having an expandable row which should display a custom component, it seems to be required to also have `rowTemplate` set. When setting this,  your component will be put inside a div with a class with a class of `datagrid-cell-layout` applied to it, which will have `display: table-cell`, which you cannot override. 

```ts
const gridOptions = {
  rowTemplateComponent: SomeComponent,
  rowTemplate: '<div class="this-class-for-custom-styling-will-do-nothing"></div>'
}
```
I've tried adding a class to it (like the example above), but it will not be applied because the innerHtml is overwritten by the following lines in soho-datagrid.component.ts:
![image](https://user-images.githubusercontent.com/73601152/151777580-f26b62ac-9344-4951-b9bc-44413af25960.png)

**To Reproduce**
1. Go to [this stackblitz](https://stackblitz.com/edit/ids-quick-start-1301-g5ksfn?file=src%2Fapp%2Fdatagrid%2Frow.component.ts)
2. Click on the + to expand the row
3. Inspect the DOM
4. You will now see a div with class `datagrid-cell-layout` and not the one specified for the rowTemplate
![image](https://user-images.githubusercontent.com/73601152/151780847-5cb2623d-123b-48d9-95e2-695925406a41.png)

**Expected behavior**
1. I'd expect not even having to provide the `rowTemplate` to start with. Is this really needed? If empty, can't the ids-component handle it, create an unstyled div or something i.e. not apply the datagrid-cell-layout class on it? 
2. When having a `rowTemplate` I'd expect it to be used, i.e. The element with its classes and/or inline styles should be respected.

**Version**
- ids-enterprise-ng: 13.0.0

**Screenshots**
Display issue of dynamic component, which I want to take full-width, inside expandable row:
![image](https://user-images.githubusercontent.com/73601152/151779233-032ae38f-a00b-48eb-aca6-ace9a7328995.png)

**Platform**
 - OS Version: OSX
 - Browser Name n/a
 - Browser Version n/a
 
 Thanks!

**Comment by whernebrink** [comment]
Just found out that the `datagrid-cell-layout` is actually applied to my component (which selector is not present but replaced by this div with that class - which was confusing for me). Atleast I can do the following as a workaround:

```scss
:host {
  display: block !important;
}

![image](https://user-images.githubusercontent.com/73601152/151782656-3fa3749b-a4e8-4800-ba6d-b2aee7b2f382.png)

**Comment by tmcconechy** [comment]
As far as i know using the `:host` is the "angular" way to do it. So think given that works its not only a workaround but possibly the only solution...

CC @EdwardCoyle

**Comment by whernebrink** [comment]
@tmcconechy, well the somewhat weird thing is that I provide the following on my datagrid options:
```ts
{ 
  rowTemplateComponent: SomeComponent,
  rowTemplate: '<div class="some-class"></div>'
}
```
And what i get in the markup is a merge of the rowTemplate and my component (my component becomes a div, i.e. no longer an element selector, with the mentioned added class).
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/73601152/151856727-9da5457e-4126-48ae-a0a9-8f97231c4654.png">

Given the datagrid options, I think I would expect something like this:
```html
<div class="some-class">
   <my-expandable-row></my-expandable-row>
</div>
```
and not:
```html
<div class="datagrid-cell-layout" _nghost-hly-some-magic="">
  <h1>My expandable row component content</h1>
  <p>More of my component's content</p>
</div>
```
If that makes sense?

**Comment by tmcconechy** [comment]
yeah i guess that does.. but given the examples we would have to figure out some way to make this not a breaking change.
can you put the `<div class="datagrid-cell-layout">` in your `SomeComponent` instead?

**Comment by whernebrink** [comment]
Nah, it doesn't make any difference. I will still end up with my host as a div with that class, followed by what ever I have in my component:

The highlighted row is my component, as a div with the class, 
The div below I added in my component with the datagrid-cell-layout class to it. 
<img width="720" alt="image" src="https://user-images.githubusercontent.com/73601152/152065316-7d9ceb13-97d6-4c7c-8bd4-f3f69ea30422.png">

**Comment by tmcconechy** [comment]
Ok we will have to investigate this one

**Comment by whernebrink** [comment]
@tmcconechy that's great, however it's not a current blocker since I can do the `display: block !important`, but I think it would be good for the framework to have it looked at, when there is time... This ticket could atleast help anyone else running in to the same issues. :)
