### ISSUE TITLE
NotificationBadge: Cannot be configured for single 'accordion-header'. Also not applicable to 'soho-toolbar-flex-nav-button'.

### ISSUE THREAD

**Issue by pgrochowski-infor** [infor-design/enterprise-ng#1235]
**Describe the bug**
1). Notification badge in current form is not applicable to 'soho-toolbar-flex-nav-button'.
It is possible to make a workarounds either with:

1.a). Using 'soho-button', but top-right notification dot is misplaced:
![obraz](https://user-images.githubusercontent.com/90457153/153855994-dd8153fd-2d49-41ae-bd5b-52e5a7f6d510.png)

1.b). Using 'soho-notification-badge', but top right notification dot is misplaced:
(More importantly, the button can no longer open menu!)
![obraz](https://user-images.githubusercontent.com/90457153/153856245-9f8d04ce-ad71-4063-9065-fdb0b8e81a0f.png)

2). For menu entries it is not possible to have badge on only one element:
(Probably since badge switch is provided to 'accordion' and not 'accordion-header'. Latter only accepts color and position.)
![obraz](https://user-images.githubusercontent.com/90457153/153857137-9ecba5ce-591a-4a0b-b1ab-2cbb51cf5a3a.png)

**To Reproduce**
1). Just use 'soho-toolbar-flex-nav-button'. It does not accept badge configuration.

1.a). Style 'soho-button' to act as ''soho-toolbar-flex-nav-button':
```
<button soho-button="icon" [icon]="'menu'"
    class="btn-icon application-menu-trigger"
    [buttonOptions]="{
        notificationBadge: true,
        notificationBadgeOptions: {
            position: 'upper-right',
            color: 'alert'
        }
        }">
</button>
```

1.b). Surround 'soho-toolbar-flex-nav-button' with 'soho-notification-badge':
```
<div soho-notification-badge
        [color]="'alert'"
        [position]="'upper-right'">
    <button soho-toolbar-flex-nav-button></button>
</div>
```

2). Configure badge on accordion menu:
(Notice there is only a global switch.)
```
<div class="accordion panel inverse" data-options="{'allowOnePane': false, 'notificationBadge': true}" >
    <ng-container *ngIf="menuItems.length === 0">
    <div class="accordion-header" data-options="{'position': upper-left, 'color': complete}">
        <svg soho-icon [icon]="'home'"></svg>
    </div>

    <div class="accordion-header" data-options="{'position': upper-right, 'color': yield}">
        <svg soho-icon [icon]="'profile'"></svg>
    </div>
    </ng-container>
</div>
```

**Expected behavior**
1. Ability to configure, enable/disable badge on 'soho-toolbar-flex-nav-button'. (With correct positioning.)
2. Ability to enable/disable notification badge on single 'accordion-header' entry.

**Version**
- ids-enterprise-ng: v13.0.2

**Additional context**
Application: Infor WFM
Used in Angular app.

**Comment by jbrcna** [comment]
This has been QA tested and passed on v4.62.0-dev.
https://main-enterprise.demo.design.infor.com/components/toolbar-flex/test-toolbar-nav-badge.html
<img width="865" alt="image" src="https://user-images.githubusercontent.com/56722184/160049957-4dca0c38-3d3b-447d-872e-d2f3e74f17ba.png">
