### ISSUE TITLE
Datagrid: removeRow typing is incorrect.

### ISSUE THREAD

**Issue by LucasLundJensen** [infor-design/enterprise-ng#1238]
**Describe the bug**
Datagrid's removeRow method is explained incorrectly, the method requires the index of the row wishing to be removed, but the description & syntax explains it as the row's data itself needing to be passed through.
This can result in the first row being removed from the datagrid, but never results in the correct row being removed.

**To Reproduce**
See:
[Typing](https://github.com/infor-design/enterprise-ng/blob/main/projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.component.ts#L1520)
[Actual implementation](https://github.com/infor-design/enterprise/blob/main/src/components/datagrid/datagrid.js#L655)

**Expected behavior**
Typing to reflect the correct behavior.

**Version**
- ids-enterprise-ng: 13.1.1

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
