### ISSUE TITLE
Modals created with SohoModalDialogService have too wide minimal width for some mobile devices

### ISSUE THREAD

**Issue by pgrochowski-infor** [infor-design/enterprise-ng#1240]
**Describe the bug**
Modals created with SohoModalDialogService have to wide minimal width for some mobile devices.

**To Reproduce**
Use any device with screen width more narrow than 400 pixels.
(E.g. Samsung Galaxy S8+, which is in fact 360 pixels wide.)
![obraz](https://user-images.githubusercontent.com/90457153/155542896-b4ab020a-f95c-4e48-89ff-a765e458d473.png)

**Expected behavior**
1. Either minimal width of modal reduced to for e.g. 300 pixels.
2. Or possibility to provide custom min-width with SohoModalOptions.

**Version**
- ids-enterprise-ng: v13.0.2

**Additional context**
Application: Infor WFM
Used in Angular app.

**Comment by tmcconechy** [comment]
Not sure i follow this issue? Can you reproduce it on any example in https://main-enterprise.demo.design.infor.com/components/modal ? 

Modals created with SohoModalDialogService  - would mean every modal done in angular so must be more to this...

![Screen Shot 2022-02-24 at 9 36 12 AM](https://user-images.githubusercontent.com/814283/155544875-ba480164-c0c0-4adf-acc6-8f80ec52d0fb.png)

**Comment by pgrochowski-infor** [comment]
The problem seems to only manifest with modals with "x" close button.

Steps to reproduce in enterprise-ng demo:

1. Got to "modal-dialog.demo.ts".
2. Add close button to FullSizeModalDialog:
![obraz](https://user-images.githubusercontent.com/90457153/155726408-001be823-c6e5-40a7-b34c-d9e5d54aaf1d.png)

3. Display "Modal Dialog" demo Samsung Galaxy S8+.
4. Click "Full on Tablet".
5. Observe result:
![obraz](https://user-images.githubusercontent.com/90457153/155726689-cc1fb990-d6fd-4b45-999d-ed6cb4bc4d83.png)

Tested on enterprise-ng 13.0.2 tag.

**Comment by tmcconechy** [comment]
Cant 100% see it here but it doesnt look perfect either https://main-enterprise.demo.design.infor.com/components/modal/example-close-btn.html

**Comment by janahintal** [comment]
QA Passed. Thanks. Verified in https://main-enterprise.demo.design.infor.com/components/modal/example-close-btn.html
![image](https://user-images.githubusercontent.com/45757016/167850386-bcc085da-49b7-4dde-9370-956412f23d8c.png)
![image](https://user-images.githubusercontent.com/45757016/167850626-ffdfc894-5f3a-4e3f-b753-81e6148afbc1.png)
