### ISSUE TITLE
Button NotificationBadge - Doesn't support changing badge states

### ISSUE THREAD

**Issue by LilBiggs** [infor-design/enterprise-ng#1241]
**Describe the bug**
The Soho-Button doesn't currently support changing the notificationBadge state. Either from true/false or false/true. Only the initial state persists. In the soho-button code, you will see the `//todo: how to updat ethe button when options change?` comment.

**To Reproduce**
1. Set initial [notificationBadge]="false"
2. Update [notificationBadge]="true"
3. See -> https://stackblitz.com/edit/ids-quick-start-1311-w3n5hi?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
Badge should show/hide based on the current status of notificationBadge

**Version**
- ids-enterprise-ng: v13.1.0

**Screenshots**
![image](https://user-images.githubusercontent.com/6730716/155812117-67c9820b-3fa2-4efe-a37d-ed2074f97a09.png)

**Additional context**
Infor Team: WFM

**Comment by tjamesallen15** [comment]
Just wanna ask for clarification. I happen to remember while doing this, that we can use the disable() method for the notification badge to turn on/off the notification dot in the UI. Can't we just use that for this use case? @tmcconechy

**Comment by tmcconechy** [comment]
Yep thats what im reading..

Set initial: `[notificationBadge]="false"`
Update: `[notificationBadge]="true"`

So when setting that they want the badge to show/hide. It seems like a valid use case for when there is no alerts but then later there is.

**Comment by tjamesallen15** [comment]
> Yep thats what im reading..
> 
> Set initial: `[notificationBadge]="false"` Update: `[notificationBadge]="true"`
> 
> So when setting that they want the badge to show/hide (should work either way false or true initially). It seems like a valid use case for when there is no alerts but then later there is.

got it, @tmcconechy. thanks!

**Comment by LilBiggs** [comment]
> So when setting that they want the badge to show/hide (should work either way false or true initially). It seems like a valid use case for when there is no alerts but then later there is.

Our use case is for a filter button. When no filter is applied the notification badge does not show. When a filter is applied, then the notification badge is shown.

**Comment by jbrcna** [comment]
QA Passed. v4.63.0-beta0
https://4630-beta0-enterprise.demo.design.infor.com/components/button/test-badge-toggle.html
<img width="341" alt="image" src="https://user-images.githubusercontent.com/56722184/166222470-02b00fbd-6945-4cd4-80be-407e01158ba9.png">
