### ISSUE TITLE
Clicking datepicker icon when the calendar is shown does not hide the calendar

### ISSUE THREAD

**Issue by inforrpunay** [infor-design/enterprise-ng#1244]
**Describe the bug**
Clicking datepicker icon when the calendar is shown does not hide the calendar. This previously works in [4.29.3](https://design.infor.com/code/ids-enterprise/4.29.3/demo/components/datepicker/example-index.html).

**To Reproduce**
1. Go to [this demo](https://design.infor.com/code/ids-enterprise/4.60.0/demo/components/datepicker/example-index.html)
2. Click on the datepicker icon to show the calendar
3. Click on the datepicker icon again while the calendar is shown
4. You can observe that the calendar appears to hide then show again

**Expected behavior**
The calendar is expected to hide upon clicking the icon while it is shown

**Version**
- ids-enterprise: 4.60.0

**Screenshots**

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 98.0.4758.102 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
We actually noticed this on a PR in this area and fixed it already in 4.61 so you can see it here:

https://main-enterprise.demo.design.infor.com/components/datepicker/example-index.html

**Comment by janahintal** [comment]
This issue is now resolved. Verified in https://main-enterprise.demo.design.infor.com/components/datepicker/example-index.html
Thanks!
