### ISSUE TITLE
Tabs: Inactive tabs background is no longer darker when a color is selected

### ISSUE THREAD

**Issue by inforrpunay** [infor-design/enterprise-ng#1245]
**Describe the bug**
Background color for active and inactive tabs is the same when you use a color other than the default. For the default, inactive tabs have darker background color. This works in [4.52.0](https://design.infor.com/code/ids-enterprise/4.52.0/demo/components/tabs-module/example-index.html)

**To Reproduce**
1. Go to [this demo](https://design.infor.com/code/ids-enterprise/4.60.0/demo/components/tabs-module/example-index.html).
2. Here you can observe that the inactive tabs have darker background color.
3. Switch to a different color other than Default.
4. Now you cannot see a difference in the background color between the active and inactive tabs

**Expected behavior**
Inactive tabs have darker background color

**Version**
- ids-enterprise: v4.60.0

**Screenshots**
![image](https://user-images.githubusercontent.com/55830499/156295749-97fc2e9b-b1de-43cc-a6e3-64c2a023d106.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 98.0.4758.102 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
@inforrpunay which team are you from. thanks!

**Comment by inforrpunay** [comment]
> @inforrpunay which team are you from. thanks!

Hi @tmcconechy, I am part of the M3 team. Regards!

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
