### ISSUE TITLE
Move @angular/cli in dependencies of publish script to peerDependencies

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#125]
**Describe the bug**
At the moment, when installing `enterprise-ng`, it will automatically install `@angular/cli@^6.0.7`.
I think `enterprise-ng` should not take care of installing `@angular/cli`. It should only inform the user via `peerDependencies` that they need to have `@angular/cli@^6.0.0` to be able to use the latest release version of `enterprise-ng` (v4.8)

**To Reproduce**
**N.A.**

**Expected behavior**
`@angular/cli` should be in `peerDependencies` instead of `dependencies` in https://github.com/infor-design/enterprise-ng/blob/master/publish/package.json

**Screenshots**
**N.A.**

**Platform**
 - Device **N.A.**
 - OS Version: **N.A.**
 - Browser Name **N.A.**
 - Browser Version **N.A.**

**Additional context**
**N.A.**

**Comment by tmcconechy** [comment]
Here's a good write up on peerDependencies for anyone reading this. https://nodejs.org/en/blog/npm/peer-dependencies/

I'm wondering if Angular CLI is even a dependency at all. Several teams are using these without CLI although to me it is highly recommended.

Thoughts on this?

**Comment by ahnpnl** [comment]
agree with @tmcconechy about `@angular/cli` shouldn't be a dependency at all. Actually `enterprise-ng` codes use other packages of Angular like `@angular/core`, `@angular/common` etc. Perhaps they are worth to be added in peer dependencies rather than `@angular/cli`.

**Comment by bthharper** [comment]
Totally agree with @ahnpnl.   From a publishing perspective, `@angular/cli` is not required, only for building.

**Comment by tmcconechy** [comment]
Right building :) Ok so is it easy as moving these to peerDependencies? In this and quick start?

**Comment by anhallbe** [comment]
If `@angular/cli` is only used for building, then shouldn't it be a devDependency?

I.e it should be installed when running `npm i` in the source directory, but it should never be installed with `npm i enterprise-ng`

**Comment by bthharper** [comment]
@tmcconechy  I think this can be closed now, as #143 as been committed.  We only include the dependencies we required and the use of `@angular/cli` is optional.
