### ISSUE TITLE
Datagrid: Column Drag Behavior

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-ng#1252]
**Describe the bug**
When a column separator is drag to resize a column, the width of the column does not follow the mouse move and resizes randomly.

**To Reproduce**
1. Get latest enterprise-ng main branch (March 3, 2022)
2. Build and run
3. Open Datagrid Angular Editor
4. Resize the first column
5. Size does not always follow the mouse, sometimes the size changes randomly

**Expected behavior**
Column Drag - Resize should follow the mouse.

**Version**
- ids-enterprise-ng: v13.0.2, main

**Screenshots**
Attached video

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]

https://user-images.githubusercontent.com/53523076/157604662-3f1e419c-b843-4676-ab07-f71dc24ba982.mp4

 - Browser Name : chrome
 - Browser Version  99.0.4844.51

**Comment by tmcconechy** [comment]
We are aware of the behavior not being perfect but we have tried and there is no viable fix. The datagrid would need to be refactored to be a set of divs and rewrite the drag code. We are doing this on a 5.x version for later so it may be fixed there. But no easy fix at the moment. I think it does work ok for now
