### ISSUE TITLE
DatePicker: writeValue returns an Invalid Date if we pass empty string

### ISSUE THREAD

**Issue by sjasaniel** [infor-design/enterprise-ng#1256]
**Describe the bug**
writeValue returns an Invalid Date if we pass empty string. This only happens on date/timestamp range field when we're trying  to clear the value.

**To Reproduce**
Add this line in datepicker.demo.ts::clear
  clear() {
    this.model.standard = new Date(0);
    this.model.range2 = '';   <=====
  }
1. Go to 'http://localhost:4200/ids-enterprise-ng-demo/datepicker'
2. Select start and end date in range2 field (label is Date with Range (set via range))
3. Press clear button.

**Expected behavior**
range2 value should be cleared. 

**Actual Result**
the value in range2 becomes NaN

**Version**
- ids-enterprise-ng:

**Screenshots**
![InvalidDate](https://user-images.githubusercontent.com/9715303/158550669-8b962a12-aea8-48f6-a164-bfde9b98ddf5.gif)

**Platform**
 - OS Version: WIndows10
 - Browser Name Chrome
 - Browser Version: 99.0.4844.74 (Official Build) (64-bit)

**Additional context**
project: Landmark

**Comment by jbrcna** [comment]
QA Passed. v4.63.0-dev
https://main-enterprise.demo.design.infor.com/components/datepicker/test-input-datefield-clear.html
