### ISSUE TITLE
Lookup: Changing the selection results in incorrect selections

### ISSUE THREAD

**Issue by madebyannalam** [infor-design/enterprise-ng#1258]
**Describe the bug**
When we have a Lookup Component set up as a single select, with pagination enabled and running in async mode, the popup modal is returning multiple selections when one jumps between selections repeatedly.

**To Reproduce**
Please refer to the attached Stackblitz: [Lookup Single Select Async Bug](https://lookup-single-select-async-bug.stackblitz.io/) ([Source code](https://stackblitz.com/edit/lookup-single-select-async-bug))
1. Run the above Stackblitz
2. Open the modal
3. Select the 1st item on page 1
4. Reopen the modal and navigate to page 2 and select select any of the items from that page
5. Reopen the modal and select any item from page 1. At this point, you should have 2 selections in the textbox.
6. If, at step 5, you do not have the 2 selections, repeat steps 3-5 until you do.

**Expected behavior**
No matter how many times we change the selection for a single select scenario, we should only ever return a single selection from the modal.

**Version**
- ids-enterprise-ng: 13.0.1

**Screenshots**
![image](https://user-images.githubusercontent.com/93908047/159196984-b93c1ddd-6268-470b-b9df-605eb27d2a12.png)

**Platform**
 - Device (if applicable): Dell Laptop
 - OS Version: Windows 11 Enteprise
 - Browser Name: Google Chrome
 - Browser Version: Version 99.0.4844.74 (Official Build) (64-bit)

**Additional context**
This issue was reported on behalf of Sumeeth Prabhakar of the MRM team.

**Comment by tmcconechy** [comment]
@thatannalam can you test it with
```
          [options]="{
...
            allowSelectAcrossPages: true,
...
          }"
```

There is an option that might make it work? Also i suggest adding a checkbox column if using multiselect

**Comment by SumeethPrabhakar** [comment]
adding  allowSelectAcrossPages: true to options has not fixed the issue.
