### ISSUE TITLE
Dropdown: Opening a dropdown by clicking does not allow moving with arrow keys

### ISSUE THREAD

**Issue by xqses** [infor-design/enterprise-ng#1262]
**Describe the bug**
Nesting two dropdowns within a label next to a radio button makes the dropdown menus unable to be navigated using the arrow keys. Which maybe seems like a bit odd of use-case but it's used for adding Announcments to Homepages. The bug only appears if we have a radio button next to the label. The bug only appears if we open the dropdown by clicking on it - tabbing to focus the dropdown and using the arrow keys works fine.

**To Reproduce**
1. Add a (Soho) radio button next to a (Soho) label within a block element.
2. Add two dropdown menus inside the label alongside some text.
3. Click on one of the dropdowns.
4. Use the arrow keys to try to navigate the menu.
6. See error

**Expected behavior**
We should be able to navigate the dropdown using the arrow keys.

**Version**
- ids-enterprise-ng: "13.2.1"

**Screenshots**
GIF: https://imgur.com/a/RlzbNFX
(I'll admit the GIF is not perfect for showing that we are trying to navigate the dropdown using the arrow keys - but later in the video we tab to the element and navigate using the arrow keys).
[Reproducible code](https://github.com/xqses/ids-repro/tree/master/src/app/double-dropdown)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: Windows 11
 - Browser Name Chrome, Edge, stock browser]
 - Browser Version latest

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/dropdown/test-label?theme=classic&mode=light&colors=2578a9
![image](https://user-images.githubusercontent.com/45757016/167561011-2fd5215c-9742-46b1-aaae-3b141556e9ec.png)
