### ISSUE TITLE
ListBuilder: as an angular component

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise-ng#1264]
**Is your feature request related to a problem? Please describe.**
In the specs from our designers, we will be needing the [ListBuilder](https://design.infor.com/code/ids-enterprise/latest/listbuilder) as an angular component.

**Describe the solution you'd like**
Be able to use the listbuilder as a angular component.

**Describe alternatives you've considered**
Considerd using the web component (if done?), but since those are not released, and from what I think i've read, you cannot use them in combination with AOT (?), that is not really an option for us at this time.

**Comment by tmcconechy** [comment]
We could add the NG component for this (not sure why we went to long without it). But you could also try the web component. It is done and done a lot better than the old one. Its 0.0.0-beta right now. I think it would be a good test.

Would like the most to here about what your thinking with AOT? How would I test this. Seems like something we should make work....

**Comment by whernebrink** [comment]
@tmcconechy, I might have mistakenly based that it "won't work with AOT" on [this comment ](https://github.com/infor-design/enterprise-wc-examples/blob/e04ca22782d5294fa7335a58505b5fd8371a2409/angular-ids-wc/src/helpers/native-element.decorator.ts#L5) by you (?). But now when reading it, it seems like it is just the helper function that won't work in AOT? :)

**Comment by tmcconechy** [comment]
Ah i see. i got this code someplace - so not sure about that comment. But this enabled me to use this https://github.com/infor-design/enterprise-wc-examples/blob/main/angular-ids-wc/src/app/app.component.ts#L16 which is a convenience only thing that made it possible to cast the ViewChild to the actual type in one step.

It isn't entirely needed and i don't know whether or not it doesn't work in AOT. Also we might change to 100% Typescript which may change the way this works/further prevent the need.
I'll keep this in mind.

**Comment by whernebrink** [comment]
Alright! We can check out the web component then when we need the list builder. Would be interesting to try actually. :)

> Also we might change to 100% Typescript

Do you mean for all web components?

**Comment by tmcconechy** [comment]
Yes the web component will be ts files (mostly js but generating the d.ts with ts and some types and sprinkling of TS). Might help in other ways...

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
