### ISSUE TITLE
DatePicker: Issue with format date for french and Deutsch  local

### ISSUE THREAD

**Issue by manel-abbes** [infor-design/enterprise-ng#1273]
**Describe the bug**
Hello Team, I upgrade the angular version from 12 to 13 and the ids-enterprise-ng version from 10.6.1 to 13.3.1, I get an issue  with the french local with the range mode a format NaN/NaN/NaN -NaN/NaN/NaN is displaying instead the start and the end date 
I used the dd/MM/yyyy for french local and dd.MM.yyyy for the Deutsch. it returns an invalid date you can find a screenshot. 

**To Reproduce**
1. Go to date picker with range mode 
3. NaN/NaN/NaN -NaN/NaN/NaN is displaying instead the start and end date  for french local 

**Expected behavior**
the start and end date must display instead of the invalid date 

**Version**
- ids-enterprise-ng: [13.3.1]

**Screenshots**
![image](https://user-images.githubusercontent.com/82028679/164035906-f890b044-cb61-443a-89b7-005bc7f02793.png)

**Comment by tmcconechy** [comment]
How did you make the example show french mode? I.E. what changes have to be made to see this in the NG app?

**Comment by manel-abbes** [comment]
i set the date format to dd/MM/yyyy and  i work with an example according to the date format, for the enterprise project

**Comment by tmcconechy** [comment]
Can you post the code changes? Im still not sure what to change where to see it

**Comment by tmcconechy** [comment]
cc @manel-abbes see above

**Comment by manel-abbes** [comment]
Hello, Sorry for my late reply, i tried to execute the issue on stackblitz with the same package  i just modify the format of dateFormat  tp dd/MM/yyyy and the range2 in the modal to get the issue  .
https://stackblitz.com/edit/ids-quick-start-1331-bfswhx?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/datepicker/test-datepicker-french.html?theme=classic&mode=light&colors=2578a9
![image](https://user-images.githubusercontent.com/45757016/177522230-1491f97c-9f06-4fef-9631-82d63a721292.png)
![image](https://user-images.githubusercontent.com/45757016/177523490-925f31f2-83f2-445d-aed3-d768f621477f.png)
