### ISSUE TITLE
Datagrid: Shift-click on the always selects the first row

### ISSUE THREAD

**Issue by inforrpunay** [infor-design/enterprise-ng#1274]
**Describe the bug**
When performing multi-select of rows using shift-click, the datagrid selects even the unwanted rows from the first row all the way to the bottom of the intended rows to be selected. This can be observed when using tree grid.

**To Reproduce**
1. Go to [this stackblitz](https://stackblitz.com/edit/ids-quick-start-1311-kt9oe2)
2. Make sure that no row is selected
3. Click on the row with Id = 295 to select it
4. Perform a shift-click on the row with Id = 298
5. You can observe that rows with Id = 1 up to Id = 298 are all selected. A slight delay in row selection can also be observed.

**Expected behavior**
Only rows with Id = 295 to 298 are selected

**Version**
- ids-enterprise: 4.60.0

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 100.0.4896.127 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Yes something seems wrong in your example but it seems to work as expected on https://main-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html

Looking at the example It seems weird its got `[treeGrid]="true"` turned on but it is not a tree grid - can you remove that setting as i suspect it might treat the selections as if its a tree.

**Comment by inforrpunay** [comment]
> Yes something seems wrong in your example but it seems to work as expected on https://main-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html
> 
> Looking at the example It seems weird its got `[treeGrid]="true"` turned on but it is not a tree grid - can you remove that setting as i suspect it might treat the selections as if its a tree.

Hi @tmcconechy, we need to use `[treeGrid]="true"`. We have cases where our list can have children. You can also encounter the issue in this example: https://design.infor.com/code/ids-enterprise/4.60.0/demo/components/datagrid/test-tree-select-multiple.html. First, click on the row with Id=4 then do a shift-click on the row with Id=8. Regards!

**Comment by tmcconechy** [comment]
Yeah i see - this is a confusing interaction in this situation

**Comment by tmcconechy** [comment]
@ericangeles can you assign this one. Maybe @davidcarlsonberg is available?

**Comment by janahintal** [comment]
QA Passed. Verified in http://localhost:4000/components/datagrid/test-tree-multiselect-no-children.html
<img width="1938" alt="Screen Shot 2022-06-30 at 4 06 31 PM" src="https://user-images.githubusercontent.com/45757016/176626259-40520bc3-d8e3-4708-afe0-ec0865e8bc19.png">
