### ISSUE TITLE
Memory Leak: Card, ListView, Toolbar-Flex, HeaderToolbar an

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-ng#1275]
**Describe the bug**
Memory leak on IDS components. Detached Html Elements accumulates after destroying these components:
Card, ListView, Toolbar-Flex, HeaderToolbar and Datagrid-Custom Formatter Components

Card – http://localhost:4200/ids-enterprise-ng-demo/cards
Toolbar Flex - http://localhost:4200/ids-enterprise-ng-demo/toolbar-flex-basic 
ListView - http://localhost:4200/ids-enterprise-ng-demo/listview
Header-Toolbar - http://localhost:4200/ids-enterprise-ng-demo/header-toolbar
Datagrid Custom Formatter - http://localhost:4200/ids-enterprise-ng-demo/datagrid-custom-formatter

**To Reproduce**
1)	Run enterprise-ng
2)	Select the Card demo
3)	Open Dev tools
4)	Select Memory tab – select Allocation Instrumentation on timeline
5)	Record and stop after 3 seconds. This is to stablish a baseline for comparing the detached html elements
6)	Filter for “detached html”
7)	Start a new record
8)	Click on the demo next to Card demo and then go back to Card demo. This should destroy the components on Card demo and create new ones
9)	Click on Force Garbage Collect and Stop recording
10)	Filter for “detached html”
11)	Compare the two recordings
12)	New detached elements have been added. This accumulates as more Card demo components are created and destroyed.

**Expected behavior**
There should be no detached HTML elements found after destroying the components. Other demo components does not leave any or accumulate any detached HTML elements.

**Version**
- ids-enterprise-ng: [main/13.x]

**Screenshots**
Attached video of the replication

**Platform**
 - OS Version: [e.g. Windows 11

https://user-images.githubusercontent.com/53523076/164233576-5280971e-8401-4c74-9a07-9417a44c472b.mp4

 - Browser Name [e.g. chrome]
 - Browser Version [100.0.4896.75 (Official Build) (64-bit)]

**Additional context**

https://user-images.githubusercontent.com/53523076/164233352-3f93004f-4cce-4762-a2f6-5f372c737d31.mp4

Opening and closing components on the enterprise-ng demo components to check for memory leaks.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
