### ISSUE TITLE
Popupmenu: Overlapping popup menus after context menu element is removed

### ISSUE THREAD

**Issue by xqses** [infor-design/enterprise-ng#1280]
**Describe the bug**
If we have a popup menu opened as a context menu, opening another popup menu as a context menu (via right-click) will close the first menu. However, if we have a list of context menus linked to a popup menu, and one of the menus are removed, going through the same process as earlier will not close the first popup menu when the second menu is opened, resulting in overlapping menus.
**To Reproduce**
1. Go to [this repro example](https://xqses.github.io/ids-repro/popupmenu-overlapping).
2. Right click one of the context menu items, observe a popupmenu opening.
3. Right click the widget backdrop, observe the first popupmenu closing and a new popupmenu opening.
4. Right click one of the visible context menu items and select ("Remove whale"), observe that the menu element will be removed.
5. Right click one of the remaining context menu items, observe a popupmenu opening.
6. Right click the widget backdrop, observe another popupmenu opening without closing the first menu.

**Expected behavior**
The open popupmenu should close when another popupmenu is opened.

**Version**
- ids-enterprise: Observed in 4.62, Homepages. (To reproduce there, do the same thing with the standard Mingle notes widget).

**Screenshots**
[GIF](https://imgur.com/a/ddqjlw2)
[Example source code.](https://github.com/xqses/ids-repro/tree/master/src/app/popupmenu-overlapping)

**Comment by tmcconechy** [comment]
I do see the issue but wondering from a UX standpoint if its a bit of overuse of context menu having several menus on the same widget doing different things? Just mentioning as you could perhaps consider buttons for some actions.

But we will have a look when we can

**Comment by xqses** [comment]
Hi Tim, I see your point and agree to some extent. As far as I can tell, we have had this functionality for the widget for many years, so changing the behavior would be impactful. My counterpoint is that it probably shouldn't be too difficult to extend whatever method(s) is/are checking for '.is-open', and to remove that class from all open popupmenus, when it is relevant?
 
I.e., I don't think this needs to be fixed in particular for this problem, but more likely this problem just means that closing open popupmenus is not rigorous enough.
