### ISSUE TITLE
Button Component: hide-focus class disrupts button css

### ISSUE THREAD

**Issue by kels0** [infor-design/enterprise-ng#1282]
**Describe the bug**
When changing between button classes "Primary", "Secondary" and "Tertiary" there is a new another class prepending into Buttons classes.
The class "Hide-focus" is put in the front and disrupts the css of the button.

**To Reproduce**
https://stackblitz.com/edit/ids-quick-start-1331-sbzvm1?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
The button should keep the css and "hide-focus" class should be appended in the back.

**Version**
13.3.1

**Screenshots**
Attached stackblitz link.

**Platform**
All

**Additional context**

**Comment by kels0** [comment]
If I also add a class for example "**busy-sm**" it will also disrupt the button css.

**Comment by jbrcna** [comment]
QA Passed. v4.64.0-dev
https://main-enterprise.demo.design.infor.com/components/button/test-button-change-style.html
<img width="705" alt="image" src="https://user-images.githubusercontent.com/56722184/170911464-4524a668-18bf-41bc-9afc-6bae086ebd46.png">
