### ISSUE TITLE
Datagrid: Add virtualization setting

### ISSUE THREAD

**Issue by inforrpunay** [infor-design/enterprise-ng#1288]
**Is your feature request related to a problem? Please describe.**
A slowness in datagrid process is encountered when there are already more than a hundred rows available.

**Describe the solution you'd like**
Angular implementation for this sample: https://design.infor.com/code/ids-enterprise/4.60.0/demo/components/datagrid/test-large-dataset-performance-virtualized.html

**Additional context**
We noticed that virtualized option is removed for the angular implementation of soho-datagrid
![image](https://user-images.githubusercontent.com/55830499/166657375-5c0c35d2-937d-421f-bd5e-5d0c2d7c32b8.png)

**Comment by tmcconechy** [comment]
The reason this is disabled is it doesn't work very well. I think to fix it we will have to redo the core of the datagrid. We have started this in the new version with this in mind.

That example works ok but its clunky when scrolling and almost every feature doesn't work well like editing ect. It might be ok with an entirely readonly grid tho. But any other features we would have to recode them.

So not wanting to introduce this as it will introduce more issues that are pretty much impossible to fix without rewrite from the core up so dont think its worth allowing teams to use this at this point.

**Comment by tmcconechy** [comment]
Using paging for now... As a way to solve this.

**Comment by EdwardCoyle** [comment]
Noting here that:
- Currently we aren't able to integrate virtualization into the 4.x datagrid per Tim's comments above
- M3 is unable to use paging as a workaround (their users are not expecting the pager to be added)
- M3 is currently waiting on a fully-supported version of the WebComponents datagrid so they can use virtualization.

**Comment by tmcconechy** [comment]
Also noting I am working on it this sprint next and the remaining items are listed on https://github.com/infor-design/enterprise-wc/issues/737 based one what was told was being used
