### ISSUE TITLE
Swaplist: Question on how to clear/filter

### ISSUE THREAD

**Issue by ashachodavarapu** [infor-design/enterprise-ng#1290]
<soho-swaplist
id="documents-swaplist"
searchable="true"
availableCardTitle="{{ 'MODEL_DETAILS.AVAILABLE_DOCUMENTS' | deskTranslate }}"
availableCardSearchTitle="{{ 'MODEL_DETAILS.SEARCH_DOCUMENTS' | deskTranslate }}"
[availableItems]="availableDocuments"
selectedCardTitle="{{ 'MODEL_DETAILS.SELECTED_DOCUMENTS' | deskTranslate }}"
selectedCardSearchTitle="{{ 'MODEL_DETAILS.SEARCH_DOCUMENTS' | deskTranslate }}"
[selectedItems]="selectedDocuments"
[attributes]="[{ name: 'id', value: 'documents' }]"
(updated)="onDocumentSelected()"
>
</soho-swaplist>

I am trying to clear filter -> after reload -> Soho-swaplist component-
I can't find a filter event emitter in the Soho-component

My problem-
When I refresh the component/reset the data the filter in available items are refreshed/defaulted but the filter is not working even though the text is present in the filter box which i entered before, the problem is shown in the attachments.

My concerns-
* How to clear the data from the filter box?
*How to get the filter value and filter it in my component?
*Can we send the filter value in the soho-swaplist -> null to clear it?
*Can you tell me how to implement the filter?

![1](https://user-images.githubusercontent.com/105051938/167121983-d5a0ed16-3210-4929-b555-c62d0ad50999.jpg)
![2](https://user-images.githubusercontent.com/105051938/167121991-3bedb83d-abf4-45fa-87ec-f9768a874c1c.jpg)

**Comment by tmcconechy** [comment]
@ashachodavarapu we don't have any way to do this as the search is part of the swaplist template and internalized. But when you reload the page it should be cleared. it is on example http://localhost:4200/ids-enterprise-ng-demo/swaplist-search

So not seeing a way you can access it and manipulate it manually. Unless you use js and query the DOM and find it?

**Comment by tmcconechy** [comment]
Closed and answered for what we have right now
