### ISSUE TITLE
Chart: Wrong interfaces of SohoChartSelectEvent

### ISSUE THREAD

**Issue by kkoscielski** [infor-design/enterprise-ng#1296]
The result that is logged in the console differs from the following Soho interfaces: SohoBarSelectEvent, SohoPieSelectEvent, SohoColumnSelectEvent, SohoLineSelectEvent.

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/bar/test-selected?theme=uplift&variant=light
2. Click on any bar.
3. See the result that is logged in the console.
4. The documentation suggests that SohoBarSelectEvent looks like:
```
interface SohoBarSelectEvent {
  elem: HTMLElement[];
  data: any[];
  index: number;
}
```
**Expected behavior**
The actual result is an array of SohoBarSelectEvent (see attached photo as well).

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/column-grouped/example-get-selected?theme=uplift&variant=light
2. Click on any column.
3. See the result that is logged in the console.
4. The documentation suggests that in the case of column-grouped or bar-grouped chart SohoColumnSelectEvent looks like:
```
interface SohoColumnSelectEvent {
  elem: HTMLElement[];
  data: any[];
  index: number;
}
```
**Expected behavior**
In the case of column-grouped or bar-grouped chart the actual result contains three properties: groupElem, groupIndex and groupItems. The groupItems property is an array of SohoColumnSelectEvent or SohoBarSelectEvent (see attached photo):

**Version**
- ids-enterprise-ng: ^13.1.1,

**Screenshots**
![image](https://user-images.githubusercontent.com/105841567/169222391-0b913ddf-3938-4edb-825c-1c027120229b.png)
![image](https://user-images.githubusercontent.com/105841567/169222343-1debaa54-88c1-4d2d-8e4e-5f3031b4ee96.png)

**Comment by jbrcna** [comment]
https://main-enterprise.demo.design.infor.com/components/bar/test-selected?theme=uplift&variant=light
<img width="571" alt="image" src="https://user-images.githubusercontent.com/56722184/175239403-78ba4c6f-bdd3-4118-b5f7-143367175a2a.png">

https://main-enterprise.demo.design.infor.com/components/column-grouped/example-get-selected?theme=uplift&variant=light
<img width="570" alt="image" src="https://user-images.githubusercontent.com/56722184/175239816-6cde8531-67b3-4a40-b653-d33598f94752.png">

**Comment by jbrcna** [comment]
QA Passed.
https://main-enterprise.demo.design.infor.com/components/bar/test-selected?theme=uplift&variant=light
<img width="571" alt="image" src="https://user-images.githubusercontent.com/56722184/175239403-78ba4c6f-bdd3-4118-b5f7-143367175a2a.png">

https://main-enterprise.demo.design.infor.com/components/column-grouped/example-get-selected?theme=uplift&variant=light
<img width="570" alt="image" src="https://user-images.githubusercontent.com/56722184/175239816-6cde8531-67b3-4a40-b653-d33598f94752.png">
