### ISSUE TITLE
Chart: Wrong type of the data property in SohoChartSelectEvent

### ISSUE THREAD

**Issue by kkoscielski** [infor-design/enterprise-ng#1297]
The result that is logged in the console differs from the following Soho interfaces: SohoBarSelectEvent, SohoPieSelectEvent, SohoColumnSelectEvent, SohoLineSelectEvent. 

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/bar/test-selected?theme=uplift&variant=light
2. Click on any bar.
3. See the result that is logged in the console.
4. The documentation suggests that the property called “data” is an array of any type:
interface SohoBarSelectEvent {
  elem: HTMLElement[];
  data: any[];
  index: number;
}

**Expected behavior**
The actual result is not the array, but an object (see the attached photo):

**Version**
- ids-enterprise-ng: ^13.1.1,

**Screenshots**
![image](https://user-images.githubusercontent.com/105841567/169311563-4989c4fb-ba9e-4d7d-995a-52ff9db08d02.png)

**Comment by tmcconechy** [comment]
Do feel free to do a Pull request if you see a fix. It could take us a while to get to this
