### ISSUE TITLE
Datagrid: Tooltip callback returning wrong data when grouping is used

### ISSUE THREAD

**Issue by ftunholm** [infor-design/enterprise-ng#1298]
**Describe the bug**
When enabling tooltip for data grid and using the callback function to provide a custom tooltip for a cell, the wrong rowData will be passed to the callback function when grouping is enabled on the data grid. Without grouping it works as expected.

**To Reproduce**
1. Setup a data grid.
2. group it by a random column.
3. enable contentTooltip on another column + callback function for the tooltip.
4. Inspect the "rowData" argument in the callback function when the tooltip gets activated for your column.

https://stackblitz.com/edit/ids-quick-start-1331-pinfxk?file=src/app/grid-tooltip/grid-tooltip.component.ts

**Expected behavior**
That the correct rowData is passed to the callback function - the same behaviour as when not using grouping.

**Version**
10.1.3

**Screenshots**
When grouping is used:
![image](https://user-images.githubusercontent.com/8871986/169541781-3c40d421-3a41-4ae4-92b0-8ca02c72fd67.png)

When grouping is NOT used:
![image](https://user-images.githubusercontent.com/8871986/169542043-eddefdbd-04ae-407a-9b99-00e8c4bda482.png)

Callback function:
![image](https://user-images.githubusercontent.com/8871986/169542177-d6038f14-aa89-44bc-8341-d2c283f608cc.png)

**Platform**
Google Chrome Version 101.0.4951.67 (Official Build) (64-bit)

**Additional context**
-

**Comment by tmcconechy** [comment]
@ftunholm - i dont really 100% understand what to do to reproduce the issue. Can you make an example using the stackblitz template https://stackblitz.com/edit/ids-quick-start-1331?file=src%2Fapp%2Fapp.component.ts maybe?

Or something we can drop in the project and run?

**Comment by ftunholm** [comment]
@tmcconechy I can definitely create a working example to reproduce. I would not mind giving it a try on a pull request. 

Can you point me to the file in the repo where the callback is done? And I'll clone it down and have look.

Have a good weekend!

**Comment by tmcconechy** [comment]
I think that the fix would be in this repo https://github.com/infor-design/enterprise/ (not the ng wrapper). I was a little confused about the contentTooltip part but thats here: https://github.com/infor-design/enterprise/blob/main/src/components/datagrid/datagrid.js#L12389 - its idea is to use the content for the rich text editor in a tooltip

But the call back is here https://github.com/infor-design/enterprise/blob/main/src/components/datagrid/datagrid.js#L12503

Im sure the rowData is not taking grouping into account. You could modify a grouping example to show a tooltip and run this repo https://github.com/infor-design/enterprise/tree/main/app/views/components/datagrid (with grouping in the name).

See also: https://github.com/infor-design/enterprise/blob/main/docs/DEVELOPER.md

Any questions ping me on Ms teams or here.

**Comment by ftunholm** [comment]
Hi @tmcconechy,

I have created an example to recreate the issue. Hope you will find it helpful. https://stackblitz.com/edit/ids-quick-start-1331-pinfxk?file=src/app/grid-tooltip/grid-tooltip.component.ts

A pull request with a fix would be a bit too time consuming for me at this point.

**Comment by jbrcna** [comment]
QA Passed
v4.66.0-dev
https://main-enterprise.demo.design.infor.com/components/datagrid/test-datagrid-grouping-tooltip.html
<img width="1655" alt="image" src="https://user-images.githubusercontent.com/56722184/180113769-87a25000-495d-4ed1-817d-3f8e2f630f8a.png">
