### ISSUE TITLE
Datagrid - expose the rowData property in SohoDataGridSelectedEvent for NG usage

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#1299]
**Describe the bug**
The datagrid selected event defines the event for a select or unselect to be SohoDataGridSelectedEvent.  In the SohoDatGridSelectedEvent, the provided rowData argument is not passed in NG.

**To Reproduce**
1. Go to 'ids-enterprise-ng-demo/datagrid-mixed-selection'
2. Click on the selection checkbox for rows 1 & 2
3. Click on the selection checkbox for row 2 to unselect the row
4. Look at the console log, examine the event data
5. Notice that the rowData (for the unselected row) was not provided

**Expected behavior**
Expected the rowData to be included in the SohoDataGridSelectedEvent.

Note:
Changed datagrid-mixed-selection.demo.html to expose the selected event in the template.
Changed datagrid-mixed-selection.demo.ts to include a console log of what is received for the selected event.

When testing with enterprise using the datagrid example, example-mixed-selection.html the rowData argument is passed when a row is unselected.

**Version**
- ids-enterprise-ng: 13.3.4
- ids-enterprise: 4.64.0-dev.20220504

**Additional context**
Required for a feature being developed by Landmark.

**Comment by claudenbach** [comment]
![GitNG-1299](https://user-images.githubusercontent.com/39804038/169621353-fe9a9d8c-8eb5-4567-8d7c-3af840e4a329.gif)

**Comment by tmcconechy** [comment]
@claudenbach having a hard time following the issue it seems like its working for me?

I tried https://main-enterprise.demo.design.infor.com/components/datagrid/example-mixed-selection.html
-select 2 rows
-deselect 1 row -> now i see in the log the rows that are still selected

I pushed console logs for the events to main for this repo and if you pull the latest and run 

- go to http://localhost:4200/ids-enterprise-ng-demo/datagrid-mixed-selection
-select 2 rows
-deselect 1 row -> now i see in the log the rows that are still selected

Can you tell me whats missing? As im not seeing it. If you do have a fix feel free to PR im sure its my misunderstanding of the video

**Comment by claudenbach** [comment]
I've attached another example that hopefully illustrates the ask.

When I use http://localhost:4000/components/datagrid/example-mixed-selection.html, I've updated it slightly to show all of the parameters being passed on the selected event when the user unselects a row.  You'll notice that it passes the rows selected, the type of 'deselect' and rowData, which is for the unselected row.

Within datagrid.js, the method unselectRow, will trigger the select event...
if (!noTrigger) {
  self.element.triggerHandler('selected', [self._selectedRows, 'deselect', rowData]);
}

When testing in NG, the last argument of rowData (which is the unselected / deselected row's data) is not passed along.  This is what I'm requesting for NG users.

**Comment by claudenbach** [comment]
![GitUnselectExample](https://user-images.githubusercontent.com/39804038/170762536-d6b9680b-fd4c-4abc-8d4b-9c138ee95548.gif)

**Comment by tmcconechy** [comment]
Got it - new i was missing something. Here you go: https://github.com/infor-design/enterprise-ng/pull/1306
Happy 🇺🇸  day weekend

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
