### ISSUE TITLE
Click outside of pop-down doesn't close the pop-down

### ISSUE THREAD

**Issue by AndrewDeiak** [infor-design/enterprise-ng#1304]
**Describe the bug**
Click outside of pop-down doesn't work in the example `http://localhost:4210/ids-enterprise-ng-demo/popdown`.
As discussed, by making the property `keepOpen` to false it should close pop-down in case user click outside of it.

**To Reproduce**
1. Go to `enterprise-ng\src\app\popdown\popdown.demo.ts`
2. Set option `[keepOpen]="false"` to `soho-popdown`
3. Run project, open browser, e.g. `http://localhost:4210/ids-enterprise-ng-demo/popdown`
4. Click on `My Cart`, `pop-down` is opened
5. Click outside of `pop-down` doesn't close the pop-down

**Expected behavior**
By making the property `keepOpen` to false it should close pop-down in case user click outside of it.

**Version**
- ids-enterprise-ng:  v^13.4.0

**Screenshots**

**Platform**
 - Browser Chrome

**Comment by tmcconechy** [comment]
It is working here on the core component https://main-enterprise.demo.design.infor.com/components/popdown/example-index.html so something wrong in the NG component maybe?

**Comment by AndrewDeiak** [comment]
Yes, I think something with angular component, that is root cause. Can you check it in Angular component implementation?

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
