### ISSUE TITLE
Datagrid: Menu buttons in contextual toolbar stops working when refreshed

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-ng#1309]
**Describe the bug**
When there is a `soho-menu-button` inside a Datagrid's `.contextual-toolbar`, the button stops working when datagrid properties are set (i.e when it is refreshed, I think?).

**To Reproduce**
1. Go to 'https://anhallbe.github.io/ids-repro/popupmenu-toolbar'
2. Follow instructions on the page

**Expected behavior**
The menu button should not stop working.

**Version**
- ids-enterprise-ng: 13.4.0

**Screenshots**
https://user-images.githubusercontent.com/4991954/170982664-9d384005-3809-4f29-9b3b-f91db90ddbd6.mov

**Additional context**
Original Ticket: https://jira.infor.com/browse/MINGLEDEV-35193
Repro source code: https://github.com/anhallbe/ids-repro/blob/master/src/app/popupmenu-toolbar/popupmenu-toolbar.component.html

**Comment by anhallbe** [comment]
@tmcconechy is there any way to bump the priority on this? Or perhaps if there's a workaround for it?

Here's original ticket for context: https://jira.infor.com/browse/MINGLEDEV-35194

**Comment by tmcconechy** [comment]
@ericangeles do you guys have the ability to pick this up this week for this sprint.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
