### ISSUE TITLE
Popups does not close if click event happens on different iframe

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise-ng#131]
**Describe the bug**
Popups are not disappearing if click inside iframe

**To Reproduce**
1. use this html code
```
<div>
  <div class="field">
    <label for="input-menu">Label</label>
    <input id="input-menu" type="text" value="Right Click Me" soho-context-menu menu="action-popupmenu" trigger="rightClick">
  </div>
  <ul soho-popupmenu id="action-popupmenu">
    <li soho-popupmenu-item><a soho-popupmenu-label>Hey</a></li>
  </ul>
  <iframe src="https://www.wikipedia.org" style="height: 100vh; width: 100vh"></iframe>
</div>
```
1. rightlick popup menu
1. click in wikipediea content
1. witness popup not closing

**Expected behavior**
Popup would close even when clicking on iframe

**Screenshots**
![image](https://user-images.githubusercontent.com/10186522/42514238-3a8878f2-8459-11e8-9450-c42870bd792c.png)

**Comment by tmcconechy** [comment]
Descoping this issue as we are limited in what we can do here.
