### ISSUE TITLE
Datagrid: Toggle expandable row prgrammatically

### ISSUE THREAD

**Issue by jriedel-osp** [infor-design/enterprise-ng#1312]
**Describe the bug**
The method to toggle the expandable row detail of the datagrid `toggleRowDetail(dataRowIndex)` (as described in the docs [here](https://design.infor.com/code/ids-enterprise/latest/datagrid)) isn't available in the angular wrapper package `ids-enterprise-ng`.

**Expected behavior**
I want to toggle the expandable row of the datagrid programmatically.

**Version**
- ids-enterprise: v4.63.2
- ids-enterprise-ng: 13.4.1

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
