### ISSUE TITLE
Soho Editor: dark screen when trying to insert an image.

### ISSUE THREAD

**Issue by JBismonte** [infor-design/enterprise-ng#1323]
**Describe the bug**
We're trying to attach an image with the following URL in the soho editor, clicking insert causes the screen to get stuck

**To Reproduce**
1. Go to http://localhost:4200/ids-enterprise-ng-demo/editor
2. Click on the insert an image button from the toolbar of the soho editor.
3. Paste the following link https://helpx.adobe.com/content/dam/help/en/photoshop/using/convert-color-image-black-white/jcr_content/main-pars/before_and_after/image-before/Landscape-Color.jpg and click insert
4. this will leave a dark screen on the page.

**Expected behavior**
Image to be successfully on the editor.

**Version**
- ids-enterprise-ng: 13.5
- ids-enterprise: 4.64

**Screenshots**

https://user-images.githubusercontent.com/29673378/173756632-47f8a556-d4ad-475a-a2ae-11249f6759a6.mp4

**Platform**
 - Team: Landmark
 - Device (if applicable) : NA 
 - OS Version: Windows 10
 - Browser Name : Firefox
 - Browser Version: 101.0.1

**Additional context**[
Infor Jira Ticket](https://jira.lawson.com/browse/LMCLIENT-40675)

**Comment by tmcconechy** [comment]
Seems like just a check is needed:

<img width="422" alt="Screen Shot 2022-06-15 at 9 52 40 AM" src="https://user-images.githubusercontent.com/814283/173844902-4ccf2aed-9ef9-4a92-822b-029845090640.png">

Also can probably work around it by providing an empty setting for attributes

**Comment by tjamesallen15** [comment]
Hello, @tmcconechy , 

I believe this is connected to a policy issue, I tested this on IDS and it displaying a broken image.
![image](https://user-images.githubusercontent.com/34049950/180914589-7e22b3ee-41b8-43c6-a192-3c1c2dfe2270.png)
