### ISSUE TITLE
Toolbar teardown error

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-ng#1327]
**Describe the bug**

**To Reproduce**
1. Build and run IDS enterprise-NG demo
2. Go to Soho Contextual Action Panels,
3. open, and then close `Panel with Searchfield in flex toolbar`

**Expected behavior**
Overlay should go away, but stays.

**Version**
- ids-enterprise-ng: 14.0.2

**Screenshots**
![contextual-panel-close-error](https://user-images.githubusercontent.com/542598/174621988-2e2c877c-6ee3-48e6-8f9d-f4069bd263db.gif)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
