### ISSUE TITLE
Datagrid: Not reacting to to empty dataset when grouping is used

### ISSUE THREAD

**Issue by ftunholm** [infor-design/enterprise-ng#1332]
**Describe the bug**
When passing an empty dataset to the datagrid while grouping is enabled then the grid will not display empty data, old dataset will remain for display. If grouping is not enabled then the datagrid seems to behave normally.

**To Reproduce**
Project to reproduce the issue:

https://stackblitz.com/edit/ids-quick-start-1331-7jseth?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
That the datagrid is cleared when passing an empty dataset.

**Version**
10.1.3

**Screenshots**
"Data1" checkbox will toggle an empty dataset and a populated dataset. Group checkbox will toggle grouping.

![image](https://user-images.githubusercontent.com/8871986/175881992-1ecbf102-0240-4d32-bf3a-53c9f91a4fe7.png)

**Platform**
Chrome: Version 102.0.5005.115 (Official Build) (64-bit)

**Additional context**

**Comment by jbrcna** [comment]
QA PAssed
v4.66.0-dev
https://main-enterprise.demo.design.infor.com/components/datagrid/test-grouping-update.html
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/56722184/182286847-6d26af2b-99f8-4d0d-8767-45e5527dee5d.png">
