### ISSUE TITLE
Datepicker: Second Today click on datepicker dialog does not trigger change event

### ISSUE THREAD

**Issue by Michael-Cao** [infor-design/enterprise-ng#1334]
**Describe the bug**

**To Reproduce**
1. Go to datepicker for range field. https://main-enterprise.demo.design.infor.com/components/datepicker/example-range.html
2. Click on 'Calendar icon in the input box', datepicker dialog prompts
3. Click "Today" link on the datepicker dialog
4. Check browser console, change event could be found
5. Click "Today" link again on the datepicker dialog 
6. Check browser console, no change event found.
7. no such issues for click digit link on the datepicker dialog

**Expected behavior**
Like clicking digit link on the datepicker dialog, both "Today" click should trigger change event.

**Version**
- ids-enterprise-ng: 13.3.1

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: CentOS 
 - Browser Name: Chrome
 - Browser Version: Version 101.0.4951.54 (Official Build) (64-bit)

**Additional context**

**Comment by GlenlieMaye** [comment]
QA tested and passed.

**_before fix:_**
https://4500-enterprise.demo.design.infor.com/components/datepicker/example-range.html


https://user-images.githubusercontent.com/102151352/180166212-fec7fdc6-5593-44b0-8d90-c8737ce25065.mov


**_after fix:_**
https://main-enterprise.demo.design.infor.com/components/datepicker/example-range.html

https://user-images.githubusercontent.com/102151352/180166247-07202db9-f7ba-46b5-b230-01d356d3dade.mov
