### ISSUE TITLE
Datagrid: Columns in modal not covering the full width

### ISSUE THREAD

**Issue by Annfo637** [infor-design/enterprise-ng#1342]
**Describe the bug**
After update to 14.1.1 the columns of the datagrid in a modal no longer covers the full width of the modal. It seems the table now have a fixed width instead of adjusting to the modal's size. See screenshots below.

**Expected behavior**
The columns should cover the full width.

**Version**
- ids-enterprise-ng: 14.1.1

**Screenshots**
![image](https://user-images.githubusercontent.com/54262041/178777426-4b1cd9a9-7c31-49dd-ada6-9f83f55804fb.png)

![image](https://user-images.githubusercontent.com/54262041/178778976-9b2a92f5-59d0-48f1-a350-e0b68d286ab5.png)

**Platform**
 - OS Version: Windows 11
 - Browser Name Chrome
 - Browser Version 103.0.5060.114 (Official Build) (64-bit)

**Additional context**
This was also reported in the Teams channel: https://teams.microsoft.com/l/message/19:6d4c9079385840c0bc61e55bcdd16a33@thread.skype/1657621732870?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1657621732870&teamName=IDS%20Enterprise%20Development&channelName=Problems&createdTime=1657621732870

**Comment by radovaniljic** [comment]
The issue appears when setting a fixed width on the modal (or its content), which we were previously doing. We've changed that so this is no longer an issue for us. 

@tmcconechy This issue can be closed unless it's something you want to fix/change anyway.
