### ISSUE TITLE
Badges: Button badge won't work if there is a label

### ISSUE THREAD

**Issue by zyto45** [infor-design/enterprise-ng#1347]
**Describe the bug**
When there is a button with icon and label the badge directive won't work correctly. It is the same for notification-badge. In addition when passing custom attributes to NotificationBadgeOptions (attributes: {name: 'id', value: 'my-unique-id'}) there seems to be no effect at all (attribute is not added to notification badge element)

**To Reproduce**
https://stackblitz.com/edit/ids-quick-start-1411-tyjm7t

**Expected behavior**
I would expect, when there is a button with icon and label, position of badge should work as expected placing notification badge in upper-left corner of icon. Additional placement options could be considered whether lower-right should be applied to icon only or icon and label. 

When custom attributes are passed via NotificationBadgeOptions, they should be applied to html element.

**Version**
- ids-enterprise-ng: 14.1.2

**Screenshots**
![image](https://user-images.githubusercontent.com/57151167/180194840-a47d6d00-23df-4b65-8611-f970c863c551.png)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: Windows 10
 - Browser Name chrome
 - Browser Version 103.0.5060.114  (Official Build) (64-bit)]

**Comment by tmcconechy** [comment]
It "might" be possible to make this work on tertiary buttons but this was not considered in the original cases

**Comment by tmcconechy** [comment]
Maybe test this in web components as well and fix

**Comment by jbrcna** [comment]
QA Passed
https://main-enterprise.demo.design.infor.com/components/button/example-badge.html
<img width="870" alt="image" src="https://user-images.githubusercontent.com/56722184/187600275-2dbd505b-cf26-404b-9b00-1a9101fa94b0.png">
