### ISSUE TITLE
PopupMenu: popupMenuAPI.getSelected() does not work

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-ng#1349]
**Describe the bug**
Using @ViewChild to get SohoPopupMenuComponent to retrieve what's selected in a multi selectable menu always returns 0.

However if I get the popupMenuAPI via SohoContextualMenuDirective, and then call getSelected() it will return correct data.

**To Reproduce**
Check code.
https://stackblitz.com/edit/ids-quick-start-1411-tcuu6a?file=src/app/app.component.ts

**Expected behavior**
Should return selected menu items

**Version**
- ids-enterprise-ng: 14.1.1

**Comment by jbrcna** [comment]
QA Passed
https://main-enterprise.demo.design.infor.com/components/popupmenu/example-multi-selectable.html
<img width="1608" alt="image" src="https://user-images.githubusercontent.com/56722184/189013849-72d431f6-ad15-4e96-b5a2-2f7218eaa717.png">
