### ISSUE TITLE
Contextual Action Panel is leaking divs when closed.

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#135]
**Describe the bug**

When running the demo app for the Contextual Action Panel, closing the modal dialog does not remove all the added markup.  Adding this multiple times causes multiple `div` elements to be added to the page.

**To Reproduce**

Run the angular demo app and navigate to the "Contextual Action Panel" demo, and open and close the panel several times.

The standard modal dialog works correctly, cleaning up all dynamic markup.

**Expected behavior**

Any markup added as part of the CAP should be removed when closed.

**Screenshots**

![image](https://user-images.githubusercontent.com/8340092/42681349-543b2f1a-867f-11e8-969a-877672d1f5a7.png)

**Platform**

N/A

**Additional context**

**Comment by tmcconechy** [comment]
Noting that this seems to be angular specific as it is not occurring here http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/example-jquery.html or here http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/example-index.html

**Comment by tmcconechy** [comment]
I think this issue was fixed.
