### ISSUE TITLE
SohoStandalonePager is missing option to show page selector input

### ISSUE THREAD

**Issue by kwolentarski** [infor-design/enterprise-ng#1350]
**Is your feature request related to a problem? Please describe.**
The EP standalone pager has an option to show page selector input as can be seen in https://main-enterprise.demo.design.infor.com/components/pager/example-standalone.html. 
This option is missing from the angular component, leaving this pager as arrows only.

**Describe the solution you'd like**
SohoStandalonePage should have an option to show page selector input.

**Additional context**
Application: Infor WFM

**Comment by kwolentarski** [comment]
Hi, now that the page selector input is visible, it would be great to have a possibility to pass the dataset to the pager to be able to display something else than "Page x of 1" always.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
