### ISSUE TITLE
Flex Toolbar: deprecated method warning when using moreMenuBeforeOpenFunction

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise-ng#1352]
**Describe the bug**
A warning message is being seen when using the moreMenuBeforeOpenFunction option on a flex toolbar. This is being cause by https://github.com/infor-design/enterprise-ng/blob/main/projects/ids-enterprise-ng/src/lib/toolbar-flex/soho-toolbar-flex.component.ts#L336 setting this.toolbarFlex.settings.beforeMoreMenuOpen = beforeOpen. Since beforeMoreMenuOpen has been deprecated, we get the warning message in the javascript console.

**To Reproduce**

1. In the demo app, navigate to T -> Toolbar Flex - More Actions Ajax
2. Open the browser dev tools, look at the console with warnings on
See message

**Expected behavior**
No deprecated warning should be seen.

**Version**
- ids-enterprise-ng: 13.5.4

**Screenshots**
![image](https://user-images.githubusercontent.com/22107636/183155555-f4712e33-148c-4eaf-bf3c-79e388748596.png)

**Platform**
 - All

**Additional context**
[This](https://github.com/infor-design/enterprise-ng/issues/1118)  previous ticket didn't fix the issue.

**Comment by ericangeles** [comment]
@Sovia @tmcconechy I checked it again and it's not showing on the latest version of NG.

**Comment by tmcconechy** [comment]
@ericangeles i dont see it in the reproduction either but the warning is still there. I suggest we just remove this line https://github.com/infor-design/enterprise/blob/main/src/components/toolbar-flex/toolbar-flex.js#L65 as any warning isn't really necessary considering we have a whole new version.

**Comment by jbrcna** [comment]
QA Passed.
no deprecated message is shown in console. moving this ticket to done
