### ISSUE TITLE
Datagrid: rowspan property not working

### ISSUE THREAD

**Issue by Uma-Neeharika** [infor-design/enterprise-ng#1353]
When trying to use rowspan property for data grid as attached, getting error: **rowspan doesnot exist in type SohoDataGridColumn**.
Please refer attached for more details.

<img width="619" alt="rowspan" src="https://user-images.githubusercontent.com/110805940/183348828-0a941673-0d08-448e-8496-5b4623798fa0.png">

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
