### ISSUE TITLE
editor: focusing in and focusing out on an unedited editor via keyboard makes it dirty

### ISSUE THREAD

**Issue by JBismonte** [infor-design/enterprise-ng#1354]
**Describe the bug**
When tabbing through a read-only non modified editor is causing it to be marked dirty.

**To Reproduce**
1. Go to http://localhost:4200/ids-enterprise-ng-demo/editor
2. Click on the disable button to make the editor read only
3. Focus on the rich text editor via keyboard and tab out
4. the editor is being marked dirty.

**Expected behavior**
the dirty indicator shouldnt appear

**Version**
- ids-enterprise-ng: 14.1.0

**Screenshots**
https://user-images.githubusercontent.com/29673378/183357885-8255af3c-52b1-4e3e-b5e3-fa47d0138045.mp4

**Platform**
 - Device (if applicable): NA
 - OS Version: Windows 10
 - Browser Name: Firefox
 - Browser Version : 103.0 (64-bit)

**Additional context**
https://jira.infor.com/browse/LMWEB-1926

**Comment by tmcconechy** [comment]
@JBismonte ? Any suggestions?

**Comment by tmcconechy** [comment]
Closing older issues with not enough info to reproduce.
