### ISSUE TITLE
Update DataGrid option toolbar and isList should trigger re-render  

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-ng#1357]
**Is your feature request related to a problem or use case? Please describe.**
`toolbar` and `isList` are two options which can be set in our Widget builder.

Within the toolbar options we want also to be able to set the following options which should trigger an update:
- `keywordFilter`
- `results`
- `title`
- `actions`
- `collapsibleFilter`
- `exportToExcel`

**Describe the solution you'd like**
When changing any of those options it should trigger refresh of the data grid component so that the new options set to the grid are reflected.

Currently it doesn't work as can be seen in the example stackblitz
https://stackblitz.com/edit/ids-quick-start-1421-9cff2d?file=src/app/odd-data-grid/odd-data-grid.component.ts

**Comment by tmcconechy** [comment]
Moving as i think this would go in the NG project. But may need changes in both code bases

**Comment by jbrcna** [comment]
this is working as expected. 
v4.70.0-dev
https://main-enterprise.demo.design.infor.com/components/datagrid/test-update-toolbar
<img width="1586" alt="image" src="https://user-images.githubusercontent.com/56722184/202707585-a39deb51-e73b-451f-9c3c-ff75742fe132.png">
