### ISSUE TITLE
Modal: fullsize resposive issue when modal contains a datagrid

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#1358]
**Describe the bug**
Have a modal dialog using the option of fullsize responsive, the last column within the datagrid does not flex when the user resizes the browser window.

**To Reproduce**
1. Using '.../ids-enterprise-ng-demo/datagrid-lookup-click-function'
2. Within the file datagrid-lookup-click-function.demo.ts need to change the options provided to the modal service to 
       include the option of fullsize repsonsive
3. With the change in place make the browser window smaller
4. Notice that the last column of the datagrid doesn't flex to fill the space

**Expected behavior**
Columns of the datagrid fill the space.

**Version**
- ids-enterprise-ng: v14.1.4

**Additional context**
Started seeing this issue once Landmark moved to 14.1.x (has been working correctly in 13.5.x).  This is a HUGE issue for Landmark.

**Comment by claudenbach** [comment]
[ModalFullsizeResponsive.zip](https://github.com/infor-design/enterprise-ng/files/9374410/ModalFullsizeResponsive.zip)

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/185412642-0a72e6ae-e2f3-4def-829d-8acf80e9b041.png)

**Comment by tmcconechy** [comment]
Do you think it could be https://github.com/infor-design/enterprise/issues/6725 ?

**Comment by tmcconechy** [comment]
Will need to look at this too @ericangeles but might be the same as 6725? Thats my guess

**Comment by claudenbach** [comment]
I'm trying to use the enterprise example of http://localhost:4000/components/datagrid/example-modal-datagrid.html, but I've been unsuccessful updating the code to add the options to specify the setting of fullsize responsive.

**Comment by tmcconechy** [comment]
Does https://github.com/infor-design/enterprise/pull/6769 fix this issue?
