### ISSUE TITLE
Popupmenu: First time clicking a submenu closes the popupmenu

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise-ng#1359]
**Describe the bug**
`soho-popupmenu` causes the menu to close the first time clicking one of its submenus.

**To Reproduce**
1. Go to http://localhost:4200/ids-enterprise-ng-demo/popupmenu
2. Right click the top input field.
3. Click on one of the submenus.
4. Notice that the popupmenu closes.

**Expected behavior**
The menu should stay open when clicking a submenu in a `soho-popupmenu`

**Version**
- ids-enterprise-ng: 14.1.1

**Screenshots**
![popupmenu](https://user-images.githubusercontent.com/63045013/185843945-5c02cd3a-2a5f-40c1-9409-4ca8fcda5a85.gif)

**Additional context**
As mentioned, this only happens the first time a submenu is clicked, so if you repeat the steps again the menu stays open as expected.

**Comment by tmcconechy** [comment]
When i run the stackblitz i just get a blank page, so cant see the issue. But judging by the screen shot:

a) why is one "not using soho-popupmenu"?
b) what if you do them both the same way?

What if you use https://github.com/infor-design/enterprise-ng/tree/main/projects/ids-enterprise-ng/src/lib/menu-button for both?

**Comment by radovaniljic** [comment]
The left menu is irrelevant to the issue, i just included it to illustrate that by **not** using `soho-popupmenu`, it works as expected, i.e. the menu stays open when you click the submenu.

It's when you actually do use the `soho-popupmenu` that the issue appears.

**Comment by tmcconechy** [comment]
Still having a hard time seeing what i see in the video? Do you see this in any of our examples / can clarify the steps?

1) You should not have to click the submenu item to open and close the submenu contents. (hover will work)
2) You should only have to click the submenu contents element to select that (and it should then close)

**Comment by radovaniljic** [comment]
I updated the original post using your examples. 

Yeah you don't **need** to click a submenu to open it since hover is enough, but clicking it seems like a pretty common thing to do and the menu shouldn't close if you do.
