### ISSUE TITLE
SOHO-7686: Data Entered In Typeahead Not Available In The Dropdown Control

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-ng#136]
### Original tickets: 
- Soho JIRA - [SOHO-7686](https://jira.infor.com/browse/SOHO-7686)
- Enterprise - infor-design/enterprise#266

*NOTE:*  There was a bug open for this issue in the Enterprise components against infor-design/enterprise#267 that is resolved and part of the Q/A cycle for v4.9.0.  This issue is specifically for the Angular hooks related to that issue.

### Original Issue Description:

hi, I think we have an error in the Dropdown typeahead binding & I'm seeing the same thing in the 4.4.0 build.

The control I'm looking at is the Angular "Dropdown-Single Select" with "States - From Source".

What I'm looking for is a subscription to the typeahead data. Each time the user presses a key then my app needs to respond & do something extra. The way to do this is through the "source" property which the Angular control uses - [source]="source".

However, the source method (in dropdown.demo.ts) is getting called only once with a searchTerm of "".  It doesnt get called again after subsequent user keypresses.

Could you please have a look. Maybe this is expected behavior - if so could we please have a "searchTerm" Output event added to the API so we can subscribe that way? Thanks

![screenshot-1-1](https://user-images.githubusercontent.com/742319/41861308-dcc3a386-786e-11e8-8aaa-3c6668f78ea6.png)

**Comment by brianjuan** [comment]
@EdwardCoyle Can you please provide the page where can we test this for QA, and also the necessary steps. Thanks!

**Comment by tmcconechy** [comment]
The fix is in the angular project as noted on https://github.com/infor-design/enterprise-ng/pull/138
We havent previously test that out, so i think this one is not testable.

**Comment by brianjuan** [comment]
Thanks @tmcconechy, moving this now to Done.
