### ISSUE TITLE
Datagrid does not respect mask options

### ISSUE THREAD

**Issue by ablomq** [infor-design/enterprise-ng#1362]
**Describe the bug**
Unable to override Locale settings by providing a maskOption object to the column definition.

**To Reproduce**

[StackBlitz example](https://stackblitz.com/edit/ids-quick-start-1421-axkdyz?file=src/app/datagrid/datagrid.ts)

1. Try to enter 12,1234 in the Quantity column (using comma as decimal separator.
2. Try to enter 123456,12 (should be possible according to the maskOptions object
3.  It's possible to enter a negative value even if allowNegative is set to false.,

```
maskOptions: {
        allowNegative: false,
        allowDecimal: true,
        integerLimit: 6,
        decimalLimit: 4,
        allowThousandsSeparator: false,
        symbols: {
          thousands: '',
          decimal: ',',
        },
        process: 'number',
        placeholder: '1,00',
      } as SohoMaskOptions,
```

**Expected behavior**
Should be possible to override Locale settings by providing a maskOptions object.

**Version**
- ids-enterprise-ng: [14.2.1.]

**Comment by tmcconechy** [comment]
It works in this example https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup-mask.html on the productId column.

I can see from the data that the shape is a bit different here.. https://github.com/infor-design/enterprise/blob/main/app/views/components/datagrid/test-lookup-with-mask.html#L75

a) we pass a patternOptions and the process is on a different level
b) it could be u need this as well https://github.com/infor-design/enterprise/blob/main/app/views/components/datagrid/test-lookup-with-mask.html#L84


Made this change here and it seemed to work https://stackblitz.com/edit/ids-quick-start-1421-xduflz?file=src%2Fapp%2Fdatagrid%2Fdatagrid.ts

**Comment by ablomq** [comment]
Thanks for your help. Seams to work now.
