### ISSUE TITLE
RichText: if the richtext has an initial field value with a non breaking space, the dirty indicator triggers.

### ISSUE THREAD

**Issue by JBismonte** [infor-design/enterprise-ng#1363]
**Describe the bug**
When the rich text editor value originally has a non breaking space set, modifying it and returning it to its original value still marks it as dirty.

**To Reproduce**
1. Overwrite the files in the src/app/editor folder with this zip [editor.zip](https://github.com/infor-design/enterprise-ng/files/9422580/editor.zip)
2. try to type a letter to the editor to make it dirty
3. delete the typed letter.
4. the rich text editor is still dirty.

**Expected behavior**
The rich text editor shouldnt be dirty when returned to its original value.

**Version**
- ids-enterprise-ng: 4.65.1

**Screenshots**
See screen recording
https://user-images.githubusercontent.com/29673378/186606592-719cd0c0-527b-445a-9201-72692795dbf6.mp4

**Platform**
 - Device: NA
 - OS Version: Windows 11
 - Browser Name: Firefox
 - Browser Version : 104.0 (64-bit)

**Additional context**
https://jira.infor.com/browse/LMWEB-1980

**Comment by tmcconechy** [comment]
@ericangeles we will need https://github.com/infor-design/enterprise/issues/6032 fixed as well for 4.67 (and possible patch)

**Comment by janahintal** [comment]
Hi @tjamesallen15, tested this in https://main-enterprise.demo.design.infor.com/components/editor/test-dirty-tracking.html but I'm having an error 404. 
![image](https://user-images.githubusercontent.com/45757016/193579852-65eb348f-eff1-42fb-9c6b-caca4b31f4c0.png)

**Comment by tmcconechy** [comment]
@ericangeles usually when this happens it was a failed build on the merge https://github.com/infor-design/enterprise/actions/runs/3174610434 commit. I just merged another issue. So when this runs lets recheck its there...
