### ISSUE TITLE
Datagrid: Value in Input field not selected when using InlineEditor

### ISSUE THREAD

**Issue by ablomq** [infor-design/enterprise-ng#1365]
**Describe the bug**
Value in Input field not selected when using InlineEditor in Datagrid

**To Reproduce**

[Stackblitz example](https://stackblitz.com/edit/ids-quick-start-1421-yvstkn)

1. Click in one of the input fields in the "Quantity Inline Editor" column
2. The value is not selected so to change I need to use backspace or delete button
3. Click on one of the input fields in the "Quantity" column
4. The value in the input field is selected

**Expected behavior**
When you click in an input field the value should be selected so it's easy to change. But when using InlineEditor the user must first erase the value before entering a new value.

**Version**
- ids-enterprise-ng: [14.2.1]

**Screenshots**
Clicking in one of the input fields in the "Quantity" column:
![image](https://user-images.githubusercontent.com/42343009/186937461-c278328f-c735-48fa-a389-f8de83d82d0e.png)

Clicking in one of the input fields in the "Quantity Inline Editor" column:
![image](https://user-images.githubusercontent.com/42343009/186937696-219dceef-b11d-4251-9277-88e0fc15849e.png)
(Value should be selected in the same way in both Quantity columns)

**Comment by tmcconechy** [comment]
Yeah these inline editors have never worked as well is the non inline ones. We will have to make them more "official".

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-with-inline-editor.html. Thanks!
![image](https://user-images.githubusercontent.com/45757016/199517640-7ed5ca2b-c115-4715-a517-8eaaa69ae40e.png)
