### ISSUE TITLE
Decimal separator get missing in input fields for german language

### ISSUE THREAD

**Issue by anne-schwarz-osp** [infor-design/enterprise-ng#1370]
**Describe the bug**
If we set the language to german and enter e.g. `1,5` into an input field then after leaving and reentering the input field it turns first to `1.5` and after another round to `15`. 

**To Reproduce**
See [Stackblitz example](https://stackblitz.com/edit/infor-design-system-data-grid-demo-s2grhs?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts,src%2Findex.html) and explanations in it.

**Expected behavior**
We expect that the entered `1,5` stay `1,5`, no matter how often the user enters or leaves the input field.

**Version**
    - ids-enterprise: 4.58.3
    - ids-enterprise-ng: 10.11.4

**Additional context**
I think the problem could be based in the different use of dots and commas as separators for thousands and decimals. In english language you would write 1,234.5, in german 1.234,5 would be correct.

**Comment by tmcconechy** [comment]
This does seem odd. I will point out it does work here https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html?locale=de-DE

So maybe if in a rush for this to be investigated you can review. Maybe its the inline editor. Or setup?

**Comment by anne-schwarz-osp** [comment]
I checked the example and the problem occurred there as well. I can enter 1,5 into the empty price field and, yes, 1,500 is correctly displayed. But if I enter and leave it again - 1,500 turns into 15,000.
![input bug sample](https://user-images.githubusercontent.com/78731418/187838862-828e88d4-8fb4-4c74-823d-7e60a9ff074d.gif)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
