### ISSUE TITLE
Tabs: Vertical Tab Menu Does Not Work in Data Grid

### ISSUE THREAD

**Issue by anne-schwarz-osp** [infor-design/enterprise-ng#1375]
**Describe the bug**
We want to use a vertical tab menu inside a data-grid, so we created a component for that. This component works pretty fine outside a data grid (all tabs get displayed vertically), but if we use it in a data grid only the first tab gets displayed.

**To Reproduce**
See [Stackblitz example](https://stackblitz.com/edit/infor-design-system-data-grid-demo-eg9lau?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Frow-template.component.ts,src%2Fapp%2Frow-template.component.html,src%2Fapp%2Fapp.module.ts) and explanations in it.

**Expected behavior**
The vertical tab menu inside a data-grid should look the same inside and outside the data grid.

**Version**
- ids-enterprise: 4.58.3
- ids-enterprise-ng: 10.11.4

**Additional context**
When you inspect the elements, you can see that the other tabs are there, but they are displayed next to each other instead of one below the other.
![image](https://user-images.githubusercontent.com/78731418/189829401-7c6fc0ff-ee90-4045-b5ed-dca409c9a545.png)

**Comment by tmcconechy** [comment]
This seems a little weird to me from a UX and accessibility perspective. And naturally not something we support.
I would consider a different design for this. I dont think tabs belong in a datagrid.

**Comment by anne-schwarz-osp** [comment]
Yeah, well, I can't deny that :D 

We have an order entry with a result list of purchasable items. We use the collapsible table to provide more settings for the item (selecting a supplier, adding a custom position number, ...). But I'm not a big fan of this solution. Sadly, we do not have enough time/budget to refactor the current implementation. 
We applied a patch for our case to get it working. It would be nicer if it would work right out of the box, but I understand that this is not a supported combination of components.
