### ISSUE TITLE
Listview: Scrollbar hides when unselecting more than one element on list with contextual toolbar

### ISSUE THREAD

**Issue by kwolentarski** [infor-design/enterprise-ng#1377]
**Describe the bug**
When using multiselect listview with contextual toolbar the list scrollbar disappears when unselecting more than one element on the list at once (e.g. using clearAllSelected() method). 
![image](https://user-images.githubusercontent.com/86295640/190634031-4963953c-d1e1-4032-a214-fe81487fdb45.png)
 
When the contextual-toolbar is used the listview height is set to 100%.
![image](https://user-images.githubusercontent.com/86295640/190633127-4da5fb40-4cbf-477b-af49-97d776f409db.png)
When unselecting multiple elements the .is-hidden class is not applied to (or applied to and then removed from) the contextual-toolbar, causing the listview to have no height limitation making the scrollbar to disappear.

**To Reproduce**
1. Go to https://stackblitz.com/edit/list-view-contextual-scrollbar?file=src/app/list/list.component.html
2. Observe that scrollbar is visible
3. Select more than one item on the list
4. Click 'Unselect All' button on the contextual toolbar
5. Notice that the scrollbar disappears
6. Select any item and notice that scrollbar reappears

**Expected behavior**
The scrollbar should not disappear when unselecting more than one item at once.

**Version**
- ids-enterprise-ng: latest

**Screenshots**
See above

**Platform**
 Any device, any browser

**Additional context**
Application: Infor WFM

**Comment by tmcconechy** [comment]
Not sure if this is a bug or an issue on your end. But will add to the backlog.
It could also be a bug in our clearAllSelected method. As i did notice that it works if you deselect one by one.

**Comment by tjamesallen15** [comment]
Hello @tmcconechy,

I can't reproduce this issue at all. See the video below.

https://user-images.githubusercontent.com/34049950/201060824-7186ecf1-f4fb-422d-94c0-4b9f34b76453.mp4

cc @ericangeles

**Comment by tmcconechy** [comment]
@tjamesallen15 / @ericangeles - see it in the stackblitz...

https://watch.screencastify.com/v/5eSdmMomT9E480QzKNOm

**Comment by tjamesallen15** [comment]
> @tjamesallen15 / @ericangeles - see it in the stackblitz...
> 
> https://watch.screencastify.com/v/5eSdmMomT9E480QzKNOm

Yep. I just ported the test page into our project and try to test it but I can't reproduce it that's why I made video for it.

**Comment by tmcconechy** [comment]
Ok @kwolentarski can you test this on [14.4.3](https://www.npmjs.com/package/ids-enterprise-ng/v/14.4.3) - seems like it might be fixed.

**Comment by tmcconechy** [comment]
@tjamesallen15 maybe clean up PR the test page as well 👍🏻
