### ISSUE TITLE
VPAT Treegrid: invalid treegrid role on div.

### ISSUE THREAD

**Issue by JBismonte** [infor-design/enterprise-ng#1378]
**Describe the bug**
An invalid ARIA role="treegrid" is applied to the <div> container, this is not an issue on enterprise, only in enterprise-ng.

**To Reproduce**
1. Go to http://localhost:4200/ids-enterprise-ng-demo/datagrid-treegrid
2. Check that the table element has a treegrid role, but also the parent div.

**Expected behavior**
remove the treegrid role on parent div. 

**Version**
- ids-enterprise-ng: 14.3.0

**Screenshots**

![image](https://user-images.githubusercontent.com/29673378/191652627-232a7571-d316-4e41-a873-1b2ad5de4e13.png)

**Platform**
 - Device (if applicable): NA
 - OS Version: Windows 11
 - Browser Name: Firefox
 - Browser Version: 104.0.2

**Additional context**
[Jira Ticket](https://jira.infor.com/browse/LMWEB-1526)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
