### ISSUE TITLE
DatePicker: Date not formatted correctly when after blur when changing disable dates

### ISSUE THREAD

**Issue by kwolentarski** [infor-design/enterprise-ng#1380]
**Describe the bug**
When using datepicker with disabled dates that are changing and format containing EEEE, there is an issue with formatting date correctly. When the disabled dates are changed and then we pick the date again the date is formatted fine, but after clicking outside of datepicker (blur) the format changes.

**To Reproduce**
1. Go to https://stackblitz.com/edit/datepicker-disable-dates-change?file=src/app/form/form.component.ts
2. Select some date in both date pickers	
3. Observe that date is formatted correctly based on the format passed	
4. Click Change Disable Dates button	
5. Change the date in first datepicker and then click outside the input to cause blur
6. Observe that value now is e.g. 'Sep EEE 28, 2022' instead of 'Sep Wed 28, 2022'
7. Change the date in second datepicker and click outside the input to cause blur
8. Observe that value now is e.g. 'Thu 29, 2022' instead of 'Sep Thu 29,2022'

**Expected behavior**
The datepicker should display the date based on provided format.

**Version**
- ids-enterprise-ng: 14.3.1

**Screenshots**
Before changing disable dates
![image](https://user-images.githubusercontent.com/86295640/191984351-7c8208fb-a68c-4928-a2fc-5d978ad92cf6.png)
After changing disable dates and blur
![image](https://user-images.githubusercontent.com/86295640/191984428-54c6620c-7348-4d8e-ac3c-1006df519c74.png)

**Additional context**
Project: Infor WFM

**Comment by jbrcna** [comment]
QA PAssed . v4.70≥0-dev
https://main-enterprise.demo.design.infor.com/components/datepicker/test-mask-disable-update.html
<img width="293" alt="image" src="https://user-images.githubusercontent.com/56722184/205269175-030ef7df-d68c-4a6f-be95-b9ac6c7ab6cb.png">
