### ISSUE TITLE
Swaplist: Question about the component

### ISSUE THREAD

**Issue by ashachodavarapu** [infor-design/enterprise-ng#1381]
https://github.com/infor-design/enterprise-ng/issues/1290#issue-1227749769

As suggested in the above issue, we have cleared the filer after refreshing in the Soho-swaplist component but the "X" icon in the search field remains. As there is no search element in the search field we are not required with the "X" icon so we would like to have some solutions to the concerns mentioned below.

Before refresh:
<img width="863" alt="image" src="https://user-images.githubusercontent.com/105051938/192225508-f6e08f58-ddcd-4918-a0db-54dddcb160bd.png">

After Refresh:
<img width="746" alt="image" src="https://user-images.githubusercontent.com/105051938/192225627-191ea2d8-eebd-426b-ab39-843cd66008c7.png">
![image](https://user-images.githubusercontent.com/105051938/192225685-8ac8b8ee-b40b-401c-beae-758d2545dc71.png)

My concerns:
1. How to remove the "X" icon in the search field.
2. Whether or not is it possible to remove that "X" icon in the search field?

**Comment by tmcconechy** [comment]
maybe you can call the clear method https://github.com/infor-design/enterprise/blob/main/src/components/searchfield/searchfield.js#L2219 on the field?

**Comment by ashachodavarapu** [comment]
I tried with that clear() but it's not working. should I try with jquery by using that icon class name?

**Comment by tmcconechy** [comment]
Closing issues as answered
