### ISSUE TITLE
SohoStandalonePager: Missing dataset option

### ISSUE THREAD

**Issue by kwolentarski** [infor-design/enterprise-ng#1389]
**Describe the bug**
This is a follow-up for https://github.com/infor-design/enterprise-ng/issues/1350. Now that SohoStandalonePager has a possibility to show page selector input, it should also be possible to set total pages number. This I think is set by passing dataset in jquery component. 
![image](https://user-images.githubusercontent.com/86295640/195085964-f9921134-8014-4061-b800-1b2a396627ff.png)

**To Reproduce**
1. Go to 'http://localhost:4200/ids-enterprise-ng-demo/pager-standalone'
2. Notice page selector input says Page 1 of 1 and there is no way to change the "of 1" right now

**Expected behavior**
Pager should know about total pages to render correctly as "Page X of totalPages"

**Version**
- ids-enterprise-ng: current

**Additional context**
Product: Infor WFM

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
