### ISSUE TITLE
Change primary-color

### ISSUE THREAD

**Issue by martinabdulghni** [infor-design/enterprise-ng#1394]
Is there any possible way to change the primary-color? (the blue-color).

**Comment by tmcconechy** [comment]
You cant change the color as its in the css and the style guide. But we have a personalization feature https://main-enterprise.demo.design.infor.com/components/personalize/example-index.html?colors=BB5500 where you can change some elements like the header.

```
  $('body').on('initialized', function() {
    $(this).personalize({
      startingColor: '#2578A9' // Azure07
    });
  });
```
