### ISSUE TITLE
Datagrid: summaryRow

### ISSUE THREAD

**Issue by stavridd** [infor-design/enterprise-ng#1395]
Hello!
I have an issue with summary row. When I use aggregator: "sum" the results displayed just fine but when I use aggregator: "avg" or "max" the datagrid isn't displayed and I get this error message: "error typeerror undefined is not a function".

My version of angular is 12.2.7, ids-enterprise is 4.55.3 and ids-enterprise-ng is 10.6.3. 

Can you please help me?

**Comment by tmcconechy** [comment]
Seems to work in these examples https://main-enterprise.demo.design.infor.com/components/datagrid/test-grouping-aggregators-max.html
https://main-enterprise.demo.design.infor.com/components/datagrid/test-grouping-aggregators-avg.html

Maybe you can look. Here is the source:

https://github.com/infor-design/enterprise/blob/main/app/views/components/datagrid/test-grouping-aggregators-avg.html
https://github.com/infor-design/enterprise/blob/main/app/views/components/datagrid/test-grouping-aggregators-max.html

I dont have angular examples. So you will have to do the "translation". Also you could try the latest version but i dont recall any bugs here. So must be the setup...

**Comment by tmcconechy** [comment]
Closing as answered
