### ISSUE TITLE
SohoModalButton click action should be handled inside ngZone

### ISSUE THREAD

**Issue by kwolentarski** [infor-design/enterprise-ng#1396]
**Describe the bug**
When defining buttons for SohoModal the click function is not handled inside ngZone by default. This can cause issues with other components e.g. SohoBusyIndicator, where it does not show up or is stuck until change detection is triggered. It also leaves it to developer to add ngZone for all modal buttons.

**To Reproduce**
1. Use any of the modal-dialog demo examples
2. Add soho-busyindicator to the modal content e.g.
`<div soho-busyindicator displayDelay="0" [activated]="isLoading">`
4. Change the loading state in button click function e.g. 
`dialogRef.componentDialog.isLoading = true`
5. Test it and see that after button is clicked the loading indicator does not show up
6.  wrap click function in ngZone.run and test it again
7. Notice the loading indicator now showing up correctly

**Expected behavior**
SohoModalButton click function should be wrapped in ngZone.run by default

**Version**
- ids-enterprise-ng@14.4.3

**Screenshots**

**Additional context**
Team: Infor WFM

**Comment by edgarinfor** [comment]
This is basically making us to manually do an **ngZone.run** within the **SoHo Modal Button** click callback:
```
// Button click callback:
click: () => {
    // Run callback logic within ngZone:
    this.ngZone.run(() => {
        // Callback logic...
    });
} 
```
Other **IDS** components seem to have fixed this by calling the jQuery callback within **ngZone.run** instead.

**Comment by tmcconechy** [comment]
Ok @edgarinfor do you have a PR you can propose?

**Comment by edgarinfor** [comment]
@tmcconechy, we explored the possibility but, we couldn't find where the modal buttons "_click_" is exposed in the NG components so, we needed more time to dig in.

However, we created an internal JIRA to follow up with this issue since our capacity is tight with a major releasable now.

**Comment by tmcconechy** [comment]
ok we will keep it here in our backlog as well and see who can get to it first
