### ISSUE TITLE
Misplaced dropdown list

### ISSUE THREAD

**Issue by vrata48** [infor-design/enterprise-ng#1398]
**Describe the bug**
The dropdown is misplaced from parent text box.

**To Reproduce**
1) Open Infor Data Fabric
2) Go to Pipelines/Stream Pipelines
3) Edit an existing pipeline
4) Select a data object to open editor
5) Open Object Name dropdown
![image](https://user-images.githubusercontent.com/37781264/200536358-3fe905ff-aecb-4a1e-8294-6927f9885b67.png)

**Expected behavior**
The dropdown fully covers the textbox.

**Platform**
 - Device: Yes
 - OS Version: Windows
 - Browser Name: Chrome
 - Browser Version: Version 107.0.5304.88 (Official Build) (64-bit)

**Additional context**
Same issue can be reproduced on multiple places in Data Orchestrator as well.

**Comment by tmcconechy** [comment]
Unfortunately we cant accept bugs in your application. We need you to provide a test case and reproduction that is outside of your app.

You can either:
- modify our examples to show the issue
- use the stackblitz template https://stackblitz.com/edit/ids-quick-start-1431 for angular
- use the component stackblitz https://stackblitz.com/edit/ids-enterprise-4680

**Comment by vrata48** [comment]
Unfortunately I cannot reproduce the issue in stackblitz so I would like to ask you to check the actual usage in our application. As I mentioned, It's Data Fabric where it can be seen on numerous places.

Pls contact me on Teams (vratislav.cermak@infor.com) for access to the environment/sources.

**Comment by tmcconechy** [comment]
You should be able to - otherwise we cant verify it. Did you try to fork, the component repo and make an example page?

Just try to make one with the same size ect initially or possibly with the same items. Looks like a minor placement issue. Also you can try to make sure you try the latest version.

**Comment by vrata48** [comment]
I cannot reproduce the issue on simple example with dropdown in a panel and I cannot copy half of the application to the stackblitz. I tried for an hour and I failed. Next logical step would be to look at the issue together.

**Comment by vrata48** [comment]
Awesome, thanks a lot!
