### ISSUE TITLE
TextArea: Textbox length restriction doesn't work properly with pasted text

### ISSUE THREAD

**Issue by maltsevy** [infor-design/enterprise-ng#1401]
team: WFM
**Describe the bug**
When the angular property [maxLength] is used instead of the native html maxlength - the length restriction doesn't apply to the pasted text. If the text contains the "\n" symbol then the length of the text is calculated wrongly

**To Reproduce**
1. Use soho-textarea component with [maxLength]=100 angular property:
<textarea soho-textarea [maxLength]="100" name="counter"></textarea>
2. Paste in the textarea text which length exceeds the restriction. For example: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec rutrum hendrerit nunc sed mollis. Quisque pharetra venenatis aliquam." (132 chars)
3. See that the whole text was pasted

**Expected behavior**
When pasting the text which exceeds the length restriction, the text should be cut until the length of the text fits the limitation. In the example provided below only the first 100 chars should be displayed "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec rutrum hendrerit nunc sed mollis. Qui"

**Screenshots**
![image](https://user-images.githubusercontent.com/44119194/201104158-9a78e516-a8d7-4007-934d-315f594ade4c.png)
![image](https://user-images.githubusercontent.com/44119194/201104226-1f1be130-8bf0-4267-ae4b-536cfaf6a9d2.png)

**Describe the bug**
When the native html property maxlength is used then the ids component miscalculates the length for the pasted text, which contains the "\n" (new line) symbol.

**To Reproduce**
1. Use the soho-textarea component with [maxLength]=100 angular property:
<textarea soho-textarea maxlength="100" name="counter"></textarea>
2. Paste text, which contains the "\n" (new line) symbol and is exactly 100 chars
For example: "Lorem ipsum dolor sit amet, consectetur

adipiscing elit. Donec

rutrum hendrerit nunc sed mollis..."
3. See that the whole text was pasted
4. Remove the last character
5. Try to type one letter back
6. See that it is not possible to type the character back

**Expected behavior**
When you remove a character you can type it back

**Screenshots**
![image](https://user-images.githubusercontent.com/44119194/201108628-785efd58-0bb8-4316-a4d5-4d52c4dd3742.png)
![image](https://user-images.githubusercontent.com/44119194/201108573-fcbacbda-dc25-4a0f-bdeb-fed6d3fd15cd.png)
![image](https://user-images.githubusercontent.com/44119194/201108751-8abeb5e2-7858-4dc5-8aac-3c6c7b748d09.png)

**Version**
- ids-enterprise-ng: 4.67.0-dev.20220831

**Platform**
 - Device: Laptop
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 107.0.5304.106 (Official Build) (64-bit)

**Comment by jbrcna** [comment]
QA Failed
when pasting the text twice. it trims the copied text which left 3 character. see below
steps
1. copy this text
```
Lorem ipsum dolor sit amet, consectetur
adipiscing elit. Donec

rutrum hendrerit nunc sed mollis...
```
2. select all ( ctrl + a )
3. Hit backspace to delete
4. paste text
5. notice the ending letters are `nunc s `
6. select all again ( ctrl + a )
7. then paste again
8. notice the ending letters now are `nun` with 3 characters left. it removes `c s`

![Large GIF (568x288)](https://user-images.githubusercontent.com/56722184/210713645-741bb691-3208-409a-84b5-f37bc2f73c7f.gif)

**Comment by jbrcna** [comment]
QA Passed. thank you
https://main-enterprise.demo.design.infor.com/components/textarea/example-index
