### ISSUE TITLE
popupmenu: rendering issue on iOS Safari when not attached to body

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-ng#1402]
**Describe the bug**
When a popupmenu (`soho-popupmenu`, `soho-menu-button` etc) uses the `[attachToBody]="false"` binding, it isn't always rendered properly when running in iOS (Safari).

**To Reproduce**
1. In the samples directory, modify the **toolbar-flex-basic-demo.html** or any other sample that has a popup menu, and add `[attachToBody]="false"`, e.g `<button soho-menu-button [attachToBody]="false">`
2. Serve it up, and visit the site in Safari on an iOS device
3. Open the menu
4. Notice that the menu get partially (or fully) hidden behind other elements

NOTE: Sometimes the menu just looks bad e.g when it's partially hidden by text. But sometimes the menu isn't visible at all if it's hidden behind an element with background color etc. In either case, it is not clickable.

**Expected behavior**
The z-index of the popupmenu should ensure it is always on top. This doesn't always seem to be the case in iOS/Safari.

**Version**
- ids-enterprise-ng: 14.3.2, 14.5.0

**Screenshots**
<img width="564" alt="image" src="https://user-images.githubusercontent.com/4991954/201918395-6ef9cafc-dc80-4540-bfe1-8f516722e82d.png">

**Platform**
 - Device: iPhone X / iPhone 14 Pro / iPhone 13
 - OS Version: 16.1 / 15
 - Browser Name: Safari

**Additional context**
- https://jira.infor.com/browse/SCRMPORTALV2-4902
- https://jira.infor.com/browse/TSDEVSUP-41876
- https://stackoverflow.com/questions/40895387/z-index-not-working-on-safari-fine-on-firefox-and-chrome

I tried working around the issue with the [following CSS](https://oxford.awsdev.infor.com/inforosportal/portal-client/-/merge_requests/2197/diffs):
```css
html.is-safari.ios .popupmenu-wrapper {
  -webkit-transform: translateZ(1px);
}
```
At first this seemed to solve the issue, as it made the menu visible. However clicking/tapping in the menu did not work.

**Comment by tmcconechy** [comment]
We introduced the the attachToBody because of stacking context issues in safari. But we could investigate the attempted fix and try all teh various safari versions to see if any do fix the issue now
