### ISSUE TITLE
Vulnerable version of d3-color is used

### ISSUE THREAD

**Issue by albinbergvall** [infor-design/enterprise-ng#1404]
**Describe the bug**
While scanning for vulnerable and packages, we found that ids-enterprise-ng uses a vulnerable package, d3-color@1.4.1. This is a transitive dependency from d3@5.16.0. Fix has been made in d3-color@3.1.0, which is used by d3@7.4.0.

**To Reproduce**
Run `npm list d3-color`:
```
> npm list d3-color
└─┬ ids-enterprise-ng@14.5.0
  └─┬ d3@5.16.0
    ├── d3-color@1.4.1
    ├─┬ d3-interpolate@1.4.0
    │ └── d3-color@1.4.1 deduped
    ├─┬ d3-scale-chromatic@1.5.0
    │ └── d3-color@1.4.1 deduped
    └─┬ d3-transition@1.3.2
      └── d3-color@1.4.1 deduped
```

**Additional context:**
D3 fix version: https://github.com/d3/d3/releases/tag/v7.4.0
Vulnerability: https://security.snyk.io/package/npm/d3-color

**Comment by tmcconechy** [comment]
Duplicate of https://github.com/infor-design/enterprise/issues/6912 work under way on https://github.com/infor-design/enterprise/pull/6731
