### ISSUE TITLE
SohoListView: Missing filtered event in Angular component

### ISSUE THREAD

**Issue by kwolentarski** [infor-design/enterprise-ng#1405]
**Describe the bug**
In Angular wrapper for Listview there is no filtered event, which is available on the jquery element.
It would be nice to have it to e.g. have a way to display empty message when all items are filtered out when using searchfield.

**To Reproduce**
1. In listview demo pick one of searchable example
2. When typing there is no way to say how many items are currently visible on the list

**Expected behavior**
Filtered event should be available in the Angular wrapper component.

**Version**
- ids-enterprise-ng: 14.5.0

**Additional context**
Team: Infor WFM

**Comment by tmcconechy** [comment]
Feel free to add a quick PR if you want 👍🏻
