### ISSUE TITLE
Bubble Chart: Overlapping issue in Bubble chart

### ISSUE THREAD

**Issue by MadhuKiran4247** [infor-design/enterprise-ng#1407]
Hi General
In the below Bubble chart widget, We have an issue .

 We have 2 WorkCentre WOCE and WCAMS1, both Work Centre's has same data as “Delayed Bucket15”,”No Of Days Delayed 23”, “No Of Orders 1”
Due to this same data, 2 Bubbles are getting overlapped at the same coordinates so we are unable to depict both the Bubbles at a time though logically we are getting the data right code wise

Could you please check below screenshots for your reference and help us, Thanks

<img width="356" alt="image" src="https://user-images.githubusercontent.com/119498230/204822281-55df65e6-bacc-43c5-96e0-7a915f02a24a.png">
<img width="282" alt="image" src="https://user-images.githubusercontent.com/119498230/204822350-3af98a57-e28b-4e14-a20c-e4e0e5ad921d.png">

**Comment by tmcconechy** [comment]
This is a tough situation. Im not really sure what can be done about it. Maybe we could split the circle in two parts or something or show both in the tooltip.

But this wont be an easy enhancement.
