### ISSUE TITLE
Are soho components intended for general use?

### ISSUE THREAD

**Issue by stewrutledge** [infor-design/enterprise-ng#1408]
Recently the infor soho documentation, https://design.infor.com/, has been restricted to what seems like only infor employee access. The figma kits are also only available to employees.

Does infor consider soho to be an internal design language? Should non-infor developers look at other alternatives?

**Comment by tmcconechy** [comment]
@inforandy can you answer this?

**Comment by tmcconechy** [comment]
@stewrutledge Assume you're an Infor partner? 

Checking into this - some of the content on the site was temporarily locked down but we plan on opening it open again on the site after a bit of a redesign in the near future.

However, all the components are still Open Source with the same license open source licenses https://github.com/infor-design/enterprise-wc/blob/main/LICENSE and you can use them. Also if you want to have access to the site we can also add you until we open it back up. Just send details to: Luca Columbu <Luca.Columbu@infor.com> 

Also check out our new version soon https://github.com/infor-design/enterprise-wc its beta 👍🏻

**Comment by stewrutledge** [comment]
@tmcconechy Unfortunately we're not infor partners. We've contacted infor a number of times but have never gotten any response.

I'll contact Luca about getting access, but to be honest it's a little concerning that the documentation can be locked like this, we worried that it might present issues with maintenance in the future if documentation and maybe even tooling around soho become more and more restricted.

**Comment by tmcconechy** [comment]
Sure, i understand. I'm trying to get this resolved as well on my end as it does hurt adoption. I will continue to look into this. We plan on the components remaining open source. So do reach out to Luca for now.

Also just FYI the bulk of component documentation is also still in the repo contained in the `README.md` files as well (as well as the source code comments) and is just generated into the site. In the case of the new version its all in the README's https://github.com/infor-design/enterprise-wc/tree/main/src/components/ids-about

BTW did you try reaching out here: https://www.infor.com/partners ? Just a suggestion there

**Comment by inforandy** [comment]
Hi @stewrutledge 

Can you reach out to me at andrew.kopas@infor.com? You can feel free to cc Luca Columbu if you would like to, but I'd like to understand a little bit more about your use case here and how we can make sure you can still get value out of the SoHo design language if it makes sense.

Thank you!

**Comment by stewrutledge** [comment]
@tmcconechy thanks for the tips regarding the partner page, but we’ve filled out that form 4-5 times and never get a response. We’ve also reached out to some contacts via mail and linkedin but haven’t made any progress that way either. Maybe we’re too small?

@inforandy We’ve used the soho components when building H5 apps, especially when a customer specifically asks for a sort of “native” look (native to infor os).

We’ve also built with primeng and used aggrid in at least one project, which have also worked well for us.
