### ISSUE TITLE
Lookup: Selection is not reflected in dialog when using multiselect and async source 

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise-ng#1409]
**Describe the bug**
When a multiselect-lookup gets async data using the [source] input, the selected items are not "checked" in the lookup dialog.

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1450-vb5u3e?file=src/app/app.component.html
2. Open the "Lookup with source"
3. Notice that the correct items are selected in the dialog
4. Open the "Lookup with async source"
5. Notice that no items are selected in the dialog

**Expected behavior**
The specified items should be selected in the dialog.

**Version**
- ids-enterprise-ng: 14.5.0 (but this has been an issue for a very long time)

**Additional context**
Related to [1132](https://github.com/infor-design/enterprise-ng/issues/1132) which has been fixed but this is still not working if the data is async.

Jira ticket: [LIME-7085](https://jira.infor.com/browse/LIME-7085)

**Comment by jbrcna** [comment]
QA Passed.
https://main-enterprise.demo.design.infor.com/components/lookup/test-lookup-source-async.html
<img width="958" alt="image" src="https://user-images.githubusercontent.com/56722184/221768307-68f86f6a-7204-4180-a2f0-ef79d48e6d40.png">
