### ISSUE TITLE
SohoToolbarFlexNavButton missing an updated() function

### ISSUE THREAD

**Issue by White-NW** [infor-design/enterprise-ng#1414]
**Describe the bug**
An updated() function like soho-button has is needed for soho-toolbar-flex-nav-button to correctly show and hide the notification badge

**To Reproduce**
1. Go to ids-enterprise demo page: button-badge.demo.html
2. Click on "Toggle On" and "Toggle Off" for the button icon

**Expected behavior**
The notification badge around the icon will be turned on or off. We need a similar function updated() for for nav button.

**Version**
- ids-enterprise-ng: v4.68.0

**Comment by tmcconechy** [comment]
Not 100% sure i follow this one. But if you want to please submit a pull request with what your thinking? As this is open source

**Comment by White-NW** [comment]
Sorry for the confusion, I am implementing the notification badge for flexnavbutton and with the function it could let the navbutton update its buttonoption to show/hide the button while some change is detected. I will fix this one by myself
