### ISSUE TITLE
Ability to force new new empty state icons

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-ng#1418]
**Is your feature request related to a problem? Please describe.**
We want to use the "new" new empty state icons, e.g `#icon-empty-new-project-new`. We'd like for *all* empty states in the app to use the new icons, without having to change every single `SohoEmptyMessageDirective.icon` input. This is especially important for micro-frontend apps such as Portal / Homepages, where we are not able to modify all of the source code (widgets, extensions).

**Describe the solution you'd like**
Add an option *somewhere* that makes it so that e.g `soho-emptymessage icon="icon-empty-no-data"` is equivalent to `soho-emptymessage icon="icon-empty-no-data-new"`.

Some possible solutions:
1. Add a `SohoIconsEmptyNewNewComponent` that loads the the "new" new SVG:s with the "old" identifiers.
2. Add a  `[forceNewNewIcons]="true"` option to `SohoIconsEmptyNewComponent`, which does the same as above.

**Describe alternatives you've considered**
The only alternative (aside from implementing the above on our own) is to change all the `<soho-emptymessage icon="..."` in the code. This is not possible to do at exactly the same time for all external code (widgets) as it would involve similar changes to thousands of lines of code spread over many developers/teams/companies.

**Additional context**
I'm using the term "new new" somewhat tongue in cheek here, because I don't know what the "new" new icons should be called... 😉

**Comment by tmcconechy** [comment]
I think maybe just an option to https://github.com/infor-design/enterprise-ng/blob/main/src/app/emptymessage/emptymessage.demo.html#L3 that is `useNewIcons` or something that appends the "new" prefix. Instead of having a whole new component...

**Comment by tmcconechy** [comment]
Or we could simple remove the new prefix in the icons and call the other ones old.  But not sure about that yet. that was the eventual plan i believe

**Comment by karinpb** [comment]
To have a property on the component or a new component defeats the purpose that we want to force this change onto all widgets in OS Portal without them having to do any changes. We want to switch to the new (new) icons in OS Portal, but not in Homepages since that is not using uplift. Just replacing the old, I don't know, if that is a good idea. What about the suggesstions from Andreas, any comment on those?

**Comment by tmcconechy** [comment]
Why not just a setting then `[useNewIcons]="true` but add it to `SohoIconsEmptyComponent`  https://github.com/infor-design/enterprise-ng/tree/main/projects/ids-enterprise-ng/src/lib/emptymessage 

I dont see the point of maintaining two components. And especially dont like the idea of `NewNew` or `New` as the new of the component. Wouldnt a setting work to force it?

**Comment by anhallbe** [comment]
@tmcconechy yeah I like the `@Input()` idea rather than separate components. In fact, I would prefer this way to both the "empty" and other icons.

Something like:
```html
<!-- Use the "new" new empty icons. Should be default? -->
<soho-icons-empty icons="colorful"></soho-icons-empty>

<!-- Use the current soho-icons-empty-new icons. Deprecate soho-icons-empty-new? -->
<soho-icons-empty icons="new-compat"></soho-icons-empty>

<!-- Use the classic empty icons -->
<soho-icons-empty icons="classic"></soho-icons-empty>
```

The only issue I see with this is that it might be hard (impossible?) to tree-shake unused icons.

**Comment by tmcconechy** [comment]
Ok lets do that... I like your suggestion. Im not sure about tree shaking icons. Not sure if its possible either.

**Comment by anhallbe** [comment]
Created a PR for experimentation/discussion: #1426

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
