### ISSUE TITLE
DataGrid | Pager - beforePaging and afterPaging not fired without a source on datagrid options

### ISSUE THREAD

**Issue by LucasLundJensen** [infor-design/enterprise-ng#1419]
**Describe the bug**
The afterPaging and beforePaging events are only emitted from the datagrid if a source is attached in the datagridOptions.

**To Reproduce**
1. Create a datagrid without a source
2. Listen for the event and execute a console.log
Result: Nothing happens

Alternatively:
1. Remove the source from this repositories example
2. See console not emitting event when changing page

**Expected behavior**
The events should be fired regardless of a source being attached in the datagrids options or not.

**Version**
- ids-enterprise-ng: 14.7.1

**Platform**
 - OS Version: Windows 10
 - Browser Name Chrome
 - Browser Version  104.0.5112.102 64-bit

**Comment by LucasLundJensen** [comment]
I'll create a pull request that exposes the events, just like it's done with the standalone pager component.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
