### ISSUE TITLE
Animated bar of Tabs uses wrong width

### ISSUE THREAD

**Issue by kenneth-acejo** [infor-design/enterprise-ng#142]
Steps to reproduce:

1. Click sessionNode3 (now has "is-selected")
2. Click "Tab Name 1" or "Tab Name 4" (both have a textbox with "data-validate="required"")
3. Start typing on either textbox, Name 1 or Name 4
4. Observe Animated Bar of the tabs

Expected: Animated bar should have the width of currently selected tab, positioned under the selected tab.
Actual: Animated bar uses width of currently selected tree node, positioned under first tab with slight margin.

Note: You can use the splitter to change width of the tree node.
![tree-tab](https://user-images.githubusercontent.com/17284784/43180365-546a7aec-900a-11e8-9841-7c7f7b67595f.PNG)

Sample project:
[tree-tab-bug.zip](https://github.com/infor-design/enterprise-ng/files/2226548/tree-tab-bug.zip)

**Comment by tmcconechy** [comment]
This should be fixed by this commit in 4.9 https://github.com/infor-design/enterprise/commit/03c8b8ac3

On investigation whats happening is on that like the old selector `li.is-selected' is targetting the tree so its messing up.

**Comment by tmcconechy** [comment]
This should be fixed by the above commit by now.
