### ISSUE TITLE
Cannot create modal using SohoModalDialogService

### ISSUE THREAD

**Issue by Suhas-kc** [infor-design/enterprise-ng#1420]
**Describe the bug**
Not able to create a modal using SohoModalDialogService. Getting this error
![image](https://user-images.githubusercontent.com/13628420/208005051-b2609eb0-a4ab-4137-8e6a-c29b93ccdd1b.png)

I've made sure to inject the modal service and to add the ErrorModalComponent under declarations in app.module.ts
Please let me know if I'm doing something wrong.

**To Reproduce**
```
const dialogRef = this.modalService.modal<ErrorModalComponent>(ErrorModalComponent).title(`Notifications`).buttons(buttons);
dialogRef.open();
```

**Expected behavior**
A modal should appear.

**Version**
- ids-enterprise-ng: 14.4.3

**Screenshots**
Attached above

**Platform**
 - OS Version: Windows 10 
 - Browser Name Chrome
 - Browser Version  108.0.5359.100

**Comment by tmcconechy** [comment]
@Suhas-kc can you be more precise about how to reproduce this? Where does this code go? 

There is a working example in this repo that does work https://github.com/infor-design/enterprise-ng/blob/main/src/app/modal-dialog/nested-modal-dialog.component.ts#L43

Can you consult that?

**Comment by tmcconechy** [comment]
Was not able to replicate this
