### ISSUE TITLE
Datagrid: Flex toolbar error

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-ng#1423]
**Describe the bug**
With enterprise-ng 14.7.1 we are getting the following error
![image](https://user-images.githubusercontent.com/542598/208447642-8127b9bb-b9ec-4d89-8949-42de5d05c663.png)

**To Reproduce**
It happens when using soho-datagrid together with soho-toolbar-flex . There wasn't a stackblitz for version 14.7.1.
So instead I reproduced the error by using enterprise-ng demo project.
 

1. Clone [https://github.com/guoliang/ids-datagrid-issue](https://github.com/guoliang/ids-datagrid-issue)
2. Build and run demo project
3. Go to http://localhost:4200/ids-enterprise-ng-demo/datagrid-sandbox
4. Open dev tools and click to console
5. On the view click on the Get Dataset button

**Expected behavior**
Expects to get dataset, but instead you get exception thrown in console. Error won't happen if you remove <soho-toolbar-flex>

**Version**
- ids-enterprise-ng: 14.7.1

**Comment by tmcconechy** [comment]
@ericangeles seems like a regression when done the LM stuff can you guys take a look?

**Comment by ericangeles** [comment]
@tjamesallen15 please take a look at this issue. Thanks!

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
