### ISSUE TITLE
Dropdown: Colors next to text does not work with dynamic values

### ISSUE THREAD

**Issue by kels0** [infor-design/enterprise-ng#1425]
**Describe the bug**
Adding data-icon to dropdown to show colors next to the text is not working as expected.

![image](https://user-images.githubusercontent.com/4634476/208643660-c2cc0db8-3b0f-4e27-890f-d997a7b09764.png)

This is how it SHOULD work in my sense but by doing this you get this in the HTML:

![image](https://user-images.githubusercontent.com/4634476/208643839-03918e58-edca-451d-ba11-7a86dfc0266b.png)

Other alternatives gives out errors in the IDE.

**To Reproduce**
1. Make a simple dropdown with a list
2. Do an NgFor to loop through the list
3. Add values to data-icon
4. See result

**Expected behavior**
Colors and value should show

**Version**
- ids-enterprise-ng: 14.4.3

**Screenshots**
See above

**Comment by sanjeewasap** [comment]
Hi @tmcconechy any updates on this issue?

**Comment by tmcconechy** [comment]
@sanjeewasap what app is this for BTW?

**Comment by sanjeewasap** [comment]
This is for IAD App designer in Infor OS
