### ISSUE TITLE
Question: A set release schedule?

### ISSUE THREAD

**Issue by LucasLundJensen** [infor-design/enterprise-ng#1428]
Hi,

I simply just have a question, is there a set release schedule for when this package is updated / a new release is pushed?

**Comment by tmcconechy** [comment]
Yes, If you look at the projects in github you can see the coming releases https://github.com/orgs/infor-design/projects (the ones that say Enterprise 4.xx.x for example [Enterprise 4.71.x (Dec 2022) Sprint](https://github.com/orgs/infor-design/projects/132))

They will always be for a month. Then in the end of that month we release a beta and QA it and a final approx around the 5-10 of the next month.

So pretty much every month around the 5-10th of the month depending on test situations.

We may be changing this sometime but for now its monthly.
