### ISSUE TITLE
[Safari] Elements are not positioned properly after switching languages rtl<>ltr [ex : Gb and AR]

### ISSUE THREAD

**Issue by jjorge1999** [infor-design/enterprise-ng#1431]
**Describe the bug**
Elements are not positions properly after switching languages Ar<>Gb

**To Reproduce**
1. Go to (https://ids-quick-start-1311-zegjhy.stackblitz.io) - the code here is simplified just to show actual Safari behavior base on investigation
2. Click on the Arabic button
3. Click on the English button

**Expected behavior**
Elements should smoothly switch direction (dir) without a problem 

**Actual behavior**
Notice:
1. Checkbox icon is not positioned properly
2. Hover on to the row the values on the type column losses parts of the texts
3. Click one of the value under Type column this show a dropdown but notice the dir of the text it does not go back to ltr. This also happens on the Column title. 

Kindly use the screenshots for reference:

**Version**
- ids-enterprise-ng: v4.70.0

**Screenshots**
<img width="272" alt="image" src="https://user-images.githubusercontent.com/122866382/213084311-ad17cd07-71b6-45cf-aaf4-e726a7442247.png">
<img width="269" alt="image" src="https://user-images.githubusercontent.com/122866382/213084379-e7f2001d-75ab-4615-a5b1-cb1eea1bf23f.png">

**Platform**
 - Device (if applicable): Mac
 - OS Version: MacOS Big Sur v11.6.6
 - Browser Name Safari
 - Browser Version : 14.1.2 (16611.3.10.16)
 
**Additional context**
     Safari remembers the previous dir value specially after ".removeAttr" this happens during changing language is soho specifically **Soho.local.set('lang)**

*Note: Can be tested through Safari. Thank you

**Comment by tmcconechy** [comment]
1. the checkbox position is an issue in all browser -> it doesnt flip
2. the hover issue would go over the readonly field is in all browsers
3. is safari only

**Comment by jbrcna** [comment]
Qa failed.
`Arabic`
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/56722184/221452525-5504e25f-3572-4577-9d4e-d042508c12e3.png">

`English`
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/56722184/221453034-09641f39-eb1b-4f20-a250-c6bff3fbc615.png">

issue
1. toolbar title doesn't go back to english.
2. disassembled pagination

**Comment by jbrcna** [comment]
working as expected. moving this ticket to done. thanks
![Large GIF (1300x472)](https://user-images.githubusercontent.com/56722184/222664944-8c8db9ca-3b52-41a9-8291-ee2cb676f81b.gif)
