### ISSUE TITLE
Arrange: Create wrapper for Arrange component

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise-ng#1432]
**Is your feature request related to a problem? Please describe.**

Arrange component doesn't work in angular wrapper. Create an angular wrapper for arrange component.

**Describe the solution you'd like**

Add typing definition, component and example page for arrange component.

**Additional context**
N/A

**Comment by tmcconechy** [comment]
I think we need to prioritize the header/tabs/color changes first especially with things that need patching

**Comment by ericangeles** [comment]
Sure @tmcconechy, no prob with that.
