### ISSUE TITLE
Update SohoDataGrid dataset removes SohoToolbarFlex

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-ng#1434]
**Describe the bug**

For some reason the toolbar disappears when being interacted with (buttons are pressed)

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1480-1t7bj3?file=src/app/app.component.ts
2. Click on the toolbar button
4. See error -> toolbar disappears

**Expected behavior**
Should not disappear and it didnt in the previous version.

**Version**
- ids-enterprise-ng: 15.0.1

**Additional context**
- Issue described [here] 
- Narrowed it down to setting `toolbar: { keywordFilter: true }`

**Comment by tmcconechy** [comment]
@andriivarhanov can you take a look into this one? Thanks cc @ericangeles

**Comment by tmcconechy** [comment]
FYI issue will be patched in 4.80.2 / NG 14.8.2 ~ running shortly

**Comment by jbrcna** [comment]
QA Passed.
verified in https://main-enterprise.demo.design.infor.com/components/datagrid/test-clear-searchfield-on-update-dataset.html
https://main-enterprise.demo.design.infor.com/components/datagrid/test-update-toolbar.html
