### ISSUE TITLE
Monthview's parameter 'Active Date' not working

### ISSUE THREAD

**Issue by Abrai7** [infor-design/enterprise-ng#1445]
**Describe the bug**
Active Date parameter on Monthview component is not working correctly. After using a number the component will disappear and a message 's.activeDate.getDate is not a function' will be shown on the console.

**To Reproduce**
1. Go to https://stackblitz.com/edit/monthview-component-activate-date-not-working-re3fx8?file=src%2Fapp%2Fform%2Fform.component.html
2. Add parameter [activeDate]="2"
3. See how component disappears.
4. Check console 

**Expected behavior**
The selected date on the component should be changed and the component should remain visible.

**Version**
- ids-enterprise-ng: 13.6.2

**Screenshots**
<img width="619" alt="image" src="https://user-images.githubusercontent.com/9669865/220741558-b939dea3-3fc8-4adb-9b39-42ed1d2b9234.png">

**Additional context**
I've verified on 'monthview-api-func-test.js' file that the activeDate parameter was set to "new Date(2022, 6, 10)", so maybe the input type is wrong on the final version of the component.

**Comment by tmcconechy** [comment]
Actually i dont think activeDate should be public. If your trying to set the dat to show i would use the three individual settings.

```
  month: new Date().getMonth(),
  year: new Date().getFullYear(),
  day: new Date().getDate(),
```

The active date is a date object that represents that date as a date object. We use it internally to know the current day as a date object but i dont think setting it in the manner will work.

**Comment by Abrai7** [comment]
What if I want to change/update the date after the component is created? I have tried to change any of the 3 parameters after an event i.e. a click and I can see that a new component is being created instead of updating the original one.

<img width="379" alt="image" src="https://user-images.githubusercontent.com/9669865/220766169-edf39d83-d15e-4fdd-8d20-a3ee1be2f5eb.png">

**Comment by Abrai7** [comment]
I was able to reproduce the issue on stackblitz. Closing this issue and opening a new one.
