### ISSUE TITLE
Pager: setting showPageSizeSelector to true does not work on soho-standalone-pager.component

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#1459]
**Describe the bug**
Setting the showPageSizeSelector to true, does not show the page size selector for the soho-standalong-pager.component.ts.

Looking at the code, seems like should be setting this.updateRequired to true.

**To Reproduce**
See the attached file.

**Expected behavior**
When setting the showPageSizeSelector to true, expect the page size selector to be displayed.

**Version**
- ids-enterprise: v4.80.3
- ids-enterprise-ng: v14.8.3

**Additional context**
Several Landmark customers are affected.

**Comment by claudenbach** [comment]
![showPageSizeSelectorExample](https://user-images.githubusercontent.com/39804038/230666803-3c9ab4cc-a7ad-4183-9921-d2c389084ec4.gif)

**Comment by claudenbach** [comment]
Suggested code change to soho-standalone-pager.component.ts...

```
  @Input() set showPageSizeSelector(showPageSizeSelector: boolean) {
    this.options.showPageSizeSelector = showPageSizeSelector;
    if (this.pager) {
      this.pager.showPageSizeSelector(showPageSizeSelector);
    }
    this.updateRequired = !!this.pager;
  }
```

**Comment by tmcconechy** [comment]
@claudenbach so this should do it? https://github.com/infor-design/enterprise-ng/pull/1460 ?

**Comment by claudenbach** [comment]
Yes.
