### ISSUE TITLE
Chart Bar looks strange when there is only one value that equals 0

### ISSUE THREAD

**Issue by kkoscielski** [infor-design/enterprise-ng#1463]
**Describe the bug**
Chart Bar looks strange when there is only one value that equals 0 (please see the first screenshot).

**To reproduce**
Go to: https://stackblitz.com/edit/ids-quick-start-1030-xkrbmf?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

**Expected behavior**
Please compare the first screenshot with the second one. The second screenshot depicts more than one record and the value of the first record is 0. The chart bar, which contains only one record and its value equals 0, should present the result in a very similar manner.

**Version**
- ids-enterprise-ng: 13.5.5,

**Screenshots**
![image](https://user-images.githubusercontent.com/105841567/231431099-66351e52-c38f-4bdc-93f5-56e45c48cfd1.png)
![image](https://user-images.githubusercontent.com/105841567/231431563-8a3a8519-c250-408f-8fa5-b35a23367df2.png)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by EdwardCoyle** [comment]
cc @whernebrink

**Comment by tmcconechy** [comment]
@kkoscielski can you attach a way to reproduce this? We probably only need the settings and example data you are passing to the chart and which chart (soho-chart or soho-bar?).

**Comment by kkoscielski** [comment]
@tmcconechy Please visit the stackblitz to examine the issue and see the structure of the data: https://stackblitz.com/edit/ids-quick-start-1030-xkrbmf?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

**Comment by tmcconechy** [comment]
Oh sorry i guess I missed that link.

**Comment by ericangeles** [comment]
@kkoscielski, I can only see an empty message on StackBlitz.

**Comment by kkoscielski** [comment]
@ericangeles Please have another look (https://stackblitz.com/edit/ids-quick-start-1030-xkrbmf?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts)

**Comment by ericangeles** [comment]
@tmcconechy @danielortiz1982 , can this be assessed by our designer? Based on the use case at hand, I don't believe we have any existing solution or feature that addresses this particular requirement.

**Comment by tmcconechy** [comment]
@ericangeles Im not sure what they would do about it. I think its just going to be a blank item like 

https://user-images.githubusercontent.com/105841567/231431563-8a3a8519-c250-408f-8fa5-b35a23367df2.png

If its zero? Seems like a bug that it centers it instead. We do also have this https://main-enterprise.demo.design.infor.com/components/bar/test-empty.html but if its zero it should just render a zero width bar.

**Comment by ericangeles** [comment]
So, if there is no data available, are we going to display a forced empty message? I don't know, it doesn't make sense at all.

**Comment by tmcconechy** [comment]
No it would be like this..

```
data = null or data = [] -> shows empty message
data: {point1: 0, label: 'xxx'}  -> shows a label xxx with a zero width bar
data: {point1: 20, label: 'yyy'}  -> shows a label yyy with a 20 point width bar
```
