### ISSUE TITLE
Datagrid flex toolbar "more" button disappearing, toolbar fields shift position

### ISSUE THREAD

**Issue by dmcodrum** [infor-design/enterprise-ng#1468]
**Describe the bug**
Using "soho-toolbar-flex-more-button", when the more button (ellipsis) is clicked, the more button content displays far left, the more button itself disappears and other fields within the toolbar get shifted center. 

**To Reproduce**
1. Open the IDS NG demo  source.
2. In the ./toolbar-flex/toolbar-flex-datagrid.demo.html file replace the line (26):

<soho-toolbar-flex-more-button [isPageChanger]="true">...

with these lines:

    <soho-toolbar-flex-more-button>
      <ul class="popupmenu">
        <li><a href="#" id="item-one">Pre-defined Item #1</a></li>
        <li><a href="#" id="item-two">Pre-defined Item #2</a></li>
        <li><a href="#" id="item-three">Pre-defined Item #3</a></li>
      </ul>
    </soho-toolbar-flex-more-button>

3. Start the demo app and open the "Toolbar Flex - Datagrid" app.
4. Note normal appearance of the toolbar.
5. Click the more button (...).
6. Note the more button dropdown appears to the left of the toolbar and the other fields fields have shifted to the center of the toolbar.
7. Note the more button disappears and the search field and the delete icon button shift to the center of the toolbar.

**Expected behavior**
More button should not disappear, content should appear under the button and other fields should not shift.

**Version**
- IDS NG Version: 15.2.0

**Screenshots**
Before click:
![image](https://user-images.githubusercontent.com/39279254/235196927-b9949ec0-2eb6-45ca-bd7b-fd0a8333e9f9.png)

After click:
![image](https://user-images.githubusercontent.com/39279254/235197261-a4d25757-f99d-4363-93d1-aa0875865604.png)

**Platform**
 - Device PC
 - OS Version: Windows 11
 - Browser Name Chrome 
 - Browser Version 112.0.5615.138
 - 
**Additional context*

**Comment by dmcodrum** [comment]
I couldn't reproduce this in any of the enterprise demo apps but I do realize this may turn out to be an enterprise issue.

**Comment by tmcconechy** [comment]
@dmcodrum i do see in the demo app that the .. menu is moved below the fold. Is this the same issue. @ericangeles did we happen to fix that?

**Comment by dmcodrum** [comment]
> @dmcodrum i do see in the demo app that the .. menu is moved below the fold. Is this the same issue. @ericangeles did we happen to fix that?

Not sure what you're asking here Tim...

**Comment by tmcconechy** [comment]
@dmcodrum 
Just asking if you run the demo app on main you can see the more button is also disappearing. I do believe we fixed this case. You can see it as you will notice the more button is gone and its hidden below the toolbar out of sight?

We can reverify this when 4.83 is released

**Comment by dmcodrum** [comment]
Ok, yes it is hidden after the click. What is the time frame for 4.83? Our IDS upgrade is on hold due to this issue.

**Comment by tmcconechy** [comment]
Next week (ish)... May 14th - 23th time frame

**Comment by tmcconechy** [comment]
Looks good in 4.83 beta and 16 NG beta
