### ISSUE TITLE
DataGrid: Column alignment with group headers and hide column within the group

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#147]
**Describe the bug**
Misalignment of the column headers over the column data when have group headers and hide a column within the group header.  

**To Reproduce**
I've attached an updated version of the example datagrid-grouped-header.demo.ts.
Added a call to hideColumn for the initial paging request.
 
1. Go to the existing example datagrid-grouped-header.demo.ts
2. Notice that Grouped Headers 2 is correctly over the columns 'Price' and 'Order Date'
3. Update the ts file with my provided example 
4. Notice that Grouped Headers 2 is now over the columns 'Quantity' and 'Price'

In Landmark, when a column contains a progress bar, the header and data is also misaligned.

**Expected behavior**
Group headers stay over the appropriate columns.

**Screenshots**
Display of datagrid-grouped-header.demo.ts without my changes:
![image](https://user-images.githubusercontent.com/39804038/43288257-e650da7c-90ec-11e8-9295-3039912fbc46.png)

Display of datagrid-grouped-header.demo.ts with my changes (which is a hideColumn()
![image](https://user-images.githubusercontent.com/39804038/43288474-979da04e-90ed-11e8-97fc-1799552774ee.png)

In Landmark, the alignment is even more egregious when columns contain a progress bar.
![image](https://user-images.githubusercontent.com/39804038/43289017-3d7596ba-90ef-11e8-8229-d214e2bd40a8.png)

[datagrid-grouped-header.demo.ts.txt](https://github.com/infor-design/enterprise-ng/files/2233631/datagrid-grouped-header.demo.ts.txt)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by lipetzan** [comment]
How do we get this on the next sprint?

**Comment by tmcconechy** [comment]
Will mark as critical so i can bring it up next sprint plan

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datagrid/example-grouped-headers.html
Passed QA testing, working across all browsers.
