### ISSUE TITLE
ApplicationMenu: Hamburger menu icon missing when hovering

### ISSUE THREAD

**Issue by edinfor** [infor-design/enterprise-ng#1470]
**Describe the bug**

hamburger icon is missing after hovering
quick reference to Angular component: https://edinfor.github.io/ids/personalize-color-api

**To Reproduce**
1. Go to 'personlize component'
2. Change theme to "New Light" 
3. Color to "Azure" or anything else
4. Hover over menu icon
5. See missing "icon"

**Expected behavior**
icon should still existing

**Version**
- ids-enterprise-ng: 15.2.6

**Screenshots**

![image](https://user-images.githubusercontent.com/82842191/235784859-a6878d11-3749-472d-b1d5-9cab1a468cbc.png)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
https://edinfor.github.io/ids/personalize-color-api is giving "This site can’t be reached"

**Comment by tmcconechy** [comment]
Actually i think its because we replaced the pseudo elements with an actual svg. https://main-enterprise.demo.design.infor.com/components/applicationmenu/example-index.html

Check your markup and make sure it is now

```
<button id="header-hamburger" class="btn-icon application-menu-trigger hide-focus" type="button" aria-controls="application-menu" aria-expanded="false" tabindex="-1">
              <span class="audible" data-translate="text" data-translate-key="AppMenuTriggerTextAlt">Application Menu Trigger</span>
              <svg class="icon" focusable="false" aria-hidden="true" role="presentation">
                <use href="#icon-menu"></use>
              </svg>
            </button>
```

Wasnt aware the old way would break if it did. But this is the look we want now. As it cleans up the icon

**Comment by tmcconechy** [comment]
OK,So the component needs updating in NG? Or did you change that? Also did you try the latest version of NG?

**Comment by tmcconechy** [comment]
@edinfor I thought this was going to work with the old markup but its not. You will need to change your markup to fix it to use the icon instead of the 3 spans https://github.com/infor-design/enterprise/blob/main/app/views/components/applicationmenu/example-index.html#L61

Its more pixel perfect
