### ISSUE TITLE
Tab: Item sortable not working in Enterprise NG

### ISSUE THREAD

**Issue by crisjoshua-inf** [infor-design/enterprise-ng#1480]
**Describe the bug**
When using the sortable option for tabs in IDS Enterprise ng, we are experiencing console log errors when dragging a tab to another tab and the exchange of tab positions does not work as expected.

2 scenarios were observed:

1st Scenario: Console log errors seen when dragging tabs
**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1521-kyyvva?file=src/app/app.component.html
2. Wait for the stack blitz to compile for the first time (do not tab out)
3. When the preview is now ready, and the code has compiled, immediately (within 2 seconds of the preview has loaded) drag tab1 to tab2 (When unable to replicate, refresh the preview and repeat within 2 seconds of the preview finished loading attempt to drag tab1 to tab2)
4. See error and console errors.

**Expected behavior**
tab1 and tab2 should have swapped positions with no console log errors.

2nd Scenario: Unable to redrag tab to original position
**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1521-kyyvva?file=src/app/app.component.html
2. Wait for the stack blitz to compile for the first time (do not tab out)
3. When the preview is now ready, and the code has compiled wait for atleast 10 seconds as to not to encounter scenario 1, then drag tab2 to tab1(Should be working as expected)
4. Redrag tab2 to tab1 back to its original position
5. tab2 stays in the tab1 position

**Expected behavior**
tab2 should have return to its original position.

**Version**
15.2.1

**Screenshots**
Scenario 1:
<img width="553" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/115533426/94e941e6-859c-48b3-bc8e-4118a03a0324">
Scenario 2:
<img width="556" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/115533426/a60e2c02-0046-43ce-b9ab-d7c32dafd1fb">

**Platform**
 - Infor Application/Team Name: Infor M3
 - Browser Name: Chrome/Edge
 - Browser Version: 113.0.5672.92 (Official Build) (64-bit) / 113.0.1774.35 (Official build) (64-bit)

**Additional context**
Was raised before in teams:
https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1676532243198?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1676532243198&teamName=IDS%20Enterprise%20Development&channelName=General&createdTime=1676532243198

**Comment by crisjoshua-inf** [comment]
hi @tmcconechy, could you share your stack blitz that does not replicate this issue so I may cross reference what maybe causing it in the stack blitz that was provided in the ticket?
As per rechecking the stack blitz link that was provided, can still replicate the issues.

**Comment by crisjoshua-inf** [comment]
hi @tmcconechy could you provide the stack blitz that does not reproduce the issue? so we can identify the differences.
As per rechecking, i can still replicate the issue in the stackblitz link attached to this ticket.

**Comment by crisjoshua-inf** [comment]
Hi @tmcconechy, unfortunately I can still replicate the first issue mentioned here even in the updated IDS Version
16.8.1.
Is there any thing I'm missing or setup that I've done incorrectly? Your assistance here would be extremely appreciated. 
Stack blitz: https://stackblitz.com/edit/ids-quick-start-1681-yctnv8?file=src%2Fapp%2Fapp.component.html

**Comment by tmcconechy** [comment]
Hmm the issue was verified by QA on https://github.com/infor-design/enterprise/pull/7728
Also i tried your example and i can drag them around? So not really sure what you mean? Maybe some caching?

Seems fixed to me on https://stackblitz.com/edit/ids-quick-start-1681-yctnv8?file=src%2Fapp%2Fapp.component.html

**Comment by crisjoshua-inf** [comment]
Luckily I was able to replicate it in this repo using the tabs-module.demo.html and ts file
I'm attaching the two modified files and a video of the issue.

https://github.com/infor-design/enterprise-ng/assets/115533426/afd490c9-4cc7-4a02-bfa2-8813465ab2cb
[tabs-module.demo.zip](https://github.com/infor-design/enterprise-ng/files/13388700/tabs-module.demo.zip)

**Comment by tmcconechy** [comment]
@tjamesallen15 can you check this again? To clarify @crisjoshua-inf you need to modify our example with the one in the zip?

**Comment by crisjoshua-inf** [comment]
@tmcconechy yes. The attached zip are modified examples of tabs-module.demo files

**Comment by inforrpunay** [comment]
Hi @tmcconechy, can this be prioritized as this feature is being asked by customers for quite some time already. Thanks!

**Comment by tmcconechy** [comment]
@inforrpunay marked it to popup with more importance in next sprint grooming. @tjamesallen15 get a chance to check this out again?
