### ISSUE TITLE
Request to publish InforOS Portal 2 components

### ISSUE THREAD

**Issue by BrutalCSkakan** [infor-design/enterprise-ng#1482]
Infor has released the InforOS Portal 2 to all customers, this is a big revamp of the layout in InforOS.

However, we are stuck with the "old" Soho components & layouts, while the Portal uses components such as <portal-osmenu-tab>, <portal-nav-bar> and so on.

I'd like to get access to these components, is that possible?

**Comment by tmcconechy** [comment]
Hey @BrutalCSkakan you dont need "access" other than maybe a free github account. This is open source.

- you can use npm to get these https://www.npmjs.com/package/ids-enterprise-ng
- or clone this repo to play around with the examples
- we also have a chat channel thats free to join for support

https://teams.microsoft.com/l/channel/19%3a83173693057f4991b7a84f030975c06d%40thread.skype/Angular%2520Components?groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&tenantId=457d5685-0467-4d05-b23b-8f817adda47c

Also consider our even newer web component version:  https://github.com/infor-design/enterprise-wc https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc

BTW What is the name of the app your working on?

**Comment by BrutalCSkakan** [comment]
Sorry, my comment redacted the examples as the were containing less-than & great-than signs.

As I stated, the enterprise-ng projects is missing components that are used in the new Infor OS Portal, examples of these components are `<portal-osmenu-tab>, <portal-nav-bar>` and I'd like to have these pushed to the Soho library. 

Are these planned to be developed for Soho, or where & when will these components be available?

**Comment by tmcconechy** [comment]
@BrutalCSkakan i not 100% sure the answer to that. But `<portal-osmenu-tab>`, `<portal-nav-bar>` are not components I'm aware of and not in Soho. So maybe check with the "portal" team?
