### ISSUE TITLE
TargetedAchievement on dataGrid

### ISSUE THREAD

**Issue by stafylas** [infor-design/enterprise-ng#1497]
I am trying to create a column of TargetedAchievement on my datagrid with that way.
     options.columns.push({
              id: 'minutes',
              name: 'Minutes',
              field: 'minutes',
              formatter: Soho.Formatters.TargetedAchievement,            
            });
how can i define ranges of that ?

I cannot find an example of something like that. Is it working ?
I tried that link https://design.infor.com/code/ids-enterprise/latest/demo/datagrid/test-targeted-achievement.html?font=source-sans but it isn't working.

**Comment by tmcconechy** [comment]
You can use the same options in the column in angular. If one is missing we may need to add.
