### ISSUE TITLE
Datagrid: headerIconTooltip is missing in datagridcolumn-model

### ISSUE THREAD

**Issue by kels0** [infor-design/enterprise-ng#1514]
**Describe the bug**
headerIconTooltip is missing in the model.

**Expected behavior**
Expected to have that property in the model

**Version**
- ids-enterprise-ng: "15.3.2",

**Screenshots**
![image](https://github.com/infor-design/enterprise-ng/assets/4634476/5bb92a29-7d33-48c7-a4b4-d333b6f6ea65)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Comment by tmcconechy** [comment]
See attached PR @kels0 
FYI for a workaround can do any... fx (columns as any).headerTooltip = 'xxx'

**Comment by kels0** [comment]
> See attached PR @kels0 FYI for a workaround can do any... fx (columns as any).headerTooltip = 'xxx'

That is what I did but I hate using **any**...
