### ISSUE TITLE
Search feature on swaplist component on enterprise-ng

### ISSUE THREAD

**Issue by JestoniFajardo** [infor-design/enterprise-ng#152]
**Problem**
On existing behavior of swaplist component can't search on both **available** and **selected** list

**Acceptance Criteria**

- User can search on both list which is same with list view component search feature. If user searched an item which is not found on the list it will display ang empty state or message that gives information that item searched is not available.

- Search textbox has clear button which reset the searched value.

**Additional context**
Sample Screenshots:
![image](https://user-images.githubusercontent.com/42030487/43591031-ff35cddc-96a4-11e8-960d-a5b26a4c6b34.png)

**Comment by tmcconechy** [comment]
We do have this feature as you can see on this example? http://master-enterprise.demo.design.infor.com/components/swaplist/example-search.html

Are you on the latest version?

**Comment by tmcconechy** [comment]
Working with @JestoniFajardo i found that although we have this working in http://master-enterprise.demo.design.infor.com/components/swaplist/example-search.html

There is not a working example in the sample app. Just changing the input '[searchable]="true"` has no effect.

Should add an example for this.

**Comment by tmcconechy** [comment]
@deep7102 knows about this feature. If you have questions feel free to ask him.
