### ISSUE TITLE
Module nav additional web app icon support

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise-ng#1523]
**Is your feature request related to a problem? Please describe.**
1. Add ability to set tooltip on webapp icon (when in collapsed state)
2. Add ability to pass in a URL for webapp icon
3. Additionally support using existing IDS icons. Looks like the option to do so is there, but doesn't appear to be working, or fully implemented.
<img width="406" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/1056684/f7fed345-faf0-48c1-80bf-d66b1baa9628">

**Describe the solution you'd like**
Can probably use `soho-tooltip` directive for tooltip support. And add an @input() allowing a tooltip message to be passed into the control. Similar approach could be used for the url.

![no-tooltip](https://github.com/infor-design/enterprise-ng/assets/1056684/20c4c3a3-40ab-4ab3-9c58-0234815f5a91)

**Comment by EdwardCoyle** [comment]
Noting here:  The tooltip issue is resolved on #1522, and is simply controlled by setting the Module Switcher's `moduleButtonText` input

**Comment by EdwardCoyle** [comment]
Noting for URL support -- we have a discusson going on [MS Teams]()

By URL support, we don't mean "make an AJAX call internally" but rather having the ability to set a `src` attribute on an image.  We can either do this by just simply passing a URL text string, OR we can hook into the Module Switcher's current `icon` setting to return a properly-formatted `<img>` tag with the correct source.  We should work closely with @krishollenbeck on the Landmark team's needs for this issue.
