### ISSUE TITLE
Datagrid: Exandable row with custom component has restricted width 

### ISSUE THREAD

**Issue by kwolentarski** [infor-design/enterprise-ng#1524]
**Describe the bug**
When using Datagrid with expandable rows created from custom component there is an issue with the available width. The custom component is created inside div with class .datagrid-cell-layout, which causes it to be displayed as table-cell, which restricts the available width of the component.

**To Reproduce**
Go to https://stackblitz.com/edit/ids-popover-issues?file=src%2Fapp%2Fapp.module.ts
2. Click on 'Popover 2'
3. Extend any data grid row
4. Notice that content is not taking all available space
5. Once the datagrid-cell-layout is removed the content is taking all available space (see comparison below)
 
![image](https://github.com/infor-design/enterprise-ng/assets/86295640/6cfef1ea-5bf8-4dfb-bc6c-aa24eb7ee37c)

**Expected behavior**
The host element for custom component should not have datagrid-cell-layout class applied, to make it possible to use whole available space

**Version**
- ids-enterprise-ng: 15.4.1

**Platform**
 Infor Application/Team Name: Infor WFM

**Comment by tmcconechy** [comment]
@kwolentarski so you just want to remove the padding? I think that may be problematic from a breaking change standpoint?

https://github.com/infor-design/enterprise-wc -> might handle it better

Also i think its too much content for a popup. So maybe it works if you include it an page in the workflow instead of a popup?

**Comment by kwolentarski** [comment]
Here's example outside of popover: https://stackblitz.com/edit/ids-datagrid-expandrow?file=src%2Fapp%2Fapp.component.html
The padding itself is fine, don't have problem with that:
![image](https://github.com/infor-design/enterprise-ng/assets/86295640/70f38e2e-d4fb-4ad8-9f07-31a63eee368c)
What I would like to remove is the .datagrid-cell-layout class which causes it to display as table-cell, not taking the whole available space:
![image](https://github.com/infor-design/enterprise-ng/assets/86295640/fd12e7fa-35af-4d3f-be45-7666d6c735a9)

**Comment by tjamesallen15** [comment]
@tmcconechy If i remember correctly, the datagrid-cell-layout is in the rowTemplate which can be customized.

![image](https://github.com/infor-design/enterprise-ng/assets/34049950/78be3842-42e5-4897-bdbf-29adb4995f82)

**Comment by tmcconechy** [comment]
@tjamesallen15 @kwolentarski 

I dont know if this is safe to remove but the request is to remove this rule https://github.com/infor-design/enterprise/blob/main/src/components/datagrid/_datagrid.scss#L4670

Have a look and see if it breaks any of our examples. Could break someone else if we do. So maybe you need to workaround it with your own css @kwolentarski 

But see if we can get away with removing @tjamesallen15 and we can decide

**Comment by kwolentarski** [comment]
@tmcconechy, actually I don't want to remove the CSS rule, but I would like to remove this class from the row-template host container:
https://github.com/infor-design/enterprise-ng/blob/main/projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.component.ts#L2383
Since the component is provided, it should define itself how it looks, similarly to how basic rowTemplate works. It is still restricted with parent .datagrid-row-detail-padding, as shown in the screenshot from my previous comment
