### ISSUE TITLE
Nav Button: Better tooltip support for module nav button menu

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise-ng#1525]
**Is your feature request related to a problem? Please describe.**
Would like to show a tooltip on the "Settings" button menu. But only when it is in a collapsed state.

**Describe the solution you'd like**
Possibly provide a tooltip input for `SohoModuleNavSettingsComponent`.

**Describe alternatives you've considered**
Currently this works, for adding a tooltip. But the tooltip is not isolated to just the icon. Which causes the tooltip to still display when hovering over "Settings" in an expanded state.

```
<soho-module-nav-settings>
    <div soho-menu-button soho-tooltip [content]="'Settings'" ...>
        <a href="#"><span>Settings</span></a>
    </div>
</soho-module-nav-settings>
```

**Additional context**
![tooltip-on-expanded](https://github.com/infor-design/enterprise-ng/assets/1056684/dba587f1-fcae-4710-ae29-8ebe66f1338a)

**Comment by krishollenbeck** [comment]
@tmcconechy This was specifically for the "Settings menu". I had to add a tooltip for the icon.  Problem is, the tooltip also displays when the menu is expanded..

```
<div soho-menu-button
    id="module-nav-settings-btn"
    class="module-nav-settings-btn accordion-header"
    soho-tooltip content="{{'More' | translate}}"
    [icon]="'settings'"
    [hideMenuArrow]="true"
    [showArrow]="false"
    [returnFocus]="true"
    [ripple]="false"
    [menu]="'module-nav-settings-menu'">
    <a href="#"><span>{{'More' | translate}}</span></a>
</div>
                    ```

**Comment by tmcconechy** [comment]
This should be working if you do not provide a custom tooltip and just set the text as described

**Comment by krishollenbeck** [comment]
@tmcconechy There is no tooltip by default.

![tooltip-issue-ng](https://github.com/infor-design/enterprise-ng/assets/1056684/a53ebe29-34e1-40d3-9011-172aa91ffdcf)

I added a tooltip using the `soho-tooltip` directive. Like this..

```
<div soho-menu-button
    id="module-nav-settings-btn"
    class="module-nav-settings-btn accordion-header"
    soho-tooltip content="{{'More' | translate}}"
    [icon]="'settings'"
    [hideMenuArrow]="true"
    [showArrow]="false"
    [returnFocus]="true"
    [ripple]="false"
    [menu]="'module-nav-settings-menu'">
    <a href="#"><span>{{'More' | translate}}</span></a>
</div>
```

Problem is, this adds the tool tip to the container. So the tooltip shows up when I hover over the "more" menu item in an expanded state. Instead I would like to have the ability to add the tooltip to just the button.

**Comment by krishollenbeck** [comment]
![tooltip-example](https://github.com/infor-design/enterprise-ng/assets/1056684/f96b2b2e-3492-4b47-aa49-fd23728d1e5c)

**Comment by tmcconechy** [comment]
I get a tooltip by default https://main-enterprise.demo.design.infor.com/components/module-nav/example-index.html?colors=fff for all the items here only when collapsed

**Comment by krishollenbeck** [comment]
My example is from the NG project. So probably something specific to the NG project.

**Comment by tmcconechy** [comment]
Looks ok there too https://watch.screencastify.com/v/KC60wQu3npclZ3nNUILi
Maybe cross check your construction? Its just using this span and showing that text in the right states by default https://github.com/infor-design/enterprise-ng/blob/main/src/app/module-nav/module-nav.demo.html#L95

If you added a tooltip manually try using the text instead

**Comment by krishollenbeck** [comment]
The issue is only on the "settings" button.

**Comment by tmcconechy** [comment]
Ok i see now on https://github.com/infor-design/enterprise-ng/issues/1525#issuecomment-1660458804 no tooltip?

@EdwardCoyle do you happen to know why it doesnt show a tooltip in NG?

**Comment by tmcconechy** [comment]
Adding a fix. You will be able to do this.

```
      <soho-module-nav-switcher
        class="module-nav-switcher"
        [icon]="false"
        ....
    </div>
```

**Comment by tmcconechy** [comment]
Moved code to future 4.84.6 patch and 4.86.0
