### ISSUE TITLE
Module Nav Switcher: Changing `moduleButtonText` input doesn't update collapsed-mode tooltip

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-ng#1528]
**Describe the bug**
When using the `moduleButtonText` input to programmatically change the button's text content, the corresponding tooltip that is displayed does not also update.

**To Reproduce**
1. Pull both of these branches, build and `npm link` properly:
  - EP:  https://github.com/infor-design/enterprise/tree/ng1477-tooltip-patch
  - NG:  https://github.com/infor-design/enterprise-ng/tree/1477-tooltip-patch
2. Go to http://localhost:4200/ids-enterprise-ng-demo/
3. In Module Nav's collapsed mode, hover the Module Button to see the text "Standard Module" in a tooltip.
4. Open the settings menu and choose the option that says "Change Module Switcher Button Contents".  This uses the input to switch the module button text content
6. Try hovering the Module button again.  See that no tooltip is present.

**Expected behavior**
The tooltip should display, and it should contain the updated text content

**Version**
- special branch

**Additional context**
My testing up to this point has shown me a couple things:
- The module button text itself does actually update
- The tooltip component doesn't appear to be established on the Module Switcher anymore after the change to the input occurs (try looking at the jQuery `.data()` for the module switcher (READ: not the button but the thing that wraps the button)
- Sometimes after switching between the display modes a couple times (click the hamburger), it does actually update.

**Comment by tmcconechy** [comment]
No longer needed as i understand it from @EdwardCoyle but we did include a fix (seems wierd i know)
