### ISSUE TITLE
Editor does not support pasting of plain text

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise-ng#153]
**Describe the bug**
Rich Text Editor does not support pasting of plain text
used version: 4.8.0
**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/editor/example-index?font=source-sans
2. Copy url from Chrome url bar
3. Try to paste into Editor
4. See paste ignored

**Expected behavior**
Editor supports paste of plain text

**Comment by tmcconechy** [comment]
Can you put this one over at https://github.com/infor-design/enterprise as its a general issue not angular specific... I'll mark it critical there
