### ISSUE TITLE
MoreNav: External icon support for module nav role switcher

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise-ng#1533]
**Is your feature request related to a problem? Please describe.**
Would like to have a way to pass in URLs for icons displayed within the role switcher. Similar to what is currently supported for the webapp icon.

<img width="236" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/1056684/7026a620-215e-4391-9087-9eae5b127f6f">

**Describe the solution you'd like**
Potentially something like this..

```
 public dropdownRoles: Array<SohoModuleNavSwitcherRoleRecord> = [
    { text: 'Admin', value: 'admin',  'icon': 'http://some.svg' },
    { text: 'Job Console', value: 'job-console',  'icon': 'http://some.svg'  },
    { text: 'Landing Page Designer', value: 'landing-page-designer',  'icon': 'http://some.svg'  },
    ...
  ]
```

**Comment by tmcconechy** [comment]
Ultimately this means adding url functionality to the dropdown icon support

**Comment by krishollenbeck** [comment]
> Ultimately this means adding url functionality to the dropdown icon support

Yeah

**Comment by EdwardCoyle** [comment]
This was incorrectly closed before, reopening but PR-ing shortly
