### ISSUE TITLE
Module Nav: Add ability to disable search on the role switcher

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise-ng#1535]
**Is your feature request related to a problem? Please describe.**
Add ability to disable search on the role switcher. Sounds like this is an existing option, but not yet exposed via the angular wrapper.

<img width="239" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/1056684/5a4bb18e-626b-4ac9-99e1-2dc4da9775d9">

**Describe the solution you'd like**
Add an option to disable/enable search in the role switcher. Currently it is enabled with no API exposed to disable it.

**Comment by tmcconechy** [comment]
yeah i guess this is the no-search option https://main-enterprise.demo.design.infor.com/components/dropdown/example-no-search.html

If you have the time and its just a matter of a type in NG? Maybe do a PR. If not will get to it...
