### ISSUE TITLE
Datepicker: Cannot re-enable datepicker component

### ISSUE THREAD

**Issue by sjasaniel** [infor-design/enterprise-ng#1540]
**Describe the bug**
cannot re-enable datepicker component

**To Reproduce**
Please update the ff files:
1. In datepicker.demo.html, update dynamicLegend element
<input soho-datepicker #dynamicLegend **[disabled]="isDisabled"** id="dynamicLegend" name="dynamicLegend" dateFormat="MM/dd/yyyy" mode="standard" placeholder="MM/dd/yyyy" [(ngModel)]="model.standard" (change)="onChange($event)" (listopened)="onDynamicListOpened()" (monthrendered)="onDynamicMonthRendered($event)" [showLegend]="true" [legend]="legend$ | async"/>
2. In datepicker.demo.ts, 
  a. add this line in setEnable  this.isDisabled = false;
  b. add this line in setDisabled  this.isDisabled = true;
  c. add property public isDisabled = false;

Steps to replicate:
1. Click 'Disable' button
2. Click 'Enable' button

![LMWEB-18053_soho](https://github.com/infor-design/enterprise-ng/assets/9715303/818ef783-cefa-4764-a1cc-15fdcf68a459)

**Expected Result**
Datepicker should be enabled when enable button is clicked

**Actual Result**
Datepicker remains disabled.

**Version**
- ids-enterprise-ng: 4.86

**Screenshots**
Please see attached gif.

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: Windows 11 enterprise
 - Browser Name: Chrome
 - Browser Version: 115.0.5790.171 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
See also https://github.com/infor-design/enterprise-ng/issues/1466 (maybe fixed it)

**Comment by pwpatton** [comment]
@tmcconechy I think this is the culprit

```typescript
  @Input() set disabled(value: boolean | undefined) {
    ...
    if (value) {
      this.ngZone.runOutsideAngular(() => {
        this.datepicker?.disable();
      });
    } else {
      this.ngZone.runOutsideAngular(() => {
        if (this.readonly === null || this.readonly === undefined) {
          this.datepicker?.enable();
          this.isReadOnly = false;
        }
      });
    }
  }
```

Setting `this.isReadOnly = false` causes `get readonly()` to return false, therefore we are never able to enable the datepicker after that.

```typescript
  get readonly(): boolean | undefined {
    return this.isReadOnly;
  }
```

**Comment by tmcconechy** [comment]
If that works? Do you want to do a PR?

**Comment by pwpatton** [comment]
That just shows the issue. I did not look into how to fix it and why it's there in the first place.

**Comment by tmcconechy** [comment]
Ok we will take a look and see if thats the best.

**Comment by tmcconechy** [comment]
ok, lets see if we can add what @pwpatton suggests as well. Im not sure what caused this. Im thinking it was angular updates that did it as nothing else changed in reference to this but we started to get problems with this attribute.

**Comment by radovaniljic** [comment]
@tmcconechy this is still not working. 

```javascript
  @Input() set disabled(value: boolean | undefined) {
    ...
    if (value) {
      this.ngZone.runOutsideAngular(() => {
        this.datepicker?.disable();
        this.isReadOnly = true; // this line was added in the PR
      });
    } else {
      this.ngZone.runOutsideAngular(() => {
        if (this.readonly === null || this.readonly === undefined) {
          this.datepicker?.enable();
          this.isReadOnly = false;
        }
      });
    }
  }
```
As @pwpatton pointed out, the issue is `if (this.readonly === null || this.readonly === undefined)` preventing `this.datepicker?.enable()` from executing.

**Comment by tmcconechy** [comment]
@tjamesallen15 can you take another look perhaps adding the fix as suggested by @pwpatton
