### ISSUE TITLE
Dropdown: Dropdown with default max width leaves a space when expanded

### ISSUE THREAD

**Issue by kyfloresca** [infor-design/enterprise-ng#1541]
**Describe the bug**
Dropdown with default max width leaves a space when expanded.

**To Reproduce**
1. Go to ['Demo link'](https://design.infor.com/code/ids-enterprise/latest/demo/components/dropdown/example-virtual-scroll?theme=uplift&variant=light)
2. Open developer tools, place it on the left side
![image](https://github.com/infor-design/enterprise-ng/assets/116287798/22911973-59f1-4470-9eed-8163e9f3836e)
3. Expand dropdown
![image](https://github.com/infor-design/enterprise-ng/assets/116287798/fb89bf1c-0b62-42c3-9bf9-3c8184d90453)

**Expected behavior**
In our situation, the dropdown is placed on the rightmost of the page. We expect the dropdown list to open to the left instead of the right if there is space on the left side.

**Version**
- ids-enterprise-ng: -

**Screenshots**
![image](https://github.com/infor-design/enterprise-ng/assets/116287798/a0c7d759-7a1a-464d-bb7c-df0edd636d14)

**Platform**
 - Infor Application/Team Name: Infor M3
 - OS Version: Windows 10
 - Browser Name: Google Chrome
 - Browser Version: Version 115.0.5790.171 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
I expect it works ok if you dont use a custom width?

**Comment by kyfloresca** [comment]
yep, but the customer wants all the available options to be displayed in full.
