### ISSUE TITLE
SohoPopupMenu: Shared menu not always returning to original placement

### ISSUE THREAD

**Issue by kwolentarski** [infor-design/enterprise-ng#1546]
**Describe the bug**
When sharing popup/context menu between components, the order in which they are destroyed makes a difference where the menu will go in the DOM. The popup menu is removed from the wrapper only when the last element pointing to it is destroyed. If this last element was the first created everything works and it goes to the original place. For all other elements when context-menu is initialized, it is already placed in the wrapper and the setMenuOrgContainment method is not called. So only first element has reference to the original parent of the menu. In case the trigger element is inside component which will be destroyed, the menu will be placed next to this element and immediately removed. When the next element appears which that will point to this menu, it will not work, as there is no menu layout in the DOM anymore.

**To Reproduce**
1. Go to 'https://stackblitz.com/edit/soho-popupmenu-bug'
2. Follow the steps described on the page

You can also see the incorrect placement in one of the demo pages:
1. Go to 'http://localhost:4200/ids-enterprise-ng-demo/context-menu-shared'
2. Destroy 'Text Area' and then destroy 'Input'
3. In dev tools see that popupmenu returned to original place next to fields:
![image](https://github.com/infor-design/enterprise-ng/assets/86295640/b2acb1d2-36e7-4339-8115-129a6f690b22)
4. Refresh the page and now destroy 'Input' first and then 'Text Area'.
5. Notice in dev tools that now the popupmenu is inside 'Text Area' div
![image](https://github.com/infor-design/enterprise-ng/assets/86295640/0f1b0b72-74bb-4a37-834e-cb44aa4428f0)

**Expected behavior**
Menu should return to the original placement regardless of the order in which trigger elements are destroyed

**Version**
- ids-enterprise-ng: 16.6.1

**Platform**
 - Application: Infor WFM

**Comment by glenlieorillo** [comment]
QA Passed.


https://github.com/infor-design/enterprise-ng/assets/102151352/e342aebe-de3b-4485-9b74-6b64844606f1

**Comment by jbrcna** [comment]
moving this ticket to done. thanks
