### ISSUE TITLE
Modal: Scrollbar with a list view that loaded in a dialogbox  has a gap

### ISSUE THREAD

**Issue by AmilaViduranga** [infor-design/enterprise-ng#1547]
**Describe the bug**
Normally in soho-list view, it has a scroll bar and it loaded when there is a lengthy list.  It works fine with out any UI issue. But when we try to load the same contain in a dialog box or a modal, the scroll bar has a gap. (in bellow image, the scrol,l bar appears at the right corner and there you can see the gap between the modal/ dialogbox right border and the scollbar)

![image](https://github.com/infor-design/enterprise-ng/assets/13863481/ed1e959b-9d81-430f-a869-9978aeb3c3fb)

**To Reproduce**
1. create a component with soho-list and add large set of items to load scroll bar
2. load that component inside a dialog box
3. Observe the result

**Expected behavior**
The view should be something like this (without any gap). It is better if we can have an option to decide if we need a gap or not. By default, it should not have a gap.

![image](https://github.com/infor-design/enterprise-ng/assets/13863481/ceb29534-860b-49f5-9876-4c366dec8d83)

**Version**
- ids-enterprise-ng: v 16.5.1

**Screenshots**

**Platform**
 - Device: Any screen
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: Version 115.0.5790.173 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
This can be reproduced on https://main-enterprise.demo.design.infor.com/components/listview/test-modal.html
I dont see the need for the gap. So will just fix it to not have a gap
