### ISSUE TITLE
Pager: dataset not updated correctly

### ISSUE THREAD

**Issue by s-gasior** [infor-design/enterprise-ng#1554]
**Describe the bug**
When the dataset passed to Standalone Pager Component changes, it is not updated correctly.
Old and new datasets are merged.

Example: 
Changing dataset=[1,1,1,1,1,1] to [2,2] results in [2,2,1,1,1,1] - incorrect

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1701-vbs5jb?file=src%2Fapp%2Fapp.component.html
2. Open Stackblitz Console.
3. Click on "Change dataset".
4. See old and new datasets in Console.

**Expected behavior**
New dataset should replace old one.

**Version**
- ids-enterprise-ng: 16.7.1

**Comment by ericangeles** [comment]
@s-gasior Hi, have you tried using the latest version of IDS NG (16.9)? I've tested both in the core (enterprise latest) and in the latest Angular wrapper, and I haven't encountered this issue.

**Comment by s-gasior** [comment]
Hi, I have just checked, here is the updated example https://stackblitz.com/edit/ids-quick-start-1701-vbs5jb?file=src%2Fapp%2Fapp.component.html
The issue remains

**Comment by tmcconechy** [comment]
@s-gasior can you explain the example more in the steps? i wonder if its just a wrong example. Because at no time do i see any data at all in the grid?

**Comment by s-gasior** [comment]
It is about standalone pager, so the easiest way to check is by looking at the console log. The initial dataset is [1,1,1,1,1,1]. After clicking the "Change dataset" button, the dataset should change to [2,2]. However it is changed to [2,2,1,1,1,1] (caused by merging the settings).

**Comment by ericangeles** [comment]
@s-gasior Yes, I used the standalone example and set it up the same way as your example. Could you please try using the latest version first and check if the issue still persists? We typically don't apply patches to older versions unless it's necessary.

**Comment by s-gasior** [comment]
**Use case**
Changing the dataset passed to the pager (eg. new set retrieved from backend or removing item on frontend).

When new dataset is smaller than the old one, it is not updated correctly.

Please see attached patch, with the changes to pager-standalone.demo files to reproduce the issue
[pager-standalone.demo.patch](https://github.com/infor-design/enterprise-ng/files/13391176/pager-standalone.demo.patch)

Initial dataset has 100 elements. New dataset has 20 elements
Steps:
1. Click on "Show Model" to see initial dataset of 100 items
2. Check the total number of pages - 10
3. Click on "Change dataset" - initial dataset should be replaced by new dataset
4. Check the dataset displayed under "Hide Model" button - displays new dataset with 20 items
5. Check in console, where old and new datasets are printed - both of them have 100 elements, new one should have 20
6. Check the total number of pages - 10, should be 2

**Comment by tmcconechy** [comment]
@s-gasior i think if your using standalone page you should know its 100% standalone. I.E. it wont change the data in your dataset. So wouldnt you need to make the logic to correct the data in the pager events?

Or does this help see an issue @ericangeles Im not picking up an issue here myself.
