### ISSUE TITLE
Verify event handlers and Outputs on widgets

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#156]
**Describe the bug**

I have noticed many of the events exposed by the Angular components are not correct, either using `any` or not using the correct value.

The events are also populated inconsistently, either by injecting the "args" into the `JQuery.Event` object, ignoring the event, or create an untyped result.

**To Reproduce**

For example, in `soho-chart.component.ts`:

```ts
this.jQueryElement.on('selected', (event: JQuery.Event, ui: any, data: any) => {
  this.selected.emit({ event, ui, data });
```

Also `soho-editor.component.ts`:

```ts
  this.jQueryElement.on('change', (e: JQuery.Event, args: SohoEditorEvent) => this.onChange(args));
  this.jQueryElement.on('updated', (e: JQuery.Event, args: SohoEditorEvent) => this.updated.next(args));
```

**Expected behavior**

Events should be consistent, correct and complete for each widget.

**Screenshots**
 
N/A

**Platform**

N/A

**Additional context**

**Comment by bthharper** [comment]
I have resolved the issues with DataGrid, however additional work may be required on other components.

**Comment by tmcconechy** [comment]
Descoping this as ongoing work
