### ISSUE TITLE
Datagrid: UpdateRow not triggering component formatter

### ISSUE THREAD

**Issue by Elias-Hjelm** [infor-design/enterprise-ng#1564]
**Describe the bug**
When using an angular component to format a cell, updateRow will not trigger the formatter.

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1671-ru5kiu?file=src%2Fapp%2Fformatter%2Fformatter.component.ts,src%2Fapp%2Fdatagrid%2Fdatagrid.component.ts,src%2Fapp%2Fdatagrid%2Fdatagrid.component.html
2. The value in the second column will initially be  the string "formatted".
3. Edit the value in the first column, this will trigger the onCellChange method, which will invoke the updateRow method.
4. The row will get updated, but the angular component that is used to format the second column's cells will not be triggered. So the value in the second column will be the string "Building10". If it actually got formatted the value would be the string "formatted" as it previously was.

**Expected behavior**
I expected updateRow to trigger the angular component formatter. Because it triggers the "normal" formatters like the Date one.

**Version**
- ids-enterprise-ng: 16.7.1

**Platform**
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 117.0.5938.132 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
@Elias-Hjelm this may be solved by https://github.com/infor-design/enterprise/issues/8058
