### ISSUE TITLE
Monthview: Calendar is not updated when date is updated

### ISSUE THREAD

**Issue by lbursey-infor** [infor-design/enterprise-ng#1565]
**Describe the bug**
When updating the date in the monthview calendar, I am not seeing the change reflected in the calendar

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1671-fschdg?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html
2. Click on button
3. See that date is not updated

**Expected behavior**
The selected date should be changed on the calendar

**Version**
- ids-enterprise-ng:16.7.1

**Additional context**
I've noticed that updating activeDate also does not work. In the IDS project activeDate is a number type, but it looks like it gets used as a date in the library itself, as I see a console type error (trying to call getDate() on number) when I try to update it. Casting to any and then feeding it a date does not fix my original issue.

**Comment by lbursey-infor** [comment]
@tmcconechy I'm having the same issue using soho-calendar and soho-calendar-monthview, as in the following stackblitz: https://stackblitz.com/edit/ids-quick-start-1671-z7wcgo?file=src%2Fapp%2Fapp.component.html

Note that soho-calendar does not expose a [day] input. I can open a separate issue if that's preferred.

**Comment by tmcconechy** [comment]
@lbursey-infor sound like the same thing. But i think we would rather have the input be a date. Vs having several inputs
