### ISSUE TITLE
Timepicker: Button Disabled When Timepicker is Enabled

### ISSUE THREAD

**Issue by yousef-elkaisi** [infor-design/enterprise-ng#1567]
**Describe the bug**
When the timepicker is disabled, it is grayed out and cannot be clicked. Then when it's re-enabled, it becomes un-grayed out, but the button is still disabled and cannot be clicked.

**To Reproduce**
Go to http://localhost:4200/ids-enterprise-ng-demo/timepicker 
Time picker is initially enabled and works as expected.
Click the disable button. Now timepicker is disabled and not clickable as expected.
Now click the enable button. Timepicker appears enabled but it is not clickable.

**Version**
- ids-enterprise-ng: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
See below, button has disabled attribute when timepicker is enabled.
![image](https://github.com/infor-design/enterprise-ng/assets/132393590/5bfbb814-d991-47cd-b410-511258e84bdc)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - Windows 11
 - Chrome
 - 117.0.5938.150

**Comment by tmcconechy** [comment]
Did you check 16.8? (main?) Sounds like it but we have addressed similar issues.

**Comment by yousef-elkaisi** [comment]
I pulled from main this morning.

**Comment by eddieinfor** [comment]
@tmcconechy do we have any updates on this issue? it's causing an critical bug for us because this disregards all the form control validation and allowing users to submit forms even when the form is invalid. thanks!

**Comment by tmcconechy** [comment]
Not yet. But we do have it scheduled for the month. I made it high so it doesnt get dropped. So expect it in 4.91 in Dec.

If you have a fix feel free to PR but we do have it assigned and scheduled.

**Comment by edinfor** [comment]
@tmcconechy will it be possible to patch 15.6.0? we are still on 15 right now, and upgrading to 16 is planned, we are currently blocked due to issues with building AngularJS application using node 16 and above.

Thanks!

**Comment by tmcconechy** [comment]
@edinfor Yes, i can try. Sometimes the 15 branches are out of sync and maybe the release wont work. But its not that old so should be possible. (i.e. I try it works or not).

First of all need a fix here then remind me when its merged

**Comment by tmcconechy** [comment]
@edinfor where do you need this patch? What npm version where you using.

**Comment by tmcconechy** [comment]
@edinfor what was the version of ids-enterprise-ng you want it patched in? I think the angular version doesnt help we had a lot of versions on NG 15?

Or did you mean ids-enterprise-ng@15.6.0?

**Comment by tmcconechy** [comment]
ok @edinfor its ids-enterprise-ng@15.6.1 

https://www.npmjs.com/package/ids-enterprise-ng/v/15.6.1

**Comment by jbrcna** [comment]
QA Passed.
verified in https://main-enterprise.demo.design.infor.com/components/timepicker/test-states.html
