### ISSUE TITLE
Pager: expose activePage to Angular component

### ISSUE THREAD

**Issue by s-gasior** [infor-design/enterprise-ng#1571]
**Is your feature request related to a problem? Please describe.**
It is not possible to set active page of a pager programmatically.

**Describe the solution you'd like**
Pager will be more flexible if it has the ability to set activePage in code (as a component input)

**Describe alternatives you've considered**

**Additional context**
Eg. scenario:
Dataset changes, but I want to stay on the current page. Currently the activePage resets to the first one, which is fine. But I would like to have the ability to navigate back to the previously selected page programmatically.

**Comment by tmcconechy** [comment]
Note that you can use this like this at the moment https://github.com/infor-design/enterprise/blob/main/app/views/components/datagrid/test-paging-specific-page.html#L46

But this makes sense....
