### ISSUE TITLE
Multiselect: Add editor/row and filter example

### ISSUE THREAD

**Issue by puriaayush01** [infor-design/enterprise-ng#1573]
**Is your feature request related to a problem? Please describe.**
Currently, we only have a Dropdown in the Soho.Editor, and it does not support multi-select dropdown selection as it does in the Enterprise-grade web component. Therefore, a multi-select editor is required for my project, which needs a multi-select dropdown in the Editable Grid.

**Describe alternatives you've considered**
I have tried using "(Soho.Editors as any).MultiSelect", but unfortunately, it still doesn't seem to work.

**Additional context**
<img width="229" alt="MicrosoftTeams-image (15)" src="https://github.com/infor-design/enterprise-ng/assets/110390926/c0f4e3f0-3b91-4815-9223-c9547e87cc46">

**Comment by tmcconechy** [comment]
For this lets add an example like https://github.com/infor-design/enterprise/blob/main/app/views/components/datagrid/test-multi-select-dropdown-selection.html#L260-L283
 
But with filter as well and make sure it works in both EP and Angular. I added the type https://github.com/infor-design/enterprise-ng/commit/d38083d3043416b8359412373d96531ca6ff9832 but i guess more than it to it.
