### ISSUE TITLE
Tabs: Veto of tab swapping is not working

### ISSUE THREAD

**Issue by lpagdanganan** [infor-design/enterprise-ng#1578]
**Describe the bug**
Using soho tabs, the beforeActivated event's veto of tab swapping is not working. Even if the beforeActivated return false, the swapping of the tab proceeds.

**To Reproduce**
1. Use soho tab, add 2 tabs.
2. Add beforeActivated event and trigger a function.
3. Set the function to return false.
4. In the UI, click another tab. The tab swap (which should veto) proceeds which is the bug.

**Expected behavior**
The tab swapping is vetoed.

**Version**
- ids-enterprise-ng: 16.8.3

**Screenshots**
![image](https://github.com/infor-design/enterprise-ng/assets/40621184/2bc495d2-e99c-42cb-a14e-90a50dac207a)

**Platform**
 - OS Version: Windows 10
 - Browser Name Chrome
 - Browser Version: Version 118.0.5993.71 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Can you attach an example so its clear how to set this up? Can use https://stackblitz.com/edit/ids-quick-start-1681

**Comment by lpagdanganan** [comment]
Hi @tmcconechy,
Please check this.
https://stackblitz.com/edit/ids-quick-start-1681-2cd5wt?file=src%2Fapp%2Fapp.component.html

Also, I already had discussion in teams with @tjamesallen15. Thanks

**Comment by lpagdanganan** [comment]
Hi @tmcconechy,
Is there any update on this one?
Thanks

**Comment by tmcconechy** [comment]
@tjamesallen15 get any chance to review this again?

**Comment by lpagdanganan** [comment]
Hi @tmcconechy / @tjamesallen15 , do we have ETA for the fix? Thank you.

**Comment by tmcconechy** [comment]
We decided to timebox this which means we are'nt confident there is a simple fix we can do. But assuming we fix will be in 4.91 which is slated for first week of Jan.

Do keep looking on your end because Im not certain its really a component issue, its more about the implementation of vetoing that you want to do vs it linking.

**Comment by lpagdanganan** [comment]
Hi @ericangeles,
Any update on this? Thanks

**Comment by ericangeles** [comment]
Hello @Ipagdanganan, we'll try to address it in this February sprint as we still have other important tasks to prioritize. Is this a blocker on your end?
