### ISSUE TITLE
Working with inforBusinessContext

### ISSUE THREAD

**Issue by kimanderssonm3cs** [infor-design/enterprise-ng#1579]
Hello!
I would like to emit/receive information to the Context Viewer in M3 through my H5 SDK. 
How can this be done? 

Comparing to Experience Designer or App Designer, they both can publish/subscribe to the Context Viewer, but I cannot understand how to do it from an SDK.

Does the Soho library handle this out of the box, or do I have to use some class that I can't manage to find?

**Comment by tmcconechy** [comment]
No the component library doesnt handle this. I think this is a question for https://github.com/infor-cloud/m3-h5-sdk maybe ask there?
