### ISSUE TITLE
Datagrid: When all columns are frozen, grid is not displayed correctly

### ISSUE THREAD

**Issue by bartlomiej-k** [infor-design/enterprise-ng#1590]
**Describe the bug**
We use Datagrid to dynamically display some properties of an object. There are two columns that are always there and are configured to be frozen (they act as identifier columns), other (optional) object properies are standard columns. The datagrid itself is configured to be displayed as a list with a spacer column. When there are no other columns than frozen columns, which can happen when other object properties are missing, the whole datagrid is rendered incorrectly - it's missing heeader row, non-frozen column section is not displayed.

**Expected behavior**
Display all frozen columns along with an empty column in non-frozen columns section as `spacerColumn` setting of the Datagrid is set to true.

**To reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1701-crmkzs.
2. Observe that for the first datagrid, header row is missing and standard columns section is displayed as a grey bar at top of the grid.
3. Observe that for the second datagrid, the header row is displayed and the standard columns section contains an empty column like `spacerColumn=true` setting would suggest.
4. Example of a workaround: click on a cell in the standard columns section of this grid. Observe that in fact there are two columns - a narrow empty column that forces the grid to render anything in this section and a spacerColumn.
5. Observe that for the third datagrid, as it contains some proper columns defined, everything is displayed as expected.

**Version**
- ids-enterprise-ng: v17.0.1 (latest)

**Screenshots**
![image](https://github.com/infor-design/enterprise-ng/assets/49535453/cd3bea0a-adb4-4072-9d4c-0201acc9655d)

**Platform**
- Infor Application/Team Name: Infor WFM

**Comment by tmcconechy** [comment]
@bartlomiej-k so the problem is when you only have frozen columns and no other columns? Is that a valid use case? What i would do in that case is not use frozen columns. But perhaps its a case where we could re configure that internally (if no other columns but stick then ignore the sticky)

**Comment by bartlomiej-k** [comment]
Yes, when we only have frozen columns and no other. And I think it's a valid use case, at least I haven't found any information in docs/readme of the component that it's not 😉

Unfreezing the columns in the background sounds fine, as long as they preserve all other settings, like custom classes, so users don't see any difference in proper frozen and reconfigured frozen columns.

Currently, as a workaround, we are using an empty column to trigger rendering of the spacer column (second datagrid in the Stackblitz example). We could implement this this frozen columns reconfiguration on our own, but it still feels like a gap in the datagrid itself. Or misconfiguration, if this scenario makes it to 'frozen columns limitations' section of the readme.

**Comment by tmcconechy** [comment]
I think its borderline valid. At least it has a workaround to unfreeze it. Basically its rendering what you gave it. But i think we can do better here.

**Comment by tmcconechy** [comment]
In this use case should

a) show the header for the frozen side we have
b) show an empty header and cell for the other side

Roughly like:

![Image](https://github.com/infor-design/enterprise-ng/assets/814283/40cd04c5-d8e4-4633-9e91-e05a5c532c26)
