### ISSUE TITLE
Dutch (Nethelands) datetime format is incorrect

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise-ng#160]
**Describe the bug**
Dutch datetime format is incorrect for 4.8.0 it is
M/d/yyyy HH:mm
while it should be
d/M/yyyy HH:mm

**To Reproduce**
1. Go to assets with Soho Locale
2. Find dateFormat object
3. See incorrect format

**Expected behavior**
datetime format is correct for Dutch language

**Additional context**
This issue was reported by our colleague from Nethelands

**Comment by pwpatton** [comment]
@tmcconechy Should this issue be transferred to enterprise?

**Comment by tmcconechy** [comment]
Ah, Yes it should be. Please create this over at https://github.com/infor-design/enterprise @Fruko

**Comment by Fruko** [comment]
done, see https://github.com/infor-design/enterprise/issues/608
