### ISSUE TITLE
ng build fails on fresh project 

### ISSUE THREAD

**Issue by kimanderssonm3cs** [infor-design/enterprise-ng#1601]
**Describe the bug**
When pulling a clean project, then running 'npm i' followed by 'ng build' you'll get an error saying that the 'ids-enterprise-wc' tsconfig cannot find the 'ids-enterprise-typings'. 
There's no instruction on how the expected build routine should be done, however the typings are already in the package.json so I except the 'ng build' to work without having to do anything else.

**To Reproduce**
1. git clone/pull https://github.com/infor-design/enterprise-ng.git
2. npm i
3. ng build

**Expected behavior**
The project should be built without any error

**Version**
- 16.10.2

**Screenshots**
<img width="629" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/105789291/e9be5c7c-2300-4e85-bfb6-9797211ea388">

**Platform**
 - Device: Windows
 - OS Version: Windows 11
 - Angular CLI: 16.2.8
 - Node: 20.10.0 (Unsupported)
 - Package Manager: npm 10.2.3
 - OS: linux x64

 - Package                      Version
 - ------------------------------------------------------
 - @angular-devkit/architect    0.1602.8 (cli-only)
 - @angular-devkit/core         16.2.8 (cli-only)
 - @angular-devkit/schematics   16.2.8 (cli-only)
 - @schematics/angular          16.2.8 (cli-only)

**Comment by tmcconechy** [comment]
I wasnt able to reproduce any problems but i think you just need `npm run build:lib` try this.

```sh
rm -rf node_modules
nvm use // node 20
npm prune && npm i
npm run build:lib
npm run build
npm run start
```

I just pushed a minor update to dependencies.
