### ISSUE TITLE
ContextMenu: Multiple selected events fired when context menu is shared between multiple elements

### ISSUE THREAD

**Issue by lbursey-infor** [infor-design/enterprise-ng#1608]
**Describe the bug**

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1671-7fpece?file=src%2Fapp%2Fapp.component.html
2. Right click button 1, then button 2
3. Click the context menu element from button 2's context menu
4. See that an event is fired for button 1 and then for button 2

**Expected behavior**
Only the button which is displaying a context menu should have an event firing.

**Version**
- "ids-enterprise-ng": "15.5.0"

**Comment by tmcconechy** [comment]
@lbursey-infor i noticed you said 15.5.0 and this seems like a familiar past issue. Did you confirm if you still have the problem on the latest version/main? Looks like you tried 16.7.1 by the stack blitz

**Comment by lbursey-infor** [comment]
@tmcconechy Yeah, it looks like it's fixed on IDS latest. Thanks!

**Comment by tmcconechy** [comment]
Ok great. Will close this then @lbursey-infor
