### ISSUE TITLE
Soho-tabs: First tab not highlighted by default after IDS-Enterprise-ng version upgrade

### ISSUE THREAD

**Issue by Uma-Neeharika** [infor-design/enterprise-ng#1615]
**Description**
We are using soho tabs in our Angular project. After version upgrade of IDS-Enterprise-ng from 15.0.5 to 16.10.2, could see that first tab is not highlighted (selected by default) on load. But before IDS-Enterprise-ng upgrade, first tab used to be highlighted by default on load. 

**To Reproduce**
1. Download the project present in below link. It contains Angular 15 and IDS-Enterprise-ng 15.0.5 version.
2. Run npm install in project path in cmd.
3. Navigate to src folder and run ng serve --o.
4. In browser login page opens. Provide Email ID: umaneeharika.sethupathi@infor.com, Password can be left blank. Click login.
5. It redirects to a page and here we can see first tab is highlighted by default as expected.
~6. Now delete all node modules, package.json, package-lock.json files.~
~7. Paste package.json, package-lock.json files provided below.  It contains Angular 16 and IDS-Enterprise-ng 16.10.2 version. Run npm install again.~
~8. Navigate to src folder and run ng serve --o.~
~9. Now we can see that first tab is not highlighted which is not the expected behavior.~
~10. PFB images before and after upgrade. ~

Project link: https://inforonline-my.sharepoint.com/:f:/r/personal/umaneeharika_sethupathi_infor_com/Documents/Documents/StatusPageWebApp?csf=1&web=1&e=sj8vvY 

[package.json](https://github.com/infor-design/enterprise-ng/files/13873628/package.json)
[package-lock.json](https://github.com/infor-design/enterprise-ng/files/13873629/package-lock.json)

**Expected behavior**
First tab should be highlighted by default. 

**Version**
- ids-enterprise-ng: 16.10.2

**Screenshots**

After version upgrade:

<img width="953" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/110805940/2c21445c-2e6f-4845-a563-8785edeceb40">

Before version upgrade:

<img width="950" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/110805940/2196b544-8252-42b4-bb08-f4a509b956b1">

**Comment by tmcconechy** [comment]
Seems to be firing `removeClass('is-selected')` on line 2483 -> not sure why this happens only in the app example case.
To simplify the steps i only needed: Steps 1-5

**Comment by tjamesallen15** [comment]
@ericangeles @tmcconechy @Uma-Neeharika i dont have access atm.

![image](https://github.com/infor-design/enterprise-ng/assets/34049950/c7a58931-6e06-4c6e-8e0f-ade0993d16c5)

**Comment by Uma-Neeharika** [comment]
@tjamesallen15 
Granted access. Could you please verify the same.

**Comment by tjamesallen15** [comment]
Hello @Uma-Neeharika,

It is already selected by default when i checked it on your app. Try removing the node modules and npm install again
![image](https://github.com/infor-design/enterprise-ng/assets/34049950/3de63799-3228-480c-9952-9d42cf5332f5)

cc @ericangeles @tmcconechy

**Comment by Uma-Neeharika** [comment]
Hello @tjamesallen15 
The App works as expected i.e., first tab is highlighted by default with the project I shared. 
After IDS-Enterprise-ng module upgrade, we face the issue I mentioned. 
To replicate it, I already shared the upgraded package files and other steps. These need to be replaced in the project I shared.
Or I have now uploaded the project where you can replicate the issue in below link. Please review and let me know in case of any clarification. 
https://inforonline-my.sharepoint.com/:f:/r/personal/umaneeharika_sethupathi_infor_com/Documents/Documents/[StatusPageWebAppAfterUpgrade](https://inforonline-my.sharepoint.com/:f:/r/personal/umaneeharika_sethupathi_infor_com/Documents/Documents/StatusPageWebAppAfterUpgrade?csf=1&web=1&e=eB6kip)?csf=1&web=1&e=eB6kip
