### ISSUE TITLE
Dropdown: Dropdown items is covered by scrollbar

### ISSUE THREAD

**Issue by kyfloresca** [infor-design/enterprise-ng#1619]
**Describe the bug**
The dropdown items are covered by the scrollbar, even when a specific width attribute is provided. Issue related to: https://github.com/infor-design/enterprise-ng/issues/1541

**To Reproduce**
1. Create a dropdown with width greater than the dropdown's length.
![image](https://github.com/infor-design/enterprise-ng/assets/116287798/6cd3639d-a3f0-449e-8a85-daf060853729)

2. Add an item with almost the same length as the dropdown.
![image](https://github.com/infor-design/enterprise-ng/assets/116287798/6ec6989a-a0fc-4f2c-a644-240908efea1f)

3. Continue adding items until the dropdown list reaches its maximum height or when the scrollbar appears.
![image](https://github.com/infor-design/enterprise-ng/assets/116287798/118b1aee-a47e-4d07-aa6e-0688858e6257)

**Expected behavior**
The dropdown item/s should not be covered by the scrollbar. The set width should trigger.

**Version**
- ids-enterprise-ng: 4.91.0
- ng-version: 17.0.8

**Platform**
 - Browser Name: Chrome
 - Browser Version: 120.0.6099.217 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
@kyfloresca not 100% sure about reproducing this one but we have a setting where it will grow to contents/max width as shown here https://main-enterprise.demo.design.infor.com/components/dropdown/test-max-width.html

Normally it will just stay the width of the input field by default. So your choice. Does that work?

**Comment by kyfloresca** [comment]
Hi @tmcconechy, to reproduce this issue better, follow these steps:
1. Create a dropdown with a set maximum width/width.
2. Include a dropdown item that is as wide as the dropdown itself.
3. Continuously add items to the dropdown until a scrollbar appears.
4. The problem arises: despite the set dimensions, the item from step 2 doesn't adjust but instead gets truncated with ellipsis.

While this may be an edge case, my primary concern is the behavior described in step 4.

**Comment by tmcconechy** [comment]
@kyfloresca would you be able to make an example with those items? Preferable in https://github.com/infor-design/enterprise repo but if not https://github.com/infor-design/enterprise-ng will do.

Or via stackblitz

**Comment by kyfloresca** [comment]
hi @tmcconechy, i've recreated the issue [here](https://stackblitz.com/edit/ids-quick-start-1730-ymkrhb?file=src%2Fapp%2Fapp.component.ts). there is a short read me in `app.component.ts` line 101. let me know if this helps!

**Comment by tmcconechy** [comment]
@kyfloresca yes this helps. Now have to figure out how to solve.

1. When i select an item i get an error. Is this part of the issue (thats fixable if it is)
2. What if we just add a small bit of padding its really all i can think of. IDEA:

<img width="317" alt="Screenshot 2024-01-30 at 10 57 33 AM" src="https://github.com/infor-design/enterprise-ng/assets/814283/7f2b6bfd-dca0-4fce-ae01-01a67710c790">

**Comment by kyfloresca** [comment]
hi @tmcconechy, 1 isn't part of the issue, it s more on this:

![image](https://github.com/infor-design/enterprise-ng/assets/116287798/afc7f38c-cbb3-40d1-a654-e9e88bd00130)

we wanted to see the whole text of the list item.

**Comment by kyfloresca** [comment]
hi @tmcconechy,
a) expanding the dropdown size may not fully address the issue, as users could still add list items with the same width as the adjusted dropdown.
b) in the provided StackBlitz, the set max width is not currently triggered.

is it feasible for the scrollbar to extend outward from the dropdown instead of inward to prevent the item/s from being overlapped by it?

**Comment by tmcconechy** [comment]
@kyfloresca so the problem is the maxWidth setting isnt apply in Angular? It is an input https://github.com/infor-design/enterprise-ng/blob/main/projects/ids-enterprise-ng/src/lib/dropdown/soho-dropdown.component.ts#L221

So are you just saying the maxWidth doesnt work?

**Comment by ericangeles** [comment]
@tmcconechy, I have checked, and I think it's a valid bug. There seems to be an issue with the type checking in the enterprise that doesn't work well with the wrapper. `maxWidth` is functioning correctly, but the width isn't, causing this issue.

**Comment by ericangeles** [comment]
Also, we may consider using the `auto` value for `maxWidth` if we want to make it dynamic. The way it works right now is that if the type of the value is not a number, the `maxWidth` will be set to `auto`.

**Comment by tmcconechy** [comment]
Ok, I dont fully follow can you try to make a fix when you can @ericangeles ? Lets put it back in the plan for later
