### ISSUE TITLE
Popupmenu: Checkmark isn't added to the selected item when binding isChecked to a variable in a single select menu

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise-ng#1620]
**Describe the bug**
The checkmark isn't added to the selected item when binding `isChecked` to a **_variable_** in a single select popupmenu. It's added to the initial selected item, but isn't when selecting a new item, i.e:

```html

<!-- This works - the first item initially has a checkmark and is then handled by IDS when selecting other items -->
...
<li soho-popupmenu-item [isChecked]="true">...</li>
<li soho-popupmenu-item [isChecked]="false">...</li>
<li soho-popupmenu-item [isChecked]="false">...</li>
...

<!-- This doesn't work - the first item initially has a checkmark but when selecting a new item, the checkmark isn't added -->
...
<li soho-popupmenu-item *ngFor="let item of items; let i = index;" [isChecked]="item.isChecked" (click)="onChange(i)">...</li>
...
```
```typescript
items = [ { text: 'First Item', isChecked: true }, { text: 'Second Item', isChecked: false } ];

onChange(index: number): void {
  this.items[index].isChecked = true;
  this.items[index ? 0 : 1].isChecked = false;
}
```

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1721-yexkxw?file=src%2Fapp%2Fapp.component.ts
2. Open the popupmenu
3. Select the unselected item
4. Open the popupmenu again
5. Notice that the checkmark isn't added

**Expected behavior**
The checkmark should correctly be added when binding `isChecked` to a variable

**Version**
- ids-enterprise-ng: `17.2.0`

**Additional context**
This seems to be caused by [this](https://github.com/infor-design/enterprise/blob/9a3d03d47dbfdf1963ce3f5c52471f7253971825/src/components/popupmenu/popupmenu.js#L2246-L2248), so not actually an issue in the angular wrapper but isn't reproducible in the core component (?)

**Comment by tmcconechy** [comment]
@yohannahbautista can you please look at this next. Want to include in the next patch. Thanks!

**Comment by tmcconechy** [comment]
I picked this up so you can focus on https://github.com/infor-design/enterprise/issues/8434 @tjamesallen15
