### ISSUE TITLE
Soho icons are white (while selected) when using Alabaster theme

### ISSUE THREAD

**Issue by James-Carlin** [infor-design/enterprise-ng#1625]
**Describe the bug**
When using soho icons with the alabaster theme, they are displayed in white when selected. This is an issue as they are usually against a white background

**To Reproduce**
1. Go to any application using soho icons
2. Change the theme to Alabaster
3. Observe the color of selected icon is white (When it should be default blue I guess?)

**Expected behavior**
I suspect that the default color for selected soho icons should be azure when using Alabaster (which will become the new default theme)

**Version**
- ids-enterprise-ng: v17.2.1

**Screenshots**
See attached file for reference and example of a selected icon being invisible when selected within a soho toolbar

**Platform**
 - Device: Dell laptop
 - OS Version: Windows 11
 - Browser Name: Chrome
![tiles_invisible_buttons](https://github.com/infor-design/enterprise-ng/assets/56592791/3e5821ad-2851-4941-ad85-81a1bf52db7c)

**Comment by tmcconechy** [comment]
@James-Carlin i cant reproduce this in any examples https://main-enterprise.demo.design.infor.com/components/toolbar/example-toolbar-input.html?colors=ffffff

Can you put together an example? One thing it could be is the `is-personalizable`

**Comment by James-Carlin** [comment]
Hey Tim, yeah upon further inspection it seems to be this is-personizable class. I have taken over this theming work from someone else apologies for lack of knowledge. I will close this as Soho issue and try fix this is-personizable one. Thanks for your time!

**Comment by tmcconechy** [comment]
No problem. Glad that works. You probably dont need it anymore as we sort of stopped all the wierd color customizations in general
