### ISSUE TITLE
Action Sheet not working as used in Demo files

### ISSUE THREAD

**Issue by misaelmv1995** [infor-design/enterprise-ng#1632]
**Describe the bug**
Tried to implement and no action sheet is showing up. 
There is also an error where [actions] is expecting a SohoActionsheetActions instead of an array of said object.

**To Reproduce**
Setup the action sheet just like it is in the Demo in a separate project

**Expected behavior**
To see the Action Sheet

**Version**
- ids-enterprise-ng: v15.5.0

**Screenshots**
[Stackblitz link](https://stackblitz.com/edit/ids-quick-start-1711-nvxpct)

**Platform**
 - OS Version: Windows 11
 - Browser Name Chrome
 - Browser Version 120.0.6099.225

**Comment by tmcconechy** [comment]
@misaelmv1995 just to clarify one thing? Didnt check but does action sheet work on https://github.com/infor-design/enterprise-ng when you run those examples?

**Comment by misaelmv1995** [comment]
> @misaelmv1995 just to clarify one thing? Didn't check but does action sheet work on https://github.com/infor-design/enterprise-ng when you run those examples?

It does work for that but I can't get it to work anywhere else, not sure what is different

**Comment by tmcconechy** [comment]
ok @misaelmv1995 will take a look when i can at the stackblitz, my guess would be imports
