### ISSUE TITLE
Lookup: Unexpected multi-select in Lookup on manually entering input

### ISSUE THREAD

**Issue by jehrnstrom** [infor-design/enterprise-ng#1635]
**Describe the bug**
If a user selects a single option (record) in a Lookup field it works as expected, i.e. when re-opening the browse dialog the previously selected option remains single selected. However, if the user types in a second option in the lookup input field, then next time opening the browse dialog both values are selected.

**To Reproduce**
1. Run the enterprise-ng project locally.
2. Find and start the Lookup example from the menu.
3. Locate the 'Products (Async Results)' field and select any value from the browse dialog. Dialog closes on select.
4. Type in another option directly into the input field, e.g. '2142201'.
5. Click the prompt button to open dialog again.
6. Both previously selected option and newly manually entered option are selected.

**Expected behavior**
Only the latest selected or entered option should be selected in the browse dialog.

**Version**
- ids-enterprise-ng: 4.91.0

**Screenshots**
![image](https://github.com/infor-design/enterprise-ng/assets/122875674/c5c28d4a-8130-4294-a70c-01ea2367aae4)
![image](https://github.com/infor-design/enterprise-ng/assets/122875674/6ed91002-7038-46de-aba3-f83ac83ed14a)
![image](https://github.com/infor-design/enterprise-ng/assets/122875674/9db7d966-c803-4080-9656-19c4f78571d3)
![image](https://github.com/infor-design/enterprise-ng/assets/122875674/ce44a2cb-d22d-46cd-a1b1-d14c6c5e4d4a)
![image](https://github.com/infor-design/enterprise-ng/assets/122875674/2004918c-083d-4931-bf56-4e783df1a149)

**Platform**
 - Device: Dell Precision 7550
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 121.0.6167.86 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Yes looks like a bug. Could try to set `multiselect = "false"` but that should be the default https://github.com/infor-design/enterprise-ng/blob/main/projects/ids-enterprise-ng/src/lib/lookup/soho-lookup.component.ts#L490

But maybe a workaround is explicitly setting either the lookup or datagrid setting.

**Comment by jehrnstrom** [comment]
Thank you for the tip. I've already tried setting the selectable = "single" on the Lookup's datagrid options, and it unfortunately does not work for this scenario (typing input). I could not find a corresponding attribute on the Lookup component itself. Did I mis one?

The issue seems tied to the async datasource. I cannot reproduce the same error in the first two Lookups: 'Products (Single Select) with mask' and 'Products (Single Select Stored as Object) with mask'.

**Comment by jehrnstrom** [comment]
If the same issue exist in web component version of the lookup component, please apply any fix to it as well.

**Comment by tmcconechy** [comment]
@jehrnstrom added this one to the sprint for Web Components i do see the issue and I raised it here https://github.com/infor-design/enterprise-wc/issues/1808 feel free to add anything in a comment i may need
