### ISSUE TITLE
soho-editor: unable to display in read only state

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise-ng#164]
**Describe the bug**
Unable to set the soho-editor to display as readonly state. The disabled option is applied in ngAfterViewChecked() and undoes the readonly option.

**To Reproduce**
1. Go to the Rich Text Editor demo
2. Click on the Read Only button
3. The state of the editor component does not change to read only

**Expected behavior**
The editor component should change to display as read only.

**Additional context**
Seems to be a regression caused by PR #94

**Comment by bthharper** [comment]
This is caused by the way the `ControlValueAccessor` works, which caused `disabled=false` to be called effectively negating the readonly request.

The solution will be the same as implemented by @tmcconechy in datepicker (https://github.com/infor-design/enterprise-ng/pull/137).

**Comment by lipetzan** [comment]
Will we be adding a test for this read-only case?  When regressions are found it's nice to see coverage expanded in the area.

**Comment by tmcconechy** [comment]
That would be a good idea. Who is going to work on this one?
