### ISSUE TITLE
FieldFilter: Unable to reset a field filter operator using selectedFilterType

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#1641]
**Describe the bug**
Landmark has a feature were a default filter operator can be defined for a field filter element.  Also want the ability to restore the filter operator to the default.  Unable to restore the filter operator back to the default when using selectedFilterType (also tried filterType).

I've also tested an example that I created in enterprise and it works correctly using setFilterType().

**To Reproduce**
1. Using the attached changes to field-filter.demo.html & field-filter.demo.ts
2. Click on F > Field Filter
3. Change operator and the value for the text field
4. Click on Reset Default button
5. Notice that the value is cleared, but the selected field operator has not

**Expected behavior**
Able to reset the field filter operator to a default operator.

**Version**
- ids-enterprise-ng: v17.5.0-dev.0 (ids v4.92.4)

**Platform**
 - Browser Name: Chrome 

**Additional context**
Landmark ticket attached to this request

**Comment by claudenbach** [comment]
[GitNG-1641.zip](https://github.com/infor-design/enterprise-ng/files/14409187/GitNG-1641.zip)

**Comment by claudenbach** [comment]
Here is the enterprise example....

[EnterpriseExample.zip](https://github.com/infor-design/enterprise-ng/files/14409250/EnterpriseExample.zip)

**Comment by JimMoe** [comment]
Adding a comment here in hopes I may receive emails about the progress of this ticket.
