### ISSUE TITLE
Datagrid: Dropdown issues (Error and position) and Cell readonly

### ISSUE THREAD

**Issue by manjaripalavancha** [infor-design/enterprise-ng#1644]
**Describe the bug**
1)  Getting an error for the dropdown when we directly navigate from one cell to another cell
2)  Soho datagrid cell disable/editable functionality should call the respective function when we update row or update cell. It’s 
          calling only when we update the entire datagrid.

**Steps to reproduce the behavior:**

    **1)	Getting an error for the dropdown**
           a)	Create sohodatagrid with lookup and dropdown and provide an option to add new row.
           b)	Add new row and enter value for the lookup cell
           c)	Don’t click outside/tab out from the cell
           d)	navigate to dropdown cell directly from the lookup cell
           e)	Observe the issue on the console that “Cannot read properties of undefined (reading 'replace')”
           f)	In the stackblitz it the error is populated and stops me to proceed further, In case of our project the error occurred in the 
                  console and the position of the dropdown is not proper.
           g)	You can refer the below screenshots and recordings along with stackblitz example.
![image](https://github.com/infor-design/enterprise-ng/assets/104565263/cb9e8a60-5b84-45cf-a853-68603f15fb4b)
![image](https://github.com/infor-design/enterprise-ng/assets/104565263/d1d72cef-6779-4309-a3db-dcdb28ec18e4)

https://github.com/infor-design/enterprise-ng/assets/104565263/bcae40d9-aeba-412a-b857-a2d88393eadf

       **2)	Soho datagrid cell disable/editable functionality should call the respective function when we update row or update cell**
           a)	Create a datagrid with one disable column
           b)	Enter any value and try to enable the cell based on the cell change
           c)	Use updateRow or updateCell functions to enable the disabled cell
           d)	Observe above two functions will not enable the disabled cell
           e)	Use updated function, then it will enable the cell
           f)	But updated function is shrinking the datagrid as we are updating entire datagrid for one cell action
           g)	Can refer the below stackblitz example and the recording for your reference.

https://github.com/infor-design/enterprise-ng/assets/104565263/51f406d1-737f-4c36-a44e-d1025404f2ea

**Expected behavior**
1)	Getting an error for the dropdown
         **Expected:** The error should not be occurred, and the dropdown position should be proper
2)	Soho datagrid cell disable/editable functionality should call the respective function when we update row or update cell
          **Expected:** Any validations or cell editable/disable functions should call with updateRow or updateCell functions as well

**Version**
- ids-enterprise-ng: 17.3.0

**Stackblitz example**
[https://stackblitz.com/edit/ids-quick-start-1730-own5vn?file=src%2Fapp%2Fdatagrid%2Fdatagrid.component.ts,package.json](url)

**Additional context**
You can refer below recording and the discussion link as well for your refrence.
**Recording:**
[datagrid-dropdown-cellchange.zip](https://github.com/infor-design/enterprise-ng/files/14457596/datagrid-dropdown-cellchange.zip)

**Communication:**
[https://teams.microsoft.com/l/message/19:83173693057f4991b7a84f030975c06d@thread.skype/1707728270044?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1707728270044&teamName=IDS%20Enterprise%20Development&channelName=Angular%20Components&createdTime=1707728270044](url)

**Comment by tmcconechy** [comment]
Quick Summary:

1) Fix the error on the dropdown ~ this should fix the position as well
2) Make sure that `updateCell` and `updateRow` runs the `isEditable` logic on a cell and refreshes it
