### ISSUE TITLE
Header: Descender Text is cut off

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#1649]
**Describe the bug**
In Header the descender Text is cut off

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1759?file=package.json
2. See Error

**Expected behavior**
The G should not be cut off.

**Screenshots**
![Screenshot 2024-03-06 at 8 39 57 AM](https://github.com/infor-design/enterprise-ng/assets/814283/6ecbb1f0-25c7-4451-95a1-1f551d66da74)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by ericangeles** [comment]
Looks like it has already been fixed.

https://stackblitz.com/edit/ids-quick-start-1771?file=src%2Fapp%2Fapp.component.ts

**Comment by ericangeles** [comment]
@infor-design/qa, please test it using the stackblitz link.

**Comment by jbrcna** [comment]
for some reason it keeps on loading on my end
<img width="1721" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/56722184/dc4fc366-a64a-42dc-a568-fae4f4dedf10">

**Comment by tmcconechy** [comment]
Yes seems fixed to me. Another way to test it @jbrcna is to just go to https://main-enterprise.demo.design.infor.com/components/header/example-index.html

And edit the DOM in chrome tools and change the text to confirm.

![Screenshot 2024-05-14 at 10 14 42 AM](https://github.com/infor-design/enterprise-ng/assets/814283/205eda40-eef0-440d-8c45-4612f4e057f3)

Sometimes those angualr stackblitz have problems loading...

**Comment by jbrcna** [comment]
thanks for clarifying @tmcconechy . working as expected.
<img width="974" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/56722184/1fe5496e-3a93-471f-b79a-f3360176b097">
