### ISSUE TITLE
Tooltip: Wrong placement when dynamic tooltip is inside a popdown

### ISSUE THREAD

**Issue by lynzleb** [infor-design/enterprise-ng#1654]
**Describe the bug**
Wrong placement when dynamic tooltip (SohoTooltipDirective.beforeShow) for an element inside a popdown.
It appears in the upper left of the page instead of near the element.

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-mn7fuc
2. Click on 'POPDOWN'
3. Hover to 'TEXT WITH DYNAMIC TOOLTIP' to see the tooltip in the upper left corner
4. Hover to 'Delete' button for comparison, in this case, the tooltip is placed properly near the element.

**Expected behavior**
Dynamic tooltip to be properly placed for elements in the popdown.

**Version**
        "ids-enterprise": "4.87.0",
        "ids-enterprise-ng": "16.7.1",

**Screenshots**
Original Application (SalesHub)
![image](https://github.com/infor-design/enterprise-ng/assets/83392536/47c27b0b-c6d0-41fe-a015-905619b69633)

IDS environment:
![image](https://github.com/infor-design/enterprise-ng/assets/83392536/9634d451-44d7-49c4-b64f-af33a853dd4d)

**Platform**

**Additional context**
This does not occur when the tooltip is set normally (SohoTooltipDirective.title) in an element inside a popdown.
This does not occur when the dynamic tooltip is set for an element outside the popdown.

**Comment by GRAMIK0** [comment]
@tmcconechy! Any news about status for this ticket?

**Comment by tmcconechy** [comment]
No news we have several hundred issues i the backlog. I'll see if we can get it in a sprint? Maybe you can find some workaround?

**Comment by tjamesallen15** [comment]
@lynzleb could you try to use the latest ng and ids? lets see if its fixed. I can't reproduced this one on my end in the latest version.

**Comment by tmcconechy** [comment]
Will mark it as fixed unless we get additional info
