### ISSUE TITLE
Datagrid: Nested datagrid disappears after render

### ISSUE THREAD

**Issue by dmcodrum** [infor-design/enterprise-ng#1656]
**Describe the bug**
Expanded/nested datagrid not working after upgrade from IDS NG 16 to 17. 

I am unable to recreate this in test or stackflow environment with a simple example but Tim is aware of the details of this issue.

**To Reproduce**
1. In our application (GLT), open a 'Material Content Report'
2. In the datagrid click one of the expanders.
3. The nested inside datagrid appears for a brief moment and then disappears. There is still an empty space where the inside grid should still be showing.

**Expected behavior**
The inside grid should remain visible

**Version**
- ids-enterprise-ng: 17.x

**Platform**
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 122.0.6261.129

**Additional context**
In discussion with Tim , we believe that this bug may be caused by these fixes:
https://github.com/infor-design/enterprise/pull/8070/files
and/or
https://github.com/infor-design/enterprise-ng/pull/1464/files
In our application the nested datagrid is an Angular component.

**Comment by AAlviar** [comment]
Hi @dmcodrum - Please provide an environment for to reproduce this issue. We will reach out separately for the credentials.

**Comment by dmcodrum** [comment]
I'll let you know when I have something setup. Thanks!

**Comment by tjamesallen15** [comment]
Where's the test page for this one? @AAlviar

**Comment by tmcconechy** [comment]
This one is complicated @tjamesallen15 you will have to look at some setup that @dmcodrum provides and try and debug it and see if you can figure out the issue.

cc @AAlviar 

Maybe the fix might be something like making sure https://github.com/infor-design/enterprise/pull/8070/files#diff-13c32b0c73b40992aa6d376fb22d6746845a3b7d6d2545e19bd30687bcabb5a5R4417 only fires once per render for expandable areas..

**Comment by dmcodrum** [comment]
@tjamesallen15 - like Tim said, this is a difficult one to create a test case for. My idea is for us to have a Teams call so I can show you the issue. Likewise, you can run/debug in a remote session on my machine. Please schedule a call to discuss to fit your availability. You can see my calendar on outlook - daniel.mcodrum@infor.com. I'm EST. Thanks!

**Comment by tjamesallen15** [comment]
> @tjamesallen15 - like Tim said, this is a difficult one to create a test case for. My idea is for us to have a Teams call so I can show you the issue. Likewise, you can run/debug in a remote session on my machine. Please schedule a call to discuss to fit your availability. You can see my calendar on outlook - [daniel.mcodrum@infor.com](mailto:daniel.mcodrum@infor.com). I'm EST. Thanks!

I messaged you on teams so that we can test about this topic.

**Comment by tjamesallen15** [comment]
Update:

@dmcodrum and I checked up the bug and I have an initial code change for this one. I will just test this on our code base to see if any will issue will arise.

cc @tmcconechy  @ericangeles

**Comment by tjamesallen15** [comment]
Made a PR for this one, cross tested with @dmcodrum via call
