### ISSUE TITLE
Datagrid: Server Paging - Cell editor is only working on First page but not Other pages.

### ISSUE THREAD

**Issue by vsatyamsetty** [infor-design/enterprise-ng#1672]
**Describe the bug**
Datagrid - Paging on server side is working but editing/modifying a cell is not updating the value on the 2nd page.
Only modifying on the cell is working on 1st page, unable to modify the cell on any other pages.

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/test-expandable-paging-server-side.html 
2. Click on page 2.
3. Open the console tab in the browser.
4. Modify any of the value in the 'Product Name' Column.
5. See the error in the console. Also, the value is being updated empty in the ProductName column.

**Expected behavior**
The value should be updated by modifying the cell(ProductName) as expected on every page. Not just in the 1st page.

**Version**
- ids-enterprise-ng: [ v4.93.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise-ng/assets/134535184/494065d8-9bf7-45ee-8a75-ff11b5a3bc15)

**Platform**

 - Browser Name [e.g. chrome, safari, stock browser]

**Additional context**
Expecting this fix ASAP.

**Comment by tmcconechy** [comment]
@ericangeles one more issue for 4.84

**Comment by vsatyamsetty** [comment]
Hi @tmcconechy ,
Is it completed?
Will this work for angular?
Which package version I need to define in the package.JSON file?
"ids-enterprise": "" - what would be the version here?

Thanks,
Phani.

**Comment by tmcconechy** [comment]
@vsatyamsetty  its fixed in 4.94.0 -> ids-enterprise-ng@17.6.1

**Comment by vsatyamsetty** [comment]
@tmcconechy ,
Thanks.

The header is not blue color. The header is white color.
Is this the expected behavior for this latest version 4.94.0?

**Comment by tmcconechy** [comment]
Yes the header is now white (alabaster). It can be set to blue with personalization but thats no longer required by design.

https://main-enterprise.demo.design.infor.com/components/header/example-index.html
VS
https://main-enterprise.demo.design.infor.com/components/header/example-index.html?colors=0066D4

So this is a correct default now @vsatyamsetty
