### ISSUE TITLE
SohoDropdown: setFocus should use activate method instead of triggering activated event

### ISSUE THREAD

**Issue by kwolentarski** [infor-design/enterprise-ng#1673]
**Is your feature request related to a problem? Please describe.**
Currently SohoDropdownComponent provides setFocus method, which under the hood triggers 'activated' event. This event triggers click on the label connected to dropdown. This is fine when we have one dropdown with a label. But in case of some tabular layout with multiple dropowns in rows and one label in header it will not work correctly. 

**Describe the solution you'd like**
Instead of triggering 'activated' event, SohoDropDownStatic should expose activate method and this method should be used instead.
Also activate method should first call document.activeElement.blur() in case we want to focus on pseudoelement and currently active element is some other input.

**Comment by tmcconechy** [comment]
Not sure I'm following this on a couple fronts

1. The focus method "doesnt work" when a lot of dropdowns? Do they have unique ids?
2. You dont want focusing to fire the activate event?
3. You just want a new method called `activate` that focus it but doesnt fire the event?
1. Do we need an example to make it more clear?

**Comment by kwolentarski** [comment]
1. Many dropdowns with unique ids but single common label.
2. This is the current flow of setFocus from angular wrapper: 
![image](https://github.com/infor-design/enterprise-ng/assets/86295640/61fb3e5f-3a94-46c0-9791-6d7740716433)
![image](https://github.com/infor-design/enterprise-ng/assets/86295640/cd0f1531-e877-46b4-b1b2-8aa62b00dbcc)
![image](https://github.com/infor-design/enterprise-ng/assets/86295640/64798e79-9df2-4686-bf6b-167956c7ce90)
Instead I would like it to trigger this:
![image](https://github.com/infor-design/enterprise-ng/assets/86295640/a56a6ae2-dab0-426b-8aa0-9cf0b2fcf0b8)
which does not depend on label being there.
3. I'm fine with either the setFocus method being reimplemented or adding new method in angular wrapper.

**Comment by tmcconechy** [comment]
OK, Im not yet not fully with you here.  I think the example will help. Or maybe you can do a pull request since you can visualize the change? Thanks

**Comment by kwolentarski** [comment]
Will try to provide a pull request
