### ISSUE TITLE
Module Nav: Switcher Roles are not correctly created

### ISSUE THREAD

**Issue by Abrai7** [infor-design/enterprise-ng#1677]
**Describe the bug**
When the [roles] property on the module nav switcher is set the roles displayed on the switcher are empty.

<img width="164" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/9669865/dc9bb80b-f821-4671-8d50-81380c06b49b">
<img width="207" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/9669865/c3470ac9-fc1a-4896-a27d-993e9f1a0224">

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1711-6hzahy?file=src%2Fapp%2Fapp.component.ts
2. Setup the roles property as described.

**Expected behavior**
The user should be able to set the roles with both [roles] property or setRoles method.

**Version**
- ids-enterprise-ng: 4.86

**Platform**
Browser Name: Chrome
Browser Version: Version 123.0.6312.106 (Official Build) (64-bit)

**Additional context**
See the exact behavior whenever the roles are inside or outside the component. The problem comes when they are set as in the screenshot. If that property is erased and only the setRoles method is used, everything works fine.

**Comment by tmcconechy** [comment]
@Abrai7 the link doesnt work / not linked? 

Also for new implementations the new web component version might be better in some cases to use https://github.com/infor-design/enterprise-wc/tree/main/src/components/ids-module-nav/demos it has an easier markup based setup.

But will review this when we can.

**Comment by Abrai7** [comment]
@tmcconechy I added the correct link, sorry about that.

https://stackblitz.com/edit/ids-quick-start-1711-6hzahy?file=src%2Fapp%2Fapp.component.ts
