### ISSUE TITLE
ActionPanel: Issue in Modal Body

### ISSUE THREAD

**Issue by charantejpola** [infor-design/enterprise-ng#1687]
**Describe the bug**
While using contextual action panel we are seeing a new class being added to the modal 'has-back-button'
which adds the css property {display:flex}. which is causing below issue in UI appearance.

**To Reproduce**
1. Create a contextual action panel modal
2. Have any data inside the modal.
3. You can see a right border line which occurs as the width is being taken according to
    width of the data in modal due to display flex css.
4. when you inspect the modal you can see a class "has-back-button" being added to modal-body.

**Expected behavior**
Either the class has to be removed or else should have a setting to remove the has-back-button class

**Version**
 ids-enterprise-ng: "17.5.9",

**Screenshots**
![image](https://github.com/infor-design/enterprise-ng/assets/144307117/7cc0b20f-5677-4a8c-81b1-4e3f1a3f0f10)
![image](https://github.com/infor-design/enterprise-ng/assets/144307117/06f034b4-e411-4b08-b37a-86dfeb857356)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Also might help to add an example for this one. But i think we could change this around to:

a) actually check if there is a back button
b) do something else that has less impact on the layout

Assume your able to work around this with css?

**Comment by charantejpola** [comment]
1.Yes the question would be why a class called "has-back-button" is being added to modal-body
is it due to a setting or something else, if so what can be done to remove that
2. I didn't check for any workaround as we are using modal in lot of components, it would be hard for us to do any.
3. Here is the example https://stackblitz.com/edit/ids-quick-start-1761-ekqu4d?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fclb-vr-add-line%2Fclb-vr-add-line.component.css,src%2Fapp%2Fclb-vr-add-line%2Fclb-vr-add-line.component.html,src%2Fapp%2Fclb-vr-add-line%2Fclb-vr-add-line.component.ts,src%2Fapp%2Fapp.module.ts,src%2Findex.html
4.open the modal using add line button 
5.Inspect the modal body element you can see the class has-back-button added to it

**Comment by tjamesallen15** [comment]
@charantejpola Hello, could you use the latest version of IDS Enterprise? I cant get the error described as above when enableTooltips is set to true

cc @tmcconechy @ericangeles

**Comment by charantejpola** [comment]
@tjamesallen15 yeah I will check and let you know

**Comment by tjamesallen15** [comment]
> @tjamesallen15 I dont find those classes added in the lates versions as you can this bug was created four months back, i guess it the css class "has-back-button" must have been removed as part of some other changes or enhancement. You can see the issue which i mentioned in the stackblitz which i provided it has that class

So can we safe to say that this if fixed already?

**Comment by charantejpola** [comment]
yes @tjamesallen15

**Comment by tmcconechy** [comment]
yes i recall an issue with that class. I think its fixed. Will assume it is, while confirming
