### ISSUE TITLE
Datagrid: Want to disable the selection checkbox by conditions

### ISSUE THREAD

**Issue by charantejpola** [infor-design/enterprise-ng#1689]
**Describe the bug**
Using selection checkbox in a DataGrid, I have a requirement where I need to disable the selection checkbox on some conditions, which I am able to by setting the isEditable as true/false. Even though I have disabled them I am still able to select them on click.

**To Reproduce**
1. Create a datagrid with column formatter as selection checkbox
2. The column has isEditable being set as true/ false by a function
3. You can see the selection checkboxes disabled
4. But still able to select them

**Expected behavior**
We expect the selection checkboxes not be selected as well as the contextual toolbar shall not be triggered as well.

**Version**
- ids-enterprise-ng: "17.5.9",

**Screenshots**
Will be attaching a video for reference

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
Here is the example stackblitz.
https://stackblitz.com/edit/ids-quick-start-1761-ctlunk?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

https://github.com/infor-design/enterprise-ng/assets/144307117/291ff234-f67e-42df-bbe7-8592835df747

**Comment by charantejpola** [comment]
Need to add one more point that select all check box should only check those checkboxes which are not disabled.
As of current implementation it selects rows which are disabled as well

**Comment by sami1riaz** [comment]
Hi, is there an estimate of when this bug will be fixed and if it can be backported to version 15.6.1? We cannot release the feature we are working on without this fix unfortunately. Our deadline is August 6, 2024

**Comment by tmcconechy** [comment]
I can add this to this sprint and it would be done around Aug.6th release we usually release between 5-9th of every month. However for patches could do those right away.

We can try to backport it when it is complete, I'm not sure if 15.6.1 is possible to build anymore but can give it a try

**Comment by tmcconechy** [comment]
@charantejpola @sami1riaz 

I fixed on the attached PR https://github.com/infor-design/enterprise/pull/8882 please review if you can. Our QA will test it and when merged i can attempt to patch 15.6.1

**Comment by sami1riaz** [comment]
@tmcconechy, thanks for the quick fix. I noticed that the fix was in enterprise repo. Will it also be applied to enterprise-ng?

**Comment by tmcconechy** [comment]
yes the fix is only in the enterprise part. can you apply a patch if we just patch to the enterprise version? Or do you need some version patched?

**Comment by LilBiggs** [comment]
Hey Tim, WFM references the Angular version. So whatever jQuery IDS version is referenced by the ids-enterprise-ng package is what will be pulled in. Is it possible to bump the NG version and update the ids-enterprise that is referenced within the ng version?

**Comment by tmcconechy** [comment]
Yes, will do which version do you need patched exactly?

**Comment by sami1riaz** [comment]
Yes, we are currently using "ids-enterprise-ng": "15.6.1"

**Comment by tmcconechy** [comment]
ok @sami1riaz do i need to look at that button disabled thing? (im not sure what that looks like) or is this good as is to patch?

**Comment by sami1riaz** [comment]
What I was referring to is the disabled?: SohoDataGridColumnDisabledFunctio attribute. I still don't fully understand why that attribute doesn't work with Soho.Formatters.SelectionCheckbox but works with other formatters like Soho.Formatters.Button.

If this solution works, I am fine with getting it patched. But to me for disabling a checkbox we should be using the disabled attribute.

**Comment by charantejpola** [comment]
@tmcconechy Do we get the fix for version ids-enterprise-ng:17.7.1, as we are currently on that version and we are expecting it before our release CE-2024.10

**Comment by tmcconechy** [comment]
@sami1riaz @charantejpola 

So we want to patch this on 17.7.x AND 15.6.x? I getting a bit confused here?

**Comment by sami1riaz** [comment]
WFM needs it for 15.6.1. @charantejpola and I are not in the same team

**Comment by tmcconechy** [comment]
[ids-enterprise.zip](https://github.com/user-attachments/files/16180384/ids-enterprise.zip)

@sami1riaz i don't seem to be able to patch 15.61 as it's too old it uses node 14 and can't build. I could try to update it to latest sass but this might be complicated / include more changes?

Can you work with this? Just take this file and replace whats in node_modules/ids-enterprise

Wanting to check if you can deal with it this way?

**Comment by tmcconechy** [comment]
@sami1riaz @charantejpola working on two patches tomorrow AM i figured out my issues and will patch these on those versions

15.6.x
17.7.x

**Comment by tmcconechy** [comment]
@charantejpola for you: https://www.npmjs.com/package/ids-enterprise-ng/v/17.7.8
@sami1riaz  for you: https://www.npmjs.com/package/ids-enterprise-ng/v/15.6.2

**Comment by tmcconechy** [comment]
@sami1riaz can you add a new issue. This wasn't on the original example you provided. So please make a new issue but i will expedite it

**Comment by sami1riaz** [comment]
Raised https://github.com/infor-design/enterprise-ng/issues/1753
