### ISSUE TITLE
Slider: Not updating on button click

### ISSUE THREAD

**Issue by sanketughade** [infor-design/enterprise-ng#1696]
**Describe the bug**
I'm using soho-slider. Surrounding the sliders I have zoom-in and zoom-out buttons. On these buttons click I change the value of the variable bind to the slider using [(ngModel)] but on changing the variable's value the slider doesn't seem to update.

**To Reproduce**
1. Locate and click on the Zoom In or Zoom Out buttons that surround the slider component.
2. These buttons are typically used to adjust the zoom level or scale of the content displayed alongside the slider.
3. Despite interacting with the Zoom In/Zoom Out buttons, carefully observe the behavior of the slider component.
4. Note that even though the value of the variable bound to the slider's [(ngModel)] changes as a result of clicking these buttons, the slider itself remains static.

**Expected behavior**
1. In a properly functioning setup, adjusting the value of the [(ngModel)]-bound variable should dynamically update the position or appearance of the slider.
2. Thus, the expected outcome is that each click on the Zoom In/Zoom Out buttons should correspondingly adjust the slider's position or appearance to reflect the updated value.

I have created a stackblitz application to demonstrate the above mentioned issue. Please find the link below:

https://stackblitz.com/edit/ids-quick-start-1730-7wu5za?file=src%2Fapp%2Fslider%2Fslider.component.ts,src%2Fapp%2Fslider%2Fslider.component.html,src%2Fapp%2Fslider%2Fslider.component.css

**Version**
- ids-enterprise-ng: 17.3.0.

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Fixed on https://github.com/infor-design/enterprise-ng/pull/1796#event-14219168026
