### ISSUE TITLE
Tabs: Unable to stop closing of tab, returning false in onBeforeClose event doesn't work

### ISSUE THREAD

**Issue by hemantg05** [infor-design/enterprise-ng#1697]
**Describe the bug**
I have use case of showing a "Unsaved Changes" dialog when user clicks on X button (close button) on the module tab. There is no way to handle this case. One suggested way in documentation was to return false in beforeClose callback. But it is not working even in the example provided by IDS team.

Following example is not working. "Prevented Dismissible" tab is still being closed/dismissed.
Test Example:
https://main-enterprise.demo.design.infor.com/components/tabs/test-prevent-dismissible.html
Code:
https://github.com/infor-design/enterprise/blob/main/app/views/components/tabs/test-prevent-dismissible.html#L52

**Expected behavior**
We should have a way to stop the dismissal of tab.

**Version**
- ids-enterprise-ng: 17.5.9 
- ids-enterprise - It is reproduceable on https://main-enterprise.demo.design.infor.com/components/tabs/test-prevent-dismissible.html

**Screenshots**

**Platform**
 - Device: Windows
 - OS Version: Windows 11
 - Browser Name: chrome

**Additional context**
We are using ids-enterprise-ng. We have use case of showing a "Unsaved Changes" dialog when user clicks on X button on Edit tab. So, we would like to stop the closing of tab.

**Comment by tmcconechy** [comment]
Summary:

1) FIx the callback example
2) Add ability to disable the x button
3) Check the dismissible attribute is working (this one hides the x)
