### ISSUE TITLE
[Enterprise-Ng] Swaplist can pass component/template

### ISSUE THREAD

**Issue by JestoniFajardo** [infor-design/enterprise-ng#170]
**Current behavior**
Swaplist component can render/display only _plain text._ Which can't customize the display for available and selected list.

**Acceptance Criteria**
Swaplist component will have options or feature to display custom template for selected and available list and retain it behavior to swap.

**Feature Consideration**
A feature that we can pass template and will displayed on the assign list.

**Additional context**
Sample screen shots.
![customlayoutonswaplist](https://user-images.githubusercontent.com/42030487/44581297-bc0f7a80-a7cf-11e8-8990-55aa65bb8598.jpg)

**Comment by tmcconechy** [comment]
Just adding that on the enterprise component this is possible https://github.com/infor-design/enterprise/blob/master/app/views/components/swaplist/example-index.html#L7

**Comment by JestoniFajardo** [comment]
Hi @tmcconechy , Is this possible on ids-enterprise-ng as well? cause when I saw the code it was implemented as normal ids-enterprise or jquery if I'm not mistaken.

**Comment by tmcconechy** [comment]
It should work if you do it the same way by providing a template like https://github.com/infor-design/enterprise/blob/master/app/views/components/swaplist/example-index.html#L7 in the DOM and passing that ID in the template option

**Comment by tmcconechy** [comment]
Descoping this issue for now.
