### ISSUE TITLE
SohoDataGridColumn: Property InlineEditor does not exist in type

### ISSUE THREAD

**Issue by IdaAspen** [infor-design/enterprise-ng#1701]
**Describe the bug**
When adding property `InlineEditor` to a SohoDataGridColumn, it says that the property doesn't exist.
(We can get around this by casting columns to any)

**To Reproduce**
1. Create  SohoDataGridColumns
2. Add property `InlineEditor`

**Expected behavior**
Have the property to work for SohoDataGridColumn

**Version**
"ids-enterprise-ng": "17.6.2",

**Screenshots**
![image](https://github.com/infor-design/enterprise-ng/assets/80949028/1d64d690-1a71-46a8-992e-16a14cea2bd7)

**Comment by tmcconechy** [comment]
We can add this missing type (or feel free to add a pull request?)

If inline editor works for you great. But also wanted to mentioned we did a lot of work on inline editors in the new version https://github.com/infor-design/enterprise-wc so if you need a lot of fixes on it you might look at considering the new version.
