### ISSUE TITLE
Datagrid: Vertical scroll event not triggering above 300px height

### ISSUE THREAD

**Issue by Rinlama** [infor-design/enterprise-ng#1703]
**Describe the bug**
The vertical scroll event on grid component is not triggering above 300px height in widget SDK, it works below 300px.

**To Reproduce**
1) Add the style="height: 301px;" on soho-datagrid
2) Add the (verticalScroll)="onVerticalScroll($event)" on soho-datagrid
3) onVerticalScroll is not trigger 

**Expected behavior**
OnVerticalScroll should trigger 

**Version**
- ids-enterprise-ng: v16.8.4

**Screenshots**
<img width="417" alt="Screenshot 2024-05-22 at 10 52 05 AM" src="https://github.com/infor-design/enterprise-ng/assets/8290866/85854a1d-cf8b-4627-88c2-38cc3efd3b3c">
<img width="504" alt="Screenshot 2024-05-22 at 11 36 08 AM" src="https://github.com/infor-design/enterprise-ng/assets/8290866/8a5a14fa-7af8-45b6-a68b-ae9254a4a47c">

**Platform**
 - Browser Name [chrome]

**Comment by tjamesallen15** [comment]
Hi @Rinlama,

cc @ericangeles @tmcconechy 

Perhaps the instruction above is incomplete or it is not reproduceable on the current version.

Here is my example with your codes above
![image](https://github.com/user-attachments/assets/dd83ab8e-10ef-4f92-86d6-6ed76e3e1a36)

![image](https://github.com/user-attachments/assets/8de18ba8-ff42-42cf-bd59-357e04c58882)

![image](https://github.com/user-attachments/assets/c9e23852-92c0-46cd-a8aa-afbb6cb1ab7b)

**Comment by tmcconechy** [comment]
@tjamesallen15 i assume this was fixed by https://github.com/infor-design/enterprise/pull/8988
So i guess we can close this if it is not reproducible anymore?
