### ISSUE TITLE
DataGrid: Missing public function keywordSearch

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-ng#1709]
**Describe the bug**
According to 
https://design.infor.com/components/components/data-grid/enterprise/

There should be a function called `keywordSearch`, however it is not public.

**Version**
- ids-enterprise-ng: latest

**Comment by tmcconechy** [comment]
@guoliang feel free to add a PR if you would like, or else we will get to this soon

**Comment by guoliang** [comment]
@tmcconechy 
https://github.com/infor-design/enterprise-ng/pull/1711
