### ISSUE TITLE
Image: Require image magnifying, Zoom-in & Zoom-out component

### ISSUE THREAD

**Issue by karakasatya** [infor-design/enterprise-ng#1714]
Hi Team,
 
We have a requirement in LN Portal, where we need to show a list of thumbnail images left side and there is a large image on right side. the large image should update when we hover on that left side thumbnail image and when we hover on that large image it should magnify along with zoom-in & zoom-out (like below gif). We have checked this type of component in IDS components but we didn't find. could you please take up this requirement.

![magnifying-image -small](https://github.com/infor-design/enterprise-ng/assets/145528086/6acaf6a9-e051-4b2f-8d42-67f6127d9dbe)

Please go through this link for your reference. (https://wittlock.github.io/ngx-image-zoom/)

**Comment by karakasatya** [comment]
Hi Tim,

We have this feature in the next release, so could you please make it available as early as possible, so that we can use and tested it before release.

Thank you,
Satya Karaka.

**Comment by tmcconechy** [comment]
@karakasatya we dont have plans to make this right now. Will discuss internally
