### ISSUE TITLE
Datagrid: Missing SohoDataGridSettingsChangedEvent and columnchangeEvent

### ISSUE THREAD

**Issue by sathishchittimi** [infor-design/enterprise-ng#1734]
Issue1: SohoDataGridSettingsChangedEvent is not getting fired on Reordering the column with ColumnReorder = true.

Issue2: columnChangeEvent is not yet implemented, Requesting you to implement the same while dragging the columns.

**Comment by sathishchittimi** [comment]
hi @tmcconechy ,

Requesting you to please assign this ticket to team.

**Comment by tmcconechy** [comment]
@sathishchittimi yes we will add this in an upcoming sprint planning
