### ISSUE TITLE
Datepicker: Set to readonly not working in a form group

### ISSUE THREAD

**Issue by abacarellaInfor** [infor-design/enterprise-ng#1735]
**Describe the bug**
soho-datepicker fields are always editable by default when first loading a page. In the html, using 

```
[attr.readonly]="true",
[readonly]="true", 
[attr.readonly]="readOnly ? 'readonly' : null", 
[readonly]="readOnly ? 'readonly' : null",
[readonly]="readOnly",
[attr.readonly]="readOnly"
```

All result in the datepicker being editable by default. In our .ts, I am initializing the readOnly variable as true and also setting this.readOnly to true in ngAfterViewInit(). 

One thing that is standing out to me is that the datepicker id "lastImportDate" is part of the formbuilder group and when I comment out the line lastImportDate: [''], the datepicker is readonly by default. I have tried changing it to lastImportDate: null, but the datepicker was still editable.

We have an 'edit' button which toggles readOnly between true and false and when using the button the datepicker behavior is normal - it will toggle between editable and readonly.

**Expected behavior**
Setting the datepicker field to readonly should cause the form to be readonly when the page loads.

**Version**
- ids-enterprise-ng: 18.0.2

**Screenshots**
![image](https://github.com/infor-design/enterprise-ng/assets/115818755/861c4be0-2045-4d57-a837-48ecbba1864e)
![image](https://github.com/infor-design/enterprise-ng/assets/115818755/b7ec08b9-f0d7-4b1b-b1c0-b41dbf74b5c5)

**Additional context**
I have tested using Main branch of ng components in my project, but the issue persists.

**Comment by tmcconechy** [comment]
@abacarellaInfor would you be able to create a simple NG form field example showing this in stackblitz? https://stackblitz.com/edit/ids-quick-start-1801?

Im thinking if i passed this on to a developer as is they wouldnt know what to do since the example works.

**Comment by abacarellaInfor** [comment]
Sure I will work on that now.

**Comment by abacarellaInfor** [comment]
@tmcconechy I am having some trouble with creating the example. I tried to extract the minimum code to replicate the issue and put it in a fork of the stackblitz you linked, but I'm having some trouble with routing to the html page I created. Maybe it is something simple I am missing but if you have an idea of how I can get the preview to show my page I think it should reproduce the issue. This is what I've got so far 
https://stackblitz.com/edit/ids-quick-start-1801-xdclmm?file=src%2Fapp%2Fapp.component.ts

**Comment by abacarellaInfor** [comment]
I believe the only thing needed to reproduce this issue is:
a datepicker which sets the readonly attribute with a variable in the html 
a form which uses UntypedFormBuilder.group and has the id of the datepicker in the ts

html example:
<input soho-datepicker class="datepicker input-md" formControlName="lastImportDate" showTime="true" id="lastImportDate" name="lastImportDate" [attr.readonly]="readOnly ? 'readonly' : null" />

.ts example:
private fb: UntypedFormBuilder;
private form: UntypedFormGroup;
private readOnly = true;

		this.form = fb.group({
			lastImportDate: ['']
			});

**Comment by tmcconechy** [comment]
@abacarellaInfor i think we can work with this then and come up with an example
