### ISSUE TITLE
Need Remove button for Lookup control

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise-ng#174]
**Is your feature request related to a problem? Please describe.**
In Lookup control when we add some data or object from lookup popup to the lookup field, currently there is no provision to remove specific object or data.
Please refer below image for more details.

![lookupwithdata](https://user-images.githubusercontent.com/42198413/44852424-bc39cb00-ac52-11e8-8b5a-95a1e85b9689.jpg)

It would be great if we provide "X" (remove) button for every object.
Please refer below image for more details. 

![removebutton](https://user-images.githubusercontent.com/42198413/44852531-fefba300-ac52-11e8-9481-da564c450b56.jpg)

**Comment by tmcconechy** [comment]
This should go in https://github.com/infor-design/enterprise/issues as we will have to add it there.
Are you using angular as well? And do you mean every single component or just the lookup? (That would expand scope a lot and potential for addition)

**Comment by dhumalkishor** [comment]
I Have create same JT in https://github.com/infor-design/enterprise/issues. Yes we are using angular 4.8.0 version. We want this remove button only for Lookup control.
