### ISSUE TITLE
DataGrid: Groupings returns a different data when selecting a checkbox and cannot reselect it

### ISSUE THREAD

**Issue by jpontawe** [infor-design/enterprise-ng#1740]
**Describe the bug**
A multi select DataGrid with groupings unfortunately returns a different data than the one selected, it is also not possible to reselect a check box
 
**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-grouping-multiselect.html
2. Open developer's tools and navigate to console
3. Click the checkbox on customer id 7
4. Inspect the Row Click -> item in the console and compare the data with the one was that was clicked
5. Unselect customer id 7
6. Reselect customer id 7 (cannot reselect)

**Expected behavior**
Customer id 7's data should be printed on the browser console, and it is possible for us to reselect that record.

**Version**
- ids-enterprise-ng: [18.0.2]

**Screenshots**
![datagrid_checkbox_issue_demo_env](https://github.com/infor-design/enterprise-ng/assets/174662314/4315d251-05af-4251-934b-ff915ca7a910)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [Windows 11 Enterprise 64-bit]
 - Browser Name [Microsoft Edge]
 - Browser Version [Version 126.0.2592.81 (Official Build) (64-bit)]

**Additional context**
This exact bug was reproduced in our Infor app and was communicated within Microsoft Teams channel

**Comment by tmcconechy** [comment]
@jpontawe may just want to test this on 4.97.0 when released its possibly fixed

**Comment by jpontawe** [comment]
@tmcconechy what did you mean by 4.97.0? Apologies I am not familiar with this yet.

**Comment by tmcconechy** [comment]
@jpontawe i realized that testing https://main-enterprise.demo.design.infor.com/components/datagrid/example-grouping-multiselect.html is what i need to confirm if this is fixed or not.

It is not. We will take a look when we can

**Comment by jpontawe** [comment]
@tmcconechy thank you for clarifying.

Understood, we have temporarily disabled groupings on our data grids and will wait for this to be fixed.
