### ISSUE TITLE
ToolbarFlex : The "more-button" adds "tick" icons to menu items that are not selectable

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#1743]
**Describe the bug**

After upgrading to ids-enterprise-ng 18.1.3 the header bar that contains the "theme" switcher now adds ticks to items that are not selectable.

See https://stackblitz.com/edit/ids-quick-start-1813-wb3yt6?file=src%2Fapp%2Fapp.component.ts

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1813-wb3yt6?file=src%2Fapp%2Fapp.component.ts
2. Click on '....' on the Header (where the **Theme Selector** is)
3. Select Help
4. The Help button will now have an erroneous tick on it

**Expected behavior**

No tick is added to menu items that are not "is-selectable".

**Version**
- ids-enterprise-ng: 18.1.3

**Screenshots**

https://stackblitz.com/edit/ids-quick-start-1813-wb3yt6?file=src%2Fapp%2Fapp.component.ts

**Platform**
 - Device (if applicable) Windows / macos
 - OS Version: Win11 / maxos 14.3.1
 - Browser Name: Edge and Chrome
 - Browser Version: Latest

**Additional context**

**Comment by tmcconechy** [comment]
@tjamesallen15 can we fit this  in please?

**Comment by tmcconechy** [comment]
Think this is fixed by my suggestion. Which is done on the App side
