### ISSUE TITLE
Double click is not consistent on some devices

### ISSUE THREAD

**Issue by patrickluisdeguzman** [infor-design/enterprise-ng#1750]
**Double click is not consistent on some devices**
 
**To Reproduce**
1. Open enterprise-wc
2. Go to Lists
3. Select Datagrid
4. Select double-click.html
or Go to https://main.wc.design.infor.com/ids-data-grid/double-click.html
 
**Expected behavior**
Double click should be triggered on any device
 
**Version**
"1.0.0-beta.18"
"1.3.0"
 
**Video**
 
https://github.com/user-attachments/assets/c80c58ea-f08e-43cc-b732-5ba8a4b2aa0b
 
https://github.com/user-attachments/assets/6bf6ec7d-3a60-401c-93de-64cc1b4bdce3
 
**Platform**
- Dell Laptop
- Windows 11
- Microsoft Edge
- Version 126.0.2592.102 (Official build) (64-bit)
--------------------------
- Dell Laptop
- Windows 11
- Chrome
- Version 126.0.6478.183 (Official Build) (64-bit)

**Comment by patrickluisdeguzman** [comment]
Closing the ticket. Incorrect repo.

**Comment by tmcconechy** [comment]
@patrickluisdeguzman FYI i can move them for next time.
