### ISSUE TITLE
SohoDatePickerRange option is missing "selectWeek"

### ISSUE THREAD

**Issue by c-dani** [infor-design/enterprise-ng#1755]
**Describe the bug**
It looks like there should be an option in range, "selectWeek" to select a whole week. See this demo: https://latest-enterprise.demo.design.infor.com/components/datepicker/test-week-picker.html

SohoDatePickerRange is missing the option. But the jQuery version has it: https://github.com/infor-design/enterprise/blob/e6aa409568f06d37eb6b20f687760b35509c0d38/src/components/datepicker/datepicker.js#L227

**To Reproduce**

**Expected behavior**
SohoDatePickerRange should have selectWeek, so it's available to use.

**Version**
- ids-enterprise-ng: v18.1.5

**Screenshots**

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
Thanks we will try to add this when we can. Do note we accept pull requests if you want to try

**Comment by tmcconechy** [comment]
Added
