### ISSUE TITLE
Datagrid: Datepicker icon on hover and text on error are not that visible with the color change

### ISSUE THREAD

**Issue by nsurtida** [infor-design/enterprise-ng#1765]
**Describe the bug**
On IDS v15.6.1, datepicker used in datagrid column filter has color changes on specific events (e.g. on hover, on error), but the color changes aren't that visible.
When hovering on the datepicker icon, the text turns white on light mode so it makes it hard to see. Other elements for datepicker turn a darker color on hover. The same issue occurs on other modes.

When an invalid date value is placed on the filter text box, it also turns white on light mode and also makes it hard to see. When not in focus, the text is almost invisible.

**To Reproduce**
Pre-requisite: Use IDS v15.6.1

1. Go to datagrid component with date filter
2. Using light mode, hover on datepicker icon, icon turns white.
3. Using light mode, enter invalid value on the date filter text box. Exit element, text is almost invisible. Refocus on text box, text is more visible but still not that clear.

**Expected behavior**
Datepicker icon and text to have more visible colors. E.g. for other elements on hover, they turn darker/black like below
![image](https://github.com/user-attachments/assets/3c024e77-b5f3-4e27-b709-8ddb9bd28f62)

**Version**
- ids-enterprise-ng: v15.6.1

**Screenshots**
![image](https://github.com/user-attachments/assets/3d998ac9-e3a3-40ca-9d63-75d0e77ea7d5)
![image](https://github.com/user-attachments/assets/33de51f8-a82f-40a5-8b0d-5475c43c0df1)

![image](https://github.com/user-attachments/assets/2f6d4ce4-29a8-4349-980f-1f0b2a751b4c)
![image](https://github.com/user-attachments/assets/6199f9a4-a662-4664-b0b7-e34c1a0f3b0b)

**Platform**
 - Device (if applicable): Desktop
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 127.0.6533.89 

**Additional context**
Using WFM application

**Comment by tmcconechy** [comment]
@nsurtida we arent fixing 15.x anymore its too old. But one thing i dont understand is why the different colored headers. In that version the grid header should be black not grey?

See https://4861-enterprise.demo.design.infor.com/components/datagrid/example-books.html (4861) is the version 15.6.x is on...

**Comment by tmcconechy** [comment]
If on the old version then just keep the header black as it was. You will have to update to get the new styles
