### ISSUE TITLE
SohoDatagrid: setting enableTooltips = true, cause exception to be thrown

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-ng#1770]
**Describe the bug**
Following error is thrown when `enableTooltips` is set to `true`

![image](https://github.com/user-attachments/assets/d6969cdc-47fd-4155-ab38-f78216a94897)

Looking in soho source, the error happens here

![image](https://github.com/user-attachments/assets/e659caba-2105-4f8a-bc5e-e7c93a9493ed)

**To Reproduce**
1. One case when it happens is when add/remove rows.

**Expected behavior**
No error should be thrown

**Version**
- ids-enterprise-ng: 18.2.2

**Comment by tjamesallen15** [comment]
Hello @guoliang could you use the latest version? I cant get the error described as above when enableTooltips is set to true

cc @tmcconechy @ericangeles

**Comment by guoliang** [comment]
@tjamesallen15  still getting the same issue with latest version of `enterprise-ng`

I have looked into it a bit more on what's triggering it. 

For the case of adding and removing `rows` from one data grid to another. After removing and adding, it for some reason triggers the tooltip on the added row. Look in the video


https://github.com/user-attachments/assets/70189d67-bcd5-4a31-9932-0facd00105b0

**Comment by tmcconechy** [comment]
Fixed as per https://inforwiki.atlassian.net/browse/IDS-4155
