### ISSUE TITLE
Datagrid: Console errors related to tooltip

### ISSUE THREAD

**Issue by charantejpola** [infor-design/enterprise-ng#1791]
**Describe the bug**
While using datagrid we can see the following tooltip error in the console.
Cannot read properties of null (reading 'querySelector')
    at Datagrid.cacheTooltip (node_modules\ids-enterprise\dist\js\sohoxi.js:105337:1)

**To Reproduce**
1. Create a datagrid
2. Try filtering the data
3. In the console we can see follwoing error

**Expected behavior**

**Version**
- ids-enterprise-ng:18.2.1

**Screenshots**
<img width="949" alt="image" src="https://github.com/user-attachments/assets/a078feb2-f9bf-4bf3-a12e-7bed6c0a630a">
<img width="730" alt="image" src="https://github.com/user-attachments/assets/ec784c17-edab-4387-b5f2-614d1b48ae7a">

**Platform**

**Additional context**
In the above code it is checking for tooltip.wrapper where wrapper is null sometimes which is creating the error.
Need to add a guard here so that only if it contains the tooltip.wrapper then it should check for tooltip.wrapper.querySelector('.datagrid-expand-btn')
Please check the lines highlighted in the screenshot. add the necessary conditions

**Comment by tmcconechy** [comment]
@charantejpola can you test the fix on branch: https://github.com/infor-design/enterprise/pull/9009 ?
