### ISSUE TITLE
Button becomes re-enabled in modal validation.

### ISSUE THREAD

**Issue by crlang44** [infor-design/enterprise-ng#183]
**Describe the bug**
When a validation fails in a modal that has a button with the validate property set to true, the validation message shows successfully and the button is disabled properly. But when you click on another field in the modal, the button becomes re-enabled.

**To Reproduce**
1. Create a modal with 2 fields in it.
2. Add a validation rule to one or both of the field.
3. Add `validate: true` property to one of the buttons.
4. Make one of the fields have valid input.
4. Make the other field have invalid input. The validation message shows and the button becomes disabled.
5. Click on the other valid field. The button becomes enabled.

**Expected behavior**
For Step 6 above, the button should still be disabled since one of the fields in the modal is invalid.

**Screenshots**
![image](https://user-images.githubusercontent.com/4143306/45449817-11ca9a80-b68b-11e8-9366-5099192d68d7.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
This seems like an old problem. That maybe fixed. Which version are you on?
May have been https://github.com/infor-design/enterprise/pull/148

**Comment by crlang44** [comment]
Yes, we were on 4.7. However, I just migrated to 4.10.1 and it seems to have a different but worse issue. The custom validation seems to stay once it is evaluated as invalid. That is, it is able to identify once something becomes invalid and disables the button accordingly, but even if you change it back to something valid, the message remains and the button is still disabled.

**Comment by tmcconechy** [comment]
That problem might be because we introduced a change that you should add a type and id to the custom rules. Try adding type and id fx..

https://github.com/infor-design/enterprise/blob/master/src/components/validation/validation.js#L116

**Comment by crlang44** [comment]
You are spot on, it works now with an id specified. Thank you!
