### ISSUE TITLE
Certain Text in the ModalService, Message property causes failure.

### ISSUE THREAD

**Issue by petercullen68** [infor-design/enterprise-ng#184]
**Describe the bug**
When we use certain text in the Message Property of the ModalService, the control crashes.  If we set the Message property to "Login Failed..."  or "Would you like to clear the operators session?".  The message in the console is.

Error: Syntax error, unrecognized expression: Would you like to clear the operators session?
core.js:1673
message:"Syntax error, unrecognized expression: Would you like to clear the operators session?"
stack:"Error: Syntax error, unrecognized expression: Would you like to clear the operators session?\n    at Function.Sizzle.error (http://localhost:4200/scripts.js:1541:8)\n    at Sizzle.tokenize (http://localhost:4200/scripts.js:2193:11)\n    at Sizzle.select (http://localhost:4200/scripts.js:2620:20)\n    at Function.Sizzle [as find] (http://localhost:4200/scripts.js:845:9)\n    at jQuery.fn.init.find (http://localhost:4200/scripts.js:2873:11)\n    at new jQuery.fn.init (http://localhost:4200/scripts.js:2983:32)\n    at jQuery (http://localhost:4200/scripts.js:139:10)\n    at Modal.appendContent (http://localhost:4200/scripts.js:71437:11)\n    at Modal.init (http://localhost:4200/scripts.js:71400:14)\n    at new Modal (http://localhost:4200/scripts.js:71351:10)"
__proto__:Object {constructor: , name: "Error", message: "", …}

**Platform**
 - Chrome on Windows 10
 - Version 69.0.3497.92 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
How do i reproduce this? I tried changing this line in the sample app.
https://github.com/infor-design/enterprise-ng/blob/master/src/app/message/message.demo.ts#L35
To just `Would you like to clear the operators session?`

But could not provoke this, also what version are you on?

**Comment by petercullen68** [comment]
Hey Tim.  This may be because we are setting the text with out using any decoration i.e. <span> etc.

.message('Login Failed...')

"ids-enterprise-ng@4.10.1",

**Comment by tmcconechy** [comment]
What if you do it exactly like this example:
https://github.com/infor-design/enterprise-ng/blob/master/src/app/message/message.demo.ts#L35

**Comment by petercullen68** [comment]
Yep that works for me.  This one can be closed.  Thanks!  I've isolated the modal to one area in the application so I can enforce this standard there.
