### ISSUE TITLE
Memory leak in SohoContextMenuDirective

### ISSUE THREAD

**Issue by prkarlsson** [infor-design/enterprise-ng#185]
**Describe the bug**
The ngOnDestroy function in the SohoContextMenuDirective does not call the destroy function on the jQuery context menu. This causes leaks of detached DOM elements when creating and destroying Angular components that uses context menus. Note that there is a comment in the ngOnDestroy function that can also be found in SohoMenuButtonComponent so that component may be affected as well.

The leaked DOM elements can be found by using the Chrome Memory profiler. They show up as "Detached HTMLDivElement" etc.

**To Reproduce**
1. Create an Angular component that uses SohoContextMenuDirective 
2. Create and destroy the component multiple times in a single-page app
3. Take a heap snapshot in the Chrome Memory profiler
4. There are several detached DOM elements kept alive since the jQuery context menu is not destroyed.

**Expected behavior**
The ngOnDestroy function in SohoContextMenuDirective should call the destroy function for the jQuery context menu. There should be no detached DOM elements after destroy is called.

**Screenshots**
-

**Platform**
 - Device: N/A
 - OS Version: Windows
 - Browser Name: Chrome
 - Browser Version:  69.0.3497.92 (Official Build) (64-bit)

**Additional context**
The issue was found when using the enterprise-ng components in Infor Homepages.

**Comment by pwpatton** [comment]
https://github.com/infor-design/enterprise-ng/blob/81fb2ba03161ad40cb46fbba258ce91381b21ca6/projects/ids-enterprise-ng/src/lib/button/soho-button.component.ts#L288-L298

Button also seems to be messaging the enterprise component appropriately.

**Comment by pwpatton** [comment]
All the context menus seem to get destroyed when navigating away. 
is there a enterprise-ng sample that can be used to duplicate this?

**Comment by prkarlsson** [comment]
We are on enterprise-ng version 4.7.x. If it is already fixed in later releases we'll just patch it temporarily in our local files until we upgrade to a version that includes the fix.

**Comment by tmcconechy** [comment]
Ok, Closing unless we find additional information.
