### ISSUE TITLE
Soho popdown does not close itself upon selection in IE

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise-ng#193]
**Describe the bug**

**To Reproduce**
1. Open IE
2. Go to example application
3. Open Soho popdown
4. Select item
5. Witness popdown does not close itself upon selection

**Expected behavior**
Popdown will close the same way it does in Chrome

**Platform**
 - Browser Name: Internet Explorer v11

**Additional context**

**Comment by tmcconechy** [comment]
Descoping some IE 11 issues due to https://github.com/infor-design/enterprise/issues/3756
