### ISSUE TITLE
Column charts: Carry through "yAxis" option setting from Enterprise to NG

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#194]
**Is your feature request related to a problem? Please describe.**
See this feature addition from Enterprise https://github.com/infor-design/enterprise/issues/627

**Describe the solution you'd like**
Once https://github.com/infor-design/enterprise/issues/627 is merged into ids-enterprise, carry the option through to the angular wrapper.

**Describe alternatives you've considered**
n/a

**Additional context**
You may need to `npm i` a new nightly build of `ids-enterprise` to get the feature.

**Comment by tmcconechy** [comment]
Closing this was done on https://github.com/infor-design/enterprise/pull/864
