### ISSUE TITLE
disabled button needs to show tooltip in Angular

### ISSUE THREAD

**Issue by AnaLauraMartinez** [infor-design/enterprise-ng#195]
We need to show the tooltip of buttons that are disabled.

Solution that we will like:
We will like to have some tag that will allow us to have a tooltip on a disabled button

We already tried the following code and it doesn't seem to work
<div class="disabled-tooltip" title="{{'COMMON.add' | translate}}"></div>

**Comment by tmcconechy** [comment]
Related issue is https://github.com/infor-design/enterprise/issues/453 , we need someone to find a way to do this on angular.

**Comment by pwpatton** [comment]
If the markup can't handle it using disabled attribute then do we stop using disabled and make some sort of style and setting on button? The button would need to know it's faux disabled and kill the click and other events.

**Comment by bthharper** [comment]
Change the `button` template to:

```html
<svg soho-icon *ngIf="hasIcon" [icon]="currentIcon"></svg>
<span>
  <ng-content></ng-content>
</span>
<ng-content select="div.disabled-tooltip"></ng-content>
```
Then use:
```html
<button soho-button="icon" icon="bullet-list" disabled soho-tooltip title="DATAGRID_VIEW">
  <div class="disabled-tooltip" title="DATAGRID_VIEW"></div>
</button>
```

**Comment by tmcconechy** [comment]
@bthharper do you plan a PR, if not i can get Manilla team to try and set this going?

**Comment by bthharper** [comment]
Yes - just about to submit.
