### ISSUE TITLE
timepicker and datepicker components do not support required 

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#198]
**Describe the bug**

Setting `data-validate="required"` does not work on `soho-datapicker` or `soho-timepicker` components.

**To Reproduce**

In `validation-form.demo.html` add the following markup:

```html
<div class="field">
  <label for="required" class="label required">Required Date</label>
  <input soho-datepicker name="required" [(ngModel)]="requiredDate" data-validate="required" />
</div>
<div class="field">
  <label for="required" class="label required">Required Time</label>
  <input soho-timepicker name="required" [(ngModel)]="requiredTime" data-validate="required" />
 </div>
```

Also add two new properties in `validation-form.demo.ts`:

```typescript
requiredDate: string;
requiredTime: string;
```

Run the **demo application**, and navigate to:  [http://localhost:4200/validation](http://localhost:4200/validation) you will see neither date or time pickers are working correctly.

Note: Adding `customValidation="false"` does not work either as the order the `validation` api is applied means the standard validation provided in the component overrides the custom validation added in the directive.

**Expected behavior**

The standard validation support works for both `datepicker` and `timepicker`.

**Screenshots**

![image](https://user-images.githubusercontent.com/8340092/46159595-936c1c00-c278-11e8-9cf4-4bc5c9c668d0.png)

**Platform**

**Additional context**

Speaking to @tmcconechy, changes to the `ids-enterprise` time and date pickers are required to ensure any custom validation is not removed when the widgets are initialised.

**Comment by bthharper** [comment]
This is a placeholder issue to ensure any changes made to the `ids-enterprise` controls are reflected in the angular components and tested.

**Comment by tmcconechy** [comment]
I think this has been fixed, no?
