### ISSUE TITLE
Datagrid export to CSV using customDS doesn't work correctly

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#203]
**Is your feature request related to a problem? Please describe.**

The export to excel (excel utilities) are not exposed to me.
https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/test-export-without-datagrid.html#L57

**Describe the solution you'd like**

Expose it , by creating an angular type/wrapper. Perhaps similar to some of whats done on locale.js

**Additional context**
Replaces https://github.com/infor-design/enterprise/issues/775

**Comment by bthharper** [comment]
This is just a matter of creating a typings file, which you could do locally for now.

Something like:

```typescript
interface SohoExcelStatic {
  exportToCsv(fileName: string, customDataSource: any, datagrid: SohoDataGridStatic);
  exportToExcel(fileName: string, worksheet: string, customDataSource: any, datagrid: SohoDataGridStatic): void;
}

interface SohoStatic {
   excel: SohoExcelStatic;
}
```

@tmcconechy  there's a case here for the enterprise project to manage the typings, rather than the angular project. Is this something we should discuss?

**Comment by hohnzy** [comment]
Is this working? I am not able to trigger customDs. Everytime I get the result from current dataset (version 5.3.0). And what is separator good for? It just changes the first line string, but the values are still separated by ',' even if I parse something else like 'sep=;'

**Comment by tmcconechy** [comment]
@hohnzy yes it seems to work for me on the sample page http://master-enterprise.demo.design.infor.com/components/datagrid/test-export-without-datagrid.html in this example a static export is passed in. The seperator option is described here https://github.com/infor-design/enterprise/issues/378 it was needed for some locales.
