### ISSUE TITLE
Searchfield in toolbar does not clear ngModel

### ISSUE THREAD

**Issue by gushanson** [infor-design/enterprise-ng#204]
**Describe the bug**
When using an ngModel on the soho-toolbar-searchfield and clicking the x-button, the value in the searchfield is cleared but not the ngModel.

**To Reproduce**
1. Replace the attached files with the corresponding files in  project/ids-enterpise-ng/src/lib/app
[toolbar.zip](https://github.com/infor-design/enterprise-ng/files/2440877/toolbar.zip)
2. ng serve and go to http://localhost:4200/toolbar-basic
3. Expand the search field and type "testing"
4. Click the x-button in the searchfield
5. See error: the ngModel is not cleared.

**Expected behavior**
The searchfield and the ngModel is cleared.

**Screenshots**
ngModel vs searchfield:
![image](https://user-images.githubusercontent.com/4129417/46394010-ecf4a080-c6e7-11e8-9e27-e42b3e7887f0.png)

**Platform**
- Windows 10
- Chrome 69
- ids-ng 4.10

**Additional context**
Also noted an alert when expanding the searchfield.
Really weird, didn't see anything in the example code that would cause this...

**Comment by tmcconechy** [comment]
I wonder if just triggering a change on the click of the x would work ( in ids code possibly).

The alert is in toolbar-basic.demo.ts...

```
import { Component } from '@angular/core';

@Component({
  selector: 'app-toolbar-basic-demo',
  templateUrl: './toolbar-basic.demo.html'
})
export class ToolbarBasicDemoComponent {
  searchString: string;
  onSelected(event: SohoToolbarSelectedEvent) {
    const data = event.item[0].dataset.action;
    alert(data);
  }
}
```

**Comment by bthharper** [comment]
To get this working correctly would require the `SohoToolbarSearchFieldComponent` to implement the `ControlValueAccessor` interface.

**Comment by tmcconechy** [comment]
Is this still needed?

**Comment by tmcconechy** [comment]
Closing this for now. Since we use the flex-toolbar more anyways
