### ISSUE TITLE
 Data Grid Nested Grids

### ISSUE THREAD

**Issue by BasithAli** [infor-design/enterprise-ng#206]
**Is your feature request related to a problem? Please describe.**
We would like to use nested grids in angular ids-enterprise-ng. This was added in NG but need to know how to do this in angular.

**Describe the solution you'd like**
Make an example for nested grids in ng.

**Additional context**
https://github.com/infor-design/enterprise/pull/210
http://localhost:4000/components/datagrid/example-nested-grids.html

**Comment by tmcconechy** [comment]
Any initial thoughts about ideas for tackling this @bthharper and @pwpatton

**Comment by pwpatton** [comment]
Could use content project here if it were all template based. But since datagrid is really a single element in the dom with a datagrid doing the heavy lifting doesn't this have to be specified the same way as with soho/ep?

**Comment by tmcconechy** [comment]
It could be, i.e. just create a datagrid into the template on the event. That might be the only way.
Just have to integrate with the model

**Comment by tmcconechy** [comment]
Moving this to next sprint as we could not figure it out. Branch is `206-datagrid-nested-grids`
@pwpatton and @bthharper any suggestions to make this work in NG?

**Comment by tmcconechy** [comment]
Does this have a branch i can look at? It appears this might not be technically feasible.

**Comment by clepore** [comment]
FYI, @deep7102 's branch is: 206-datagrid-nested-grids

**Comment by tmcconechy** [comment]
I have an idea for this that may simplify it. What if we just put the nested data on the dataset for example

```
mayData = [
 { id: 1, field1: 'something', sublines: [
  {id: 1.1, subline: 'Item One'},
  {id: 1.2, subline: 'Item Two'},
  {id: 1.3, subline: 'Item Three'}
  ],
 { id: 2, field1: 'something', sublines: [
  {id: 2.1, subline: 'Item One'},
  {id: 2.2, subline: 'Item Two'},
  {id: 2.3, subline: 'Item Three'}
  ]
]
```

This means this problem would be simple to solve on the EP side and then in NG we just add some settings: `nestedGrids: true, nestedGridField: 'sublines'`. To the wrapper.

This might make this go faster but the negative is that you would need to preload the lines with the data, so making sure thats possible?

**Comment by tmcconechy** [comment]
Some conversation on this https://teams.microsoft.com/l/message/19:83173693057f4991b7a84f030975c06d@thread.skype/1563806330431?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1563803992406&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=Angular%20Components&createdTime=1563806330431 

Possible idea is to add code like codeblock editor and formatter so that its possible to hook into the expandable row and provide an NG component for the expandable row. That could be a datagrid.
