### ISSUE TITLE
"Enter" on grid button column sends different args than click

### ISSUE THREAD

**Issue by s-schwenck** [infor-design/enterprise-ng#208]
**Describe the bug**
A grid with a "click" event in a button column sends different sets of args for a "click" action and a "enter" press when focus is in the column.

**To Reproduce**
1. Create a grid with a button column that has a click event and at least one other column. Fill with data
2. Click one of the rows' button icon. Observe the args passed to the function include the clicked row, cell, and row data.
3. Click into one of the grids other columns and navigate using the arrow keys to the button column.
4. Press Enter. Observe the args passed back include the row and cell, but not the row data.

Or

1. go to http://localhost:4000/components/datagrid/test-icon-buttons.html
2. tab into the grid and arrow to the button fields
3. hit enter

An error is shown, because the event handler also expected the args to be in a different way.

**Expected behavior**
Pressing "Enter" in a button formatted column should produce the same args result as a mouse click in that same column.

**Platform**
 - Device: Windows PC (testing a touch device in Chrome)
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
A workaround is to go grab the data using the row passed back in the args, but we shouldn't need to take that extra step.

**Comment by tmcconechy** [comment]
This issue was fixed i believe on another ticket
