### ISSUE TITLE
Wrap renderLoop with Angular Component

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise-ng#214]
**Is your feature request related to a problem? Please describe.**
`renderLoop` appears to trigger a handful of the setTimeout violations we are seeing in chrome. Seems like this is a potential performance bottleneck.

**Describe the solution you'd like**
Currently `renderLoop` is initialized via Sohoxi.js. If we wrap this with an Angular wrapper (possibly a service), we could initialize it via  app.module. For example..

```
SohoRenderLoopService,
    {
      provide:    APP_INITIALIZER,
      useFactory: ... ,
      deps:       [ ]
    },
```

And then in the service have something like..

```
  this.ngZone.runOutsideAngular(() => {
      renderLoop()
  });
```

This way we can ensure `requestAnimationFrame` is running outside of Angular Zone.

**Comment by tmcconechy** [comment]
Also should the loop only be running when a component needs it? For example if a toast is running

**Comment by pwpatton** [comment]
Does this get started just due to sohoxi.js being loaded ? or is there function ep-ng calls where we could run outside angular?

**Comment by tmcconechy** [comment]
Are you going to make this change @krishollenbeck ?

**Comment by pwpatton** [comment]
One thing to not is that the renderLoop is called from an IIFE. So some sort or refactor will be required in soho/ep.
```
  // Setup a single instance of RenderLoop for export.
  var renderLoop = new RenderLoop();
  renderLoop.start();
```
which starts to `tick()` right away.

**Comment by krishollenbeck** [comment]
@tmcconechy I am okay with working on this. @EdwardCoyle Is there a use case I can refer to test that it works correctly, or the way you intend it to work?

**Comment by bthharper** [comment]
Is this complete now?

**Comment by EdwardCoyle** [comment]
@bthharper yes, this is complete.  @krishollenbeck added the Angular part in #259, and infor-design/enterprise#1095 added the EP part.
