### ISSUE TITLE
Column-Stacked Chart:Not getting tooltip for x-axis labels.

### ISSUE THREAD

**Issue by nilamthakur** [infor-design/enterprise-ng#217]
**Describe the bug**

Stacked type column chart is showing ellipses for long name but not showing tool-tip when we are hovering on it.

**Additional context**
PFA column-stacked.zip
[column-stacked.zip](https://github.com/infor-design/enterprise-ng/files/2478613/column-stacked.zip)

See also https://github.com/infor-design/enterprise/issues/829 an attempt was made to reproduce but this seems like an angular only issue

**Comment by tmcconechy** [comment]
Descoping this issue for now
