### ISSUE TITLE
Tooltip does not keep position on buttons

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise-ng#218]
**Describe the bug**
Sometimes click on button makes tooltip appear on different place

**To Reproduce**

1) Copy this example over searchfield.demo.html and run it [reproduction-tooltip-bug.zip](https://github.com/infor-design/enterprise-ng/files/2486922/reproduction-tooltip-bug.zip)

**Expected behavior**
Tooltip would always show on correct place

**Screenshots**
![image](https://user-images.githubusercontent.com/10186522/46949807-f33d3200-d082-11e8-9d44-18d6aaa45df6.png)

![image](https://user-images.githubusercontent.com/10186522/46949816-fb956d00-d082-11e8-9a2e-f30c642bae8e.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome

**Additional context**

**Comment by Fruko** [comment]
I did not try it, but this would mean that we would have to destroy tooltip everywhere in our application. 
Also the example just shows icon button,but I suspect this would happen in different cases too

**Comment by tmcconechy** [comment]
The idea is you toggle the icon right? Maybe thats a better way. But putting this in as a bug for now so we can investigate further later.

**Comment by tmcconechy** [comment]
Took a look at this example on the latest 7.5.x and could no longer see this issue. Appears this has been fixed over time

**Comment by Fruko** [comment]
Hello @tmcconechy, we updated to 8.1.2 and the issue re-appeared again, we have seen with toolbar buttons that are used with ngIf

**Comment by tmcconechy** [comment]
Ok, come to think of it i have seen some random tooltips floating around. We should probably get to the bottom of this.

I suspect its the place logic placing it at 0,0 then moving it?

**Comment by Fruko** [comment]
yeah, if the button is removed from the DOM a random tooltip appears on the 0,0 (top left corner of the window)

**Comment by tmcconechy** [comment]
Yeah where ever its doing that it should probably be hidden at that point.

**Comment by tmcconechy** [comment]
I fixed this in pager which was showing this quite readily. The fix was to destroy the tooltip there before rebuilding it. Whats happening is a tick is firing after its removed. So i added code to the destroy to make sure this doesnt happen.

We cant really call this randomly all over the place so if you do still see it you may need to call destroy.

**Comment by tmcconechy** [comment]
PR https://github.com/infor-design/enterprise/pull/4649

**Comment by jbrcna** [comment]
working as expected. thank you!
v4.35.0-dev
https://master-enterprise.demo.design.infor.com/components/lookup/example-multiselect-paging-serverside.html
