### ISSUE TITLE
SohoModalDialogInjector is not exported.

### ISSUE THREAD

**Issue by edgarinfor** [infor-design/enterprise-ng#221]
**Describe the bug**
Cannot ` import { SohoModalDialogInjector } from 'ids-enterprise-ng';` causing the compilation to fail.

**To Reproduce**
Try to import "SohoModalDialogInjector" as described above.

**Expected behavior**
SohoModalDialogInjector should exported from "ids-enterprise-ng".

**Comment by bthharper** [comment]
@edgarinfor  why do you need access to this?

**Comment by edgarinfor** [comment]
@bthharper , we created an injectable "ModalDialogService" which acts as a helper for opening dialogues:

    public modal<T>(component: ComponentType<T>, parent: ViewContainerRef): ModalDialogRef<T> {
        ArgumentHelper.checkNotNull('component', component);
        ArgumentHelper.checkNotNull('parent', parent);

        const modalDialogRef = new ModalDialogRef<T>();
        const dialogInjector = new SohoModalDialogInjector(modalDialogRef, this.injector);
        const componentFactory = this.componentFactoryResolver.resolveComponentFactory(component);
        modalDialogRef.component = parent.createComponent<T>(componentFactory, parent.length, dialogInjector);
        modalDialogRef.afterOpen(this.buildBusyIndicator);
        return modalDialogRef;
    }

**Comment by bthharper** [comment]
Why not create a delegate that wraps the `ModalDialogService` and adds the busy indicator on a call to modal:

```typescript
class ModalDialogServiceWithBusyIndicator<T> {
  public modal<T>(component: ...) {
    return dialogService.modal(component, parent).afterOpen(this.buildBusyIndicator);
}
```

**Comment by bthharper** [comment]
I would be concerned about "duplicating" code, and also exposing internals that are likely to change.

**Comment by bthharper** [comment]
@edgarinfor  are you okay with the solution?

**Comment by tmcconechy** [comment]
If the only use case is showing a busy indicator I think we could consider doing that as a common/supported featire?

**Comment by edgarinfor** [comment]
That's a good idea, @tmcconechy: like other components the dialogues could provide an easier way to show/hide a busy indicator as that's a quite generic feature. 👍

**Comment by bthharper** [comment]
How about we provide a mechanism for creating a custom `SohoModalDialogRef`?

```typescript
const dialogRef = this.modalService
  .modal<ExampleModalDialogComponent>(ExampleModalDialogComponent, this.placeholder, {},
    typeof AdvancedModalDialogRef<ExampleModalDialogComponent>)
  .open();
```

defined as follows:

```typescript
export class AdvancedModalDialogRef<T> extends SohoModalDialogRef<T> {
  // Extra methods!
}
```

This gives you the flexibility you want, without exposing the innards of how this is achieved.

**Comment by edgarinfor** [comment]
Yes, @bthharper. I think that that was the goal of the developer using the "SohoModalDialogInjector". 

That would allow us to extend the dialogues with anything we may need. 

However, I would still consider adding the "busy indicator" as an out-of-the-box feature.

**Comment by bthharper** [comment]
Of course, difficult to second guess all requirements but the `busyindicator` is definitely one.  

Maybe we could change this one to allow the SohoModalDialogRef to be extended, and add a new one for providing `busyindicator` support?

**Comment by tmcconechy** [comment]
Im going to descope this issue for now as im not sure how to fix it. I think the current work on https://github.com/infor-design/enterprise-ng/issues/508 replace the need for this because it works much different now.

Either that or we need a new issue to be created with an updated description.

**Comment by edgarinfor** [comment]
Should we re-open #508 then? That is the issue that re-occurred and that @bthharper is looking at again (we've been talking about it in the channel). Because things work different now, the previous workarounds don't really work anymore.

**Comment by tmcconechy** [comment]
Yes your right probably should be. I reopened. I’m really not sure how to fix that one. Hope Theo can figure out something.
Maybe you can start looking for workarounds and post them.
