### ISSUE TITLE
Toolbar searchfield does not work in Safari

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise-ng#225]
**Describe the bug**
Toolbar searchfield does not work. User can't type any value in it

**To Reproduce**
1. Run enterprise-ng project 
2. Go to Toolbar - Data-driven panel
3. Try to use search field

**Expected behavior**
Searchfield would react on keyup event

**Screenshots**

**Platform**
- Platform: Mac Os
 - Browser Name Safari
 - Browser Version12.0 safari/605.1.15

**Comment by Fruko** [comment]
Hello,

this issue is still reproducible in ids-enterprise 5.0.0, If I am not mistaken it should be already in?

![image](https://user-images.githubusercontent.com/10186522/52281346-3edf5880-295e-11e9-93d0-aa772246491d.png)

**Comment by tmcconechy** [comment]
This was fixed just after 5.0 of NG https://github.com/infor-design/enterprise-ng/releases since it was merged on Dev 12. So would be in 5.1.0 when we release that later this month
