### ISSUE TITLE
Upgrade to Angular 7

### ISSUE THREAD

**Issue by petercullen68** [infor-design/enterprise-ng#227]
Since Angular 7, was released we should upgrade the project.

https://blog.angular.io/version-7-of-angular-cli-prompts-virtual-scroll-drag-and-drop-and-more-c594e22e7b8c

- [ ] Follow upgrade guide and make needed changes
- [ ] Confirm tests and examples are still working

**Comment by tmcconechy** [comment]
I was going to raise an issue for it, so we can plan. No timeline yet.

**Comment by petercullen68** [comment]
Excellent!  Thanks Tim,

**Comment by tmcconechy** [comment]
Yes, i'd wait for 4.13 (can push on master starting next week).

**Comment by petercullen68** [comment]
No problem with that approach.  When I upgraded our project to 7 to see what would happen, I saw issues around jquery and typing.

**Comment by pwpatton** [comment]
agreed, seems reasonable to wait until 4.13

**Comment by bthharper** [comment]
Typescript is far stricter, so many of the `typings` in the `enterprise-ng` project need updating.  This will take sometime, I don't expect it to affect the api too much, but may have a knock on affect.

There may also be other issues.

Definitely think we should wait till at least 4.13.

**Comment by bthharper** [comment]
I have the demo app working now, but the unit tests require some more work.  

Nothing that difficult to solve yet.

**Comment by bthharper** [comment]
FYI https://github.com/DefinitelyTyped/DefinitelyTyped/issues/27657
