### ISSUE TITLE
Provide a configuration  option to hide drop-down arrow icon on a menu-button

### ISSUE THREAD

**Issue by richardgowen** [infor-design/enterprise-ng#234]
**Is your feature request related to a problem? Please describe.**
Using a menu-button for the "User" control on the masthead but don't want to see the drop-down arrow next to the User icon

**Describe the solution you'd like**
Provide a configuration option the can hide the drop-down arrow icon

**Comment by bthharper** [comment]
I discussed this with @tmcconechy , and agreed that `showArrow` is the correct way to achieve this, however this does not currently work..

A corresponding change has been made in the enterprise-ng control to support `showArrow`, see https://github.com/infor-design/enterprise-ng/issues/226.

**Comment by bthharper** [comment]
Just realised this should probably be created against the enterprise project

**Comment by tmcconechy** [comment]
Sure will close, you can create it there?
