### ISSUE TITLE
soho-lookup issues when using dataset input

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#236]
**Describe the bug**

When initialising a lookup using the `dataset` input, there are errors when initialising and also when selecting apply.

**To Reproduce**

Download the attached example.
```sh
npm i
ng s
```

navigate to http://localhost:4200/

**Expected behavior**

The lookup should initialise with the specified data, and when apply is selected the selected items should be set on the model.

**Screenshots**

**Additional context**

There are two issues here:

a) the `dataset` input is trying to set the dataset on the datagrid in the lookup directly and not via an api on the lookup, this causes issues when the datagrid is not currently visible.
b) the `dataset` is [] when the apply button is selected, which causes an error in the apply code.

See https://github.com/infor-design/enterprise/issues/1080 for the enterprise side of this issue, and once the problem has been fixed there the code in angular can be updated.

**Comment by bthharper** [comment]
Several comments to make.

1. The `settings` on the `lookup` component should be set using the `Input` to ensure they are set at the right time and not whilst angular is instantiating the component.  Current the component does not support setting the settings in one go.

So I recommend the following:
```html
<input soho-lookup [source]="sourceFn" [multiselect]='true'  [paging]="true" [sortable]="false"  .../>
```

2. There is no need to set the `class` on `lookup` explicitly, just annotate the component with `soho-lookup`.

3. Avoid setting the dataset directly via a async method, 

```typescript
this.service.getAvailableTemplates().subscribe(result => {
   this.templates = result.data;
});
```
Instead, set the `dataset` before the component is instantiated, or alternatively use the source function as per the demo.

NOTE: 

The `dataset` input is currently broken - so needs some rework.

**Comment by darinw** [comment]
Is this something that is going to be added to a roadmap soon?

**Comment by tmcconechy** [comment]
Added it to next sprint as we have some room. Any more thoughts on this @bthharper i didnt dig in but seems clear here?

**Comment by darinw** [comment]
is there documentation on [source] somewhere?

**Comment by tmcconechy** [comment]
Probably the best way to look at that is this example https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/example-paging.html#L44

So souce is a function that gets an arg with the request info (filter, page needed ect). Then when you do your ajax call you pass that back to the response callback.
