### ISSUE TITLE
'validate' not exposed by SohoDataGridColumn

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#243]
**Describe the bug**

The validation api provided by `datagrid` is not exposed by the angular component.

**To Reproduce**

Try adding validate: `"required"` to a column

**Expected behavior**

Expect the column to be marked required when editing.

**Screenshots**

**Platform**
**Additional context**

**Comment by ericangeles** [comment]
Hi @bthharper , could you give more details about this issue? Thanks!

**Comment by tmcconechy** [comment]
Im also not seeing any issues. I modified the datagrid-editors.demo.ts to have

```
  {
    id: 'quantity',
    name: 'Quantity',
    field: 'quantity',
    sortable: false,
    filterType: 'number',
    width: 105,
    editor: Soho.Editors.Input,
    validate: 'required'
  },
```

And then when i run that app and blank out the Quantity i see the validation happening

**Comment by bthharper** [comment]
Fixed as part of https://github.com/infor-design/enterprise-ng/pull/252.
