### ISSUE TITLE
application menu does not use ngZone

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise-ng#244]
Describe the bug

All the components need updating to use ngZone to avoid redundant change detection being fired.

To Reproduce

Run the application-menu-lazy demo.
ng s

Expected behavior

Change Detection should not be fired multiple times when calling / handling any of the widget methods / triggers.

Screenshots

Platform

Additional context

**Comment by tmcconechy** [comment]
Has a PR - seems like this should be marked closed
