### ISSUE TITLE
Datagrid Action Column is not working properly in 2nd page and rest

### ISSUE THREAD

**Issue by Hemalrajapaksha** [infor-design/enterprise-ng#248]
version 4.10.1 recently upgraded (4.5.0 is working properly)
I'm using datagrid component with
- Server-side pagination (intermediate = false)
- Groupable true

Initial page action column is working properly but, when we click next and click row action column it doesn't work as expected.  

in second page, when I click highlighted line
![image](https://user-images.githubusercontent.com/17869003/47702160-126ebe80-dc42-11e8-81c6-c72db8ee5971.png)

gives following error

![image](https://user-images.githubusercontent.com/17869003/47702017-b441db80-dc41-11e8-8db6-2f8463967369.png)

and also in the error,  After navigate to script.bundle.js 
the dataset was 2 items. but there are 40 items(20 first page items + 20 first page groupable header items)

![image](https://user-images.githubusercontent.com/17869003/47702051-cb80c900-dc41-11e8-8ce5-31c960fd41b3.png)

this is relevant datagrid option
```
   const gridOptions: SohoDataGridOptions = {
      columns: this.jobsGridPagingService.getColumns(),
      paging: true,
      pagesize: pageSize,
      pagesizes: [20, 50, 100],
      indeterminate: false,
      sortable: false,
      filterable: true,
      rowHeight: 'short', // short, medium or normal
      emptyMessage: emptyDataGridMessage,
      disableClientSort: true,
      groupable: {fields: [this.groupType], expanded: true, aggregator: 'sum'},
      source: (req: SohoDataGridSourceRequest, response: any) => {       
        this.jobsGridPagingService.getData(req, filterOptionsMap).subscribe((result: any) => {
          this.changeDetectorRef.detectChanges();
          const sorted = result.data.sort(function (a, b) {
            return new Date(b.lastRun).getTime() - new Date(a.lastRun).getTime();
            // return b.lastRun.localeCompare(a.lastRun);
          });
          req.total = result.total;
          response(sorted, req);
        });

      },
    } as SohoDataGridOptions;
```

**Comment by tmcconechy** [comment]
We never really supported grouping with paging, we dont have any examples of this. I'm surprised you were able to make it work.

I think we would have to add official support for using paging with grouping. When i tried it it worked ok on client side paging but it showed the number of records per page as the number of groups. Im not really sure how it would work to calculate the number of records when the groups. (For example 10 records per page and the groups have 20 each.

A possible workaround is to drop paging when using groups. I think i can possible fix the error but grouping isnt really working properly with paging and never has.

Also i think we should move this to https://github.com/infor-design/enterprise
