### ISSUE TITLE
Datagrid (rendered ) and (afterRender) callbacks are not called

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise-ng#251]
**Describe the bug**
rendered and AfterRender output callbacks are not called when Datagrid is initialized

**To Reproduce**

1. add afterRender and rendered outputs callback to datagrid
2. See that they are never called

**Expected behavior**
afterRender and rendered callbacks would be called once datagrid is rendered

**Additional context**
Seen in version 4.11.0

[Downloads.zip](https://github.com/infor-design/enterprise-ng/files/2538863/Downloads.zip)

**Comment by Fruko** [comment]
see attached Downloads.zip containing html and ts file with reproduction

**Comment by bthharper** [comment]
@pwpatton @tmcconechy  - in `soho-datagrid` the events are hooked up after the data is loaded (esp. if  `gridData` is set).  

Moving this block of code after the event hookup code fixes the issue with `afterRendered` but I am never seeing `rendered`.   

```typescript
.on('rendered', (e: any, args: SohoDataGridRenderedEvent) => { console.error('rendered'); this.onRendered(args); })
```

Any ideas when `rendered` should be called?

**Comment by bthharper** [comment]
It looks like it's called at the end of the init, when again we've not added events.  So the event hookup code should go before the widget init call?

**Comment by pwpatton** [comment]
@bthharper yes I think so, in most places we seem to hookup events before component init. We should definitely pick one or the other and before the init means we should be able to get the rendered event. Not sure why it's not firing.

**Comment by bthharper** [comment]
Have moved the event hookup code before the init and data method, and it works okay now.

**Comment by tmcconechy** [comment]
So all good then? I noticed the event is wrongly named `afterrender` should be `afterrendered`. To match `rendered`. But minor..

**Comment by tmcconechy** [comment]
Yeah that would.. Its covered here for refactoring on a major release. https://github.com/infor-design/enterprise/issues/643 since its breaking (but we could support both so it doesnt). I say leave as is for now.
