### ISSUE TITLE
Update Hierarchy NG to match changes made to hierarchy enterprise. 

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise-ng#254]
**Describe the solution you'd like**
Hierarchy (enterprise) control now supports a submenu and disabled menu items in the actions menu. Need to add an example of that functionality to the NG version. Also need to update `SohoHierarchyAction` with new properties supported in the enterprise version.

**Additional context**
![hierarchy-example](https://user-images.githubusercontent.com/1056684/47925919-47228600-de8d-11e8-8f97-4b21ea41cb72.png)

https://github.com/infor-design/enterprise/issues/1044

**Comment by tmcconechy** [comment]
This has PR - so should be fixed now 👍
