### ISSUE TITLE
Adding missing arguments for openMenu function in soho-application-menu

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise-ng#255]
**Describe the bug**
openMenu function in applicationMenu control takes 3 optional arguments and soho-application-menu should also allow these arguments.

**Platform**
 - OS Version: Windows 10
 - Browser Name : Chrome
 - Browser Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Noting some of the options are internal - passed in different internal cases. Which ones do you want to use for something? I guess cant hurt to add them all.

- @param {boolean} noFocus If true, sets focus on the first item in the application menu.
- @param {boolean} [userOpened] If true, notifies the component that the menu was manually opened by the user.
- @param {boolean} [openedByClass] If true, only adjusts bare-miniumum requirement  for the application menu to appear open (should be used in cases where the application menu has the `is-open` CSS appended to it via markup).  This skips events, animation, etc.

**Comment by vonnyw** [comment]
I need to pass userOpened=true to force the application menu to be opened after a search on a mobile device.

**Comment by tmcconechy** [comment]
This has a merged PR so assume its fixed now
