### ISSUE TITLE
Colorpicker is not initially disabled if using editable=false

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise-ng#257]
**Description**
If a colorpicker is non-editable, it can never be disabled initially. The disabled state is not enforced. I suspect this might be an issue with the core component as well due to the order of operations in its `build()` method. If the colorpicker is non-editable, it will call `readonly()`, which in turn calls `enable()`.. I got a bit confused by the order of operations, and the number of times `readonly()` was called versus `disable()`, when I tried to debug this further.

**To Reproduce**
1. Edit this sample
https://github.com/infor-design/enterprise-ng/blob/master/src/app/colorpicker/colorpicker.demo.html
2. Use inputs `[editable]="false"` and `[disabled]="true"`
2. Run sample

**Expected behavior**
Colorpicker is disabled.

**Actual behavior**
It's not. If the disabled state were to be toggled to false then back to true, it works.

**Workaround**
Code below works, but we can't really know when it's ready to be disabled without interference.
```
ngAfterViewInit() {
	this.colorpicker.editable = false;
	setTimeout(() => {
		this.colorpicker.disabled = true;
	}, 100);
}
```

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done folder.
