### ISSUE TITLE
DatePicker needs to support new useCurrentTime property

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise-ng#261]
**Describe the bug**
The ids-enterprise datepicker control was recently updated to have a new useCurrentTime property and the ids-enterprise-ng soho-datepicker component needs support for it.

**Comment by tmcconechy** [comment]
I added this in this PR https://github.com/infor-design/enterprise-ng/pull/287 @fitzorama 
I forgot you were going to do it 👍
