### ISSUE TITLE
Datagrid emptyMessage not visible when set via gridOptions input

### ISSUE THREAD

**Issue by gushanson** [infor-design/enterprise-ng#267]
**Describe the bug**
The datagrid emptyMessage is not visible when set via [gridOptions] input (gridOptions.emptyMessage). It works when set via the [emptyMessage] input.

**To Reproduce**
- Replace the attached example files with the ones in src\app\datagrid\
[datagrid.zip](https://github.com/infor-design/enterprise-ng/files/2566191/datagrid.zip)
- ng serve and go to http://localhost:4200/datagrid-empty-message

**Expected behavior**
The configured emptyMessage is visible.

**Screenshots**
No empty message:
![no_empy_message](https://user-images.githubusercontent.com/4129417/48267409-9559fb00-e432-11e8-89af-3f19e0abc13a.PNG)

**Platform**
 - Win 10
- All browsers

**Comment by tmcconechy** [comment]
May be related to https://github.com/infor-design/enterprise/issues/1467

**Comment by tmcconechy** [comment]
Descoping this for now - but may be fixed as infor-design/enterprise#1467 is fixed
