### ISSUE TITLE
Need the ability to change a modal title

### ISSUE THREAD

**Issue by jayblack-infor** [infor-design/enterprise-ng#271]
**Describe the bug**
I'd like to change the modal title based on selections in the modal after opening.   Tried this.dialog.title(“New title”) but that didn’t work.

Asked about this on the Angular Components Teams channel.    Here's the discussion:
Theo Harper:  When modal was implemented, there was no API on modal to allow the title to be updated.  That may have changed, so I would raise a ticket on github.

**Comment by bthharper** [comment]
@tmcconechy the code for changing the title of an open model is present in ng, but I was not clear what to call on the modal widget to update the title once the settings were changed.  What would you suggest?

**Comment by tmcconechy** [comment]
I think we will need a ticket in enterprise to do this. The idea would be to make the updated method check if there is a title passed in the settings, and if there is actively update it depending on if its open or not. Then the angular part should just call updated as it presently does with the new setting

**Comment by tmcconechy** [comment]
Descoping this for now.
