### ISSUE TITLE
Busy Indicator closed (.close() fired) after each click on menu

### ISSUE THREAD

**Issue by dubde** [infor-design/enterprise-ng#281]
**Describe the bug**
Close() method is called after clicking on accordions, causing the busy indicator to close right after it's started. Bug open after [request on Microsoft Teams](https://teams.microsoft.com/l/message/19:6d4c9079385840c0bc61e55bcdd16a33@thread.skype/1543309937711?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1543309937711&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=Problems&createdTime=1543309937711) , I attached example page to reproduce it on the enterprise-ng-quickstart project.

**To Reproduce**
0. (Download and npm install bugged app attached to this report, run it locally)
1. Go to main page
2. Click on any entry on menu

**Expected behavior**
We would like to handle freely the busyIndicator and avoiding situations that the interface became interactive when it shouldn't, just because the accordions "close()" is called

**Version**
- ids-enterprise-ng: [5.0.0-dev.20181113 and before..]

**Platform**
 - OS Version: [Windows 10]
 - Browser Name [chrome, firefox, ie]

[bug-app.zip](https://github.com/infor-design/enterprise-ng/files/2623693/bug-app.zip)

**Comment by tmcconechy** [comment]
We should look at the closeChildren function in lifecycle.js for a fix that excludes closing active busy indicators. We should also make an Enterprise example for this and possibly move it there if that can be verified.

**Comment by dubde** [comment]
I tryed to add the directive to the EXCLUDE_FROM_CLOSE_CHILDREN
```var EXCLUDED_FROM_CLOSE_CHILDREN = ['.expandable-area', '.accordion', '[soho-busyindicator]'];```
 and seems to be working then.. 

I don't know if it's interfering with other instances of the busy indicator that are, indeed, meant to be closed.

**Comment by tmcconechy** [comment]
Ok, if you want to try a pull request. If it works as well it might be better to use the `busyindicator` class because it will work both if its a IDS or NG issue 

https://github.com/infor-design/enterprise/blob/master/src/utils/lifecycle.js#L3

```
const EXCLUDED_FROM_CLOSE_CHILDREN = ['.expandable-area', '.accordion', '. busyindicator]'];
```

**Comment by dubde** [comment]
Unfortunately, as I see, the class is applied only to the Loading Spinner, but the directive doesn't add it to the element that it's firing it. I just tried with '.busy-indicator' as class but doesn't change the wrong behavior. 

This is what is in the dom: 
```
<div _ngcontent-c0="" blockui="true" displaydelay="0" soho-busyindicator="" ng-reflect-block-u-i="true" ng-reflect-display-delay="0" ng-reflect-text="Loading..." style="">
  <div class="overlay busy"></div>
  <div class="busy-indicator-container blocked-ui" aria-live="polite" role="status">
      <div class="busy-indicator active">
        <div class="bar one"></div>
        <div class="bar two"></div>
        <div class="bar three"></div>
        <div class="bar four"></div>
        <div class="bar five"></div>
    </div>
    <span>Loading...</span>
    </div>
  </div>
</div>
```

Any clues?

**Comment by dubde** [comment]
Digging within the code, I see that here it's called: https://github.com/infor-design/enterprise/blob/master/src/components/accordion/accordion.js#L1415 the closeChildren()
`$('body').children().not('.application-menu, .modal-page-container, .page-container').closeChildren();` , 

As I see now, 
1: the busy indicator should be inside a .page-container, while we had it as sibling to the main page-container. With latest demo app and `<div soho-busyindicator></div>` inside the `<div class="page-container"></div>` and it's working as it should, covering the whole UI. I think this is fixed here: https://github.com/infor-design/enterprise/commit/2a1b78ff77732b834175ab5a40761e19b92e246d

2: Digging into blames, that call to closeChildren was added as part of this fix:
https://github.com/infor-design/enterprise/commit/01b805f1533d37170f416ebe859a7a1cce8180ea
But looking at the number of exclude (and .not()) it's visible that from commit to commit more object are added to these two lists. I am afraid that adding also the references for the busy indicator could be the best solution for it. Maybe something that will avoid this closeChildren on whole body could prevent further additions to these lists.. what do you think?

3: Looking at the [documentation](https://design.infor.com/code/ids-enterprise/latest/busyindicator) the example for blocking the full UI is wrong linked as it show the busy Indicator for Ajax calls. Should I open another bug for it?

**Comment by tmcconechy** [comment]
1. Yes, you probably want the page-container as it gives a height on the body to center the busy indicator in. 

2. @EdwardCoyle What do you think?

3. We can fix that agains this as well.
