### ISSUE TITLE
Contextual Toolbar: buttons are sometimes hidden from view

### ISSUE THREAD

**Issue by deep7102** [infor-design/enterprise-ng#283]
**Describe the bug**
When resizing a Contextual Toolbar (CT) with multiple buttons, the buttons sometimes disappear due to width containment (see recording).

**To Reproduce**
1. Open sample "datagrid-mixed-selection" and add some more buttons to the buttonset of the CT
2. Select an item in the datagrid and resize the width of the browser window
3. Problem: rightmost items get pushed below the visible area

**Expected behavior**
All buttons are visible regardless of width.

**Version**
- IDS Version: IDS Components (+ NG) 4.12.0-dev

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 70.0.3538.67 (Official Build) (64-bit)]

**Additional context**
Moved from the EP project: infor-design/enterprise#1058

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
