### ISSUE TITLE
Soho-editor change event is not emitting the correct value

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise-ng#284]
**Describe the bug**
The change event in soho-editor is emitting an empty string value which is being based on an incorrect jQuery usage. Consumers of the component could confuse this as the correct value of the editor.

**To Reproduce**
1. Open the editor.demo.ts and editor.demo.html to add the change event to display the value on the console
2. Run the editor demo and change some content
3. The console should display an empty value.

**Expected behavior**
The onChange() method needs to use this.jQueryElement[0].innerHTML to obtain the correct value for the editor control. It should then use an additional property on the event to set the value and emit the event.

**Version**
- ids-enterprise-ng: 4.13

**Screenshots**
![soho-editor-empty-change-event](https://user-images.githubusercontent.com/20212079/49470904-06da5e80-f7d1-11e8-9575-7f39abc3465a.gif)

**Additional context**
Landmark

**Comment by theakatz** [comment]
@fitzorama are you still working on this ticket?

**Comment by fitzorama** [comment]
@theakatz No, I am not currently working on this.

**Comment by tmcconechy** [comment]
And it still needs a fix right @fitzorama ?

**Comment by fitzorama** [comment]
That's a good question. Some change events don't emit a value. I think if there is no one else needing it, it can be closed and a new ticket opened if and when there is a need.

**Comment by tmcconechy** [comment]
Sounds like a plan, lets evaluate later if needed.

**Comment by janahintal** [comment]
Hi, @tmcconechy, may we know where can we test this? Thank you!

**Comment by tmcconechy** [comment]
You can’t test this one as it is an ng issue
