### ISSUE TITLE
Datagrid: SohoDataGridColumn maxLength property should be typed as a number

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#294]
**Is your feature request related to a problem? Please describe.**
Change the definition of the maxLength property of the SohoDataGridColumn to be a number so Landmark can use it to enforce the number in input characters in the Editors.

Currently defined: `maxLength?: boolean;`

**Describe the solution you'd like**
Should be defined: `maxLength?: number;`

**Describe alternatives you've considered**
n/a

**Additional context**
Never caught this when the maxLength property was exposed via https://github.com/infor-design/enterprise-ng/pull/35

**Comment by clepore** [comment]
@claudenbach Thanks for your submission, but please update the description to follow the `bug request` or `feature request` template. Thanks!

**Comment by pwpatton** [comment]
max length is already defined as a number in the column SohoDataGridColumn object.

**Comment by pwpatton** [comment]
I'm not sure when that was changed but it was quite a while ago I believe

**Comment by clepore** [comment]
Yeah the pull request was Jan 10th (linked up above).
