### ISSUE TITLE
Datagrid: Expose the method "clearRowError"

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#314]
**Is your feature request related to a problem? Please describe.**
The method `clearRowError()` for the datagrid isn't exposed in enterprise-ng.

**Describe the solution you'd like**
Expose `clearRowError()`

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by clepore** [comment]
@claudenbach Thanks for your submission, but please update the description to follow the `bug request` or `feature request` template. Thanks!
