### ISSUE TITLE
Datagrid: Incorrect data is passed to datagrid column component when using tree grid.

### ISSUE THREAD

**Issue by chrisfried** [infor-design/enterprise-ng#315]
**Describe the bug**
When using an Angular component to format a column, the wrong data is passed to rows deeper than the first level in treegrid.

Before applying a component:

|- Value 0
|- Value 1
|- Value 2
|-|- Value 3
|-|- Value 4

After applying a component:

|- Value 0
|- Value 1
|- Value 2
|-|- Value 0
|-|- Value 1

**To Reproduce**
1. Create a tree grid that uses with a column component.
2. Be frustrated.

**Expected behavior**
The proper row value should be passed to the component.

**Version**
- ids-enterprise-ng: v5.0.0

**Screenshots**
Left: No column components
Right: Column components on Description and Data Type
![components](https://user-images.githubusercontent.com/422381/50849594-b8bafc80-1334-11e9-9b3f-d0271c887c53.png)

**Comment by tmcconechy** [comment]
Im not clear what the column component is? The chart ? http://latest-enterprise.demo.design.infor.com/components/column/example-index.html

Do you have some code you can add to reproduce this behavior?

**Comment by chrisfried** [comment]
You can define a column with a 'component' that will be used to format each cell, rather than a 'formatter'

```
{
      id: 'description',
      name: this.translations.columns.description,
      field: 'description',
      component: SchemaPropertyFormatterComponent,
      filterType: 'text',
      width: 300
}
```

**Comment by chrisfried** [comment]
The component being an Angular Component, as opposed to a formatter written with jQuery.

**Comment by tmcconechy** [comment]
ok yeah we did that for a couple use cases like this one https://github.com/infor-design/enterprise-ng/blob/master/src/app/datagrid/datagrid-angular-card-formatter.demo.html

I guess it doesnt play well with what the tree is doing. Can you upload a sample html and js we can drop in?

**Comment by chrisfried** [comment]
![ids](https://user-images.githubusercontent.com/422381/50851342-ca52d300-1339-11e9-95cf-28ff97bfe9d8.png)

**Comment by janahintal** [comment]
QA Passed. Moving to Done. 
Tested in: http://localhost:4000/components/datagrid/test-post-renderer-tree.html
