### ISSUE TITLE
Busy Indicator stuck on loading

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#32]
Issue moved from https://jira.infor.com/browse/SOHO-8033

Toggling the "activated" state of the busy indicator quickly can sometimes cause it to be stuck in one state. Possibly only during component initiation.

Code:

```
// Component template
<div soho-busyindicator [activated]="isBusy" [blockUI]="true" [displayDelay]="0">

// Component controller
class MyComponent {
  isBusy: boolean;

  ngOnInit() {
    this.isBusy = true;
    fetchSomething().then(() => this.isBusy = false);   // Busy indicator remains "activated" after this
  }
}

```

SOHO version:

```
$ cat package.json | grep ids-enterprise
    "ids-enterprise": "4.7.0-beta",
    "ids-enterprise-ng": "4.7.0-dev.20180523",

```

The problem appears to be the asynchronous handling of `initiallyActive` in `ngAfterViewInit`` in soho-busyindicator.directive.ts. Basically, if the `activated` input is changed between the callbacks for `this.ngZone.run(() => setTimeout(() => ...))`, then it will still get stuck with the "initiallyActive" state.

I tried fixing it locally (http://git.infor.com/projects/ITECH/repos/homepages/commits/d30cc35d6da4a54df6b90a11d9de5c6e4e5b5846), and it seems to solve my problem. But I don't know if it would cause new problems elsewhere.. For instance -- Why is there a setTimeout there to begin with?

**Comment by tralarn** [comment]
@tmcconechy , would be really good to get this fixed for 4.7.0. Related to Homepages 12.0.25 release.

**Comment by tmcconechy** [comment]
Based on the comments on http://git.infor.com/projects/ITECH/repos/homepages/commits/d30cc35d6da4a54df6b90a11d9de5c6e4e5b5846

It seems we dont need the timeout. If you want to push a pull request here , we can go with your fix.

@clepore we didnt make a 4.7.x branch so if he pr's onto master will this be included in 4.7.0 this week?

**Comment by clepore** [comment]
That's up to the devs in the NG team and if it's ready.

**Comment by tmcconechy** [comment]
Ok, Cool. So not sure of andreas github details but if he can get a PR in with this change we should be good for 4.7 to review and add.

**Comment by bthharper** [comment]
@anhallbe a component that uses the `soho-busy-indicator`, and when run show the issue (possibility intermittently as I know these things are often ordering / timing related).  Tim put a pseudo version of the test component above, which I assume came from your original issue.

**Comment by tmcconechy** [comment]
Closing this as done - even though the example would be great.
