### ISSUE TITLE
Application menu items are not clickable

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-ng#321]
**Describe the bug**
When there are accordions in an application-menu, their `(click)` handler is not fired if items are added too fast.

**To Reproduce**

See template: https://github.com/anhallbe/ids-repro/blob/accordion-click/src/app/app.component.html
...and controller: https://github.com/anhallbe/ids-repro/blob/accordion-click/src/app/app.component.ts

1. Clone https://github.com/anhallbe/ids-repro/tree/accordion-click
2. Run the application with `ng serve`
3. Open the menu, and click some items
4. Add a delay to the adding of `links$` by uncommenting in `app.component.ts`
5. Open the menu and click some items

**Expected behavior**
In step 3, the click handler should be called and it should display some toasts. Step 5 should be exactly the same.

Currently, nothing happens on step 3. The click listener is never fired.

**Version**
- ids-enterprise-ng: 5.0.0

**Screenshots**
![accordion-click](https://user-images.githubusercontent.com/4991954/51116212-c841b600-180a-11e9-9f8d-da225f36f0da.gif)

**Platform**
Windows, MacOS, Android, iOS, Chrome, Safari, Firefox, WebView

**Additional context**
It may have something to do with `handleAnchorClick` in `accordion.js` in `ids-enterprise`, where the event is stopped from propagating.

**Comment by anhallbe** [comment]
Note: The same problem happens to ALL `soho-accordion-header` in the menu, regardless of nested level. Also, while the repro code is adding the items asynchronously, the problem is still present even if items are declared in the template:

```html
<nav soho-application-menu>
  <soho-accordion>
    <soho-accordion-header (click)="functionThatWillNeverBeCalled()"> ... </soho-accordion-header>
    ...
  </soho-accordion>
</nav>
```

**Comment by tralarn** [comment]
What is the status for this issue?

**Comment by tmcconechy** [comment]
Status: No time yet but will add to the next sprint

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to QA Done column.
