### ISSUE TITLE
Upgrade to @angular/cli and @angular 7.2

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#327]
**Describe the bug**

Targeting an application to use `ids-enterprise-ng` and `angular/cli` 7.2.x fails with the error:

```sh
ERROR in node_modules/ids-enterprise-ng/lib/utils/deprecated-event-emitter.d.ts(6,5): error TS2416: Property 'subscribe' in type 'DeprecatedEventEmitter<T>' is not assignable to the same property in base type 'EventEmitter<T>'.
  Type '(generatorOrNext?: any, error?: any, complete?: any) => void' is not assignable to type '(generatorOrNext?: any, error?: any, complete?: any) => Subscription'.
    Type 'void' is not assignable to type 'Subscription'.
```

This looks to be caused by the use of typescript 3.2.2 which is stricter on type declarations.

**To Reproduce**

Checkout `id-enterprise-quickstart-ng`

```sh
npm i
npm i @angular/cli@latest
ng upgrade @angular/cli @angular/core
ng s
```

**Expected behavior**

The application should compile and run.

**Version**
- ids-enterprise-ng: 5.0.0

**Screenshots**

N/A

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
This was added and merged.
