### ISSUE TITLE
RTL: Modal disappear out of sight

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise-ng#332]
**Describe the bug**
When running in RTL some dialogs opens and then disappears (moves out from view)

**To Reproduce**
1. Change locale to as-SA
2. Go to http://localhost:4200/modal-dialog in **Chrome**
3. Click on Vetoable
4. Error occurs here: Dialog shows for a second and then moved out of sight

**Expected behavior**
Dialog should stay in sight.

**Version**
- ids-enterprise-ng: 5.0

**Screenshots**
-

**Platform**
- OS Version: Windows 10 
 - Browser Name: Chrome
 - Browser Version: Version 71.0.3578.98 (Official Build) (64-bit)

**Additional context**
It seems to be working in IE11

**Comment by tmcconechy** [comment]
One fix i see on the EP side could be
1.  change `.modal-page-container` class to `position: fixed` 
2. Change modal.js logic to put the`zindex` on modal-page-container

- Test animation, nested modals and all modal examples.

**Comment by janahintal** [comment]
QA Passed. Will move to Done. 
Tested in http://master-enterprise.demo.design.infor.com/components/modal/test-checkbox.html?locale=ar-EG across all browser, OS and devices.
