### ISSUE TITLE
Updating to @angular/core 7.2.1 causes ng build / ng serve to fail

### ISSUE THREAD

**Issue by petercullen68** [infor-design/enterprise-ng#333]
**Describe the bug**
Updating to the latest version of @angular/core results in a build error.  Update was from 7.2.0 to 7.2.1

ERROR in node_modules/ids-enterprise-ng/lib/utils/deprecated-event-emitter.d.ts(6,5): error TS2416: Property 'subscribe' in type 'DeprecatedEventEmitter<T>' is not assignable to the same property in base type 'EventEmitter<T>'.
  Type '(generatorOrNext?: any, error?: any, complete?: any) => void' is not assignable to type '(generatorOrNext?: any, error?: any, complete?: any) => Subscription'.
    Type 'void' is not assignable to type 'Subscription'.

**To Reproduce**
1. Run  ng update @angular/core
2. run ng build or ng serve
3. See error

**Expected behavior**
ng build or ng serve should not throw an error.
**Version**
- ids-enterprise-ng:5.0.0

**Comment by tmcconechy** [comment]
We just merged this: https://github.com/infor-design/enterprise-ng/pull/331
Did you try this prior to or after this change?

**Comment by petercullen68** [comment]
Ok I can wait until it's available in a release.  Not holding me up or anything, just wanted to get it on the radar for you guys.  I update @angular frequently but staying on 7.2.1 for a while is not going to cause me any issues

**Comment by tmcconechy** [comment]
Sounds good - yep i think thats the fix you need

**Comment by pwpatton** [comment]
@petercullen68  just let me know and I can create a release for you. it would use `4.15.0-dev.20190119`
 until the `4.16` dev builds are ready.

**Comment by petercullen68** [comment]
Thanks @pwpatton, I'll let you know.
