### ISSUE TITLE
"ngModelChange" doesn't work on text change for soho-textarea 

### ISSUE THREAD

**Issue by hemantg05** [infor-design/enterprise-ng#337]
**Describe the bug**
"ngModelChange" doesn't work on text change for `soho-textarea`

**To Reproduce**
1. Add "ngModelChange" event binding to soho-textarea. Also write "onTextChange()" method in typescript code to log the text change event on the console.
         ` <textarea soho-textarea maxlength="90" name="counter" (ngModelChange)="onTextChange()" [(ngModel)]="model.counterText"></textarea>`

2. Open browser console and run above code.
3. Make some changes in the text area.
4. Notice that nothing is logged in the console. That means "ngModelChange" didn't work. The event is fired after "blur". It should be fired immediately after text changes.
5. Now make it a regular textarea by remove "soho-textearea" from the textarea markup.
6. Run this code and type something in the text area.
7. You will see the console log statement indicating that "ngModelChange" works successfully on regular textarea (non-soho)

**Expected behavior**
"ngModelChange" event binding should work for soho-textarea.

**Version**
- ids-enterprise-ng: 4.10.0 and above

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: Mac
 - Browser Name: Chrome
 - Browser Version: 71.0.3578.98 (64-bit)

**Comment by tmcconechy** [comment]
We would have to have someone investigate a solution for this. Can you use the change event?

**Comment by fitzorama** [comment]
@hemantg05 I'm wondering if the input event would work for you? In Landmark to get around this issue, we listen on the input event and then call changeDirty() on the soho-trackdirty.component to have the evaluation performed.

**Comment by hemantg05** [comment]
@fitzorama, yes, the input event works to get around this issue. Thanks for the providing this work around.

**Comment by tmcconechy** [comment]
Lowering priority as there is a workaround. This came up a couple times so maybe we should try and fix it if we ever get a chance 👍
