### ISSUE TITLE
DataGrid - Would Like To Apply Cell-Level Tooltips (Angular)

### ISSUE THREAD

**Issue by pjm16** [infor-design/enterprise-ng#342]
**Is your feature request related to a problem? Please describe.**
We've found a way to configure row-level tooltips but we'd like to have that feature at the cell-level. We're using the Angular wrapper, I've searched the code & dont think this is currently supported?

**Describe the solution you'd like**
Cell-level tooltip configuration exposed in the Angular Soho wrapper

**Describe alternatives you've considered**
We'll able to get away with row-level tooltips for now but isnt something we'll want to do for too long

**Additional context**
none

**Comment by tmcconechy** [comment]
There is an option http://latest-enterprise.demo.design.infor.com/components/datagrid/example-tooltips.html where you can set `tooltip: 'something'` in the column definition. Does this not work in angular?

**Comment by pjm16** [comment]
> There is an option http://latest-enterprise.demo.design.infor.com/components/datagrid/example-tooltips.html where you can set `tooltip: 'something'` in the column definition. Does this not work in angular?

**Comment by pjm16** [comment]
hi @tmcconechy we can set column-level tooltips in Angular but we'd like to ask for Cell level. We'd like to show a tooltip that pertains just to the one cell - maybe some extra info so we're not over-cluttering the grid itself.
