### ISSUE TITLE
'filterConditions' does not exist in type 'SohoDataGridColumn'

### ISSUE THREAD

**Issue by kvchaudhari** [infor-design/enterprise-ng#350]
**Describe the bug**
In SohoGridColumn on column we have added filter conditions like 1filterConditions:['equals','contains']`
For Angular4 version this was consider as warning. Now we are upgrading Angular4 to Angular7 . For Angular7 build is getting failed and getting error like `**"Object literal may only specify known properties, and 'filterConditions' does not exist in type 'SohoDataGridColumn'. "**`

**To Reproduce**
```
 columnsAPPInstanceList: SohoDataGridColumn[] = [
    {
      id: 'app_name', name: 'AppName', field: 'applicationName', filterType: 'text',  filterConditions: ['equals', 'contains']
    }
```
Object literal may only specify known properties, and 'filterConditions' does not exist in type 'SohoDataGridColumn

**Expected behavior**
It should be allowed to take "filterConditions" in SohoDataGridColumn

**Version**
- ids-enterprise-ng: v5.0.0

**Screenshots**
![imgo](https://user-images.githubusercontent.com/24225832/52410664-1347a400-2aff-11e9-9d17-528cbae4a5bd.jpg)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Just need to add the types and do a pull request 👍
