### ISSUE TITLE
CodeBlock: expandOnActivate does not work on code block column

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#353]
Datagrid column contains a CodeBlockFormatter and CodeBlockEditor.  The column has the property of expandOnActivate set to true.  The cell does not expand to show all content when the cell has focus.

**To Reproduce**
1. Goto datagrid-angular-editor.demo (see attached files)
2. Click on a Code Block cell to set focus
3. Column should expand to show all the content

**Expected behavior**
Code block column should expand to show all the content

**Additional context**
See the attached example that demonstrates the issue.
![expandonactivate](https://user-images.githubusercontent.com/39804038/52580824-c578b780-2dee-11e9-87a4-fa0243aee986.gif)
[ExpandOnActivate.zip](https://github.com/infor-design/enterprise-ng/files/2852213/ExpandOnActivate.zip)

**Comment by tmcconechy** [comment]
This is possibly tricky. Might be better to just use css to reduce the editor size down so it shows in the short row.

**Comment by tmcconechy** [comment]
@claudenbach - Do you think we should just style the code block to fit in the row so its less tall?

**Comment by tmcconechy** [comment]
This may be similar to https://github.com/infor-design/enterprise/issues/1643

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
