### ISSUE TITLE
CodeBlock: tooltip for a code block column is incorrect

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#354]
Datagrid column contains a CodeBlockFormatter and a CodeBlockEditor.  The grid has the option of enableTooltips set to true.  The tooltip for the column is incorrect.

**To Reproduce**
1. Go to the 'datagrid-angular-editor.demo.html' (see attached files)
2. Mouse hover over a Code Block cell to display the cell tooltip

Is there a way to provide a dynamic tooltip for a cell, versus a static method that currently exists?

**Additional context**
See the attached example that demonstrates the issue.
[CodeBlockTooltip.zip](https://github.com/infor-design/enterprise-ng/files/2852636/CodeBlockTooltip.zip)

![image](https://user-images.githubusercontent.com/39804038/52586783-fb716800-2dfd-11e9-8dce-1411bb1494ab.png)

**Comment by tmcconechy** [comment]
Is this something your looking into? I believe the code block was something your team would support.

**Comment by claudenbach** [comment]
Is there someway I can dynamically control the tooltip for a datagrid cell?  As the user fills in the various fields that make up the code block want the tooltip to reflect the changes.

**Comment by tmcconechy** [comment]
I think we would have to add a setting to EP for that to work totally well.

**Comment by tmcconechy** [comment]
Do you actually want the tooltip to work here? Seems like all the data is visible.

**Comment by brianjuan** [comment]
Hi, I've tested the bug fix on this page, http://4180-beta0-enterprise.demo.design.infor.com/components/datagrid/test-custom-tooltip-dynamic.html

The tooltip is working as expected on the Activity column. But on the Exception column, the tooltip doesn't display when you resize the column to a wider size, this happens on all browsers for Mac and Windows.

![datagrid_dynatooltip](https://user-images.githubusercontent.com/39508864/56780208-02125780-6811-11e9-975c-ab2ffc80bd48.gif)

**Comment by tmcconechy** [comment]
I’ll have to recheck this but I think it’s all working as expected, the activity column has a tooltip that always shows but the exception column has one that only shows when the column is cut off. You can do it both ways, so seems like nothing more to fix here

**Comment by tmcconechy** [comment]
If anything might want to make an explicit option and make it clear in the example

**Comment by tmcconechy** [comment]
@brianjuan We dont have to much time to change this but it is working correct, there is just two styles of tooltip in the example.

- Exception: We added a function to dynamically get tooltip content - thats one one column - this type of tooltip only runs when cut off
- Activity: The other has a static tooltip on the column - runs all the time no matter what.

Its a bit confusing but is working correctly if you consider that those two are different scenerios of tooltip in the example being shown.

**Comment by brianjuan** [comment]
Sure @tmcconechy , Thanks for the clarification.
