### ISSUE TITLE
Need a safety check in soho-listview clearAllSelected

### ISSUE THREAD

**Issue by nbcp** [infor-design/enterprise-ng#357]
**Describe the bug**
Getting a
> LMListViewComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: Cannot read property 'clearAllSelected' of undefined
    at soho-listview.component.ts:419

**To Reproduce**
1. immediately call `clearAllSelected()` without `this.listView` being defined

**Expected behavior**
Need a safety check to catch unnecessary calls to `this.listview.clearAllSelected()`

**Version**
- ids-enterprise-ng: 5.1.0

**Comment by tmcconechy** [comment]
Feel free to push a PR @nbcp and we can review 👍
