### ISSUE TITLE
SOHO-8028: When setting ngModel for multiselect dropdown to empty array the previous selections still show in the text.

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#36]
As stated in the title, when setting ngModel for multiselect dropdown to empty array the previous selections become unchecked but still show in the text area.

![textstillshowsafterclear](https://user-images.githubusercontent.com/814283/40724234-93fa797a-63ee-11e8-85d5-dc0f8845d6f3.png)

**Comment by crlang44** [comment]
Calling updated() on the SohoDropDownComponent doesn't do the trick either for me. Note: I'm not using observable and therefore cannot use the async pipe in the html which is what the dropdown-async demo does.

**Comment by bthharper** [comment]
@crlang44 what version are you using, 4.7.0 has some changes to the dropdown which may resolve your issues.  

Do you have a simple example that shows the problem I can try for you?

**Comment by crlang44** [comment]
@bthharper  Yes we just updated to 4.7.0 and I can confirm the issue is fixed! Thanks a bunch!
