### ISSUE TITLE
Toolbar searchfield misplaced tooltip

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise-ng#360]
**Describe the bug**
Toolbar searchfield has misplaced tooltip

**To Reproduce**
1. Go to example ng app
2. Go to toolbar part
3. Mouse over searchfield

**Expected behavior**
A tooltip properly aligned

**Version**
- ids-enterprise-ng: 5.0.0

**Screenshots**
![image](https://user-images.githubusercontent.com/10186522/52844583-29f48900-3105-11e9-9ccd-64eeee6285c5.png)

**Comment by Fruko** [comment]
I did a bit of debugging and it seems that padding-right: 34px is what seem to be breaking it
![image](https://user-images.githubusercontent.com/10186522/52844691-70e27e80-3105-11e9-9e82-282bbe108d6f.png)

**Comment by tmcconechy** [comment]
This is probably an EP issue that can be reproduced by putting a tooltip on a collapsible search field. This is not that common of a case.

**Comment by tmcconechy** [comment]
Descoping this issue for now. Also it may be fixed ?
