### ISSUE TITLE
Soho popdown broken style

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise-ng#361]
**Describe the bug**
Popdown shows duplicated arrows

**To Reproduce**
1. Run ng enterprise project
2. Go to popdown 
3. Click My Cart or States
4. See duplicated arrows

**Expected behavior**
Only one arrow would be shown

**Version**
- ids-enterprise-ng: 5.0.0

**Screenshots**
![image](https://user-images.githubusercontent.com/10186522/52849229-d5efa180-3110-11e9-8daa-589ee66593ea.png)

**Platform**
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name Chrome, IE

**Comment by tmcconechy** [comment]
This was fixed in 4.16 EP already http://master-enterprise.demo.design.infor.com/components/popdown/example-index.html - so should appear ok in 5.1.0 of EP

**Comment by pwpatton** [comment]
5.1.0 of EP-NG right?
