### ISSUE TITLE
SOHO-8028: When setting ngModel for multiselect dropdown to empty array the previous selections still show in the text.

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#37]
As stated in the title, when setting ngModel for multiselect dropdown to empty array the previous selections become unchecked but still show in the text area.

**Comment by tmcconechy** [comment]
@bthharper I may be wrong but did this one have a PR on it? Im not seeing it tho

**Comment by bthharper** [comment]
https://github.com/infor-design/enterprise-ng/pull/22
