### ISSUE TITLE
TrackDirty: no exportAs defined

### ISSUE THREAD

**Issue by mirekrewak** [infor-design/enterprise-ng#378]
**Is your feature request related to a problem? Please describe.**
There is a need to set dirty state of the control programmatically sometimes. For example fileupload-lm. demo needs to have such a call (https://github.com/infor-design/enterprise-ng/blob/c11c249fc2d7e07b33128ba8195129e5da307cd0/src/app/fileupload/fileupload-lm.demo.ts#L61)

SohoTrackDirtyDirective has `changeDirty()` method but accessing it from the code when **directive is used on more components** is not so easy.

**Describe the solution you'd like**
It would help if the directive has `exportAs` defined.

**Describe alternatives you've considered**
Now I need to have in the component:
`@ViewChildren(SohoTrackDirtyDirective) trackDirtyDirectives: QueryList<SohoTrackDirtyDirective>;`
and find the specific directive instance manually.

**Comment by tmcconechy** [comment]
Im not 100% clear on the ask here. Is this something you can make a pull request on for us to review?
