### ISSUE TITLE
FileUpload: change event handler called twice

### ISSUE THREAD

**Issue by mirekrewak** [infor-design/enterprise-ng#379]
**Describe the bug**
Change event is emited twice from the SohoFileUpload after selecting the file.

**To Reproduce**
1. Check 'fileupload' demo
2. Add **change** event handler onUpdated
3. Check the console output
4. There are double console output entries: 'FileUploadDemoComponent.onUpdated'

**Expected behavior**
I'd expect handler would be called once.

**Additional context**
It seems in that Event and JQuery,Event are emitted.
Maybe changing the name of component's output from 'change' to something else not colliding with JQuery could help.

**Comment by tmcconechy** [comment]
Feel free to propose a change on a pull request we can review.

**Comment by tmcconechy** [comment]
Going to descope this issue for now.
