### ISSUE TITLE
SOHO-8001: Easier installation & scaffolding with ng add

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#38]
Angular CLI 6.0 recently added the `ng add` command, which helps with setting up external frameworks/libraries.

Adding SOHO to an Angular project is not exactly trivial, since it requires changes in a number of files (angular.json, index.html, styles.css, tsconfig.json). All of this could be done automatically with `ng add @infor/sohoxi-angular`

See`@angular/material`for example: https://github.com/angular/material2/blob/master/src/lib/schematics/collection.json

**Comment by tmcconechy** [comment]
Descoping this issue for now.
