### ISSUE TITLE
Datagrid cannot expand Tree Node on 2nd page if using paging

### ISSUE THREAD

**Issue by crlang44** [infor-design/enterprise-ng#386]
**Describe the bug**
When using paging on a tree datagrid, on the first page, you are able to expand the node. But on any other pages, when you click to expand a node, the indicator animates as if it should expand but no children rows are shown.

**Expected behavior**
When you click to expand a tree node on the 2nd page of the datagrid, it will show the children nodes.

**Version**
- ids-enterprise-ng: 5.0.0
- ids-enterprise: 4.15.0

**Screenshots**
![image](https://user-images.githubusercontent.com/4143306/54062688-8276ed80-41bc-11e9-9c51-c2a60cac77fb.png)

**Platform**
 - Browser Name: Chrome

**Files**
Place these 2 files in the demo project under datagrid.
[datagrid-paging-service.demo.zip](https://github.com/infor-design/enterprise-ng/files/2947875/datagrid-paging-service.demo.zip)

**Comment by tmcconechy** [comment]
Did you upload the right files here? Im not seeing any tree on http://localhost:4200/ids-enterprise-ng-demo/datagrid-paging-service when i try this out.

I also tested this in 4.16 and 4.17-dev on Enterprise and did not see any issues combining paging and tree. But the version on 5.0.0 is a little older so you could try the 5.10-rc

**Comment by crlang44** [comment]
[datagrid-paging-service.demo.zip](https://github.com/infor-design/enterprise-ng/files/2952967/datagrid-paging-service.demo.zip)

I had attached the wrong files, these should be the correct ones.

**Comment by crlang44** [comment]
We are using ids-enterprise 4.15.0. I don't see 4.16 for that

**Comment by pwpatton** [comment]
The soon to be released 5.1 of enterprise-ng will use the released 4.16 version of enterprise.

**Comment by pwpatton** [comment]
5.1 of enterprise-ng uses 4.15 of enterprise.

**Comment by crlang44** [comment]
@tmcconechy could you provide how you used the tree + paging successfully? That way I can compare to see if we're using it incorrectly somehow.

**Comment by tmcconechy** [comment]
@crlang44 This example shows it working http://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-paging.html (non angular)

**Comment by tmcconechy** [comment]
```
  onRendered(event: SohoDataGridRenderedEvent) {
    const columnString = lscache.get(this.uniqueId + 'columns') ? JSON.stringify(lscache.get(this.uniqueId + 'columns')) : undefined;

    if (columnString && this.sohoDataGridComponent) {
      this.savedColumns = this.sohoDataGridComponent.columnsFromString(columnString);
    }

    this.sohoDataGridComponent.restoreUserSettings({activePage: this.savedActivePage, columns: this.savedColumns,
      rowHeight: this.savedRowHeight, sortOrder: this.savedSortOrder, pagesize: this.savedPagesize, filter: this.savedFilter});
  }
```

Fixes that problem but i do get the error expanding on page 5. It appears as though the tree cache array is not totally built up correctly in 

```
    setExpandedInDataset: function setExpandedInDataset(dataRowIndex, isExpanded) {
      this.settings.treeDepth[dataRowIndex].node.expanded = isExpanded;
    },
```

**Comment by tmcconechy** [comment]
I suspect we will run into this if we had an example in EP with paging (server side) and treegrid.
The example i mentioned above is clientside paging so all the rows are there. Looks like this line is picking up an invalid row...

```
        if (target.is('.datagrid-expand-btn')) {
          rowNode = $(this).closest('tr');
          dataRowIdx = self.dataRowIndex(rowNode);

          self.toggleRowDetail(dataRowIdx);
          self.toggleGroupChildren(rowNode);
          self.toggleChildren(e, dataRowIdx);
          return false; //eslint-disable-line
        }
```

When not all the data is present (just the active page is)

**Comment by crlang44** [comment]
Hi Tim, yes we are using server side paging for our implementation. I take it there may not be an easy fix/workaround for this. Currently we can adjust the first page to show more entries and this will allow more to work correctly.

**Comment by tmcconechy** [comment]
Can you retest this on 4.18 EP? I suspect this may be fixed.

**Comment by tmcconechy** [comment]
I was able to reproduce this in EP, I made a new issue https://github.com/infor-design/enterprise/issues/2132 please watch over there.
