### ISSUE TITLE
Accordion expand state is incorrect on initial load.

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise-ng#389]
**Describe the bug**
Chevron is showing collapsed state with initially expanded panels and when using `[isExpanded]='true`.

![broken](https://user-images.githubusercontent.com/1056684/54134993-f7c60680-43e6-11e9-9b30-b1fd1fd46aca.png)

**To Reproduce**
1. Go to http://localhost:4200/ids-enterprise-ng-demo/accordion

**Expected behavior**
Second panel chevron should point up on load.

**Version**
- ids-enterprise-ng: [5.1.x]

**Platform**
 - Windows 10
 - Chrome

**Additional context**

**Comment by krishollenbeck** [comment]
Yeah they look correct now that I cloned master. Not like the screenshot

**Comment by bthharper** [comment]
I notice that adding new panels to an accordion (Accordion Dynamic Demo) does not work when a new panel is added.  The arrow (on the new Accordion) is incorrect.  This was the issue I was trying to fix originally, but unsuccessfully.

**Comment by krishollenbeck** [comment]
@bthharper I can take a look on my branch. However they don't appear to work at all on master. So I think regardless this is an improvement from the previous state.

**Comment by bthharper** [comment]
@krishollenbeck  totally agree, the changes are for the better, I just wanted to point out the issues with the dynamic example.

**Comment by tmcconechy** [comment]
Marking as done
