### ISSUE TITLE
Context menu with data grid is not properly destroyed.

### ISSUE THREAD

**Issue by Rottosson** [infor-design/enterprise-ng#392]
**Describe the bug**
When using context menu with data grid it is not properly destroyed which potentially could result in it being created multiple times.  If the content in the context menu changes between the creation of new context menus the directive might bring back a context menu that it has previously failed to destroy.

**To Reproduce**
1. Run code below.
2. Right click on both rows to open context menus.
3. Click 'Toggle grid' twice so that grid is destroyed and created.
4. Repeat step 2 and 3 to create new context menus.
5. Open DOM tree to verify that multiple context menus have been created.

**Expected behavior**
Context menus should be destroyed properly.

**Version**

- ids-enterprise-ng: v4.11.0

**Additional context**
```
import { Component } from '@angular/core';

@Component({
  selector: 'documentation',
  templateUrl: './documentation.component.html',
  styleUrls: ['./documentation.component.css']
})
export class DocumentationComponent {
  public show = true;

  public readonly data = [{
    name: 'Adam',
    time: '5'
  },
  {
    name: 'Bob',
    time: '3'
  }];

  public readonly COLUMNS: SohoDataGridColumn[] = [
    { id: 'name', name: 'Name', field: 'name' },
    { id: 'time', name: 'Time', field: 'time' }
  ];

  public toggle(): void {
    this.show = !this.show;
  }

}
```

```

<div *ngIf="show" soho-datagrid [data]="data" [columns]="COLUMNS" [menuId]="contextMenu"></div>

<div #contextMenu>Hello</div>

<button soho-button (click)="toggle()">Toggle grid</button>
```

**Comment by tmcconechy** [comment]
We should make a test in EP with a destroy and invoke on the datagrid and a contextmenu.
Its likely that the destroy code in datagrid just needs to destroy the contextmenu as well if there is one.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datagrid/test-destroy.html
Passed QA testing on all browsers, will retest once beta is deployed.
