### ISSUE TITLE
Expandable area: show ellipsis text and handle Show More Link with non-ellipsis/ellipsis text

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#395]
**Is your feature request related to a problem? Please describe.**
When using expandable area, by default the component: 
- Doesn't provide the possibility to show ellipsis text. If the text is too long, the component just shows the text overflow the container.
- Even if I manage to show ellipsis text, `Show More/Show Less` will need some tricks to toggle full text/ellipsis text

**Describe the solution you'd like**
By default, expandable area: 
- Should show ellipsis text + `Show More` link when the text is too long and overflow the container.
- Shouldn't show `Show More` link when the text is not overflow the container.
- When expandable area shows an ellipsis text with `Show More` link:
      - Clicking on `Show More` link it should display the full text and `Show More` link is replaced with `Show Less`.
      - Clicking on `Show Less` link it should display the ellipsis text again and `Show Less` link is replaced with `Show More`.

**Describe alternatives you've considered**
**N.A.**

**Additional context**
I have 2 screenshots here how it looks like by making a few tricks with expandable area to achieve this.

Show More
![image](https://user-images.githubusercontent.com/27772165/54692302-146be800-4b25-11e9-8cbf-798e3f10926a.png)
Show Less
![image](https://user-images.githubusercontent.com/27772165/54692319-1df55000-4b25-11e9-861f-5159a1125a40.png)

**Comment by tmcconechy** [comment]
Descoping this for now.
