### ISSUE TITLE
Upgrade to NG 8

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#400]
**Is your feature request related to a problem? Please describe.**
Task to upgrade to NG 8, fixing anything thats necessary for that release and documenting what needs to be done for those upgrading.

https://angular.io/guide/releases#release-schedule

**Describe the solution you'd like**
- run ng update
- go through change log and fix anything
- document changes developers need to do

**Additional context**
https://angular.io/guide/releases#release-schedule

**Comment by tmcconechy** [comment]
A branch contains this work for testing https://github.com/infor-design/enterprise-ng/tree/angular-8

**Comment by tmcconechy** [comment]
@bthharper I think we can PR this on master now. Right @pwpatton ?

**Comment by pwpatton** [comment]
@tmcconechy Well, as long as we fix things in 5.5.x until we are ready to switch to NG8.

**Comment by tmcconechy** [comment]
Well we cant fix "everything" but P1/2's can go there.
