### ISSUE TITLE
'visibility' event not fired by soho-application menu

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#402]
**Describe the bug**

The `soho-application-menu` component contains an Output called `visiblity, however this event is not called when the application menu is opened or closed programmatically or by the user.  The component hooks into the expand and collapse events on the jquery element.

Looking at the EP code suggests this functionality does not exist on application menu, in which case the related Output should also be removed from NG.

**To Reproduce**

Add the following to an application-menu component:

```html
<nav soho-application-menu (visibility)="onVisibility($event)">
  <application-menu></application-menu>
</nav>
```

When the menu is opened and closed, the event is not fired.  Changing the event to `menuVisibility` works.

**Expected behavior**

`visibility` should be removed as an Output event from the application-menu component.

**Version**
- ids-enterprise-ng: 5.2.0

**Comment by tmcconechy** [comment]
Descoping this for now
