### ISSUE TITLE
Tabs type incorrect

### ISSUE THREAD

**Issue by darinw** [infor-design/enterprise-ng#409]
The tabs function for `disableTab()` and `enableTab()` are expecting a type of number. It should allow a type of string since it wants the tab name not the index

Go to https://github.com/infor-design/enterprise-ng/blob/e161c9c8435fe30acaee4bdbf0c56d97d55c3d64/projects/ids-enterprise-ng/src/lib/tabs/soho-tabs.d.ts#L63=

**Expected behavior**
should be able to pass in a string.

current work around:
```type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
type Merge<M, N> = Omit<M, Extract<keyof M, keyof N>> & N;
export type SohoTabsComponentOverload = Merge<
  SohoTabsComponent,
  {
    disableTab(tabId: string | number): void;
    enableTab(tabId: string | number): void;
  }
>;
```

to use:
`(this.headerTabComponent as SohoTabsComponentOverload).enableTab('string')`

**Comment by tmcconechy** [comment]
@darinw feel free to do a PR for this. That would really help us out
