### ISSUE TITLE
Custom validation not working for datepicker control

### ISSUE THREAD

**Issue by mdevale** [infor-design/enterprise-ng#411]
**Describe the bug**
Custom validation not working for datepicker control

**To Reproduce**

1. Do the changes as described in additional context
2. Run the project
3. Browse datepicker page
4. Inspect the Custom Validation date-picker control and check data-validate attribute. It is not retaining given 'expiryDateValidator ' custom validator.

**Expected behavior**
It should retain given custom validator.

**Version**
- ids-enterprise-ng: 5.0.0

**Screenshots**
![image](https://user-images.githubusercontent.com/40569892/55488584-f25a8580-564d-11e9-94fa-feaeba0f8d6b.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: chrome, IE, safari
 - Browser Version: Version 72.0.3626.109 (Official Build) (64-bit)

**Additional context**
1. Put below code in datepicker.demo.html file

```
<div class="row">
    <div class="four columns">
      <div class="field">
        <label for="customValidation" class="label">Custom Validation</label>
        <input soho-datepicker name="customValidation" id="customValidation" data-validate="expiryDateValidator" data-options="{'customValidation': 'true'}" />
      </div>
    </div>
  </div>
```

2. Put below code in datepicker.demo.ts file
```
  ngOnInit() {
     this.registerExpiryDateValidator();
   }

  registerExpiryDateValidator() {
    $.fn['validation']['rules']['expiryDateValidator'] = {
      check: function (value, field, grid) {
        if (new Date(value) <= new Date()) {
          return false;
        }
        return true;
      },
      id: 'custom',
      type: 'error',
      message: 'Invalid_Expiry_Date'
    };
  }

  expiryDateValidator(control: AbstractControl): { [key: string]: any }  {
    return (control.value !== undefined && new Date(control.value) <= new Date()) ? ['Error'] : null;
  }
```

**Comment by tmcconechy** [comment]
Added two prs to fix this. Solution was simple but there is no workarounds i can think of.

https://github.com/infor-design/enterprise-ng/pull/417
https://github.com/infor-design/enterprise/pull/1926/files
