### ISSUE TITLE
Datagrid: Expose the method 'resetColumns'

### ISSUE THREAD

**Issue by tomjohn9** [infor-design/enterprise-ng#413]
**Is your feature request related to a problem? Please describe.**
The method for datagrid `resetColumns()` is not exposed in enterprise-ng datagrid library

**Describe the solution you'd like**
The method `resetColumns()` on `SohoDataGridComponent`

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by EdwardCoyle** [comment]
Attaching some context from [MS Teams](https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1554297843058?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1554297843058&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=General&createdTime=1554297843058)

**Comment by bthharper** [comment]
I think this can be closed?
