### ISSUE TITLE
Error if a popup-menu option is removed/re-rendered when clicked

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise-ng#414]
**Description**
If removing a popup menu option when clicking it, a console error is shown. When trying to open the menu after this error, it will not open until clicking twice. After that, the menu works fine again.

```
<ul soho-popupmenu id="charts-menu">
   <li soho-popupmenu-item><a soho-popupmenu-label>Pie Chart</a></li>
   <li soho-popupmenu-item><a soho-popupmenu-label>Line Chart</a></li>
   <li soho-popupmenu-item><a soho-popupmenu-label>Bubble Chart</a></li>
   <li soho-popupmenu-item *ngIf="showLastOption"><a soho-popupmenu-label (click)="showLastOption = !showLastOption">Click this to remove myself</a></li>
</ul>

```
The problem will also occur if the options are rendered using an *ngFor that gets re-evaluated after a click for some reason. Example below makes no sense, but it demonstrates the issue

```
<ul soho-popupmenu id="charts-menu">
   <li soho-popupmenu-item *ngFor="let option of options"><a soho-popupmenu-label (click)="evaluateOptions()">{{option.label}}</a></li>
</ul>

evaluateOptions() {
    this.options = [ ...this.options ];
  }
```

Gif of issue:
![popupmenu-issue](https://user-images.githubusercontent.com/1101770/55565330-ed531000-56f9-11e9-805b-8754ec14f80c.gif)

**To Reproduce**
1. Change the charts-menu template to first example here, in app/menu-button/menu-button.demo.html (and add the showLastOption boolean to component)
2. Run sample at http://localhost:4200/ids-enterprise-ng-demo/menu-button
3. Open the charts menu and click last option
4. See error in console
5. Try to re-open menu 

**Expected behavior**
No console error and menu can be reopened with a single click

**Version**
- ids-enterprise-ng: v.5.2.0 

(I'm not sure whether this issue occurs in the core controls too or not)

**Comment by janahintal** [comment]
Hi @tmcconechy may I know where can we test this ticket? Thanks

**Comment by tmcconechy** [comment]
Sorry you cannot test this one its in Angualr only. Will just move to done.
