### ISSUE TITLE
SohoTreeComponent - After deselecting the leaf node it's parent node remains partially selected. 

### ISSUE THREAD

**Issue by jpatil2** [infor-design/enterprise-ng#415]
**Describe the bug**
In IE 11 , In tree control if  any Leaf node is selected then it's parent node gets partially selected. Then after deselecting the Leaf node , it's parent node remains partially selected instead of it should not be partially selected.

**To Reproduce**
1. Make tree multi-select and show checkbox for all nodes as mentioned in additional context  
2. Browse this project on IE browser
3. Browse this page http://localhost:4200/ids-enterprise-ng-demo/tree-source
4. Expand node named 'Node 1'
5. Select leaf node named 'Leaf 3' then it's parent node 'Node 1' gets partially selected.
6.  Then deselect node 'Leaf 3', then also it's parent node remains partially selected.

**Expected behavior**
Parent node should not remain partially selected.

**Version**
- ids-enterprise-ng: v5.0.0

**Screenshots**
After selecting leaf node
![image](https://user-images.githubusercontent.com/49273918/55606570-eb8b5a00-5796-11e9-953e-41577ed82512.png)

After deselecting leaf node
![image](https://user-images.githubusercontent.com/49273918/55606622-22617000-5797-11e9-9675-32feabb8f367.png)

**Platform**
 - OS Version:  Windows 10
 - Browser Name: IE
 - Browser Version: 11.1029.16299.0

**Additional context**
To make tree selectable, put below code in 'src\app\tree\tree-source.demo.ts'
`  ngOnInit() {
    this.tree.options = { hideCheckboxes: false, selectable: 'multiple' };
  }`

**Comment by tmcconechy** [comment]
Does not see that this can be reproduced on http://latest-enterprise.demo.design.infor.com/components/tree/example-select-multiple.html

**Comment by jpatil2** [comment]
Checked with the link given in **IE**  (http://latest-enterprise.demo.design.infor.com/components/tree/example-select-multiple.html) and observed the same issue. check attached screenshot for the same.

![image](https://user-images.githubusercontent.com/49273918/55732730-22cd6580-5a3a-11e9-8460-4efdd9e9ed25.png)

**Comment by tmcconechy** [comment]
Ok so only IE then? I was testing other browsers.

**Comment by tmcconechy** [comment]
Descoping this issue for now as its minor. See https://github.com/infor-design/enterprise/issues/3756 for details
