### ISSUE TITLE
SOHO-7944: sohoxi-angular library should not include .spec.ts files

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#42]
I recognized that in sohoxi-angular, there are some test files (.spec.ts) included in the package. This will increase the bundle size and the download size of the whole package. Test files should be excluded from npm publish.

*Expectation*:
there should be no test files in sohoxi-angular package.

**Comment by AhnpGit** [comment]
so now I think instead of creating JIRA on SOHO board, I'll just create issues here ? 👍

**Comment by tmcconechy** [comment]
We are moving to migrate all issues to github but started with just the angular ones so we can get more contributions and eyes on them. So for now

- Angular issue -> can create here
- Core code issue -> still user Jira
- Not sure which -> still user Jira

We will migrate core code (https://github.com/infor-design/enterprise) eventually but there are too many issues in the backlog now so we need to take care of some of them before we make the switch.

**Comment by bthharper** [comment]
@clepore  We close this now?
