### ISSUE TITLE
Bar chart labels break chart when too long

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise-ng#422]
**Describe the bug**
When a long label is used inside bar chart it breaks the chart and chart becomes unusable

**To Reproduce**
1. Open bar.demo.ts inside demo enterprise-ng application
2. Change data name from 'Category A' to something much longer
3. See error

**Expected behavior**
Tooltip and elipsis should be added when necessary

**Version**
- ids-enterprise-ng: 5.1.0

**Screenshots**
![image](https://user-images.githubusercontent.com/10186522/55888389-8e850f00-5baf-11e9-94d5-5be754144850.png)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Can this be reproduced in https://github.com/infor-design/enterprise ?

**Comment by tmcconechy** [comment]
I think we addressed this on a separate issue you can see it here:

https://master-enterprise.demo.design.infor.com/components/bar/example-long-text.html

and

https://master-enterprise.demo.design.infor.com/components/bar/test-axis-y.html
