### ISSUE TITLE
Security: npm install enterprise-ng resolves in a few vulnerable security issues

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#426]
**Describe the bug**
There are 7 vulnerabilities when installing dependencies for enterprise-ng project, 3 low, 2 moderate and 2 high. 

**To Reproduce**
1. Clone enterprise-ng project
2. Run npm install
3. Observe in the console

**Expected behavior**
enterprise-ng project shouldn't have high vulnerabilities, I think the best is there should be no moderate and above vulnerabilities, low is acceptable.

**Version**
- ids-enterprise-ng: master branch

**Screenshots**
![image](https://user-images.githubusercontent.com/27772165/55936355-5674df00-5c36-11e9-9aad-3e481f14bf80.png)

**Platform**
 - Device **N.A.**
 - OS Version: Windows 10
 - Browser Name **N.A.**
 - Browser Version **N.A.**

**Additional context**
**N.A.**

**Comment by tmcconechy** [comment]
I've tried to look at these but the problem is that mostly they are in other dependencies we dont manage. So just have to wait for someone else to fix them or report this in the dependencies that have a problem.

**Comment by tmcconechy** [comment]
Might be a couple we can update actually.

```
added 7 packages from 2 contributors, removed 9 packages and updated 25 packages in 17.887s
fixed 7 of 9 vulnerabilities in 56323 scanned packages
  2 package updates for 2 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
```

**Comment by tmcconechy** [comment]
There is a couple things we can update to reduce the counts. I'll do a quick PR. But some of the things are out of our control as you stated.

**Comment by tmcconechy** [comment]
Closing this for now as most is out of our control. But we will update #858 soon and then "could" fix somethings
