### ISSUE TITLE
Add `ids-enterprise-ng` version to page body

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#429]
**Is your feature request related to a problem? Please describe.**

To help determine the **ids-enterprise-ng** version an application is compiled with, the current version should be added to the page body, like the **ids-enterprise** version currently is.

**Describe the solution you'd like**

The result should be as follows:

```html
<html data-ids-enterprise-ng-version="5.2.1" data-sohoxi-version="4.17.1" ...>
...
</html>
```

The implementation for this could be done as an **APP_INITIALIZER** that modifies the body of the application on start.

**Describe alternatives you've considered**

**Additional context**

**Comment by bthharper** [comment]
@tmcconechy  @pwpatton  I've added code to set the version, however getting the version dynamically (from package.json) is proving problematic due to the way the enterprise ng component are packaged.

Any suggestions?

```typescript

// @todo unable to load the version from a file not included as a module in the package.
// const version = require('../../../../package.json').version;
// const version = process.env.npm_package_version;
const version = '5.2.1';
```

**Comment by tmcconechy** [comment]
@bthharper did you try setting resolveJsonModule and using import like https://stackoverflow.com/a/50674344 ?
