### ISSUE TITLE
SOHO-7925: SohoInputValidateDirective does not work on static validation value

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#43]
SohoInputValidateDirective stop validation working for static value, for example,
if it is 
{code:java}
data-validate='required', 
{code}
it won't work, and it only works for 
{code:java}
[data-validate]="'required'".
{code}

**Comment by tmcconechy** [comment]
Merged fix on https://github.com/infor-design/enterprise-ng/pull/10
