### ISSUE TITLE
Accessibility - Modals Have the Wrong Role

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#432]
**Describe the bug**
The modal in NG has the wrong role.

**To Reproduce**
1. Go to http://localhost:4200/modal 
2. Click on modal to open
3. Inspect the DOM
4. You will see `role="alertdialog"` this is only valid for messages not on modals. 
5. http://latest-enterprise.demo.design.infor.com/components/modal/example-index.html

**Expected behavior**
Should have the correct role in this case. Something is wrong in the wrapper.

- [x] Add an Axe check for correct accessibility roles - this isnt possible.  - The role is valid but the context is wrong.

**See also**
https://jira.lawson.com/browse/LMCLIENT-24206

**Comment by bthharper** [comment]
@tmcconechy - this is a demo issue, where the alert flag is being set on the dialog (erroneously).

I suggest we change `isAlert` to false in the demo.

```typescript
const dialogRef = this.modalService
      .modal<ExampleModalDialogComponent>(ExampleModalDialogComponent, this.placeholder)
      .buttons([
        { id: 'cancel-button',
          text: Soho.Locale.translate('Cancel'),
          click: (e, modal) => { modal.isCancelled = true; dialogRef.close('CANCEL'); } },
        {
          text: 'Submit', click: (e, modal) => {
            dialogRef.close('SUBMIT');
          }, isDefault: true
        }])
      .title(this.title)
      .isAlert(this.isAlert)
      .apply((dialogComponent) => { dialogComponent.model.header = 'Header Text Update!!'; })
      .open();

    // Attach a listener to the afterClose event, which also gives you the result - if available.
    dialogRef.afterClose((result, ref, dialogComponent) => {
      console.log(dialogComponent.model);
      this.closeResult = result;
    });
```

**Comment by tmcconechy** [comment]
Added as there is a PR to address this here https://github.com/infor-design/enterprise-ng/pull/438

**Comment by tmcconechy** [comment]
Does this PR solve this? https://github.com/infor-design/enterprise-ng/pull/438/files#diff-835bb092c37e3 or does the demo still need to be updated?

**Comment by clepore** [comment]
Closing, as this is related to NG
