### ISSUE TITLE
Ability to get the anchor for the expanded app-menu accordion 

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise-ng#434]
**Describe the bug**
Need ability to get the anchor for the expanded app-menu accordion so we can lazy load the correct items into the accordion menu

**Comment by tmcconechy** [comment]
@pwpatton did you do this one?

**Comment by pwpatton** [comment]
@vonnyw does this one work?

**Comment by vonnyw** [comment]
Yes, we added an event which passes the anchor element back.
