### ISSUE TITLE
Breaking change with soho-icons-ext in 5.2.1 comparing to 5.1.1 shouldn't be in minor release

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#436]
**Describe the bug**
Upgrading to 5.2.1 from 5.1.1 resolves in failed build due to `soho-icons-ext` no longer exists. This is a breaking change and it shouldn't be introduced in minor release according to sem version convention.

**To Reproduce**
1. Use an app with 5.1.1 `ids-enterprise-ng`
2. Declare `<soho-icons-ext></soho-icons-ext>` in `app.component.html`
3. Upgrade `ids-enterprise-ng` to 5.2.1
4. Start dev server (or run prod build) and see errors (IDE will notice as well).

**Expected behavior**
`soho-icons-ext` shouldn't be removed in a minor release version. Removing this component is a breaking change and it should be in major release version.

**Version**
- ids-enterprise-ng: 5.2.1

**Screenshots**
**N.A.**

**Platform**
 - Device **N.A.**
 - OS Version: Windows 10
 - Browser Name **[e.g. chrome, safari, stock browser]**
 - Browser Version **[e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]**

**Additional context**
Does `ids-enterprise-ng` follow sem version convention ?

**Comment by bthharper** [comment]
`soho-icons-ext` was removed as the icons were consolidated in the enterprise controls.  

Leaving an obsolete `soho-icons-ext` would have been sensible in this case to avoid this issue.

@tmcconechy do we fix this?

**Comment by tmcconechy** [comment]
We try to use semantic versioning but this was missed.

So, Yeah i agree. Its what we did in EP (leave an empty soho-icons-ext). We cant change the version number its too late. But we can fix this for 5.3.0 by adding the empty soho-icons-ext back in with just a comment. And then noting it in the change.log if not already there.

That we we can keep the semantic versioning going.

**Comment by ahnpnl** [comment]
or maybe a quick fix with 5.2.2 which is created from branch or tag 5.2.1 ?
