### ISSUE TITLE
[Feature request]: Allow specifying a fill color for svg of soho-button="icon", soho-icon

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#440]
**Is your feature request related to a problem? Please describe.**
In some cases it is required to display an icon with a specific fill color. There are no properties in `soho-button` and `soho-icon` to allow this.

**Describe the solution you'd like**
A new property which allows to pass in fill color for `soho-button` and `soho-icon` and these components will change the fill color of svg icon accordingly

**Describe alternatives you've considered**
For `soho-icon`, it is possible to set fill color for svg by using css with default encapsulation level of the component.
For `soho-button`, this has to be done on the root by loading css with Angular CLI via `stylePreprocessorOptions`

**Additional context**
**N.A.**

**Comment by tmcconechy** [comment]
What’s the use case of changing the color? Is it involving any hex or just our color pallette?
Also now with the new icons generated from sketch the property would be color not fill now.

I do have a pending pull request in ep where I added classes of amber02–color which you can add on. This might be enough but it means only pallets colors may be used.

I also prefer the classes only as this will involve no unsafe-inline css as we want to pas CSP. So perhaps just use the classes setting a color and only allow the palette?

**Comment by ahnpnl** [comment]
![image](https://user-images.githubusercontent.com/27772165/56353521-d7514f00-61d1-11e9-9f69-c56039ba3cb7.png)
I have this case. Adding class like `ember02-color` looks fine, but it won't be flexible indeed like you said. Only allow the palette seems to be not really nice in my opinion.

**Comment by tmcconechy** [comment]
Is that button separate from the link? If it is you can try to put it in the link like https://master-enterprise.demo.design.infor.com/components/hyperlinks/example-index.html

If it isn’t you can try to add class “hyperlink”. Not sure if that works 100%

If we do add anything for this it might need to be on the EP side. 

But I think the negatives with any hex values are:
- you will be able to not follow the design colors
- also we do dynamically change colors in different themes so the hex will be incorrect if you change themes and might not match the links
- Also you may have to use unsafe-inline and CSP won’t be possible (can be done if the code uses css dom not inline string). 

So in my opinion if the use case is only this then I think the class is probably best and easiest.

**Comment by tmcconechy** [comment]
Yeah I think that’s good, just ability to pass an extra class.
