### ISSUE TITLE
Setting svg icon color by CSS fill property is broken with 5.1.1

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#441]
**Describe the bug**
In 5.0.0, it is possible to set svg icon color by using CSS `fill` property. This is not possible anymore in 5.1.1

**To Reproduce**
1. Go to example app in `enterprise-ng` repo
2. Switch to branch **5.0.x**
3. Go to `icon.demo.ts`, create a scss file called `icon.demo.scss` and define it in metadata of `icon.demo.ts`. 
4. Add this styling in `icon.demo.scss`
```
svg {
  fill: red;
}
```
5. See that the icons in `Icons-Tree` section is red.
6. Repeat the same steps above but with branch **5.1.x** and those icons are not red anymore.

**Expected behavior**
Setting color for svg with CSS `fill` property should be possible

**Version**
- ids-enterprise-ng: 5.1.1

**Screenshots**
**N.A.**

**Platform**
 - Device **N.A.**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 73.0.3683.103 (Official Build) (64-bit)

**Additional context**
**WORKAROUND**: to make it work again, it is required to switch to use `color` CSS property instead of `fill` CSS property.

**Comment by tmcconechy** [comment]
It’s not a workaround you have to use color and not fill as the icons have been reconstructed. But that should be a problem. I would just make that change.

We didn’t actually support this in the first place, but I think the other ticket is a fine idea. Suggest closing this as we won’t be able to change the icons back as they are now generated.
