### ISSUE TITLE
SOHO-7902: List view setter of selected items is unselecting items in the list

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#45]
Summary: When using {{SohoListViewComponent.selectedItems}} setter method while there are already some items selected, those items are {{unselected}}

How to reproduce:
1. Have list-view with item selected on indices e.g. [0,1]
2. Call {{SohoListViewComponent.selectedItems = [0,1,3]}}

Expected result:
Items on indices 0,1,3 are selected

Actual result: 
Items on indices  0 and 1 are unselected

Note:
I was able to narrow down the issue to this method in {{SohoListViewComponent}}:

```
  select(index: SohoListViewItemReference | SohoListViewItemReference[]): void {
    this.apply((e) => this.listview.select(e), index);
  }
```

This method uses `this.listview.select`, but the name is misleading as the method actually does a "toggle" action. Switching the state between selected and unselected. Thus also the `selecteItems` setter does a "toggle" for all passed indices. (see attachment)

**Comment by theakatz** [comment]
![selected_items_setter](https://user-images.githubusercontent.com/34137133/40804380-170a7e96-64e9-11e8-811e-182c6913c32e.png)

**Comment by tmcconechy** [comment]
Descoping this issue for now. Not enough time and this is very old
