### ISSUE TITLE
[Feature request]: expose API to listen to closed search field event for SohoToolbarFlexSearchFieldComponent

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#459]
**Is your feature request related to a problem? Please describe.**
When using `soho-toolbar-flex` on a small device, there is a button to close search field when user focuses on search field. However, there is no event attach to this button so there is no way to perform logic on closing toolbar search field. 

Example use case:
- User types _"foo"_ => search result shows for user
- User clicks on close search field button
- We want to revert search result to original result before user types _"foo"_

**Describe the solution you'd like**
A new exposed API to listen to close search field event when clicking on button which closes toolbar search field

**Describe alternatives you've considered**
Alternately I can use input `change` event like this and listen to this change event. However it might be not consistent as it may only fire the event if the value of the input field is changed.
![image](https://user-images.githubusercontent.com/27772165/57021601-fec20600-6c2c-11e9-811a-304c4522b0da.png)

**Additional context**
**N.A.**

**Comment by tmcconechy** [comment]
Can you retest this on the latest if still needed. I "think" this might work ok now. The cleared event and the change event will omit
