### ISSUE TITLE
SOHO-7816: [SohoDropDownComponent] SelectAll makes the browser frozen when the data of the dropdown is too large

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#46]
If the data of the dropdown is too large, when clicking on select all option of the dropdown, it completely freezes the browser.

*Current setup*: I'm using dropdown multiselect with option [closeOnSelect]="false" and also with soho-tooltip on it.

*Expected behavior*
The dropdown should behave performantly when the data is too large.
I include an attachment of the data I'm using for the dropdown.

*Additional*
- only is REALLY bad clicking the checkbox vs the label.

**Comment by tmcconechy** [comment]
Closing as has a PR and issue in Jira https://jira.infor.com/browse/SOHO-7816
