### ISSUE TITLE
Notification - Provide a TypeScript support

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise-ng#461]
**Is your feature request related to a problem? Please describe.**
Most of the designs created by the UX needs notification component in Homepages widget. The SDK uses the updated version of IDS 4.17.1 so the controller is available, but the typings is not.

**Describe the solution you'd like**
Provide a notification component typings.

**Comment by tmcconechy** [comment]
Probably do this as a service similar to the toast code https://github.com/infor-design/enterprise-ng/tree/master/projects/ids-enterprise-ng/src/lib/toast
