### ISSUE TITLE
Listview: Search not working the same as EP

### ISSUE THREAD

**Issue by JestoniFajardo** [infor-design/enterprise-ng#466]
**Listview search feature**
Issue on list view search feature which doesn't filter the searched item on the list.

**To Reproduce**
1. Implement regular listview component
2. Apply searchable feature
3. Search an item
4. Item list are not filtered based on the search string

**Expected behavior**
Should filter the list item based on searched string and enhance the highlight feature

**Version**
- ids-enterprise-ng: [v5.2.1]

**Screenshots**
![image](https://user-images.githubusercontent.com/42030487/57273935-1cc7b480-70cc-11e9-94d6-d0aa104fefe9.png)

**Platform**
 - Version 74.0.3729.131 (Official Build) (64-bit)

@tmcconechy , @bthharper

**Comment by pwpatton** [comment]
@JestoniFajardo Are you using an angular template for the rows or are you passing in a javascripty template and data structure to the EP control? 

If the former then the search doesn't know anything about the data and hence cannot search it (@tmcconechy ?).

**Comment by tmcconechy** [comment]
If something needs to be added here it would be an EP feature but i cant reproduce this. If i go to http://master-enterprise.demo.design.infor.com/components/listview/example-search.html and type "purchase order" it filters out the elements that dont match and highlights. Which i think is the correct and desired behavior.

What would "enhance" the highlight feature again?

**Comment by tmcconechy** [comment]
But i am not seeing it working on http://localhost:4200/ids-enterprise-ng-demo/listview so must be an EP bug?

**Comment by pwpatton** [comment]
@tmcconechy that content is projected via the angular template. I don't see how the EP listview can filter that when it's angular managing the content. I think it's going to be up to the implementor of this to manage their own filtering (if they want to project content with ng templates).
```
    <div class="card">
      <div class="card-header">
        <h2 class="card-title">Tasks - Searchable</h2>
      </div>
      <div class="card-content" style="overflow: hidden;">
        <soho-listview
          [class]="'something-extra'"
          [dataset]="demoTasks"
          [searchable]="true"
          selectable="multiple"
          (rendered)="onRendered($event)"
          (selected)="onSelected($event)"
          (sorted)="onSorted($event)"
        >
          <input soho-searchfield placeholder="Search" [clearable]="true">
          <soho-toolbar class="contextual-toolbar is-hidden">
            <soho-toolbar-button-set>
              <button soho-button="tertiary" title="Assign Selected Items">Assign</button>
              <button soho-button="tertiary" title="Remove Selected Items">Remove</button>
            </soho-toolbar-button-set>
          </soho-toolbar>
          <li soho-listview-item *ngFor="let data of demoTasks" [disabled]="data.disabled">
            <p soho-listview-header>Task #{{data.task}}</p>
            <p soho-listview-subheader>{{data.desc}}</p>
            <p soho-listview-micro>DUE: {{data.date}}</p>
          </li>
        </soho-listview>
      </div>
    </div>
```

**Comment by tmcconechy** [comment]
Seems like its not getting these options: `listFilterSettings: {filterMode: "contains", searchableTextCallback: ƒ}`

**Comment by pwpatton** [comment]
That still won't work for NG projected content as when the soho-listview refreshes the view it will just run through the ng components list of items to create the template. To filter that list of items the NG implementor would need to filter down that listview dataset in the angular component. Does that make sense?

I think we need a disableClientSide filtering and have an event for it `(filtered)="onFiltered($event)"`.

```
        <soho-listview
          [class]="'something-extra'"
          [dataset]="demoTasks"
          [searchable]="true"
          selectable="multiple"
          (rendered)="onRendered($event)"
          (selected)="onSelected($event)"
          (sorted)="onSorted($event)"
          (filtered)="onFiltered($event)
        >
```

Then in the event the demo component internal list of items could be filtered down.

**Comment by pwpatton** [comment]
But this is ONLY for projected content. A user can still pass in a javascript template and [dataset] and the listview.js will work naturally.

**Comment by tmcconechy** [comment]
Not sure, why wouldnt that option work?

**Comment by pwpatton** [comment]
because we have 2 things attempting to place content into the listview. First the listview.js filtering then the angular template. With a javascript template, it's only listview.js managing what the user sees based on filtering.

**Comment by tmcconechy** [comment]
OK, makes this tricky then...I think. But the option has a callback https://github.com/infor-design/enterprise/blob/master/src/components/listfilter/listfilter.js#L19 i wonder what exactly happens

**Comment by pwpatton** [comment]
Probably worth trying it out just to see forsure.

**Comment by tmcconechy** [comment]
I made a branch and added the types so was able to get the options to pass in correctly https://github.com/infor-design/enterprise-ng/tree/466-listview-search but as you said its not working. At first i thought it might because its filtering against the dataset not the items in the template. So you think it would. But this issue might take a bit of time to figure out. Made it a 5 level.

**Comment by lipetzan** [comment]
This recently got labeled properly and isn't in a sprint plan, just an FYI to all.  This issue prevents users from filtering a list of conditions while personalizing their lists or reports.  This is important because there can be 100's of conditions to scroll through and not having filter working is like, a major drag man.

**Comment by tmcconechy** [comment]
Not really that acceptable but as a workaround you could use the listview templates then i think search would work. Rather than the content projection. This one may be a tough one to fix and might take several 3-4 days to figure out. But pretty sure it is an EP issue and is up for garbs.

**Comment by pwpatton** [comment]
@lipetzan perhaps we should use the ep/javascript templates for showing the conditions and just use client side filtering there.

**Comment by lipetzan** [comment]
4.21x+ is ok @tmcconechy

**Comment by tmcconechy** [comment]
Or perhaps you can use the event on the search box and manually filter the list or do a server side filter op?
