### ISSUE TITLE
[ng Modal dialog] option to disable buttons

### ISSUE THREAD

**Issue by JestoniFajardo** [infor-design/enterprise-ng#467]
**Current behavior**
On the current behavior, buttons can define on initializing of modal, can apply `click` callback event, setting a `text` and `default`

**Acceptance Criteria**
Looking for modal option that can control the behavior(disable/enable) buttons and applicable on runtime changes.

**Describe alternatives you've considered**
A property option to be assigned on the when defining buttons
```javascript
const buttonSave = { // defining modal buttons 
    isDisabled: true/false, // boolean property
    text: ...,
    click: ...,
    isDefault: ...
}
modalInstance.buttons(buttonSave); // assigning modal buttons
```

**Sample Screenshots**
![image](https://user-images.githubusercontent.com/42030487/57276833-45a07780-70d5-11e9-814a-e16153e5ec13.png)

cc: @tmcconechy, @bthharper

**Comment by bthharper** [comment]
@tmcconechy - can you specify an id for the buttons?, then they can be queried?  If do then the standard API on the EP controls would work.  As for exposing them in NG, that would be more tricky.

**Comment by tmcconechy** [comment]
Yes, would have to expose them on the EP side. I'll take a look when i get a chance.

**Comment by fitzorama** [comment]
Landmark needs this as well. A feature we would especially like is getting a collection of the buttons and having a standard api for enabling and disabling them.

**Comment by tmcconechy** [comment]
To add to this it should be possible to pass more attributes in to the button collection if this lein was changed you could pass `disabled: true` to the button list on the component.

https://github.com/infor-design/enterprise/blob/master/src/components/modal/modal.js#L466

Suggest doing this in addition to an API to get to the buttons.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done column.
