### ISSUE TITLE
Confirm icon is offset and without green color anymore

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise-ng#476]
**Describe the bug**
Confirm icon is not aligned with others and without green color anymore

**To Reproduce**
1. Demopage icons -> scroll to bottom

**Expected behavior**
Confirm Icon should be aligned with others and in green

**Version**
- ids-enterprise-ng: 5.2.1

**Screenshots**
![image](https://user-images.githubusercontent.com/11279863/57611978-3fe2e000-7574-11e9-9de6-55ec99d36e08.png)

**Platform**
 - Windows 10
 - Name Chrome
 - Version 74.0.3729.131 (Official Build) (64-bit)

**Comment by hohnzy** [comment]
just noticed confirm changed to success

**Comment by tmcconechy** [comment]
Yes thats right, we tried to change it's name without any breaking chnage but later found out some situations it would need to be renamed. Documented here: https://github.com/infor-design/enterprise/blob/master/docs/CHANGELOG.md#v4150-fixes

**Comment by tmcconechy** [comment]
Also i found you can change the color by just putting the icon in a link...

```
    <a href="#" class="hyperlink hide-focus">
      <svg role="presentation" aria-hidden="true" focusable="false" class="icon">
        <use xlink:href="#icon-launch"/>
      </svg>
    </a>
```
