### ISSUE TITLE
SOHO-7766: Add More Soho Types.

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#48]
Carying on from http://git.infor.com/projects/SOHO/repos/angular-components/pull-requests/623/overview

Some types should be add to angular like

- [ ] Soho.string.stripHTML (and any white list security functions)
- [ ] Personalize Colors / Set theme
- [ ] resetForm (and any missing Validation functions)
- [X] Soho.Locale - functions like parseDate ect

**Comment by tmcconechy** [comment]
Part of this done on https://github.com/infor-design/enterprise-ng/pull/124#issuecomment-402163055

**Comment by tmcconechy** [comment]
Descoping this issue for now.
