### ISSUE TITLE
Promise returned when setting a locale can be called before locale loaded

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#485]
**Describe the bug**

The angular applications often sets the locale required in an APP_INITIALIZER (see the demo application)

However, sometimes the current locale is still `en-US` in the `then` method.

There seems to be an intermittent problem, as it depends on whether the default locale is in the process of being loaded when the required locale is set and therefore completes before it.

This is more noticeable when the processing takes place in the done method which increase the timing window where the issue can occur.

**To Reproduce**

As this issue is intermittent the problem can be difficult to replicate.

**Expected behavior**

The promise returned from `Soho.Locale.set` should only fire when the `locale` requested is loaded.

**Version**
- ids-enterprise-ng:  5.3.0

**Screenshots**

**Platform**

**Additional context**

**Comment by bthharper** [comment]
The workaround to load the `en-US` locale first then the required locale seems to work, but it may be worth investigating this further.

```typescript
await Soho.Locale.set('en-US')
  .then(async () => {
    await Soho.Locale.set(this.locale)
      .then(() => {
        ...
    });
});

**Comment by tmcconechy** [comment]
I suspect i fixed this on https://github.com/infor-design/enterprise/pull/2238 as the promises are now return directly on the locale in an array

**Comment by tmcconechy** [comment]
Descoping this - but will rework it for 5.0
