### ISSUE TITLE
XSS in soho-autocomplete

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-ng#502]
**Describe the bug**
Script tags that are in a `soho-autocomplete` search result are executed when searching for the tag. This happens with and without a custom template.

**To Reproduce**
Given the following component:
```html
<div class="field">
  <label soho-label>Model: {{selected}}</label>
  <input soho-autocomplete [source]="source" filterMode="contains" [(ngModel)]="selected" placeholder="Search for <script">
</div>
```
```typescript
@Component({
  selector: 'app-autocomplete-xss',
  templateUrl: './autocomplete-xss.component.html',
  styleUrls: ['./autocomplete-xss.component.css']
})
export class AutocompleteXssComponent {

  selected: string;
  source: SohoAutoCompleteSource = [
    'Hello',
    'World',
    '<script>alert(1)</script>xss'
  ];
}
```
1. Enter the `<` character in the search field
2. Script is executed here

**Expected behavior**
The script is not executed in Step#2

**Version**
- ids-enterprise-ng: v5.2.1 

**Platform**
Tested in Chrome on Windows & Safari on MacOS.

**Additional context**
Repro: https://anhallbe.github.io/ids-repro/autocomplete-xss though I'm having some issues with deploying on GH Pages.

Source code here: https://github.com/anhallbe/ids-repro/tree/master/src/app/autocomplete-xss

The problem only occurs when searching for the script tag, e.g `<script`. It does not occur when searching for the other contents of the `source`. Possibly related to result highlighting?

**Comment by tmcconechy** [comment]
Did you try to reproduce this in EP by updating this example? https://github.com/infor-design/enterprise/blob/master/app/views/components/autocomplete/test-xss-security.html i was playing around with it but cant seem to reproduce this. That would make this issue easier to resolve as this should be a core EP issue I would think.

**Comment by anhallbe** [comment]
I can't reproduce it in EP, at least not with a similar autocomplete source.

**Comment by tmcconechy** [comment]
I’m also trying the same. So far no luck but not giving up yet. I do have it reproducible in NG.

If we do need to patch an NG I guess that would be a 5.3.1 since 5.3 runs 4.18.1. But still checking on where it would be solved

**Comment by anhallbe** [comment]
I just tested with a similar source to your dropdown example in the other ticket. See edited comment above

**Comment by tmcconechy** [comment]
Where you able to get this to run in the EP sample app? i keep getting "Uncaught SyntaxError: Invalid or unexpected token"

**Comment by tmcconechy** [comment]
Got it! Working on a fix

**Comment by janahintal** [comment]
QA Passed. Will move to Done.
Tested in:
https://master-enterprise.demo.design.infor.com/components/modal/test-xss.html
https://master-enterprise.demo.design.infor.com/components/dropdown/test-xss.html
https://master-enterprise.demo.design.infor.com/components/autocomplete/test-xss-security.html
