### ISSUE TITLE
XSS in soho-dropdown

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-ng#503]
**Describe the bug**
Clicking an entry with a <script> tag in a dropdown causes the script to execute. This only seem to happen when using `ids-enterprise-ng@5.2.1` and `ids-enterprise@4.18.1`.

**To Reproduce**
Given the followin component:
```html
<select soho-dropdown [(ngModel)]="selected">
  <option *ngFor="let option of options" [value]="option">{{option}}</option>
</select>
```
```typescript
@Component({
  selector: 'app-dropdown-xss',
  templateUrl: './dropdown-xss.component.html',
  styleUrls: ['./dropdown-xss.component.css']
})
export class DropdownXssComponent {
  selected = 'Hello';
  options = [
    'Hello',
    `<script>window.alert('dropdown xss')</script>XSS`,
    'World',
  ];
}
```
1. Open the dropdown
2. Click the entry with XSS
3. Script executes

**Expected behavior**
The script should not execute.

**Version**
- ids-enterprise-ng: 5.2.1
- ids-enterprise: 4.18.1

**Platform**
 Tested in Chrome on Windows.

**Additional context**
This only happens when `ids-enterprise@4.18.1` is installed, i.e not the bundled 4.17.1.
There might be other XSS vulnerabilities in 4.18.1, since I managed to get the script to execute again when it was bound with `ngModel` to an `<input>`.

**Comment by tmcconechy** [comment]
I think that this can be reproduced in EP by changing this line https://github.com/infor-design/enterprise/blob/master/app/views/components/dropdown/example-index.html#L10 to `  <option value="CT"><script>window.alert('dropdown xss')</script>XSS</option>` although thats just markup and im not sure there is anything we can do to prevent this.

This may by something we need to handle in the Angular component by calling one of the security utils in NG? Or something better handled by the backend?

**Comment by bthharper** [comment]
For info:  https://angular.io/guide/security.

**Comment by tmcconechy** [comment]
Was able to reproduce this in EP with the following example that can be pasted in to dropdown/example-index

```
<div class="row">
  <div class="twelve columns">
    <label for="states" class="label">State</label>
    <select id="states" class="dropdown">
      <option value="Hello">Hello</option>
      <option value="<script>window.alert('dropdown xss')</script>XSS">&lt;script&gt;window.alert('dropdown xss')&lt;/script&gt;XSS</option>
      <option value="World">World</option>
    </select>
  </div>
</div>
```

**Comment by janahintal** [comment]
QA Passed. Will move to Done.
Tested in: 
https://master-enterprise.demo.design.infor.com/components/modal/test-xss.html
https://master-enterprise.demo.design.infor.com/components/dropdown/test-xss.html
https://master-enterprise.demo.design.infor.com/components/autocomplete/test-xss-security.html
