### ISSUE TITLE
[Tabs component] Events emitted from component don't have correct tabIndex

### ISSUE THREAD

**Issue by mirekrewak** [infor-design/enterprise-ng#504]
**Describe the bug**
Events: onActivated, onAfterActivated emitted from Tabs component don't have correct tabIndex. 

**To Reproduce**
1. Go to **tabs-dynamic.demo.ts** example
2. Open console and click on tabs.
3. Notice message: "selected tab index is: 0" is always the same after selecting first tab or the second

**Expected behavior**
Proper tabIndex should be passed in the event.

**Version**
- ids-enterprise-ng: [e.g. v4.9.0 or v4.10.0]

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Comment by tmcconechy** [comment]
Descoping this for now as we couldnt get to it
