### ISSUE TITLE
XSS in modal dialog title

### ISSUE THREAD

**Issue by albinbergvall** [infor-design/enterprise-ng#511]
**Describe the bug**
Passing a script tag as input to the modal dialog title will execute the script when opening the modal. 

**To Reproduce**
1. Open the modal-dialog demo.
2. Pass a script as input to the title. ('<script>alert("title");</script>' for example.)
3. Open any of the modals in the demo.
4. The script is executed before the modal is opened.

**Expected behavior**
The script is not executed.

**Version**
- ids-enterprise-ng: 5.3 (recreated in 5.5.0-dev as well)

**Screenshots**
![image](https://user-images.githubusercontent.com/30404138/58871836-0a3c9d00-86c3-11e9-921a-dc51de1d1d98.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 74.0.3729.169 (Official Build) (64-bit)

**Comment by bthharper** [comment]
@tmcconechy is this an EP issue?  Angular sanitizes all content automatically.

**Comment by tmcconechy** [comment]
Yeah i think so. But i'll check into it.
