### ISSUE TITLE
SOHO-7618: Improve distributable package in npm

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#52]
I would like that the published package of soho-angular on npm is ready to be consumed as an external dependency. As it is published today it must be included in a build process in order to use it. That creates issues if the consuming project utilize another tsconfig.json setup or don't use angular-cli.

My suggestion is no use ng-packagr as part of the process when publishing to npm: [https://www.npmjs.com/package/ng-packagr]

The existing project will then need to be changed so entities are exported and imported properly. I've attached some images where I compare what rxjs publish (which is also a library using typescript) compared to what soho-angular publish.

[SOHO-7618.zip](https://github.com/infor-design/enterprise-ng/files/2054876/SOHO-7618.zip)

**Comment by tmcconechy** [comment]
There are some new features in NG 6 that can do libraries and components we should look at.
https://blog.angular.io/version-6-of-angular-now-available-cc56b0efa7a4

So prefer to use the NG6 features over ng-packag

**Comment by theakatz** [comment]
![2018-03-12_1412](https://user-images.githubusercontent.com/34137133/40804285-cda198de-64e8-11e8-9202-f48e407c3ef0.png)
![2018-03-12_1414](https://user-images.githubusercontent.com/34137133/40804289-cf195814-64e8-11e8-89b6-afa9f4181a80.png)
![2018-03-12_1423_001](https://user-images.githubusercontent.com/34137133/40804294-d061730a-64e8-11e8-96aa-5428f0a4edc5.png)
![2018-03-12_1423](https://user-images.githubusercontent.com/34137133/40804297-d1c140c2-64e8-11e8-8f3b-f21b118281ed.png)

**Comment by theakatz** [comment]
![2018-03-12_1423](https://user-images.githubusercontent.com/34137133/40804309-db56bde2-64e8-11e8-90bd-26b8eaefe887.png)

**Comment by theakatz** [comment]
![2018-03-12_1412](https://user-images.githubusercontent.com/34137133/40804311-de01aef8-64e8-11e8-86bc-9d0ffe428c90.png)

**Comment by theakatz** [comment]
![2018-03-12_1414](https://user-images.githubusercontent.com/34137133/40804313-e1560428-64e8-11e8-84bc-7b6331f0bac8.png)

**Comment by theakatz** [comment]
![2018-03-12_1423_001](https://user-images.githubusercontent.com/34137133/40804317-e4b04c8c-64e8-11e8-8822-029380996f40.png)

**Comment by bthharper** [comment]
I've started having a quick look at this to see how much work it would be, mainly as I am getting several issues including the enterprise-ng components into our projects.
