### ISSUE TITLE
Datagrid:  Tabbing into the next visible column doesn't work from a code-block cell

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#526]
Describe the bug
When tabbing out of a cell with a code-block, focus leaves the datagrid. It should put focus in the next visible cell. 

To Reproduce

1. Using the attached datagrid-code-block-editor.demo.ts
2. Put focus in the Company cell of any row
3. Hit the tab key to into the Code Block cell
4. Continue hitting the tab key to tab across the three input fields that make up the Code Block
5. Attempt to tab into the Name cell

Expected behavior
When tabbing out of a cell containing a code block, focus should be on the next visible cell.

Additional context
Changes to datagrid-code-block-editor.demo.ts
- Render only 3 fields and removed the more button for each field
- Grid options have changed to reflect what Landmark would use
- Changed the order of the columns to have a column after the code-block column

Changes to code-block.component.ts
- Removed the hidden icon-launch button

Note:
When the last field in the code-block has a more button AND the code-block-buttons div contains a button (see code-block.component.ts) then tabbing across the row works.

First cut of code-block implementation will not go out with a more button for each code block field.

**Comment by claudenbach** [comment]
[Git-NG-526.zip](https://github.com/infor-design/enterprise-ng/files/3283194/Git-NG-526.zip)

**Comment by tmcconechy** [comment]
@deep7102 Can you pick this up when you have a chance?
