### ISSUE TITLE
Typings for SohoToolbarFlexSelectedEvent are incorrect.

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#529]
**Describe the bug**

When implementing a select handler for the (selected) output on `soho-toolbar-flex`, the typings are incorrect for the item.

**To Reproduce**

The following code shows error in Visual Studio (& Code) when displaying the code.

```typescript
onSelected(event: SohoToolbarFlexSelectedEvent) {
    //
    let option = '';
    if (event.item.type === 'actionbutton' || event.item.type === 'menubutton') {
      option = event.item.selectedAnchor[0].dataset.option;
    } else {
      option = event.item.element.dataset.option;
    }

    this.store.dispatch(new RunToolbarOption(option));
  }
```

**Expected behavior**

The correct typings for the event should be defined.

**Version**
- ids-enterprise-ng: 5.4.0

**Screenshots**

![image](https://user-images.githubusercontent.com/8340092/59829145-8d512a80-9334-11e9-9800-3e9f040913fe.png)

**Platform**

ALL

**Additional context**

**Comment by tmcconechy** [comment]
Descoping this for now as we couldnt get to it
