### ISSUE TITLE
SOHO-7548: Improve SohoApplicationMenuComponent's design

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#53]
The current design for the Angular Component's `SohoApplicationMenuComponent` doesn't easily allow for the inclusion of a Searchfield in the way that the jQuery controls want the component to be structured.

The Angular Component has:
- An extra, custom element that wraps the internal accordion, which causes some of the internal CSS that normally controls list scrolling/height not to work correctly.  When using a searchfield, this also causes the Infor branding to disappear beneath the bottom edge of the window when it should always be present.
- No clearly defined integration with the searchfield from a functionality standpoint:

*Possible Solutions*
- Use [Multi-Slot Transclusion|https://scotch.io/tutorials/angular-2-transclusion-using-ng-content#toc-multi-slot-transclusion] to define clear areas for both the Accoridon and Searchfield components?
- Remove the `soho-accordion-demo` wrapper, if possible?

[SOHO-7618.zip](https://github.com/infor-design/enterprise-ng/files/2054936/SOHO-7618.zip)

**Comment by theakatz** [comment]
![untitled](https://user-images.githubusercontent.com/34137133/40803869-b856b7e4-64e7-11e8-8161-20f9eaf519ae.jpg)

**Comment by theakatz** [comment]
![screen shot 2018-02-27 at 11 14 54 am](https://user-images.githubusercontent.com/34137133/40804241-ae377068-64e8-11e8-9aa2-576bf434a55a.jpg)

**Comment by theakatz** [comment]
<img width="706" alt="screen shot 2018-02-27 at 11 14 30 am" src="https://user-images.githubusercontent.com/34137133/40804249-b3b8f1f6-64e8-11e8-9ce1-18b679df3298.png">

**Comment by tmcconechy** [comment]
Descoping this issue for now.
