### ISSUE TITLE
soho-editor: toolbar toggles highlighting broken

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise-ng#531]
**Describe the bug**
Angular wrapper for rich text editor with toolbar highlights multiple toggles that negate each other. For example alignment - all 3 options are highlighted at the same time if clicked. 

**To Reproduce**
1. Go to sample app
2. Open Text editor part
3. See issues

**Expected behavior**
As per editor shown at design.infor.com only 1 item should be highlighted at the same time if other options negate it

**Version**
- ids-enterprise-ng: 5.3.0

**Screenshots**
![image](https://user-images.githubusercontent.com/10186522/59906906-1b4b1500-940a-11e9-94ff-12f9ca3c591f.png)

**Comment by Fruko** [comment]
Additional issues found by our QA
1) When the block quote is enabled, both H3 and H4 buttons can be clicked and remain highlighted.
2) By clicking the Block quote the second time after the above scenario, second block quote indent gets added and the first one cannot be removed anymore.
3) The Strikethrough button (unlike Bold and Italic ones) does not get highlighted after clicking if the cursor is at the end of the text (text not selected).

**Comment by tmcconechy** [comment]
Descoping this for now as we couldnt get to it
