### ISSUE TITLE
Duplicate 'selected' event fired on `soho-searchfield`

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#533]
**Describe the bug**

The `soho-searchfield` component _sometimes_ fires the 'selected' event twice when selecting an item.  This can cause issues when the target application handles the event as if two selections have been made, often resulting in code being run twice.

**To Reproduce**

Checkout the latest `ids-enterprise-ng` code.
Add a `(selected)="onSelected($event)` output handler to the HTML.
Add 
```typescript
private static i = 0;

onSelected(event: SohoSearchFieldEvent) {
    console.log(`[${++SearchFieldDemoComponent.i}] Search Selected ${this.model.searchValue} ` + event.data);
  }
```

```sh
npm run build:lib
npm run start
```
Navigate to `http://localhost:4200/ids-enterprise-ng-demo/searchfield`

1. Enter B
2. Click 'Baby'
3. Enter O
4. Click 'Outdoors'
5. Enter 'M'
6. Click 'Mens'
7. ...

This does always go wrong, but occasionally you get two 'selected' events together with the same value.

**Expected behavior**

The selected event should only fire once.

**Version**
- ids-enterprise-ng: v5.4.0

**Screenshots**

![image](https://user-images.githubusercontent.com/8340092/60035591-1655c200-96a5-11e9-8df0-69ee246ac61c.png)

**Platform**

**Additional context**

**Comment by bthharper** [comment]
Checkout the branch https://github.com/infor-design/enterprise-ng/tree/533-searchfield-duplicate-selected-event.

**Comment by rvaja-infor** [comment]
Worth mentioning this is not specific to the Angular wrapper of the Enterprise controls. Ihave managed to produce this using the Enterprise controls, which we wrap in GWT, https://github.com/infor-design/enterprise.

**Comment by tmcconechy** [comment]
@rvaja-infor Have you got a sample page where you reproduced it you can attach for Enterprise?

**Comment by rvaja-infor** [comment]
> @rvaja-infor Have you got a sample page where you reproduced it you can attach for Enterprise?

As yet I have not. Will try get one written

**Comment by bthharper** [comment]
@tmcconechy is there a standard `searchfield` example under the enterprise repo?  The angular one just hooks into the 'updated' event, so should be easy to adk.

**Comment by tmcconechy** [comment]
@bthharper The sample page http://master-enterprise.demo.design.infor.com/components/searchfield/example-index.html shows the selected event. I tried selecting one after the other and seem to just get it once.

Also to note this is the autocomplete as well for the typeahead.

**Comment by tmcconechy** [comment]
Descoping this for now
