### ISSUE TITLE
Datagrid: Tab event needs to be exposed

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#536]
Describe the bug
Attempting to listen to the keydown of the tab key.  Within datagrid.js the keydown handler is capturing the tab key and is preventing propagation.  

The code does check whether the grid has an onKeyDown function, but this function has not been exposed for use in Angular.  Not sure if this is how it's intended to work?  

      // Tab, Left and Right arrow keys.
      if ([9, 37, 39].indexOf(key) !== -1) {
        if (key === 9 && self.settings.onKeyDown) {
          const ret = self.settings.onKeyDown(e);
          if (ret === false) {
            e.stopPropagation();
            e.preventDefault();
            return;
          }
        }

In 3.5, the function handleKeyDown trigger the onKeyDown event to determine whether or not the event has been handled.

     function handleKeyDown(e) {
        trigger(self.onKeyDown, {}, e);
        var handled = e.isImmediatePropagationStopped();

        if (!handled) {
           .....
        }

Landmark Business Case:
This is for the speed entry on data into a datagrid.  The user has added a new row to the datagrid.  They use the tab key to tab across the cells of the row inputting values as appropriate.  When tabbing from the last cell in the row, the intent is to automatically save the row and add a new row to the datagrid.  This worked fine in 3.5 since we could listen to the tab key.  But in 4.0, the tab key is not getting propagated. 

**Expected behavior**
Able to listen to keydown events including the tab key

**Comment by tmcconechy** [comment]
Yes thats what the onKeyDown was added for exactly. Just slightly different name.
Suggest doing a PR to expose it in NG and see if it works for what you need?

**Comment by tmcconechy** [comment]
@claudenbach were you planning to add this?

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
