### ISSUE TITLE
API Suggestion: Export component modules rather than one single module

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#543]
**Is your feature request related to a problem? Please describe.**
I think it's better to let users import the modules they want to use instead of importing a big module like current export from the package. I'm not sure if this is the future plan for enterprise-ng or not in plan yet but I will just create a feature request here.

**Describe the solution you'd like**
Export component modules to public_api and get rid of exporting SohoComponentsModule, following the pattern from angular cdk.

**Describe alternatives you've consider.**
**N.A.**

**Additional context**
**N.A.**

**Comment by tmcconechy** [comment]
@pwpatton and @bthharper I dont think this is a bad idea but one issue is that there is a interdependencies. For example if you import datagrid you might need 5-10 other components to figure out to import. Not sure if that will be an issue or how much work it would be to sort through this.

**Comment by bthharper** [comment]
You can actually do this now, simple pull in the underlying modules one by one, as required.  You may hit some dependency issues.  We could probably make a SohoCoreModule, to help with that.

For example, start from the quickstart, as this only uses the buttons (and icons) you can pull in the modules `SohoButtonModule` and `SohoLocaleModule`:.

```typescript
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    SohoLocaleModule,
    SohoButtonModule,
    SohoLocaleInitializerModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by tmcconechy** [comment]
Think we should close this then @bthharper or should we add a core?

**Comment by tmcconechy** [comment]
Will close for now unless other stuff is needed.
