### ISSUE TITLE
SOHO-7373: SohoTreeComponent node parent is disabled after expanding

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#55]
Node parent is disabled after expanding. This only happens when the data source is either Dataset or Source.

See Screen Cap
<img width="1428" alt="sohotreecomponent" src="https://user-images.githubusercontent.com/814283/40732480-67e9e51a-6401-11e8-89d0-47214df297a7.png">

**Comment by tmcconechy** [comment]
Descoping this issue for now. Not enough time and this is very old
