### ISSUE TITLE
Memory leak on soho-toolbar.component

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-ng#560]
'.more' - 'mouseover' event was not unsubscribed on ngOnDestroy() causing a memory leak on the soho-toolbar component.

**To Reproduce**
1. Dynamically create a '\<soho-toolbar/>'
2. Remove the '\<soho-toolbar/>'
3. Repeat several times
4. On developer tools, check Heap Snapshot, all instances of soho-toolbar is still retained.

**Expected behavior**
soho-toolbar should be freed from memory after use.  'mouseover' event should be unsubscribed on ngOnDestroy().

**Version**
- ids-enterprise-ng: 5.4.2

**Screenshots**
'mouseover' event was not removed:
![image](https://user-images.githubusercontent.com/53523076/62211829-16e32600-b3d2-11e9-9b09-50658df98c99.png)

**Platform**
 - Device: PC
 - OS Version: Windows 10
 - Browser Name chrome
 - Browser Version

**Comment by tmcconechy** [comment]
This issue may be fixed by https://github.com/infor-design/enterprise/issues/2496

**Comment by tmcconechy** [comment]
Assigning @EdwardCoyle to see if we can address this when solving https://github.com/infor-design/enterprise/issues/2496

**Comment by pwpatton** [comment]
We need this one in 5.5.x

**Comment by pwpatton** [comment]
@GMInf nice find! We've been looking for memory leaks so it's nice to find another we can squash.

**Comment by tmcconechy** [comment]
@pwpatton he's done a PR but cant figure out how to get it over here https://github.com/GMInf/enterprise-ng/pull/1 do you want to just recreate the PR here on a branch for @GMInf ?

**Comment by pwpatton** [comment]
We'd need that PR against 5.5.x

**Comment by pwpatton** [comment]
This is the change I'm about to PR. 
`  ngOnDestroy() {
    // call outside the angular zone so change detection isn't triggered by the soho component.
    this.ngZone.runOutsideAngular(() => {
      if (this.jQueryElement) {
        this.jQueryElement.off();
        this.jQueryElement.find('.more').off();
      }
      if (this.toolbar) {
        this.toolbar.destroy();
        this.toolbar = null;
      }
    });
  }
`

**Comment by pwpatton** [comment]
I'll PR and include @GMInf as an approver

**Comment by pwpatton** [comment]
@tmcconechy yea, this fixes only the soho-toobar memory leak and the ep/toolbar still seems to be leaking memory.

**Comment by tmcconechy** [comment]
OK waiting for your PR to approve. Thanks!

**Comment by GMInf** [comment]
Hi! We are currently using ids-enterprise-ng 5.4.2. Will this fix be included in that version too? Or do we need to upgrade to 5.5 to get the fix? Thanks!

**Comment by tmcconechy** [comment]
You would need 5.5 for the fix. We don't normally backport fixes to old versions unless it is a blocker.

**Comment by CindyMercadoReyes** [comment]
Moving this ticket to the Done folder. There is no way for QA to test this ticket.
