### ISSUE TITLE
Memory leak in SohoFileUploadComponent

### ISSUE THREAD

**Issue by nbcp** [infor-design/enterprise-ng#566]
**Describe the bug**
Unreleased event listener in jQueryElement

**To Reproduce**
1. Use SohoFileUploadComponent in a component
2. Navigate from the component to trigger destroy in SohoFileUploadComponent 
3. Create Heap snapshot from Chrome memory tab
4. filter results by 'fileupload'

**Expected behavior**
No leaking FileUpload objects

**Version**
- ids-enterprise-ng: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
Heap snapshot:
![image](https://user-images.githubusercontent.com/11013464/62440960-f37afb00-b784-11e9-85a1-8f5666a0f418.png)

**Platform**
 - OS Version: Windows10
 - Browser Name: Chrome
 - Browser Version: 76.0.3809.87 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
@nbcp see if you can add this to the 5.5.x branch for your PR. Thanks!
