### ISSUE TITLE
MenuButton: ridiculous amount of div class="arrow" renders in DOM

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#568]
**Describe the bug**
When using `soho-menu-button` in an item list, there is a ridiculous amount of `div class="arrow"` rendered in DOM whenever opening the menu. The amount of `div class="arrow"` rendered is equal to the amount of items in the item list.

**To Reproduce**
1. Go to `menu-button.demo.html`
2. Add this to HTML:
```
<ul>
  <li *ngFor="let item of items">
    <button soho-menu-button icon="user" menu="popupmenu-foo" data-options="{'hideMenuArrow': true}"
            [hideMenuArrow]="true"></button>
    <ul soho-popupmenu id="popupmenu-foo">
      <li><a soho-popupmenu-label>Action foo</a></li>
    </ul>
  </li>
</ul>
```
3. Open `menu-button.demo.ts`, add this to the file:
```
public items: number[] = [];

  constructor() {
    for (let i = 0; i < 10; i++) {
      this.items.push(i);
    }
  }
```
4. Wait for the app to recompile, there will be a list of user icon.
5. Click on a user icon, inspect DOM

**Expected behavior**
Shouldn't render this ridiculous amount of `div class="arrow"` for each opened menu. Menu should only render one arrow for that particular menu.

**Version**
- ids-enterprise-ng: 5.4.2

**Screenshots**
![image](https://user-images.githubusercontent.com/27772165/62459575-0808c480-b780-11e9-8a31-5938b5a7c831.png)
Observe that there are 10 divs matching with the length of array of `items` is 10.

**Platform**
 - Device **N.A.**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 75.0.3770.142 (Official Build) (64-bit)

**Additional context**
Angular CDK menu works way better

**Comment by tmcconechy** [comment]
Im guessing the bug is on this section of code https://github.com/infor-design/enterprise/blob/master/src/components/button/button.js#L58 can you debug it and see whats going on? If possible feel free to make a PR to enterprise.

Is it just the loop that causes the extra issue?

**Comment by brianjuan** [comment]
Moving to Done, performed smoke testing in http://4210-beta1-enterprise.demo.design.infor.com/components/popupmenu and they're working as expected.
