### ISSUE TITLE
Checkbox: weird behavior when using with Angular CDK virtual scrolling

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#569]
**Describe the bug**
When using `<input type="checkbox" soho-checkbox>` or just `<input type="checkbox" class="checkbox" />` for each list item in an item list which is rendered by Angular CDK virtual scrolling, a weird behavior occurs when checking/unchecking each checkbox.

**To Reproduce**
1. Add `@angular/cdk` and `@angular/material` to the dependencies of the project `enterprise-ng`, both at version **7.3.7**.
2. Import in `AppModule` these 2 modules: `BrowserAnimationsModule` and `ScrollingModule`.
3. Go to `checkbox.demo.html`
4. Replace the whole template with this piece of code
```
<cdk-virtual-scroll-viewport itemSize="30" minBufferPx="30" maxBufferPx="60" style="height: 400px; border: 1px solid black;">
  <ul>
    <li *cdkVirtualFor="let item of items; templateCacheSize: 0">
      <input soho-checkbox type="checkbox" [attr.id]="item.id" name="checkbox2" [(ngModel)]="item.checked">
      <label soho-label [attr.for]="item.id" [forCheckBox]="true">Checked</label>
    </li>
  </ul>
</cdk-virtual-scroll-viewport>
```
5. Open `checkbox.demo.ts`, add this piece of code:
```
public items: any[] = [];

  constructor() {
    for (let i = 0; i < 100; i++) {
      this.items.push({
        id: i,
        checked: false,
      });
    }
  }
```
6. Wait for app to reload, then go to Checkbox demo page.
7. Observe that there is an item list, which each line has a checkbox. Scroll all the way to the end of this list.
8. Check one checkbox, observe that scrollbar jumps up. Check another checkbox, scrollbar continues to jump.

**Expected behavior**
Checking/unchecking checkbox shouldn't make the scrollbar jump. This behavior doesn't happen to native HTML checkbox, the example is here: https://stackblitz.com/edit/components-issue-xkkdz1

**Version**
- ids-enterprise-ng: 5.4.2

**Screenshots**
**N.A.**

**Platform**
 - Device **N.A.**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 75.0.3770.142 (Official Build) (64-bit)

**Additional context**
**N.A.**

**Comment by tmcconechy** [comment]
The link you shared with the project is just showing the native version. Do you have a version that uses the Soho Checkbox? Also we had a similar "wierd" fix on it where it would toggle on and off. Can you test the sample project on 5.5.0-rc?

Also might help to make a branch withe project mods. Although we dont actually support the CDK or material of course it may be related to the way we do the checkbox positioning as native checkboxes cannot be styled, can probably be corrected with some sort of css change

**Comment by ahnpnl** [comment]
The link I share is example working with with native checkbox. The reproduce steps above the link is applied to example app in `enterprise-ng`. I posted a link just for comparison and prove that `soho-checkbox` causes the issue.

**Comment by tmcconechy** [comment]
You lost me on step 2. I dont know what BrowserAnimationsModule is ? So there for a branch with the changes would be a good idea and make for us to faster address this.

**Comment by ahnpnl** [comment]
https://github.com/ahnpnl/enterprise-ng/tree/checkbox-virtual-scrolling-issue 
This is the branch I created for both issue #568 and #569

**Comment by tmcconechy** [comment]
It looks like you can fix this by adding a rule to set `input.checkbox, span.checkbox > input` to position absolute. Im not 100% certain if we want to make this change as this positioning has in the past been changed to solve an array of issues. So i would probably do it on a parent like `li` or `ul` for a fix. But you could add it to your `cdk-virtual-scroll-content-wrapper`

```
input.checkbox, span.checkbox > input {
  position: absolute;
  opacity: 0;
}
```

fx
```
.cdk-virtual-scroll-content-wrapper input.checkbox
.cdk-virtual-scroll-content-wrapper span.checkbox > input {
  position: absolute;
}
```

**Comment by ahnpnl** [comment]
I think `soho-checkbox` needs a recheck about the implementation to be more generic because I believe more and more people will use virtual scrolling (it's very useful yes), and the chance to run into this issue will increase.

**Comment by tmcconechy** [comment]
I do not think the implementation is bad. We just position the actual checkbox off screen and use the labels the input needs to be hidden and the label is created off the label. This is the only way thats possible as inputs cannot be styled natively. So we will have to do adjustments based on scenarios that do not work. We did this differently in listview. One thing we could do is add a parent class to change the display you could add to your list. But i do not think we can "change the entire implementation".

**Comment by ahnpnl** [comment]
not really changing the entire implementation but I mean checking the current implementation and provide a generic fix.

**Comment by tmcconechy** [comment]
Yeah ok i was thinking that maybe if this problem happens on generic `ul`/`li` we could add a fix for that but if you need a quick solution you can try adding the css. I believe we went from `absolute` to `fixed` to solve another issue so could also look into that

**Comment by tmcconechy** [comment]
Descoping this for now as its rather old.
