### ISSUE TITLE
SOHO-7365: Provide demo example for dropdown multiple selection with validation

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#57]
I tried to find a demo example for validation on dropdown multiple selection but I couldn't find it.
I attached here the code I setup for an example and somehow the validation stops working when I add "multiple" to <select> and if I remove "multiple", the validation works again

- Add and test an example in the core components
- Fix if not working
- Then add an example to the angular components

Use Case: Simple required validation on the multiselect.

Example Attached that can be copied in

[Sample.zip](https://github.com/infor-design/enterprise-ng/files/2054759/Sample.zip)

**Comment by theakatz** [comment]
can't attach files from og ticket. Please see jira for them: https://jira/browse/SOHO-7365

**Comment by tmcconechy** [comment]
Descoping this issue for now. Not enough time and this is very old
