### ISSUE TITLE
SOHO-7344: Allow usage of angular components inside soho-toolbar and soho-button-set

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#58]
When encapsulated component containing buttons is used inside soho-toolbar, soho-toolbar is not able to create more button.

Example:

```
    <soho-toolbar class="toolbar" maxVisibleButtons="5" hasMoreButton="true" rightAligned="true">
      <soho-toolbar-button-set>
        <custom-angular-component>
              <button></button>
              <button></button>
         </custom-angular-component>
      </soho-toolbar-button-set>
    </soho-toolbar>
```

In sohoxi.js _$(selector).children()_ is used, but _$(selector).find()_ would be more sufficient as buttons encapsulated inside angular component are currently not selected.

**Comment by tmcconechy** [comment]
What is your code in `<custom-angular-component>` i'm wondering if you can flatten the content so its not in a container and this will work fx.

Could you attach a zip we could copy in to test this out on the sample project?

**Comment by tmcconechy** [comment]
Descoping in favor of flex toolbar
