### ISSUE TITLE
OnKeyDown - Dropdowns, Grids and Checkboxes

### ISSUE THREAD

**Issue by petercullen68** [infor-design/enterprise-ng#584]
Do we have any plan or timescale on when onkeydown will be available in these components?

**Comment by tmcconechy** [comment]
We have no plans right now. As this is a new issue. Could you maybe right up the issue using the isse template with the use case ect?

- Datagrid - actually recently added an onkeydown https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L107
- Dropdown - has one https://github.com/infor-design/enterprise/blob/master/src/components/dropdown/dropdown.js#L46
- checkbox - i wouldnt think you would need one (its native so probably uses native on keydown)

So maybe just need the types in this repo to fire? I think some may be there now. Checkbox will probably never need it.

**Comment by petercullen68** [comment]
Yep I'll create a new enhancement with the template.
