### ISSUE TITLE
OnKeyDown - Dropdowns and Grids.

### ISSUE THREAD

**Issue by petercullen68** [infor-design/enterprise-ng#585]
**Is your feature request related to a problem? Please describe.**
We are writing an application, for warehousing, which will run on mobile scanners, through a web browser.  It's against an older back end that although we are presenting through the browser the functionality is very much like a character based program.  The user don't use a mouse or touch, they will be navigating using key strokes, tab, shift tab etc.  So harvesting OnKeyDown from a control is very important as this drives the flow of the page.

**Describe the solution you'd like**
We would like to harvest the onkeydown events from the controls that we are using.  

**Describe alternatives you've considered**
We don't really have an alternative, at any one point, only a single control is enabled, they keydown events are used to navigate forward or backwards and this in turns drives a web call which tells the UI where to apply focus and what control to enable.

**Additional context**

**Comment by tmcconechy** [comment]
Datagrid - already has a onKeydown https://github.com/infor-design/enterprise-ng/blob/master/projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.component.ts#L1798 this was added recently

Dropdown - is missing the type https://github.com/infor-design/enterprise-ng/blob/master/projects/ids-enterprise-ng/src/lib/dropdown/soho-dropdown.component.ts but it does exist https://github.com/infor-design/enterprise/blob/master/src/components/dropdown/dropdown.js#L46

So i think this should be a simple PR to add the type. We do not have plans to put this on every component. That would be a lot of work

**Comment by petercullen68** [comment]
Thanks. That would be a big help!

**Comment by petercullen68** [comment]
Hello all, Any idea of when this will be available? Thanks.

**Comment by tmcconechy** [comment]
@pwpatton did you PR this or am i mis remembering?

**Comment by pwpatton** [comment]
I haven't done this yet.

**Comment by pwpatton** [comment]
@petercullen68 will this PR resolve this issue for you?
https://github.com/infor-design/enterprise-ng/pull/658

**Comment by petercullen68** [comment]
Thanks Phillip, from the description above, that looks like it will work for me.  I'll give it a test when I can and let you know.
