### ISSUE TITLE
Upgrade to Angular v9 and Ivy

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#586]
**Is your feature request related to a problem? Please describe.**
At the moment, the users of `ids-enterprise-ng` often needs to wait for quite long time to upgrade to the next major version of Angular. This is not flexible at all.

**Describe the solution you'd like**
A plan to prepare for Angular v9 with Ivy compiler. The reasons for the preparation are:
- #578 of `ids-enterprise-ng` was finished.
- Ivy was enabled as default compiler in the latest unreleased version of [Angular](https://github.com/angular/angular/blob/master/CHANGELOG.md#900-next3-2019-08-21)

I think it's wise to prepare before a major version of Angular is actually released. This will help users of `ids-enteprise-ng` to be more flexible to upgrade their apps to next major version of Angular instead of waiting for `ids-enterprise-ng` to be compatible. 

**Describe alternatives you've considered**
**N.A.**

**Additional context**
The reason for early preparing is assuming that `ids-enterprise-ng` finishes being compatible with next major version of Angular before the major version is released, then when the major version of Angular releases, `ids-enterprise-ng` can release at the same time. As a result, the users of `ids-enterprise-ng` can enjoy the new major version.

**Comment by tmcconechy** [comment]
It is good to be prepared and i think that we can do better to support the new versions when they are released. We dont have many resources however, so i cant guarantee we will do the updates before they are released but probably can improve the time frame.

Currently the ids version trails about a month since we develop that first and then add to NG. We dont have to do that for angular but it does require someone to have the time to work on it in a timely fashion. Some of the folks working on this repo share time with their actual projects.

PR's greatly appreciated if you want to help tackle issues.

**Comment by ahnpnl** [comment]
https://link.medium.com/SYXA5vugtZ

**Comment by bthharper** [comment]
@ahnpnl You can try ivy now if you like ;-) and feed back any issues.

https://angular.io/guide/ivy

**Comment by bthharper** [comment]
This will take a while to sort out as the ivy compiler is rightly enforcing visibility constraints between components and templates.  

Using ivy is also likely to have an impact on any consuming application.

There is also a recommendation NOT to compile library packages using ivy, however we should ensure the demo app can be compiled as such but not `ids-enterprise-ng`.

**Comment by bthharper** [comment]
I have this "mostly" working on a branch (including ivy) except the images (svg icons) are a bit hit and miss so will continue to investigate.

**Comment by bthharper** [comment]
Waiting for https://github.com/angular/angular/issues/34256.

**Comment by tmcconechy** [comment]
What do we have thats nested like that?

**Comment by bthharper** [comment]
Disabling **ivy** fixes the problem, so I am assuming it's the same problem with the **svg** icons missing the base-rectangle attribute.

**Comment by Fruko** [comment]
v9 released today, is there any ETA for v9 compatible ids-enteprise-ng? Is the svg issue blocking it or is there a workaround? We are really eager for Ivy and new TS version :)

**Comment by tmcconechy** [comment]
@bthharper did a PR we will have to test this out (you can test it too @Fruko if you like). The next version would be around end of month and if everything is good we could include this (7.0)
