### ISSUE TITLE
Lookup: Previously selected value is lost on 2nd 'Apply'

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise-ng#588]
**Describe the bug**
The selected value for a Lookup that uses **source + multi select is** is lost when opening the lookup a second time and clicking Apply without changing anything. The value looks selected correctly, but the input field is emptied. Also, if opening any other async lookup on the page after this, they will show that lost selection as a ghost selection.

**To Reproduce**
1. Modify app/lookup/lookup.demo.html so that the "Products (Async Results)" sample is multi select instead of single.
2. Run sample
3. Open lookup and select the first value (or any value)
4. Click Apply
5. Re-open lookup and click Apply without changing anything
Result: Input field is emptied, value is lost

**Expected behavior**
Value is retained in the input field

Similar occurs if selecting additional value(s) on the 2nd opening before Apply. The new selections are persisted but the selection from 1st opening is lost.

**Version**
- ids-enterprise-ng: 5.5.1

**Gif**
![lookup](https://user-images.githubusercontent.com/1101770/63518600-b12a1b80-c4f1-11e9-9970-3ef361a29604.gif)

**Additional context**
It seems to work fine for the core control:
https://design.infor.com/code/ids-enterprise/latest/demo/components/lookup/example-multiselect-paging-serverside

**Comment by tralarn** [comment]
What is the status for this issue?

**Comment by tmcconechy** [comment]
Status: No time yet but will add to the next sprint

**Comment by jbrcna** [comment]
**Test Passed**
v4.27.0-dev
This issue is now resolved, moving this ticket to Done
