### ISSUE TITLE
SOHO-7270: Create an angular example for listview lazy loading

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#60]
The core components have a few lazy loading examples as per: http://usalvlhlpool1.infor.com/4.3.2/components/listview/example-footer-navigation

These features are not implemented in angular yet. Need an example showing how to do these use cases on the angular side.

- expose any needed inputs or settings
- add a ts and example page

If possible would like the second example in a workaround form that would work in 4.3.2 / Home pages.

See also https://jira.infor.com/browse/SOHO-7307

**Comment by tmcconechy** [comment]
Descoping this issue for now. Not enough time and this is very old
