### ISSUE TITLE
Datagrid: highlighting row does not work for non-first pages in mixed mode.

### ISSUE THREAD

**Issue by micheal-cao** [infor-design/enterprise-ng#602]
**Describe the bug**
Under mixed mode, clicking any non-checkbox columns is supposed to highlight the row of a datagrid, this works fine for the first page, however, if this is not the first page, the row never get highlighted.

**To Reproduce**
1. Open src/app/datagrid/datagrid-paging-service.demo.ts file in a text editor, and change Change "selectable" from "single" to "mixed".
2. Then goto /ids-enterprise-ng-demo/datagrid-paging-service page
2. Click next page, then click any row, you will see no row got high-lighted

**Expected behavior**

**Version**
- ids-enterprise-ng: [e.g. v5.4.0, v5.5.2]

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [Windows 10]
 - Browser Name [chrome]
 - Browser Version [Version 76.0.3809.132 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
This seems like something we should be able to reproduced in ids-enterprise. But tried to do the steps similar to what you said on http://master-enterprise.demo.design.infor.com/components/datagrid/example-mixed-selection.html and not seeing any issues.

Can you update the example for ids-enterprise to reproduce or explain further what i might need to fix it there in the core components (vs the NG wrapper).

Thanks

**Comment by tmcconechy** [comment]
Descoping some older issues we didnt get to.
