### ISSUE TITLE
Datagrid: Add rowTemplate type and expandable row example.

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#606]
**Is your feature request related to a problem? Please describe.**
The rowTemplate type is missing in datagrid settings. Also we should add an example showing https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/example-expandable-row.html#L47 as a static string. Also later as an NG component

**Describe the solution you'd like**
- add rowTemplate type
- add an example showing the built in string templates like EP
- add an example showing a NG component in the template

**Describe alternatives you've considered**
Can workaround it forever with casting to any
`(this.sohoDataGridComponent.gridOptions as any).rowTemplate = '<div>stuff</div>';`
  
**Additional context**
https://teams.microsoft.com/l/message/19:83173693057f4991b7a84f030975c06d@thread.skype/1563803992406?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1563803992406&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=Angular%20Components&createdTime=1563803992406

https://teams.microsoft.com/l/message/19:83173693057f4991b7a84f030975c06d@thread.skype/1568222968040?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1568222968040&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=Angular%20Components&createdTime=1568222968040

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. This issue is an Angular related issue so it can't be QA tested.
