### ISSUE TITLE
SOHO-7268: Add an example of a listview search and paging.

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#61]
Using angular components, is there a way to link a separate search field to listview. When I tried to manually code, the pagination of listview does not adjust to the filtered list. 

Examples Needed:

- listview, paging and built in search
- listview, paging and external search field

See https://jira.infor.com/browse/SOHO-7268 for more background.

**Comment by theakatz** [comment]
![pagination with search results](https://user-images.githubusercontent.com/34137133/40804025-29b08b36-64e8-11e8-803f-a061a7add3a0.png)
![search link](https://user-images.githubusercontent.com/34137133/40804026-2b39cee0-64e8-11e8-87e4-cb24d134996e.jpg)

**Comment by tmcconechy** [comment]
Descoping this issue for now. Not enough time and this is very old
