### ISSUE TITLE
SOHO-7225: 4.0 Validation Alert - additional icon type

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#62]
Landmark needs an additional icon type for a validation alert on a form. Landmark currently has support for five alert types: red, yellow, green, blue, and icon. Four of these types map to the validation alert types of error, alert, confirm, and info. 

The icon type would use the current soho icons, such as the mail icon. The expectation is that the color for this alert would be black.

Currently this functionality is available in the Landmark Rich Client desktop application and having this functionality for the web interface would allow Landmark to fully support the alert feature.

Task Summary
- extend the example http://localhost:4000/components/validation/test-message-types-landmark
- add a new radio button for alert with icon
- extend the addMessage function to take the optional icon option (fx icon-mail)
- note this is only valid if isAlert type or its ignored
- if set this icon will be shown under the field were the error/warning icon would be.

**Comment by tmcconechy** [comment]
Closing as was actually done but not marked correctly on https://jira.infor.com/browse/SOHO-7225
