### ISSUE TITLE
Datagrid: Expand and Collapse not correct when children of children are collapsed.

### ISSUE THREAD

**Issue by AnaLauraMartinez** [infor-design/enterprise-ng#633]
Expand and Collapse get mess up when the user expands and collapse children of children.

Steps to reproduce:

Data:
```
1 object
  children> 
     children> 
       attributes
2 object
   children>
     children>
        attributes
     children>
        attributes
```

Everything needs to be collapsed initially.
1. Open 2
1. Open children
1. Open one of its children 
1. collapse 2
1. Expand 2

Issues: You will see that both children are expanded but the second children shows the icon as collapsed.

**Expected behavior**
The second set of children should be collapsed because that is how they were originally.

**Version**
 "ids-enterprise-ng": "^6.0.0",

**Platform**
 - Browser Name Chrome
 - Browser Version : Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by AnaLauraMartinez** [comment]
[datagrid-treegrid-service.demo.ts.txt](https://github.com/infor-design/enterprise-ng/files/3686763/datagrid-treegrid-service.demo.ts.txt)

**Comment by AnaLauraMartinez** [comment]
This is the video of the steps to reproduce

**Comment by tmcconechy** [comment]
Did you find a solution? Or was this closed incorrectly?

**Comment by AnaLauraMartinez** [comment]
Closed by mistake when I was attaching files

**Comment by jbrcna** [comment]
Test PASSED
Verified in http://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-children-expand-collapse.html

ALL BROWSER and Devices
