### ISSUE TITLE
SOHO-7162: Application menu lazy loading example

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#64]
The current implementation of a lazy loaded application menu has a couple issues:

1. Visually, it uses a left side button on the header instead of the right side chevron icon.
2. If the user clicks on the header but not on the left side button the panel expands without having fired the function to populate the menu.
3. The current angular wrapper for the application menu doesn't expose the underlying accordion functions, events, properties, etc.

Need an example for how to circumvent these issues as well as a true, 'fully lazy' loaded menu.

**Comment by dmcodrum** [comment]
This is still an issue for us. As-is, our app cannot display the soho application menu correctly. The top level menu headers show with a left-side '+' instead of right-side chevrons.

**Comment by tmcconechy** [comment]
Descoping this issue for now. Not enough time and this is very old. Assuming not an issue if used as per the examples.
