### ISSUE TITLE
Locale: add typings for the parseDate() options parameter

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise-ng#640]
**Describe the bug**
Add typings for the Soho.Locale.parseDate() options parameter. Internally in sohoxi, the options parameter is defined as string | object.

**Version**
- ids-enterprise-ng: 6.1.0-beta.0

**Platform**
 - All

**Additional context**

**Comment by tmcconechy** [comment]
You want this in 6.10? If so PR to branch 6.1.x
