### ISSUE TITLE
expose aggregate field and make it an array

### ISSUE THREAD

**Issue by GeTeBr-Infor** [infor-design/enterprise-ng#642]
In the javascript the property aggregate is available as the field which should be aggregated.
Is it possible to make this property available in the soho-datagrid.d.ts?

and is it possible to aggregate on multiple fields?

**Comment by pwpatton** [comment]
Is aggregate just a number? 

Here's the current SohoDataGridGroupable interface.
```
interface SohoDataGridGroupable {
  fields: string[];
  expanded?: boolean | Function;
  aggregator: SohoDataGridAggregator;
  groupRowFormatter?: SohoDataGridColumnFormatterFunction;
}
```

One thing you could try just to get it working is to force the setting in bay casting it's parent object to `any`.

For example:
```
const groupable: SohoDataGridGroupable = {
  fields: myFields,
  expanded: true,
  aggregator: myAggregator,
  groupRowFormatter: myGroupRowFormatter
}

(groupable as any).aggregate = myAggregate;
```

**Comment by tmcconechy** [comment]
This issue is fairly clear but in the future please try and use the issue template https://github.com/infor-design/enterprise-ng/issues/new/choose

Also if you would like to try a PR to add this feel free 👍

**Comment by tmcconechy** [comment]
Looking back at this one. I think its ok. Its a string which is the field name. https://github.com/infor-design/enterprise-ng/blob/master/projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.d.ts#L943

Also we only support one field at a time so the array doesnt present make sense.
