### ISSUE TITLE
SOHO-7090: Toolbar flickers after unselect all is used on listview

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#65]
Repro Steps : 
- Use multiselect listvew
- Select some items
- Call unselect all items

( Can be seen in example project, when running locally, see also attached gif)

Call for unselect is 

`listView.unselect(listView.items.map((item) => item.selector));`

Expected Results : 
Toolbar is hidden smoothly.

Actual Results : 
After the toolbar is hidden it flickers again with 1 selected item, then disappears again.

![sellect_all_bug2](https://user-images.githubusercontent.com/814283/40726430-c1e2d256-63f3-11e8-9f58-ea9c157e26db.gif)

**Comment by tmcconechy** [comment]
Could not reproduce this issue with the given video alone.
