### ISSUE TITLE
XSS in dropdown when the input is cleared

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-ng#650]
**Describe the bug**
Script tags inside dropdown options are executed when removing search text using backspace.

**To Reproduce**
Given the following component:
```html
<select soho-dropdown [(ngModel)]="selected">
  <option *ngFor="let option of options" [value]="option">{{option}}</option>
</select>
```
```typescript
@Component({
  selector: 'app-dropdown-xss',
  templateUrl: './dropdown-xss.component.html',
  styleUrls: ['./dropdown-xss.component.css']
})
export class DropdownXssComponent {
  selected = 'Hello';
  options = [
    {
      label: `<script>window.alert('xss')</script>XSS`,
      value: `<script>window.alert('xss')</script>XSS`,
  ];
}
```
1. Click the dropdown
2. Type a character, e.g "a"
3. Press backspace
4. The script executes, and an alert window is opened.

**Expected behavior**
The script should not execute.

**Version**
- ids-enterprise-ng: 6.1.0
- ids-enterprise: 4.22.0

**Platform**
 Tested in Chrome & Firefox on Windows.

**Additional context**
Related: https://github.com/infor-design/enterprise-ng/issues/503

I can reproduce it on the current `master` branch of the `enterprise-ng` project by making the following changes:

1. Remove `noSearch` from the line with `<select soho-dropdown` in `dropdown-simple.html`

**Comment by janahintal** [comment]
QA Failed. 

Unable to select values with double quotes "
1. Goto http://master-enterprise.demo.design.infor.com/components/dropdown/test-special-chars.html
2. **Using arrow key**, select "Value Contains escaped "quote" " or "it has "dbl quotes" " 


Icon color is distorted in responsive view 
1. Go to http://master-enterprise.demo.design.infor.com/components/dropdown/example-icons.html?theme=soho&variant=light&colors=941e1e
2. Minimize the screen
3. Open the Dropdown with Colors 
![image](https://user-images.githubusercontent.com/45757016/68283571-ba6d6200-00b6-11ea-867a-c0444a7232e6.png)

**Comment by brianjuan** [comment]
Additionally, in http://master-enterprise.demo.design.infor.com/components/dropdown/test-xss.html, searching some characters returns results that are not part of the list.
1. Type "(", the result will return "$1"
![image](https://user-images.githubusercontent.com/39508864/68285841-f73b5800-00ba-11ea-92cf-8b264518f7d9.png)
2. Type "x", the result will return "\&#x27;"
![image](https://user-images.githubusercontent.com/39508864/68285889-0fab7280-00bb-11ea-9f71-e6ebe4aabb7f.png)
3. In the 2nd dropdown, type "t", the result will return "\&quot;"
![image](https://user-images.githubusercontent.com/39508864/68286007-4bded300-00bb-11ea-949f-80865571b086.png)

**Comment by brianjuan** [comment]
All the issues found above are now fixed across all browsers except for the selecting of **"Value Contains escaped "quote""** and **"it has "dbl quotes""** using Enter key in http://4230-beta0-enterprise.demo.design.infor.com/components/dropdown/test-special-chars.html.
Steps:
1. Open dropdown then type "
2. Press arrow down key then select **"Value Contains escaped "quote""** by pressing Enter key
3. See issue: it won't be selected.

Should we make separate ticket/issue for that @tmcconechy ?

**Comment by tmcconechy** [comment]
I think this is fine as failed QA as that case isnt working.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this to Done bucket.
