### ISSUE TITLE
Datagrid keyword search

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise-ng#652]
**Is your feature request related to a problem? Please describe.**
We are trying to use feature of Datagrid to perform keyword search like [here](https://master-enterprise.demo.design.infor.com/components/datagrid/example-keyword-search.html) however there seem to be no example about how to achieve this in Angular wrapper, we tried to copy the code but it does not seem to work

**Describe the solution you'd like**
example of how to use Datagrid keyword search feature in Angular wrapper component

**Describe alternatives you've considered**
Use javascript to find search text in DOM and manually set Inner HTML

**Comment by tmcconechy** [comment]
Descoping this for now
