### ISSUE TITLE
Soho Tree-grid: Selection of one cell affecting another cell's value.

### ISSUE THREAD

**Issue by mythilinishtala7** [infor-design/enterprise-ng#659]
**Describe the bug**
Selecting a checkbox in tree grid, updating visually but the value is still false, a cell which is in another row (two levels upper usually) is getting true value.

**To Reproduce**
1. Checkout the project from (https://github.com/mythilinishtala7/Soho-tree-grid.git)
2. Run the project and select any checkbox.
3. Inspect and see the current grid data, the value is still false for the current selection, some other cell gets true value.

**Expected behavior**
The cell which is selected should have the updated value and other cells should not get affected.

**Version**
Works fine in  ids-enterprise-ng: 5.4.2 version but issue arises
- ids-enterprise-ng: from 5.5.0 to 6.1.1

**Screenshots**
![datagrid-data](https://user-images.githubusercontent.com/54135198/68468170-7c4e7a80-023d-11ea-836e-9a5d5477a787.png)

**Comment by deep7102** [comment]
Hi @mythilinishtala7 edit cell will not update the row data, your example page is making log for row data on `cellchange`. Instead you need to watch the `event` argument on `cellchange`.
So change [here](https://github.com/mythilinishtala7/Soho-tree-grid/blob/321b67fc714ef66e70ce7d59b8e7846a21cb84cc/src/app/audit/audit-grid/audit-grid.component.ts#L98) in your project from `console.log(this.auditData)` to `console.log(event);` and try to see console log for keys like `row, cell, column, value, oldValue` etc.

**Comment by deep7102** [comment]
@mythilinishtala7 Found an issue it should update the row data as well. It is working on parent rows but not on child rows, so looking into.

**Comment by jbrcna** [comment]
QA **Failed**
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-editable-children.html

**Notes:**
It works fine in ALL Browsers **Except** in IE11. nothing seems to be working in IE11 with the current version 4.25.0-dev

**Comment by tmcconechy** [comment]
Fixed on https://github.com/infor-design/enterprise/issues/3289 - ready to retest IE 11

**Comment by jbrcna** [comment]
The issue is now resolved. moving to Done column
