### ISSUE TITLE
SOHO-7088: 4.0 Trackdirty indicator does not display when ngModel value is changed programatically

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#66]
When updating a components value programatically, ngModel is updated correctly, but the underlying element does not receive a change event and therefore the track dirty indicator is not displayed.

**Comment by theakatz** [comment]
@fitzorama are you still working on this as well?

**Comment by fitzorama** [comment]
@theakatz I am doing something different to accomplish this by calling the soho-trackdirty methods changeDirty() and resetDirty() to get the behavior I need, so no, I am not currently working on this.

**Comment by tmcconechy** [comment]
OK sounds good - im not sure i even understand the issue. So if you have something that works lets close.

**Comment by janahintal** [comment]
Hi @tmcconechy, may I know where can I test this ticket? Thanks.

**Comment by clepore** [comment]
@janahintal Good call. I do not think there was any code or result along with this. We can move to done.
