### ISSUE TITLE
Weekview: Add new component wrapper

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#661]
**Is your feature request related to a problem? Please describe.**

Need to add a component wrapper for WeekView. Since DayView is just setting the weekview to one day, suggest just the one component and similar examples for week, one , two day.

**Describe the solution you'd like**
Add a new wrapper for weekview.js

**Describe alternatives you've considered**
None.

**Additional context**
https://github.com/infor-design/enterprise/issues/2780
https://github.com/infor-design/enterprise/issues/1757

**Comment by vonnyw** [comment]
hi @ericangeles I simultaneously worked on weekview component and its demo this past month not realizing you picked it up. I am pushing a PR and have notified @tmcconechy.

**Comment by ericangeles** [comment]
Hello @vonnyw. I'll be closing the PR that I created. Will just check your PR and see what I can add/comment. Thank you.

**Comment by tmcconechy** [comment]
This was completed . Thanks @vonnyw
