### ISSUE TITLE
Dropdown: Expose listclosed  (an event onClose)

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise-ng#662]
**Is your feature request related to a problem? Please describe.**
We use state management in our products that cause immutable state updates, so we are only interested in values once the dropdown is closed so we can dispatch actions to update our state

**Describe the solution you'd like**
I would like dropdown emit event when it is closed and values are visible in the input so I can listen to that and read values only after user is done with selecting

**Comment by tmcconechy** [comment]
The dropdown does emit `listclosed` and `listopened`. So for those we just need to add the event emiters in NG https://github.com/infor-design/enterprise-ng/blob/master/projects/ids-enterprise-ng/src/lib/dropdown/soho-dropdown.component.ts#L387

**Comment by Fruko** [comment]
Hello @tmcconechy  any ETA on this one please?

**Comment by bthharper** [comment]
@tmcconechy can you confirm what you mean by:

> Also the change event should also fire when closing and updating.

Changing the selected value fires a "change" event on the component, wanted to check I'd not forgotten something.

**Comment by tmcconechy** [comment]
@bthharper no, looks good. I was just trying to suggest that you could use changed event as a workaround

**Comment by tmcconechy** [comment]
Because @bthharper fixes this it will be in the end of this months release 6.5
