### ISSUE TITLE
SohoDataGridColumn does not include sortColumn

### ISSUE THREAD

**Issue by danhoglund** [infor-design/enterprise-ng#664]
The type SohoDataGridColumn should expose the function sortColumn so it will be accessible through that type.

1. Declare a variable of type SohoDataGridColumn. 
2. Try to set the property sortFunction on that variable

Results in a compilation error since the property is not a member of SohoDataGridColumn

**Expected behavior**
Expected the property to be available as part of the SohoDataGridColumn definition

**Additional Context**
https://teams.microsoft.com/l/message/19:83173693057f4991b7a84f030975c06d@thread.skype/1573750048669?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1573750048669&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=Angular%20Components&createdTime=1573750048669

**Comment by tmcconechy** [comment]
This means:

Add this property/function https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/example-list.html#L19 to the SohoDataGridColumn types so its available
This the line in IDS where its used https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L10406
