### ISSUE TITLE
Datagrid: When in uplift themes, the empty message icons disappear

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise-ng#665]
**Describe the bug**
When in the uplift theme, the empty message icons disappear.

**To Reproduce**
1. Go to Datagrid -> Datagrid - Empty Message
2. Change the theme to any uplift theme
3. See that the empty message icon isn't appearing

**Expected behavior**
The icon should appear

**Version**
- ids-enterprise-ng: 6.2.0-rc

**Screenshots**
![image](https://user-images.githubusercontent.com/22107636/69070304-8450ac00-09ed-11ea-88bc-7489d3356325.png)

**Platform**
 - All

**Additional context**
Need to write a new component to pull in the correct icons, like soho-icons-uplift

**Comment by bthharper** [comment]
Interesting - this is working in our apps.  Might just be the "icon" set in the empty message?

```typescript
/** Default error message displayed on the grid. */
errorMessage: {
  title: Soho.Locale.translate('Please Wait'),
  info: 'Waiting for response from server',
  icon: 'icon-empty-no-data', // needs to be the full SVG name
  color: 'azure'
}
```

![image](https://user-images.githubusercontent.com/8340092/69075678-c7307500-0a29-11ea-8158-17c0718a7876.png)

**Comment by bthharper** [comment]
Definitely something funny going on in the demos though.

**Comment by tmcconechy** [comment]
@bthharper part of this is we added new (different) icons for the uplift theme. We want it to show that but this needs a small update here. @Sovia has the details for a PR from me offline now.

**Comment by bthharper** [comment]
@tmcconechy  - no problem.  Will apps needs to make any changes if they use these icons?

**Comment by tmcconechy** [comment]
Yeah they would need to do something like:
```
<soho-icons *ngIf="!inUpliftTheme"></soho-icons>
<soho-icons-uplift *ngIf="inUpliftTheme"></soho-icons-uplift>
<soho-icons-empty></soho-icons-empty>
<soho-icons-empty-uplift *ngIf="!inUpliftTheme"></soho-icons-empty-uplift>
```

Or the old ones will just be used. We should probably make an explicit note of that.

**Comment by tmcconechy** [comment]
This was completed
