### ISSUE TITLE
General: Demo app is not running in IE 11

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#668]
**Describe the bug**
Out of the box the demo app does not run in IE. To solve this differential loading (great feature) must be disabled. So teams need to weigth the use of this with the need to support IE.

And we need to decide if the demo app should target `es6`. Solution is on and discussed here:

https://stackoverflow.com/questions/56563742/how-do-i-make-angular-8-compatible-with-ie11

**To Reproduce**
1. `npm run start`
2.  Open IE 11
3. Load http://localhost:4200/ids-enterprise-ng-demo/
4. See see that it just has a busy indicator and no error

**Expected behavior**
Works (optionally)

**Version**
- Latest (6.x, 7.x)

**Platform**
 - Browser Name IE 11

**Additional Thoughts / FIxes**

- [ ] Do we by default target es5 or not as described in the link? Or deprecate IE 11
- [ ] Document this in the docs how to set this.
- [ ] Add a second build command where you can launch if IE 11 is needed.

**Comment by tmcconechy** [comment]
cc @bthharper (thanks for finding this).
cc @claudenbach @pwpatton @fitzorama

**Comment by bthharper** [comment]
The quickest workaround (for now) is to change the target in ./tsconfig from:

```json
"target": "es2015",
```
to
```json
"target": "es5",
```

Then run `npm run start`.

**Comment by pwpatton** [comment]
Yes, when compiling for production angular handles this through "differential loading". i.e. loading es5 for IE11 vs es2015 modern browsers.

For ngserve, we need to create another npm start script to switch the target to es5 when we want to test on IE11. And ofcourse the tsconfig that sets the "target".

```
tsconfig.es5.json
{
  "extends": "./tsconfig.app.json",
  "compilerOptions": {
    "target": "es5"
  }
}
```

npm script
`"start:ie": "ng serve --configuration=es5"`

**Comment by bthharper** [comment]
If only we could drop IE11!

**Comment by pwpatton** [comment]
@bthharper I think we are getting closer and closer. Once Edge Chrome is released we may have some opportunity if our current version -1 support policy holds, and chrome edge is considered a newer version current edge - fingers crossed.

**Comment by pwpatton** [comment]
https://www.engadget.com/2019/11/04/chromium-edge-browser-release-date/

**Comment by bthharper** [comment]
Yes - been using Chrome Edge for a while.   Fast!
