### ISSUE TITLE
SohoTreeComponent should trigger "deselected" event when a node becomes unchecked

### ISSUE THREAD

**Issue by micheal-cao** [infor-design/enterprise-ng#670]
**Is your feature request related to a problem? Please describe.**
Currently, SohoTreeComponent does trigger "selected" event when a tree node becomes selected (its checkbox becomes checked), however, it does not trigger "deselected" event when the tree node becomes unselected (its checkbox becomes unchecked).

**Describe the solution you'd like**
After investigation, Tree component in sohoxi.js does trigger handler for "unselected" event, however, SohoTreeComponent does not handle it, so simply add an output for this event.

**Comment by tmcconechy** [comment]
This has been completed
