### ISSUE TITLE
FileUpload: change event fired twice

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise-ng#672]
**Describe the bug**
File upload component fires change event twice

**To Reproduce**
1. Go to ids-enterprise-ng demo page
2. add change event listener with console log
3. see event fired twice

**Expected behavior**
A change even would only get fired once

**Version**
- ids-enterprise-ng: 6.0.0

**Comment by tmcconechy** [comment]
This may be fixed i tried this on 4.23 of ep by modifying fileupload/example-index to..

```

<div class="row">
  <div class="twelve columns">

    <div class="field">
      <label for="fileupload">Upload a File</label>
      <input type="file" class="fileupload" id="fileupload" name="fileupload"/>
    </div>

    <div class="field">
      <label for="fileupload-readonly">Upload a File</label>
      <input type="file" class="fileupload" id="fileupload-readonly" readonly="true" name="fileupload" value="Readme.txt"/>
    </div>

    <div class="field">
      <label for="fileupload-disabled">Upload a File</label>
      <input type="file" class="fileupload" id="fileupload-disabled" disabled="true" name="fileupload" value="Readme.txt"/>
    </div>

  </div>
</div>

<script>
  $('#fileupload').on('change', function() {
      console.log('trigger')
  });
</script>
```

And it is firing just once.

**Comment by bthharper** [comment]
@tmcconechy the (change) event is firing twice, one from the component and the other I am not clear where it is coming from.

**Comment by tmcconechy** [comment]
Needs to be zonified. Pushing a fix.
