### ISSUE TITLE
Header columns and body columns are missaligned

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise-ng#676]
**Describe the bug**
The columns alignment is not work properly when resize the column with by using resizer. This issue observed in DataGrid where we have pagination. We can reproduce this issue in ids-enterprise-ng 6.2.0 version.

**To Reproduce**
1. Install latest ids-enterprise-ng 6.2.0 version
2. Go to DataGrid - datagrid-paging-indeterminate example
3. Set width for all columns in % - You need to edit datagrid-paging-data.ts file to set width in percentage.
4. Now access ids-enterprise-ng-demo in browser.
5. Go to DataGrid menu and click on DataGrid-Paging Indeterminate 
6. Resize the columns width by using resizer
7. Navigate to last page of the DataGrid by using pagination
8. Click on Application Menu button to close the Application menu panel
9. check DataGrid columns alignment.

Width change -Please use below code

export const PAGING_COLUMNS: SohoDataGridColumn[] = [
  { id: 'selectionCheckbox', sortable: false, resizable: false, width: 50, formatter: Soho.Formatters.SelectionCheckbox, align: 'center', exportable: false },
  { id: 'productId', name: 'Product Id', field: 'productId', sortable: false, filterType: 'text', formatter: Soho.Formatters.Readonly },
  { id: 'productName', name: 'Product Name', field: 'productName', sortable: false, filterType: 'text', filterConditions: ['equals', 'contains'], width: '15%', formatter: Soho.Formatters.Hyperlink },
  { id: 'activity', name: 'Activity', field: 'activity', sortable: false, filterType: 'text', width: '15%', hidden: true },
  { id: 'quantity', name: 'Quantity', field: 'quantity', sortable: false, width: '15%', filterType: 'integer' },
  { id: 'price', name: 'Price', field: 'price', sortable: false, width: '15%', filterType: 'decimal', formatter: Soho.Formatters.Decimal },
  { id: 'orderDate', name: 'Order Date', field: 'orderDate', sortable: false, width: '15%', filterType: 'date', formatter: Soho.Formatters.Date, dateFormat: 'M/d/yyyy' }
];

**Expected behavior**

**Version**
- ids-enterprise-ng: [e.g. v4.9.0 or v4.10.0] V6.2.0

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by dhumalkishor** [comment]
![IDS](https://user-images.githubusercontent.com/42198413/70121827-647be200-1695-11ea-96cf-9f8355efc0e5.jpg)

**Comment by tmcconechy** [comment]
All these column alignment issues should be fixed by https://github.com/infor-design/enterprise/issues/2825 and related issues as quoted. Working on a fix for all of these.
