### ISSUE TITLE
SOHO-6953: TS Wrapper for Locale / Locale.translate

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#68]
Problem:

People are using different tools such as:
https://angular.io/guide/i18n
https://github.com/masterakos/angular-localization
https://www.npmjs.com/package/i18n-translate
https://www.npmjs.com/package/ng2-translate
http://www.ngx-translate.com/

And there is no documented examples for localization/ translation.

Idea:
Make a service to wrap the local functionality and show a way to change it on the fly and use in the angular project.

Theo/Sunsystems Has: a simple service called LocalizationService which primes the angular i18n code, and also one which bootstraps the Soho Locale class.  Would be great to have just the one service which did both.

```
<div class="field">
 <label soho-label for="folderName" i18n="folderName|folder name for create folder dialog@@create_folder_dialog_folderName_label.text">Enter the folder name:</label>
 <input soho-input id="folderName" formControlName="folderName"
 i18n-placeholder="@@create_folder_dialog_folderName_placeholder.text"
 placeholder="Enter the folder's name here" asyncValidators="async" soho-error />
 </div>
```

Landmark/Mike has: 

Usage:
- in template code 
```
<span>{{currentLocale.foo}}</span>
```
- in ts code
```
Locale.set('fr-Fr');
Locale.translate('key');
//also replace {0} and {1}
```
- still retrieve locale files from the server 
- existing internal translation should work
- fix attached bugs
- call Locale.set too in the startup code 
```
export class AppComponent {
 @HostBinding('class.no-scroll') get isNoScroll() { return true; }
 public personalizeOptions: SohoPersonalizeOptions = {};
 constructor() {
   // @todo Set the locale here, to ensure all the values are setup.
   Locale.set('en-US');
   this.setInitialPersonalization();
 }
```

**Comment by tmcconechy** [comment]
@bthharper added this already
