### ISSUE TITLE
Wrong scroll-bar in filtered datagrid

### ISSUE THREAD

**Issue by petr-hlavnicka** [infor-design/enterprise-ng#680]
**Describe the bug**
If datagrid data oveflow the datagrid size, the scrollbar is correctly placed (printscreen 1). After applying filter with subsequent reduction in data displayed to the extent fitting inside the datagrid size, the scrollbar is not further displayed, but an empty space is displayed instead of it (printscreen 2).

**Version**
- ids-enterprise-ng: 6.0.0

**Screenshots**
![01_scrollbar_correctly_present](https://user-images.githubusercontent.com/49194823/70317471-1b0ace80-181e-11ea-8ce7-1371311eebcc.png)
![02_whitespace-instead-of-scrollbar](https://user-images.githubusercontent.com/49194823/70317472-1ba36500-181e-11ea-823f-2a834655935c.png)

**Comment by tmcconechy** [comment]
We have a fix coming into 4.24 for these issues already. See:
https://github.com/infor-design/enterprise/issues/2825
https://github.com/infor-design/enterprise/issues/2835
