### ISSUE TITLE
Dropdown in datagrid not working in IE11

### ISSUE THREAD

**Issue by petr-hlavnicka** [infor-design/enterprise-ng#681]
**Describe the bug**
After selection of an item from a dropdown in datagrid, error is displayed (see screenshot) - this happens only in IE 11.

The definition of the datagrid column with the dropdown is:

	{
        id: 'version',
        name: 'Version',
        field: 'version',
        formatter: Soho.Formatters.Dropdown,
        editor: Soho.Editors.Dropdown,
        validate: 'required',
        width: 200,
        editorOptions: {
          source: (response, _, gridArgs) => {
            response(gridArgs.rowData.availableVersions
              .sort(((a: AvailableVersion, b: AvailableVersion) => b.version.localeCompare(a.version)))
              .map((version: AvailableVersion) => {
                return {
                  id: `${ version.id }-${ version.version }`,
                  label: version.version,
                  value: version.version,
                };
              }));
          },
        },
        options: [
          { id: '', label: '', value: '' },
        ],
      },

**Version**
- ids-enterprise-ng: 6.0.0.

**Screenshots**
![cannot-select-library-version-ie11](https://user-images.githubusercontent.com/49194823/70318461-6e7e1c00-1820-11ea-86fb-7e8b2c5b3238.png)

**Platform**
  - Browser Name Internet Explorer 11

**Comment by tmcconechy** [comment]
This is probably the same issue as https://github.com/infor-design/enterprise/issues/2919
This was fixed in 4.23 EP which is in 6.2.0 NG
