### ISSUE TITLE
toolbar-flex-searchfield readonly doesn't make the field readonly

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#685]
**Describe the bug**
When setting readonly to `soho-toolbar-flex-searchfield`, the search field isn't set to readonly mode.

**To Reproduce**
1. Open example app in `enterprise-ng`
2. Open `toolbar-flex-basic.demo.html`, add `readonly` or `[readOnly]="true"` to `soho-toolbar-flex-searchfield`
3. Observe that the search field isn't set to readonly. It can still be used

**Expected behavior**
Should make the search field display readonly mode.

**Version**
- ids-enterprise-ng: latest master

**Screenshots**
**N.A.**

**Platform**
 - Device **N.A.**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 79.0.3945.79 (Official Build) (64-bit)

**Additional context**
**N.A.**

**Comment by tmcconechy** [comment]
This may be an EP issue, but not seeing 100% the same thing. On http://latest-enterprise.demo.design.infor.com/components/toolbar-flex/example-index.html if i make it readonly its not usable but there is no styling availble/changed for readonly.

**Comment by ahnpnl** [comment]
Additional information: when inspecting DOM, I don't see the attribute `readonly` is visible on `input` tag

**Comment by tmcconechy** [comment]
Yeah i guess that part is an NG bug, combined with the fact that the readonly style doesnt exist. Sort of no one i guess needed to disable the search yet.

**Comment by tmcconechy** [comment]
Descoping this issue
