### ISSUE TITLE
DataGrid: Opening "Personalize Columns" breaks further calls to SohoMessageService

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#688]
**Describe the bug**

After opening and closing the Personalize Columns dialog on a datagrid, calls to the SohoMessageService (which uses the soho message api) fail with the following error:

```
Uncaught TypeError: Cannot read property 'element' of undefined
    at HTMLBodyElement.<anonymous> (sohoxi.js:81407)
    at HTMLBodyElement.dispatch (jquery.js:5237)
    at HTMLBodyElement.elemData.handle (jquery.js:5044)
    at Object.trigger (jquery.js:8471)
    at jQuery.fn.init.triggerHandler (jquery.js:8555)
    at HTMLDivElement.<anonymous> (sohoxi.js:58548)
    at HTMLDivElement.dispatch (jquery.js:5237)
    at HTMLDivElement.elemData.handle (jquery.js:5044)
    at Object.trigger (jquery.js:8471)
    at jQuery.fn.init.triggerHandler (jquery.js:8555)
```

**To Reproduce**

Clone `ids-enterprise-ng` repo.

Replace `datagrid-toolbar.demo.html` and `datagrid-toolbar.demo.ts` from the attached [datagrid.zip].

```sh
npm i
npm run build:lib
npm run start
```
Navigate to:  http://localhost:4200/ids-enterprise-ng-demo/datagrid-breadcrumb
Open Personalize Menu (from datagrid more menu)
Click on trash can.
Error and the application is no longer responsive.

**Expected behavior**

The message dialog should appear.

**Version**
- ids-enterprise-ng: 6.4 (master)
- ids-enterprise: ^4.25.0-dev.20191214

**Screenshots**
![image](https://user-images.githubusercontent.com/8340092/70913220-7fdbdb00-200d-11ea-86d9-e54e34abfa2c.png)

**Platform**

**Additional context**

**Comment by bthharper** [comment]
[datagrid.zip](https://github.com/infor-design/enterprise-ng/files/3968398/datagrid.zip)

**Comment by bthharper** [comment]
I tried replicating using vanilla ids-enterprise but with no luck.

**Comment by tmcconechy** [comment]
Sounds like it was erroring out by "breaks" but i did change it significantly. So hopefully ok now.
Will look at #3255 tho.

**Comment by tmcconechy** [comment]
Think this is due to recent changes?

**Comment by tmcconechy** [comment]
These
http://localhost:4200/ids-enterprise-ng-demo/datagrid-groupable
http://localhost:4200/ids-enterprise-ng-demo/datagrid-rowreorder
http://localhost:4200/ids-enterprise-ng-demo/datagrid-service
http://localhost:4200/ids-enterprise-ng-demo/datagrid-settings

Are also missing headers? Is this just me?

**Comment by bthharper** [comment]
Changing:
```javascript
$('body').off('open.datagrid');
```
to 
```javascript
$('body').off('open.datagrid').off('beforeopen.datagrid');
```
in both the OK button and the Esc key handler, fixes the problem for me.
