### ISSUE TITLE
DataGrid: 'Reset To Default' makes columns disappear and/or too wide.

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#690]
**Describe the bug**

Selecting 'Reset to Default' on a `datagrid` makes the columns wider than the default they were given when opening the page  and/or remove all the columns.

**To Reproduce**

From a clone of ids-enterprise@master.

* Edit `src\app\datagrid\datagrid-toolbar.demo.html` 
* Add 
`<li><a data-option="reset-layout" href="#">Reset to Default</a></li>` in the more popupmenu.
* Run
```sh
npm run build:lib
npm run start
```
* Navigate to http://localhost:4200/ids-enterprise-ng-demo/datagrid-breadcrumb.
* Reset the data grid.
* The columns disappear (or they columns are too wide)

**Expected behavior**

I expect the columns to reset to those previously selected and also to have the default width.

**Version**
- ids-enterprise-ng: 4.6.x
- ids-enterprise: 4.24.x

**Screenshots**

![image](https://user-images.githubusercontent.com/8340092/71022362-31efd180-20f8-11ea-945e-dfb0b90df29d.png)

**Comment by tmcconechy** [comment]
See https://github.com/infor-design/enterprise/pull/3264 @bthharper please.

**Comment by tmcconechy** [comment]
This cant be test in EP so moving to done
