### ISSUE TITLE
SohoDropdown: Rendering issue when dynamically changing options in IE

### ISSUE THREAD

**Issue by Varalaxmi26** [infor-design/enterprise-ng#697]
**Describe the bug**
In IE, Dropdown options are not rendering properly while changing dynamically. 

**To Reproduce**
1. Create a Soho Dropdown with few options.
2.  In some event, change the options 
3. The options in the dropdown will not be updated with new ones.

**Expected behavior**
Options should be updated in the dropdown

**Version**
- ids-enterprise-ng:6.1.1

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
Note: This issue doesn't exist in  ids-enterprise-ng: 5.4.2

**Comment by tmcconechy** [comment]
It appears like i can reproduce this on http://localhost:4200/ids-enterprise-ng-demo/dropdown 
If you click the add option button im expecting the options to be updated.

Can you confirm how exactly your "updating" the array?

**Comment by Varalaxmi26** [comment]
Hi, I have a scenario like, one dropdown column was existed in a table. 
And each row should show the options in the dropdown, based on the selected options of other rows i.e. the selected options of other rows should not be shown in dropdown options.
Here I am returning the options list dynamically by checking the selected options in the other rows.

**Comment by EdwardCoyle** [comment]
@tmcconechy I'm wondering if this is fixed after we merged infor-design/enterprise#3432?

**Comment by tmcconechy** [comment]
Could very well be. Seems like that would be very related. I'll test this and let you know.

**Comment by tmcconechy** [comment]
We think this issue is fixed by https://github.com/infor-design/enterprise/issues/3432 please verify on your end @Varalaxmi26 you could do this by pulling in the latest nightly 6.5.0-dev.20200207 of ids-enterprise.

Give it a shot, we think this is fixed on our end by we cant work out exactly what you did so have no tests for it.
