### ISSUE TITLE
SohoPopDownDirective - add isOpen method

### ISSUE THREAD

**Issue by ptomanek-infor** [infor-design/enterprise-ng#698]
JQuery SoHo Popdown support isOpen() however there is no such a thing in Angular wrapper.

In our specific use case we are expending popdown functionality to be closed only in specific situations. This evaluation take some time but we don't need to execute it if popdown is already closed.

**Comment by tmcconechy** [comment]
Should be a simple enough matter to add the method https://github.com/infor-design/enterprise/blob/master/src/components/popdown/popdown.js#L175 to the popdown directive.

https://github.com/infor-design/enterprise-ng/blob/master/projects/ids-enterprise-ng/src/lib/popdown/soho-popdown.d.ts#L19

Feel free to make a PR if you have the time before we can get to this.
