### ISSUE TITLE
Mobile: link with popup menu doesn't open

### ISSUE THREAD

**Issue by gushanson** [infor-design/enterprise-ng#699]
When a link, with a popupmenu, is placed within an element that itself has a popupmenu, the links menu doesn't open on click. Instead, the containers menu is opened. This occurs on mobile and can be simulated in the Chrome mobile mode.

Attached is a reproduction using the existing example file at _\src\app\context-menu\context-menu.demo.html_
[context-menu.demo.html.zip](https://github.com/infor-design/enterprise-ng/files/4044165/context-menu.demo.html.zip)

**Reproduce**
- Replace the example with the attached file as specified above.
- Build and go to http://localhost:4200/ids-enterprise-ng-demo/context-menu
- Enable mobile mode in the browser dev tools (or use actual mobile)
- Click and hold the link "I am a link with a context menu"

Expected result: Menu One is opened.
Actual: Menu Two is opened

**Comment by tmcconechy** [comment]
@gushanson i tried this against the latest master on EP and couldnt reproduce it. The first menu is opening...

![Screen Shot 2020-03-23 at 11 40 21 AM](https://user-images.githubusercontent.com/814283/77334419-2580a380-6cfb-11ea-8ba9-3653e1481c23.png)

I did update the markup a bit because the link would redirect and the popupmenu was missing li tags...

```
<div class="row"><span class="code-tag" style="margin-left: 20px;">Live Example</span>
  <div class="twelve columns" soho-context-menu menu="menu-two" style="background-color: light-grey;">
    <h2>Area with context menu</h2>
    <div class="field">
      <ul>
        <li soho-context-menu menu="menu-one">
          <a href="#">I am a link with a context menu</a>
        </li>
      </ul>
    </div>
  </div>
  <ul soho-popupmenu id="menu-one">
    <li soho-popupmenu-item><a soho-popupmenu-label  href="#">Menu One Foo</a></li>
    <li soho-popupmenu-item><a soho-popupmenu-label  href="#">Menu One Bar</a></li>
  </ul>
  <ul soho-popupmenu id="menu-two">
    <li soho-popupmenu-item><a soho-popupmenu-label  href="#">Menu Two Foo</a></li>
    <li soho-popupmenu-item><a soho-popupmenu-label  href="#">Menu Two Bar</a></li>
  </ul>
</div>
```

**Comment by volante007** [comment]
@tmcconechy We still see this issue on mobile. From your screenshot, it seems like Menu #2 is still showing, not Menu #1?

**Comment by tmcconechy** [comment]
I'll have another look. Looks like your right the other menu is opening judging be the code and screen shot, not sure what i was thinking.

**Comment by tmcconechy** [comment]
I tried this again and i pushed the example. Not seeing it yet. Can you try this @gushanson ?

- pull master in NG
- go http://localhost:4200/ids-enterprise-ng-demo/context-menu in chrome
- select devtools -> mobile -> iphone x
- reload
- scroll down
- hold the mouse on the link -> menu one opens
- hold mouse on the text -> menu two opens
