### ISSUE TITLE
SOHO-6630: DataGrid Save User Settings Problems

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#70]
1) Angular Datagrid component needs to use the grid.uniqueId() function instead of the settings.uniqueId
2) Need a function to clear a setting (use case: want activePage maintained when I drill down to a detail and navigate back, but want it cleared when I navigate from the menu)
3) Restoring a saved a filter does not appear to put the saved values in the filter row fields, resulting in the filter settings being lost after the initial data load after restoring them.  Might be an Angular specific problem

See example: Turned on filtering and added datagrid option to save settings in the attached source file from the Angular demo system

[SOHO-6630.zip](https://github.com/infor-design/enterprise-ng/files/2054987/SOHO-6630.zip)

**Comment by tmcconechy** [comment]
I think that this issue has been fixed.
