### ISSUE TITLE
Accordion: All panes are expanded and can't be closed

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise-ng#701]
**Describe the bug**
The soho-accordion component does not work in the latest release. All its panes are expanded and can't be closed /  toggled.

**To Reproduce**
1. Go to http://localhost:4200/ids-enterprise-ng-demo/accordion
Result: All panes are expanded, nothing happens when trying to close them.

**Expected behavior**
Only the second pane should be expanded in that sample, and collapse / expand should work.

**Version**
- ids-enterprise-ng: v6.3.0
- ids-enterprise: v.4.24.0

**Additional context**
The issue is not seen in the core control:
https://design.infor.com/code/ids-enterprise/latest/demo/components/accordion/example-index

The change was introduced in this commit:
https://github.com/infor-design/enterprise/commit/9e9639e0f768d39d622a26bc82d5793b4aa8e0fe#diff-75bb29fcad7b97e804de3fd00e8252d6

The accordion pane elements no longer have `display: block`. For core control it's fine, since the panes are `div` elements and will get the block display by default. For angular component, the panes are `soho-accordion-pane` elements and gets `display: inline`

**Proposed solution**
Add style to SohoAccordionPaneComponent, like
```
styles: [`
   :host {
      display: block;
   }
`]
```

**Comment by brianjuan** [comment]
Passed QA in IDS Enterprise, we've regressed Accordion and haven't found issues.
