### ISSUE TITLE
Busy indicator missing check for container

### ISSUE THREAD

**Issue by gushanson** [infor-design/enterprise-ng#703]
**Describe the bug**
There is a scenario when the busy indicator throws an error since the addScrollParent method can't find this.container.
This happens when there is a display delay and the busyindicator's parent is removed and added via *ngIf before the busyindicator is shown.

I've reproduced this in the _src/app/busyindicator/form.demo_ example.
[busyindicator.zip](https://github.com/infor-design/enterprise-ng/files/4052831/busyindicator.zip)

**To Reproduce**
1. Replaced the zipped files in the repo as noted above.
2. Build, run and go to http://localhost:4200/ids-enterprise-ng-demo/busyindicator
3. Click Toggle Busy button
4. Click Toggle Area-button
5. Click Toggle Area-button
6. Click Toggle Busy-button
Steps 3-6 must be done within the display delay time of 3000ms.

**Expected behavior**
Expecting no error but an error is thrown.

**Version**
- ids-enterprise-ng: 6.3.0

**Screenshots**
![busy-scroll-bug](https://user-images.githubusercontent.com/4129417/72245668-5a80c380-35f1-11ea-909f-7efa8a694812.gif)

**Platform**
- Windows 10
- Chrome, Edge

**Additional context**
In our application we set the display delay to 0 in most places, but due to timing issues (I assume) this error still occur occasionally.

**Comment by tmcconechy** [comment]
moving to down as cant be regression tests alone but we will do a focus on regression testing for busyindictaor once more issues on it are solved this sprint
