### ISSUE TITLE
SohoDatagridComponent missing types

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise-ng#704]
**Describe the bug**
We have to use //@ts-ignore option when we want to call SohoDatagrid validation because the types are missing property "datagrid" 

**To Reproduce**
1. Go to SohoDatagridComponent typings
2. See missing property datagrid while in the code the property exists 

**Expected behavior**
SohoDatagridComponent types would reflect implementation

**Version**
- ids-enterprise-ng: 6.2.0

**Comment by tmcconechy** [comment]
Which types do you mean exactly @Fruko ?

**Comment by Fruko** [comment]
oh sorry @tmcconechy we use this to validate grid rows
```
this.sohoDatagrid.datagrid.validateAll()
```
however TS complains datagrid is private field. Maybe it was missing in previous versions, we have updated to latest and this is the error we are getting. Maybe we are accessing the validation wrong? Coudln't find anything in the sample app

**Comment by tmcconechy** [comment]
Ok will add these...
