### ISSUE TITLE
Broken accordion - 6.3.0

### ISSUE THREAD

**Issue by James-Carlin** [infor-design/enterprise-ng#707]
**Describe the bug**
The accordion panels are expanded by default and cannot be collapsed.

**To Reproduce**
1. Go to enterprise-ng demo
2. Click on accordion
3. See error

**Expected behavior**
Accordion panels should be collapsed based on configuration and expand/collapse should work.

**Version**
- ids-enterprise-ng: [v6.3.0]

**Comment by tmcconechy** [comment]
Duplicate of https://github.com/infor-design/enterprise-ng/issues/701

**Comment by tmcconechy** [comment]
This was found and fixed in 4.25/6.4 (4.25 now has a beta but 6.4 beta will be Friday).

**Comment by tmcconechy** [comment]
marking as it was fixed on #701
