### ISSUE TITLE
Modal: expose an API to allow set css class on modal class in a generic way

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#708]
**Is your feature request related to a problem? Please describe.**
At the moment, adding css class via `cssClass`  property is repetitive. Imagine an application has a lot of modal dialogs, each modal dialog has the same extra css class. It means one has to add `cssClass` everywhere in the application for all modal dialogs.

**Describe the solution you'd like**
Expose an API to set `cssClass` for all modal dialogs. Inspired by Angular CDK `OverlayContainer`

![image](https://user-images.githubusercontent.com/27772165/72529812-51505a80-386e-11ea-8828-175e53f0722b.png)

In this picture `OverlayContainer` exposes `getContainerElement()`. User can use this method to add extra class name to overlay container wrapper. This will have an effect for all modal dialogs which use `OverlayContainer`. `SohoModalDialogService` can do similar thing.

**Describe alternatives you've considered**
Listen to modal dialog open event and use js to manipulate class name.

**Additional context**
**N.A.**

**Comment by tmcconechy** [comment]
cc @EdwardCoyle will this be fixed by the work your doing maybe?

**Comment by tmcconechy** [comment]
Descoping this for now
