### ISSUE TITLE
SOHO-6339: SoHo Icon directive from angular components not working if <base href> tag value is anything apart from '/'

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#71]
We are facing issues related to svg icons in firefox. Icons show up in IE and Chrome, but not only on FF.

One resolution that I can find is, setting {{<base href="/" />}} in landing page for ng app, and that works too.

But problem is, for us, we have to set base href as "/App/" because of legacy application reason.
Now this issue can be fixed, if we modify {{SohoIconUseComponent}} as:

{code:title=SohoIconUseComponent|borderStyle=solid}
export class SohoIconUseComponent {
  private baseUrl: string;
  @HostBinding('attr.xmlns:xlink') xmlnsXlink = 'http://www.w3.org/1999/xlink';
  @HostBinding('attr.xlink:href') get href(): string {
    return this.baseUrl + '#' + this.icon;
  }

  @Input() icon: string;

  constructor() {
        // Current URL, without the hash
        this.baseUrl = window.location.href.replace(window.location.hash, "");
  }
}
{code}

**Comment by bthharper** [comment]
Try adding to `main.ts`: 

```typescript
export function getBaseUrl() {
  return document.getElementsByTagName('base')[0].href;
}

const providers = [
  { provide: 'BASE_URL', useFactory: getBaseUrl, deps: [] }
];
```

Then you can pull in the URL using a provider.

```typescript
 constructor(http: HttpClient, @Inject('BASE_URL') baseUrl: string) {
```

Make sure you have the correct href for development in `index.html`.
```html
<head>
  <meta charset="utf-8">
  <title>AppName</title>
  <base href="/your_app_vdir">
```

Also, when you build make sure to run this build command:

```json
"build": "ng build --extract-css  --base-href /your_app_vdir/",
```

**Comment by tmcconechy** [comment]
Thanks Theo, Closing, please note if any further issues...
