### ISSUE TITLE
Datagrid: Expander formatter doesn't sanitize/escape HTML tags

### ISSUE THREAD

**Issue by albinbergvall** [infor-design/enterprise-ng#710]
**Describe the bug**
When using the Expander formatter in a datagrid, it's possible to inject HTML elements into the DOM since they are not properly sanitized/escaped. Since HTML elements can be injected, it's also possible to inject scripts through event handlers. 

**To Reproduce**
1. Open enterprise NG project.
2. Go to src/app/datagrid/datagrid-demo-service.ts
3. Modify the product name of one if the compressors where the data is set to contain an HTML element. For example: `<a href="javascript:alert('Injected')">Click me!</a>`
https://github.com/infor-design/enterprise-ng/blob/70e3eca0d854cc6443206e9fb554687e7841b91b/src/app/datagrid/datagrid-demo.service.ts#L175
4. Open Datagrid - Groups demo
5. The HTML in the product name is injected into the DOM

**Expected behavior**
HTML elements are sanitized/escaped.

**Version**
- ids-enterprise-ng: v.6.3.0

**Screenshots**
![image](https://user-images.githubusercontent.com/30404138/72785912-92f55280-3c2c-11ea-91ab-23870a2486a4.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 79.0.3945.130 (Official Build) (64-bit)

**Additional context**
I've only been able to recreate this in enterprise-NG. In enterprise, the HTML tags are properly sanitized.

**Comment by albinbergvall** [comment]
I think i got a bit ahead of my self on this ticket. The demo I linked doesn't use the expander formatter, but rather the template formatter, which shouldn't escape HTML tags. It appears that the expander formatter actually escapes HTML in most cases, which is good.

The case when HTML isn't escaped is when the field property of a column references a field of an object property in the data set. This is what we've done in one of our data grids, which seems to be the reason why that field wasn't sanitized. Example:
```
// Title is escaped
const columns: SohoDataGridColumn = [{
  field: "title"
}];
const dataset = [ {
  title: "SomeTitle"
};

// Title is not escaped
const columns: SohoDataGridColumn = [{
field: "data.title"
}]
const dataset = [ {
  data {
    title: "SomeTitle"
  }
}
```
@tmcconechy should this case be handled by IDS as well, or is this the expected behavior? If this should be fixed, I'll update the ticket but otherwise you can close it.

**Comment by tmcconechy** [comment]
Yes if using the object/field notation does not escape. We should probably fix that.
Do you think we should close this and you raise a new issue in the EP project with slightly different details?

**Comment by albinbergvall** [comment]
Sure let's do that.
