### ISSUE TITLE
Extend soho-alert to support setting error indicator on container

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#711]
**Is your feature request related to a problem? Please describe.**

Adding an error message on an `input` component (decorated with the `soho-alert` directive) does not set an error indicator on any parent container.  

This is especially a problem when using reactive forms and angular validation which does not fire or integrate with the jQuery validation routines.  

**Describe the solution you'd like**

When a error/message is added to a `soho-alert` directive, any corresponding component should be marked as in error.

Possibly, by calling `setIconOnParent` with the corresponding jQueryElement.

**Describe alternatives you've considered**

None

**Additional context**

**Comment by tmcconechy** [comment]
cc @fitzorama

**Comment by bthharper** [comment]
@tmcconechy - looking a the the code in `validation.jquery.js` I can see that `setIconOnParent(field, settings.type);` is called in `removeMessage`.

Could we add a call in addMessage(s)?

**Comment by tmcconechy** [comment]
yes we can try.

**Comment by bthharper** [comment]
Thanks, It feels adding this to the ng components would poke around under the hood.

**Comment by tmcconechy** [comment]
Can you make an issue for that?

**Comment by bthharper** [comment]
The issue could be written as:  

> Parent tab component is not marked with an error icon after calling `addMessage(s)` on a contained field.

**Comment by tmcconechy** [comment]
Ok, maybe im not totally clear? Would the goal  of https://github.com/infor-design/enterprise-ng/issues/711#issuecomment-579280328 by ifxing above? Or getting rid of a console log deprecation warning?

**Comment by bthharper** [comment]
If setting a message on a component could also ensure any suitable parent of that component (e.g. a tab) is also marked in error then that would fix this issue.

**Comment by bthharper** [comment]
No sure about the deprecate warnings.

**Comment by jbrcna** [comment]
**QA PASSED**
tagging this ticket as Passed with Observation
v4.27.0-dev
https://master-enterprise.demo.design.infor.com/components/validation/test-error-on-tab-with-addmessage.html
`Subtle / Dark`
![image](https://user-images.githubusercontent.com/56722184/77520236-dd5caf00-6ebb-11ea-909a-ce9b18185c5b.png)
