### ISSUE TITLE
SOHO-6278: Improve custom Datagrid editors interface

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#72]
SohoDataGridColumnEditorFunction should be a Typescript class (abstract) to ensure that init(), val(), focus(), destroy() are implemented for custom editors (see Editors.Input or others in datagrid.js).
Check SohoDataGridColumnEditorFunction type signature. Is it OK that the function's return type is string? Shouldn't it be void?

**Comment by tmcconechy** [comment]
Descoping this issue for now. Not enough time and this is very old
