### ISSUE TITLE
Alert: Need support for the id property

### ISSUE THREAD

**Issue by boehmd1** [infor-design/enterprise-ng#725]
**Describe the bug**
Need to support the id property on the SohoAlertOptions

**To Reproduce**
Not applicable, make the property available for consumers to use.

**Expected behavior**
Expect the id to be passed to soho enterprise if the setter is set.

**Version**
- ids-enterprise-ng :6.5.x

**Screenshots**

**Platform**
all

**Additional context**

**Comment by bthharper** [comment]
Should this be closed now?
