### ISSUE TITLE
Textarea: Autogrow does not work in Angular when content arrives

### ISSUE THREAD

**Issue by rleedy** [infor-design/enterprise-ng#732]
From the chat:
Any one have idea how the autogrow property on  soho-textarea works? In my case it is setting an initial height  which is irrespective of the content in the textarea , also if i edit the textarea it is auto growing again. How do i make it autogrow based on text area content on intial loading.

Tim: Maybe in angular this doesnt work as the content is there later? You could try calling updated after the content is updated or maybe we need to tweak the directive a bit

**Comment by tmcconechy** [comment]
Found a fix for this. Will push a PR once https://github.com/infor-design/enterprise/issues/3471 is merged

**Comment by tmcconechy** [comment]
Added a PR to fix this that will work with 4.26 EP (current dev build)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. However, another issue was found and logged as GitHub ticket number: https://github.com/infor-design/enterprise-ng/issues/738
