### ISSUE TITLE
Datagrid: Width of columns becomes wider after selecting 'Reset to Default'

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#735]
**Describe the bug**

When displaying a grid where the total width of the columns exceeds the available space, the columns are reduced to fix the screen.

![image](https://user-images.githubusercontent.com/8340092/74642739-75ec6a80-516b-11ea-8cb0-db4dadae4ec2.png)

However, after selecting "Reset to Default" from the grids personalisation menu, the columns are resized to their maximum widths, which is not the default.

![image](https://user-images.githubusercontent.com/8340092/74642810-93213900-516b-11ea-9e92-09c9b3ed4ad2.png)

**To Reproduce**
1.  Goto http://ukfavwbrelease2.infor.com/sunsystems-security-ng
2. Logon on as admin (no password)
3. Select "..." on data grid and choose 'Reset to Default'
4. See Groups column is now very wide, and also a scrollbar has been added to the bottom.

**Expected behavior**

I would expect the the action to leave the columns unchanged, unless of course that had been resized.

**Version**
- ids-enterprise-ng: 7.0.0@dev

**Screenshots**

**Platform**
 - Chrome and Chromium Edge

**Additional context**

None

**Comment by tmcconechy** [comment]
If i get the columns and settings and data your using can i reproduce this in EP? Also wonder if this issue also fixes this case https://github.com/infor-design/enterprise/pull/3494

**Comment by bthharper** [comment]
Retried with the latest (2020-02-20T14:54:25.001Z) but still get the issue that my columns resize to the content, not the default width.

Maybe related to the data not be loaded when the datagrid is originally loaded.

**Comment by janahintal** [comment]
QA Passed. This issue is now resolved. Thanks.
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/test-columns-width.html?theme=uplift&variant=light across all platform.
