### ISSUE TITLE
Toolbar more button acts as submit button.

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#742]
**Describe the bug**

Pressing the **Enter** key within an input control activates the **more** menu / button on a flex-toolbar, if present.

**Expected behavior**

Pressing **Enter** should not activate the more menu.

**Version**
- ids-enterprise-ng: 7.0.0

**Screenshots**

![image](https://user-images.githubusercontent.com/8340092/74850877-623f3080-5332-11ea-91ab-57b4bd139fcf.png)

**Platform**
- All

**Comment by tmcconechy** [comment]
Think maybe we should check all `<button` elements and add `type="button"` especially if in a component.

**Comment by bthharper** [comment]
The issue was caused by the toolbar being inside a form, and the flex toolbar's more button not being generated with type="button".
