### ISSUE TITLE
Modal services breaks when using the options() method

### ISSUE THREAD

**Issue by edgarinfor** [infor-design/enterprise-ng#753]
**UPDATE:**
Issue appears reproduce-able with the old **SohoModalDialogService** and **SohoModalDialogRef** combination as well.

**Describe the bug**
It seems that the new **SohoModalService** breaks when using the **options()** on the returned **SohoModalRef**. 

**To Reproduce**
Edit the **modal-dialog.demo.ts** and replace the code starting on line 56 with the following code then, launch the demo and click the "Open New Modal" button:
```javascript
this.dialogRef = this.newModalService
      .modal<ExampleModalDialogComponent>(ExampleModalDialogComponent)
      .options({
        buttons: [
          {
            id: 'cancel-button',
            text: Soho.Locale.translate('Cancel'),
            click: (e) => { this.dialogRef.close('CANCEL'); }
          },
          {
            text: 'Submit', click: (e, modal) => {
              this.dialogRef.close(this.dialogRef.componentDialog.model.comment);
            }, isDefault: true
          }
        ],
        title: this.title
      })
      .isAlert(this.isAlert)
      .apply((componentDialog) => {
        componentDialog.model.header = 'Header Text Update!!';
      })
      .open();
```
All that we are doing is passing the buttons and title via the settings rather than using the separate methods.

**Expected behavior**
The demo page goes blank/breaks instead of opening the dialog.

**Version**
- ids-enterprise-ng: 7.0.0-dev.20200219

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Latest

**Additional context**
The options method is present and used in the new **SohoModalRef**.

**Comment by tmcconechy** [comment]
@nbcp can the new service you added support options? Or does that introduce back the memory leak.
Not 100% sure this is "breaking" because its a new service vs the old one.

Suggestions?

**Comment by bthharper** [comment]
@tmcconechy  - both the new and original modal have the same issue with options.  The memory leak is fixed in both versions.
