### ISSUE TITLE
Component library does not support strict compiler option

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#755]
**Describe the bug**

TypeScript 2.3 introduced a new --strict compiler option that enables a number of other compiler options related to stricter type checking.  These can be enabled in the `tsconfig.json` file in the root of the project.

However, the current code base does not compile when this option is set.

This makes it difficult (if not impossible) for downstream teams to enabling strict type checking in their applications.

**To Reproduce**

Checkout latest code from http://

Edit the `tsconfig.json` in the root folder, adding the following to the existing code block:

```json
 "compilerOptions": {
    "strict": true,
   },
```

Then run:

```sh
npm i
npm run build:lib
npm run build
```

This fails with numerous errors.

**Expected behavior**

It should be possible to compile both the components and the demo application in strict mode.

**Version**
- ids-enterprise-ng: v7.0.0

**Screenshots**

N/A

**Platform**
 - All

**Additional context**

N/A

**Comment by tmcconechy** [comment]
Any ideas what we can do about this? I can take a look if given a hint?

**Comment by bthharper** [comment]
I have a branch I was working on : see https://github.com/infor-design/enterprise-ng/tree/empty-message-strict-error.  Just fixing all the issues.

**Comment by tmcconechy** [comment]
So we just need to update that branch and then fix any errors? Or what should i test.

**Comment by bthharper** [comment]
There's are still numerous issues, let me take a quick look.

**Comment by bthharper** [comment]
There are still lots of issues, which although not complicated take time.  It's not that important an issue to rush though.

**Comment by ahnpnl** [comment]
FYI https://blog.angular.io/angular-cli-strict-mode-c94ba5965f63

**Comment by bthharper** [comment]
@ahnpnl - feel free to grab the branch and fixup some of the issues, I've not got a lot of time to spend on this at the moment.  @tmcconechy did you get much further with this one?

**Comment by tmcconechy** [comment]
I think we should first fix the NG 10 and get that in. And then restart this on a fresh branch. The branch has gotten out of date. Im comfortable on this one but would like to see master updated to NG 10 first and redo the branch.

When thats done perhaps 2 people can divide and  conquer - the branch is just out of date so this has to be done fairly quickly i think.

**Comment by tmcconechy** [comment]
so depends on #858
