### ISSUE TITLE
Typing issues in soho-locale.d.ts

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#756]
**Describe the bug**

- Typing of [Soho.Locale.currentLanguage.messages](https://github.com/infor-design/enterprise-ng/blob/60bb1f08a7940617ca29a941fc10aad20c588974/projects/ids-enterprise-ng/src/lib/locale/soho-locale.d.ts#L19) is not `SohoLocaleMessage[]`
- Missing typing for [Soho.Locale.currentLocale.data](https://github.com/infor-design/enterprise-ng/blob/60bb1f08a7940617ca29a941fc10aad20c588974/projects/ids-enterprise-ng/src/lib/locale/soho-locale.d.ts#L11)

**To Reproduce**
- For `Soho.Locale.currentLanguage.mesages`: use Chrome Dev Tools on an app which has `ids-enterprise-ng` to inspect the value and compare with the typing in source code.
- For `Soho.Locale.currentLocale.data`: use IDE and no properties suggestion.

**Expected behavior**
- For `Soho.Locale.currentLanguage.messages`: the correct type could be
```
interface SohoLocaleMessage {
	[key: string]: {
		id: string
		value: string
		comment?: string // this should be optional, comment property is not always there
	}
}
```
- For `Soho.Locale.currentLocale.data`: new interface should be introduced to provide better typings.

**Version**
- ids-enterprise-ng: master branch

**Screenshots**
For `Soho.Locale.currentLanguage.messages`
![image](https://user-images.githubusercontent.com/27772165/75977348-7bbcac80-5edc-11ea-87be-d0b1a5d911e4.png)

**Platform**
 - Device (if applicable): **N.A.**
 - OS Version: **N.A.**
 - Browser Name: Chrome
 - Browser Version: Version 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
Please also revise all the typings in [Soho Locale](https://github.com/infor-design/enterprise-ng/blob/60bb1f08a7940617ca29a941fc10aad20c588974/projects/ids-enterprise-ng/src/lib/locale/soho-locale.d.ts)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
