### ISSUE TITLE
Lookup: Count off with paging and contextualToolbar

### ISSUE THREAD

**Issue by darinw** [infor-design/enterprise-ng#758]
**Describe the bug**
When using the lookup with paging and contextualToolbar the selected count double selects all selected items on page 2 or greater when the lookup is relaunched.

![image](https://user-images.githubusercontent.com/92472/76111590-2a78ef80-5fa6-11ea-9ebf-bc3105b879d0.png)

**To Reproduce**
1. open the code for src\app\lookup\lookup.demo.html
2. add the following code to the lookup input labeled **Products (Multi Select)**
`[options]="{
              paging: true,
              pagesize: 2,
              toolbar: {
                contextualToolbar: true
              }
            }"`
3. Launch the app and see the **Products (Multi Select)** is empty
![image](https://user-images.githubusercontent.com/92472/76111993-f81bc200-5fa6-11ea-9850-54106694e40c.png)
4. open the lookup and select an item from page 2 or greater and apply the changes.
![image](https://user-images.githubusercontent.com/92472/76112074-1ed9f880-5fa7-11ea-8bf3-07b66e9b21d3.png)
5. Open the lookup and see the selected count is incorrect.
![image](https://user-images.githubusercontent.com/92472/76112398-be978680-5fa7-11ea-8d6d-b2a452d11a7a.png)

**Expected behavior**
The count should be correct

**Version**
found on ids-enterprise-ng:  v6.4.2 and dev(as of 3/6/2020)

**Comment by tmcconechy** [comment]
When i added those options i didnt just get a contextualToolbar. Any other steps i need?
Was thinking i could reproduce this on http://localhost:4000/components/lookup/example-multiselect

One thing around server side selection is that the selections will clear on changing page unless you choose to manage this server side, as only one page is ever fetched.

**Comment by tmcconechy** [comment]
Get anywhere with this one @ericangeles ? I did complete #236 FYI

**Comment by jbrcna** [comment]
**QA Passed** with observation
selected items on page 2 or greater could not be cleared/deselected unless you deselect all. Also, in Firefox, the lookup looks bigger.
v4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/lookup/test-paging-with-count.html
![Large GIF (1602x722)](https://user-images.githubusercontent.com/56722184/88756712-e970ba00-d196-11ea-93f6-36d610917b7c.gif)

**Comment by tmcconechy** [comment]
@jbrcna i think thats fine for now as this only works on one page

**Comment by darinw** [comment]
@tmcconechy our use case involves a lookup with multiple pages. Is this something that is not supported and wont be?

**Comment by tmcconechy** [comment]
@darinw it can work for multiple pages. I'm just talking about that some examples will reset the selections across pages. Unless you use the selectRowsAcrossPages option.

**Comment by jbrcna** [comment]
Noted on this @tmcconechy . thank you the clarification.
