### ISSUE TITLE
[Suggestion] CHANGELOG conventions and GitHub issue template

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#76]
Hi,

Since SOHO has moved to GitHub, I propose 2 ideas:
- `CHANGELOG.md` should have the similar conventions like other GitHub projects. For example: https://github.com/facebook/jest/blob/master/CHANGELOG.md .  There are some tools too to support format `CHANGELOG.md`. The current `CHANGELOG.md` can improve its readability and let the users know which are the new changes in which release.
- A template to create GitHub issue would be nice. For example: go to https://github.com/angular/angular/issues and create an issue. There will be a template and the user just needs to fill in it. This will help a lot for the SOHO team to get all the information.

**Comment by tmcconechy** [comment]
@clepore I thought we added the issue template already that we discussed.

@ahnpnl Yes we also thought about moving the changelog into a more github friendly format and perhaps on the releases page https://github.com/infor-design/enterprise/releases we'll perhaps work on that at the end of this release.

**Comment by ahnpnl** [comment]
hi @tmcconechy , I think I can help with the `CHANGELOG`. However, I do not know exactly which features/fixes/chores per release version. If you have a summary somewhere, I'm happy to make a PR to adjust the `CHANGELOG`

**Comment by clepore** [comment]
We do have templates in NG now for issues and PRs. I'm not quite sure why @ahnpnl didnt see those. 

@ahnpnl What changelog tools do you recommend?

**Comment by ahnpnl** [comment]
Hi @clepore, as far as I'm awared there are no tools to help generating .md file. Most of the time I usually follow the format that the repository already defined and linting will help to have a strict format for all .md files (including README etc). You can take a look at Jest repository and check the scripts in their package.json. They have a script to lint .md files.

**Comment by tmcconechy** [comment]
So the Jest example is not manual? If you wanted to put together a pull request we could take a look at it? I think the changelog looks good in comparison to what we are doing now.

**Comment by ahnpnl** [comment]
No, Jest example is manually written by the contributors but they always have run lint md to be able to keep the format consistent. I can send you an email of the `CHANGELOG` in one of the ION library and you can check it out 👍

**Comment by tmcconechy** [comment]
Link was https://oxford.awsdev.infor.com/ion-ui/ion-ng-libraries/blob/master/projects/ion-desk-integration/CHANGELOG.md (not internal infor link) but is similar to https://github.com/facebook/jest/blob/master/CHANGELOG.md
