### ISSUE TITLE
Popdown: Closes when a containing lookup dialog opens

### ISSUE THREAD

**Issue by edgarinfor** [infor-design/enterprise-ng#760]
**Describe the bug**
When a popdown contains a lookup field and, the lookup dialog is open (e.g, clicking the trigger) the popdown will close automatically.

If "keepOpen" is used, the popdown will stay open but, the user will have to explicitly close the popdown after dealing with the lookup, which might not be the desired UX.

**To Reproduce**
You need to set up a popdown component containing a lookup inside OR use the provided files and place them inside .\src\app\popdown then re-build, launch the demo.
[popdown.zip](https://github.com/infor-design/enterprise-ng/files/4343886/popdown.zip)

**Expected behavior**
Just like a dropdown (select box), opening a lookup shouldn't close the popdown.

**Version**
- ids-enterprise-ng: 7.0.0-dev.20200219

**Screenshots**
![soho_popdown_demo_01](https://user-images.githubusercontent.com/39097500/76865503-3338b380-6839-11ea-8ab8-da0fa96007f7.png)

![soho_popdown_demo_02](https://user-images.githubusercontent.com/39097500/76865527-3b90ee80-6839-11ea-8b32-780daf160593.png)

![soho_popdown_demo_03](https://user-images.githubusercontent.com/39097500/76865541-40ee3900-6839-11ea-9331-94918c19167f.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Latest

**Comment by EdwardCoyle** [comment]
Created a test branch for this:  [`ng760-popdown-lookup-integration`](https://github.com/infor-design/enterprise/tree/ng760-popdown-lookup-integration)

- Pull that branch, build, run the demoapp
- Open http://localhost:4000/components/popdown/test-trigger-lookup.html
- Click the button to open the popdown
- Click the lookup field's trigger button

The lookup opens, then the Popdown closes.  There's also an issue where the `z-index` of the Popdown causes it to sit over top of the Modal's overlay.

**Comment by janahintal** [comment]
QA Passed. Thank you! 
Verified in :
https://4290-beta0-enterprise.demo.design.infor.com/components/popdown/test-contains-lookup.html?theme=uplift&variant=light&colors=0066D4
