### ISSUE TITLE
Tooltip: Nested tooltips inside the Popover will close it

### ISSUE THREAD

**Issue by edgarinfor** [infor-design/enterprise-ng#764]
**Describe the bug**
When using **soho-tooltip [popover]="true"**, if any element inside the #popover-content uses a **soho-tooltip**, the popover will be closed when that tool-tip is shown; and, from that point on, the behavior becomes erratic.

![soho_tooltip_nested_01](https://user-images.githubusercontent.com/39097500/76886905-d26ca380-6857-11ea-922c-0f2748010fab.png)

![soho_tooltip_nested_02](https://user-images.githubusercontent.com/39097500/76886914-d5679400-6857-11ea-8fe6-ae595be39486.png)

**To Reproduce**
Launch the NG demo app, open the Tooltip demo source and add a soho-tooltip to any element of the #popover-content.

In the example above, we added it to the "Total" TH tag for demonstration...

**Expected behavior**
Tooltips inside the popover should be possible as it was when using the _deprecated_ **soho-popdown** directive instead.

**Version**
- ids-enterprise-ng: 7.0.0-dev.20200219

**Platform**
 - OS Version: Windows 
 - Browser Name: Chrome
 - Browser Version: Latest

**Comment by tmcconechy** [comment]
Descoping this issue for now

**Comment by edgarinfor** [comment]
Hi, @tmcconechy, is there any reason why this is being descoped?

It is obvious that it is a broken functionality of the library and, this prevented us from using the popover for a feature of WFM.

**Comment by tmcconechy** [comment]
Basically in the interest of time since its been a year and we cant seem to find time to get to it. Its also pretty tricky since the popover and tooltip share code. Because of this when we made the new popover and tooltip in the web component project we did them seperate so this issue is fixed there (even though it is not ready for release in full yet) it is fixed there.

We can reopen this but not sure when we would find time for it... How bad do you need it given that we fixed in the next gen version?

**Comment by edgarinfor** [comment]
Basically, we have a "hack" (wrapper) in place from before which uses the deprecated "popdown" and, last year when trying to upgrade SoHo and replace it with the "popover", we tried to do it natively and remove these hacks but, this prevented us from doing that.

Our Angular projects keep growing so, ideally, we should replace it as soon as it's available but, Angular development is measured in **eons**. I don't know if we will be able to adopt the Web Component version at this point for the existing projects so, if it could be fixed on the NG project, it'll be better for us.

**Comment by tmcconechy** [comment]
OK we can try - it could turn out the rewrite/separation is the only way. But will check if any easy fixes

**Comment by katieinfor** [comment]
https://github.com/infor-design/enterprise/issues/5197

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
