### ISSUE TITLE
[Bug] support creating Angular library using Angular CLI

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#78]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
With the `@infor/sohoxi-angular` v4.6, it is still possible to create an Angular library using `Angular CLI` v6. However, when upgrading to `ids-enterprise-ng` v4.7.0-rc, it is not possible anymore.

## Expected behavior
`4.7.0-rc` should allow the users to create an Angular library using `Angular CLI` v6

## Minimal reproduction of the problem with instructions
Here is the URL to the library using `@infor/sohoxi-angular` v4.6: https://oxford.awsdev.infor.com/ion-ui/ion-ng-libraries
- Run `npm run clean-build` or `yarn clean-build`
- Observe that build is successfully

Here is the repo with `ids-enterprise-ng` 4.7.0-rc: https://oxford.awsdev.infor.com/A.Pham/4.7.0-bug-create-library
- Download and install dependencies for the repo.
- Run `ng build test-lib --prod`
- Observe that in the console throws out lots of errors

## What is the motivation / use case for changing the behavior?
Since Angular v6 released, it supports a nice way to create a library using CLI. We should support that.

## Environment

<pre><code>
Angular version: 6.0.0
ids-enterprise-ng version: 4.7.0-rc

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.2
- Platform:  Windows 10 x64

Others:
**N.A.**
</code></pre>

**Comment by tmcconechy** [comment]
See also https://github.com/infor-design/enterprise-ng/issues/52 this may be a duplicate of that.

**Comment by ahnpnl** [comment]
Close as already mentioned in #52

**Comment by bthharper** [comment]
@ahnpnl Just to check you were able to pull in the `ids-enterprise-ng` package and create a production build?  If not then this is a slightly different issue to providing better "library" support.

**Comment by ahnpnl** [comment]
Hi @bthharper , I was able to pull `ids-enterprise-ng` package and can create a production build for the app, but creating a production build for the library it is not possible.
