### ISSUE TITLE
Accordion: On a dynamic accordion we cannot call expand

### ISSUE THREAD

**Issue by carerer2** [infor-design/enterprise-ng#783]
**Describe the bug**
The dynamic accordion has an issue to expand the header with the expand/collapse api. As we cannot obtain the listing of headers.
[Desktop.zip](https://github.com/infor-design/enterprise-ng/files/4453510/Desktop.zip)

**To Reproduce**
1. Unzip these files and drop into the accordion folder
1. Click the Do Expand button and debug
1. Notice no header is found so expand cannot be called

**Expected behavior**
The 1st accordion header should be expanded with the api call.

**Suggested Fix**
Change the expand and collapse API in EP to take a string ID. Make this change in NG too.

**Version**
- ids-enterprise-ng: [e.g. v4.27]

**Platform**
 - OS Version: Windows 10
 - Browser Name chrome

**Additional context**

**Comment by tmcconechy** [comment]
For test information please see https://github.com/infor-design/enterprise/pull/3959

**Comment by jbrcna** [comment]
**QA Passed**
v4.29.0-beta0
https://4290-beta0-enterprise.demo.design.infor.com/components/accordion/test-expand-collapse-by-id.html
