### ISSUE TITLE
Datagrid: Lookup select is not setting value in cell

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#785]
Describe the bug
Value is not being set into the datagrid cell following a lookup select.

To Reproduce
1. Go to DataGrid - Lookup Click Function (http://localhost:4200/ids-enterprise-ng-demo/#/ids-enterprise-ng-demo/datagrid-lookup-click-function)
2. Click on a cell in the Lookup Click column (last column)
3. Click on the lookup icon when the cell is active
4. From the select dialog, pick a new value

Expected behavior
New selected value is in the cell

Version
- sohoxi.js => v4.28.0-dev

**Comment by claudenbach** [comment]
![GitNG-785](https://user-images.githubusercontent.com/39804038/79137854-1c727780-7d79-11ea-8652-64ef573e977f.gif)

**Comment by claudenbach** [comment]
This is a regression.

**Comment by tmcconechy** [comment]
Yes its doing it in 4.27 final https://4270-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup.html

**Comment by lipetzan** [comment]
Add some automation here Tim?

**Comment by tmcconechy** [comment]
Yes this needs a test - i'll check why it wasnt caught, thought there was one.

**Comment by tmcconechy** [comment]
Fixed in https://github.com/infor-design/enterprise/commit/92350d7192710ddd9fd2117b975e1389be2eb98c

**Comment by tmcconechy** [comment]
Attention QA:
- this can be reproduced by:
- go to https://4270-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup.html
- click in the second lookup cell so it goes in edit mode
- now click the editor and select a row
- row data  should be inserted
- leave the cell and hover the cell
- click the trigger while out of the cell
- row data should be inserted

This now has a regression test but should add this to the QA test cases.

**Comment by pwpatton** [comment]
Ok, so we need to just wait or a 6.6 patch release then?

**Comment by tmcconechy** [comment]
Yes, was sort of waiting on cheryls other issue, seems like she solved it except for a more specific minor resize issue. So I think that’s it for now??

**Comment by claudenbach** [comment]
Yes, I'm good.

**Comment by janahintal** [comment]
QA Passed. Will now move to Done. Thanks. 
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup.html?theme=uplift&variant=light across all platform. Will retest when beta is deployed.

**Comment by tmcconechy** [comment]
Ok i made a new 6.6.2 its ready now
