### ISSUE TITLE
Datagrid: Change definition of fixedRowHeight and SohoDataGridRowHeight

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#786]
Describe the bug
Need to change the definition of fixedRowHeight and SohoDataGridRowHeight for use in angular.

Currently defined in soho-datagrid.d.ts:
fixedRowHeight?: number;

type SohoDataGridRowHeight = 'short' | 'medium' | 'normal';

Should be defined as:
fixedRowHeight?: number | SohoDataGridRowHeight;

type SohoDataGridRowHeight = 'short' | 'medium' | 'normal' | 'auto';

Version
sohoxi.js => v4.28.0-dev

**Comment by tmcconechy** [comment]
I did this already here for 7.x https://github.com/infor-design/enterprise-ng/commit/7028c478ae62eec91ca4f313927492f74f009db4
And here for 6.6x https://github.com/infor-design/enterprise-ng/commit/19ab224af049db791db87cbf1f81a22e84420860

Look as you expect? These will be in the next 6.6 patch with other fixes we made. We can discuss that offline.

**Comment by claudenbach** [comment]
Yes, the changes will work.  I was able to get this to render properly with these changes in Landmark.  Only issue is the jerkiness of resizing columns that are not fixed.  Thanks!

**Comment by claudenbach** [comment]
![GitNG-786](https://user-images.githubusercontent.com/39804038/79160987-573bd600-7da0-11ea-8336-ba01827b12b3.gif)

**Comment by tmcconechy** [comment]
I think thats a separate issue. Sometimes the trick there is removing older inline widths. This could be something else tho? Can you raise something else adding the changes we need to make to see this (or PR them against the other issue)?
