### ISSUE TITLE
Slider: Not possible to easily select a value with steps

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise-ng#787]
**Describe the bug**
When the slider has steps (1) and the user is dragging the slider it almost always jump to one value left or right

**To Reproduce**
1. Use the following settings
2. See the video below

```
<label for="slider-regular">Regular</label>
   <input soho-slider
          [value]="[model]"
          id="slider-regular"
          name="slider-regular"
          min="70"
          max="99"
          [(ngModel)]="model"
          [step]="1"
          type="range">
```

1. See the model in ts file for example `model = 90;`
1. observe like in this video where I am trying to select value 82:
![4AutMaGkDf](https://user-images.githubusercontent.com/11279863/79218480-c8d35d00-7e50-11ea-9406-0af0055e4c20.gif)

**Expected behavior**
Selecting value on slider with ticks should not jump to a different value.

**Version**
- ids-enterprise-ng: 6.5.0

**Comment by tmcconechy** [comment]
Is ticks= 1 what you really want? I think in that case you might as well not use ticks at all. If its snapping to 1 it's probably miscalculating as that wasn't a test case we thought of. 

That being said we maybe still have a bug for ticks 2 or lower in percentage to the overall slider values. That should be investigated

Ticks - Example with bigger range
https://master-enterprise.demo.design.infor.com/components/slider/example-colors-and-ticks.html

Normal - Same as ticks (1)
https://master-enterprise.demo.design.infor.com/components/slider/example-index.html

Either that or if you provide ticks 1 it should work as if no ticks are set?

**Comment by hohnzy** [comment]
When not using steps it result in values we don't want. The value is rounded when using the persist tooltip, but then the slider is not performing well. Also the performance is bad when using change event...
![image](https://user-images.githubusercontent.com/11279863/79239792-45763380-7e71-11ea-9338-2b9c253915ec.png)

**Comment by tmcconechy** [comment]
Ok, interesting. Will have to investigate that further in the EP example i dont see decimals https://master-enterprise.demo.design.infor.com/components/slider/example-index.html 

Change event should fire just once. Maybe its a ngZone issue. Will put this in next sprint and have a deeper look at this.

**Comment by hohnzy** [comment]
The performance issue is reduced if you are avoiding [(ngModel)].

**Comment by jbrcna** [comment]
**QA Passed**
This is now working as expected
v4.29.0-dev
https://master-enterprise.demo.design.infor.com/components/slider/test-change-event.html
