### ISSUE TITLE
Slider: dragend event

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise-ng#788]
**Is your feature request related to a problem? Please describe.**
We would like to handle the value when the user release the mouse button after setting the value in slider. It is not needed to listen on change - which is triggered too often. Check attached video

**Describe the solution you'd like**
Would be nice to have some _dragend_ event.

**Additional context**
![VuoaAfehdP](https://user-images.githubusercontent.com/11279863/79243337-c9cab580-7e75-11ea-8fc5-743c90530e48.gif)

**Comment by tmcconechy** [comment]
Also the component should have the ngZone changes done to other NG components. I think thats partly why it fires so much.

**Comment by pwpatton** [comment]
For landmark apps angular is also much slower with the dev tools window open for some reason. Does this go faster once you close dev tools?

**Comment by pwpatton** [comment]
@tmcconechy  that's exactly why that's so slow I believe. Angular is just drawing WAY too much

**Comment by hohnzy** [comment]
@pwpatton its better without console, but i wouldnt say its huge difference. well if the you try to console.log the change event.... :)

**Comment by pwpatton** [comment]
I think the bigger issues will be not using runOutsideAngular when calling into soho/ep code because any event or timeout in soho/ep will cause a change detection and check/render cycle.

**Comment by bthharper** [comment]
Maybe the value updates could be `debounced` too to avoid every event causing a redraw?

**Comment by tmcconechy** [comment]
Im changing this so that the change event fires on drag end. But there is a `slidestop` event this fires on dragend too. So you could use that.

**Comment by hohnzy** [comment]
I dont see any slidestop event on slider component.

**Comment by tmcconechy** [comment]
Ok yeah i see its there https://github.com/infor-design/enterprise/blob/master/src/components/slider/slider.js#L565 but not in the NG component. I can added it as well with this.

**Comment by jbrcna** [comment]
**QA Passed**
This is now working as expected
v4.29.0-dev
https://master-enterprise.demo.design.infor.com/components/slider/test-change-event.html
