### ISSUE TITLE
General: Add Schematics for ng-add & ng-update

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-ng#793]
**Is your feature request related to a problem? Please describe.**
Adding the `ids-enterprise-ng` library project involves a lot of steps (described in the QUICKSTART docs), involving adding the library, modifying angular.json, tsconfig & template files etc. This process is not really intuitive, and the setup may vary between versions. Additionally, the setup for one version might differ from another, which leads to problems when upgrading.

**Describe the solution you'd like**
Add schematics for `ng add` and `ng update`.

`ng add ids-enterprise-ng` would automate the steps described in QUICKSTART, such that no further configuration is needed. Example output:

```bash
> ng add ids-enterprise-ng 
- Installed package ids-enterprise-ng
- Added scripts to angular.json
- Added assets to angular.json
- Added style ref to index.html
- Added SohoComponentsModule to app.module.ts
- Done!
```

Possible options could be:
- Theme (light/dark/uplift)?
- Add support for translations?

`ng update ids-enterprise-ng` could then be used if the setup is changed, for instance to remove/change modifications to angular.json done by previous installations. Or to "fix" breaking changes in the library API.

This is what angular material provides https://material.angular.io/guide/schematics something similar and similar docs seems like a good idea.

**Describe alternatives you've considered**
I have experimented with this in another project: https://github.com/infor-cloud/m3-h5-sdk/blob/schematics/schematics/src/add-ids/index.ts, but I think it would be better if this feature was added to the ids-enterprise-ng library.

**Comment by tmcconechy** [comment]
This is a great idea. I was looking at this one day and thinking about uses too. I think maybe we should initially come up with a good list of things we want to do with it. Not sure if all this is possible but.

- add ids-ng to a cli project with locale translation code (really mostly required for locale)
- add ids-ng to a non cli project with locale translation code
- add ids-ng with a theme switcher

All good ideas? Is it only possible to use this for adding and updating the lib? Or can it be used for anything more?

If you got it working a PR and docs would be fantastic.

**Comment by bthharper** [comment]
@tmcconechy - I am sure we had an issue for this already, but can't find it.  It's a great idea, just never got around to looking into it.

**Comment by tmcconechy** [comment]
The other issue was #38 which i dropped out having it sit for so long. So let's keep this. Added a relevant link above.

**Comment by tmcconechy** [comment]
Going to descope this for now. As the next version doesnt really rely on wrappers so I dont think this would be needed.
