### ISSUE TITLE
Datagrid: Overlapping icons and text

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise-ng#796]
**Describe the bug**
Datagrid: Overlapping icons and text

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup.html?theme=uplift&variant=light
2. Open the lookup field in Product Id column
3. Select '11111111111'
4. Hover again in lookup filter to see the icon and ellipsis overlapping

**Expected behavior**
Icons and Text should not overlap 

**Version**
IDS 4.28x Dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/79571244-75ca0600-80ed-11ea-83fa-2d67341db4ac.png)

**Platform**
All Browser and OS. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Same issue as https://github.com/infor-design/enterprise/issues/3765
