### ISSUE TITLE
SohoContextMenuDirective missing "close" API

### ISSUE THREAD

**Issue by zli1-infor** [infor-design/enterprise-ng#798]
**Is your feature request related to a problem? Please describe.**
Soho context menu cannot be closed manually/programmatically.

**Describe the solution you'd like**
**SohoContextMenuDirective** is missing the "close" method API but, it should have been provided similar to the **SohoPopupMenuComponent**.

**Comment by tmcconechy** [comment]
Yeah that should be doable

**Comment by edgarinfor** [comment]
@tmcconechy could it be possible to create a GitHub label that we could assign to track our issues?
Perhaps, something like "product: WFM"?
