### ISSUE TITLE
Menubutton: Initially disabled button not working when enabled

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise-ng#799]
**Describe the bug**
An initially disabled `soho-menu-button`, e.g. `[disabled]="isDisabled"` where `isDisabled` is initially set to true, does not work when later enabled. Its menu does not open when clicked.

Cause: For an initially disabled menu button, the class "is-disabled" is added to the button (by the underlying jQuery control?), in addition to the regular disabled attribute. When later enabled, "is-disabled" remains and the button does not work. The css issue is there for any button, but not causing any bad effects for a regular button (click event still firing).    

This is probably an issue in the underlying jQuery control(s), but I have only reproduced for the angular components.
 
**To Reproduce**
1. Modify menu-button.demo.ts & html so that the buttons have a disabled binding
2. The boolean bound to [disabled] shall be set to true initially
3. Toggle the disabled binding using e.g. some other button.
2. Click on menu button

**Expected behavior**
Menu should open

**Actual behavior**
Menu does not open, "is-disabled" class stuck on button.

**Version**
- ids-enterprise-ng: 7.0.2
- ids-enterprise: 4.27.3

**Screenshots**
![issue](https://user-images.githubusercontent.com/1101770/79974183-242ccd00-8499-11ea-8a1c-f532098be4c8.gif)

**Additional context**
The "is-disabled" class is only being added if the button is initially disabled. If the button is initially enabled, then made disabled, class is not added. Can class be skipped always?

**Comment by tmcconechy** [comment]
I think there is a fault in this logic (when disabled is "gone" / not there). https://github.com/infor-design/enterprise/blob/master/src/components/button/button.js#L99

I dont think is-disabled should be needed either. Looks like its only used for the popupmenu and possibly the toolbar? Is that right @EdwardCoyle ?

**Comment by bthharper** [comment]
I have seen the same issue too, we worked around this by adding the following into the angular components init method.

```typescript
// @todo FIXME hack to remove the is-disabled class from the button - not sure why the underlying
// component is not removing the is-disabled class itself.
$('button:not(disabled)').removeClass('is-disabled');
```
