### ISSUE TITLE
Masthead: Support `toolbar-flex` and `img` inside masthead / soho-menu-button

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#800]
**Is your feature request related to a problem? Please describe.**

We have a requirement to display a profile picture on the masthead, similar to the user profile picture in MS Teams.

There are a number of useful photo styles defined which work on forms, however they are not suitable for the toolbars (specifically the masthead) or drop down menus.
https://master-enterprise.demo.design.infor.com/components/images/example-photos.html.

We have been unable to get the image to display correct, and have resorted to using:

```html
<div class="buttonset">
    <img class="masthead-profile-picture" [src]="photoString$ | async">
    <button soho-menu-button menu="action-popupmenu" id="user-signout" (selected)="onSelected($event)"></button>
    <ul soho-popupmenu id="action-popupmenu">
      <li>
        <a soho-popupmenu-label>
          <img id="picture" class="drop-down-profile-picture" [src]="photoString$ | async">
          {{getLoginUserName()}}
        </a>
      </li>
      <li soho-popupmenu-separator></li>
      <li soho-popupmenu-item><a id="signout">Sign out</a></li>
    </ul>
  </div>
}
```

**Describe the solution you'd like**

We'd like to be able to add an image inside the button and for it to be handled correctly.

**Describe alternatives you've considered**

We tried to move the image as above, but there is now a noticeable gap and other layout issues.

**Comment by bthharper** [comment]
![image](https://user-images.githubusercontent.com/8340092/80000144-aecef580-84b4-11ea-8756-04971875c90d.png)

**Comment by bthharper** [comment]
The above image shows how using a `soho-toolbar-flex` in the masthead results in misalignment when displayed.

```html
<div soho-toolbar-flex role="toolbar">
  <soho-toolbar-flex-section [isTitle]="true">
    <button soho-button="icon" id="logo-homepage" icon="logo" tabindex="0">
      <span class="audible">Go To Home</span>
    </button>
    <h1 class="masthead-appname">{{'AppMastheadAppName' | sohoTranslate}}</h1>
  </soho-toolbar-flex-section>

  <soho-toolbar-flex-section [isButtonSet]="true">
    <img class="masthead-profile-picture" [src]="photoString$ | async">
    <button soho-menu-button menu="action-popupmenu" id="user-signout" (selected)="onSelected($event)"></button>
    <ul soho-popupmenu id="action-popupmenu">
      <li>
        <a soho-popupmenu-label>
          <img id="picture" class="drop-down-profile-picture" [src]="photoString$ | async" alt="image">
          {{getLoginUserName()}}
        </a>
      </li>
      <li soho-popupmenu-separator></li>
      <li soho-popupmenu-item><a id="signout">Sign out</a></li>
    </ul>
  </soho-toolbar-flex-section>
</div>
```

**Comment by bthharper** [comment]
One of the main issue have have here is the location of the drop down menu, for the popup-menu.  

![image](https://user-images.githubusercontent.com/8340092/80119354-7ea15880-8581-11ea-8196-0f6b8a3c3381.png)

**Comment by bthharper** [comment]
![image](https://user-images.githubusercontent.com/8340092/80119514-b6100500-8581-11ea-86de-a0f4af669460.png)

**Comment by bthharper** [comment]
```
element.style {
    top: 50px;
    left: -999px;
}
```
The left is not calculated quite right.

**Comment by EdwardCoyle** [comment]
@tmcconechy we may want to raise an EP issue for building some samples/testing Masthead/Toolbar Flex integration.  Not sure I've fully explored that.

**Comment by tmcconechy** [comment]
Yeah i think the flex integration is not there. I just said add it on this issue.

**Comment by tmcconechy** [comment]
cc @inforandy i think this needs design feedback right?

**Comment by inforandy** [comment]
@tmcconechy yup, got it here https://jira.infor.com/browse/HLPE-451

thanks @tmcconechy

**Comment by lucacolumbu** [comment]
I added more context, and comments about this here https://jira.infor.com/browse/HLPE-453

**Comment by tmcconechy** [comment]
Updated design is on https://jira.infor.com/browse/HLPE-419?focusedCommentId=6640039&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-6640039 and in https://www.figma.com/file/NxW02D7lFiACMTtTPV0eWW/InforOS-Revised-Ming.le?node-id=1%3A2

**Comment by janahintal** [comment]
This issue is now resolved. 
Verified in
https://4310-beta1-enterprise.demo.design.infor.com/components/masthead/example-photos.html?locale=ar-EG
https://4310-beta1-enterprise.demo.design.infor.com/components/masthead/example-index.html
https://4310-beta1-enterprise.demo.design.infor.com/components/images/example-photos.html
https://4310-beta1-enterprise.demo.design.infor.com/components/images/example-photos.html


![image](https://user-images.githubusercontent.com/45757016/88916974-93386f80-d299-11ea-99f4-515b95eb8670.png)
