### ISSUE TITLE
Images: Support `photo` styles on soho-toolbars and soho-menus

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#802]
**Is your feature request related to a problem? Please describe.**

There are a number of useful photo styles defined which work on forms, however they are not suitable for the toolbars (specifically the masthead) or drop down menus.

See 
https://master-enterprise.demo.design.infor.com/components/images/example-photos.html.

**Describe the solution you'd like**

I would like to have suitable classes and components to represent these photos so they can be used in the masthead and in a profile selector.

This is the workaround we are using at this time,  but it would be preferable to have these styles provided.

```html
<soho-toolbar-flex-section [isButtonSet]="true">
    <button soho-menu-button menu="action-popupmenu" id="user-signout" (selected)="onSelected($event)">
      <div class="image-user-status">
        <img [src]="photoString$ | async" alt="image" style="width: 28px; height: 28px; border-radius: 50%;">
        <svg class="icon" focusable="false" aria-hidden="true" role="presentation"
           style="width: 10px; height: 10px; margin-left: -12px; top: 2px">
          <use href="#icon-user-status-available"></use>
        </svg>
      </div>
    </button>
    <ul soho-popupmenu id="action-popupmenu">
      <li>
        <a soho-popupmenu-label>
          <img id="picture" class="drop-down-profile-picture" [src]="photoString$ | async" alt="image">
          {{getLoginUserName()}}
        </a>
      </li>
      <li soho-popupmenu-separator></li>
      <li soho-popupmenu-item><a id="signout">Sign out</a></li>
    </ul>
  </soho-toolbar-flex-section>
```

**Describe alternatives you've considered**

None

**Comment by tmcconechy** [comment]
This is probably an EP issue but will leave in here for now

**Comment by tmcconechy** [comment]
@inforandy - might need design feedback 👍

**Comment by inforandy** [comment]
got it here https://jira.infor.com/browse/HLPE-453 thanks @tmcconechy

**Comment by tmcconechy** [comment]
Pretty much the same issue as https://github.com/infor-design/enterprise-ng/issues/800 so closing this one in favor of that.
