### ISSUE TITLE
DataGrid: gridOptions config "hidePagerOnOnePage" in typescript and columns config in html template fails the datagrid

### ISSUE THREAD

**Issue by hemantg05** [infor-design/enterprise-ng#805]
**Describe the bug**
"hidePagerOnOnePage": true in gridOptions in typescript and columns config in html template don't work together and fails the DataGrid.
.ts
```
  setupGridOptions() {
    this.gridOptions = {
      hidePagerOnOnePage: true
    };
  }

  getColumns() {
    if (this.mode === 'edit') {
      return COLUMNS_EDIT_MODE;
    }
    return COLUMNS_VIEW_MODE;
  }
```
.html
```
<div
  soho-datagrid
  [gridOptions]="gridOptions"
  [columns]="getColumns()"
>
```

**To Reproduce**
1. Write the datagrid code in above way
2. Run the application 
3. Notice that datagrid is not shown at all
4. Check console. You will see various javascript errors

**Expected behavior**
The above combination of gridOptions in .ts and other configs in html template should work

**Version**
- ids-enterprise-ng: ^6.4.2

**Screenshots**
Console Error
![image](https://user-images.githubusercontent.com/1594815/80214188-ad2f3a00-863a-11ea-8c47-c413fb20cb11.png)

**Platform**
 - MacBook Pro
 - OS Version: macOS Mojave
 - Browser Name: Chrome
 - Browser Version: Version 81.0.4044.113 (Official Build) (64-bit)

**Additional context**
Infor PIM
We had to put "hidePagerOnOnePage" in gridOptions in .ts file owing to issue https://github.com/infor-design/enterprise-ng/issues/771. Now if we remove the "hidePagerOnOnePage" from gridOptions, it works but we see the pager in on page or in empty state. The combination of different ways of configurations (some in .ts and some in .html) should work.

**Comment by tmcconechy** [comment]
Descoping this issue for now
