### ISSUE TITLE
Pager: Need a way to be able to add a custom button in soho-standalone-pager

### ISSUE THREAD

**Issue by nbcp** [infor-design/enterprise-ng#815]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
This is for a landmark feature called [collapsible lists](https://jira.lawson.com/browse/LMCLIENT-29061) in which we would need a button on the pager to expand/collapse the list. 

**preview:**
![image](https://user-images.githubusercontent.com/11013464/81895585-2f30d400-95e5-11ea-984e-95f2938084ac.png)
![image](https://user-images.githubusercontent.com/11013464/81895793-aebea300-95e5-11ea-9334-ffa0591ee360.png)

**Describe alternatives you've considered**
The pager looks like a component to simplify setting tooltips, enabling/disabling for a specific set of buttons. I think it would be more flexible if we'll make it more like the toolbar where we can just put in what buttons we wanted to include, and let the developers manage the clicks and button disabling themselves.

**Comment by pwpatton** [comment]
Can’t we just do this part in landmark by constraining the width of the standalone pager and placing the chevron buttons on the markup ourselves?

**Comment by tmcconechy** [comment]
Just wondering if we should make this a generic Soho official feature. (Slide in panel component maybe?)

But the part about just adding an icon could be done by making the pager into a toolbar with external templating. Or of course just force it in.

Does this need designs?

**Comment by pwpatton** [comment]
@tmcconechy I think it's worth a discussion. We have our own slider implementation using the classes of list-detail but not the functionality. This was required for some funky nesting we did with list-detail within a list-detail (beyond what we did for the filter list stuff). 

It's possible if we could deprecate the filter list stuff in EP if no one is using it and if we are completely off of it. @nbcp do you know if we still use parts of the filter list stuff in EP (the classes maybe)?

@nbcp I think the first thing we should do is implement it by forcing the stands-lone pager over with css and managing the chevron collapsing ourselves if possible. Since we have our own lm-drawer implementation for the list-detail pattern. If we discover a need for a larger collapse pattern in EP we could add it to their backlog. But first I think we should implement it and demo to Tim.

**Comment by EdwardCoyle** [comment]
> The pager looks like a component to simplify setting tooltips, enabling/disabling for a specific set of buttons. I think it would be more flexible if we'll make it more like the toolbar where we can just put in what buttons we wanted to include, and let the developers manage the clicks and button disabling themselves.

To approach it this way, we'd also have to separate out paging functionality into a service with events, api, etc.  The pager is a specific type of toolbar for sure, but it's also currently got all the logic for "paging" a dataset built into it.

**Comment by tmcconechy** [comment]
Ok, I re-thinking. Your right. I think maybe the drawer is a separate concern. The drawer thing has nothing to do with paging...

I.E. The pager stays as is. But just size it to account for a button on the right and add the functionality of the button

**Comment by pwpatton** [comment]
@EdwardCoyle I've always been a fan of simplifying the pager component into a simple "slave" component. The implementations using the pager component would have responsible for values in that pager (tooltips, which page your one if that enabled, etc..). To me, it seems too intertwined with the implementation of its usages (datagrid, listview, etc...).

**Comment by nbcp** [comment]
> It's possible if we could deprecate the filter list stuff in EP if no one is using it and if we are completely off of it. @nbcp do you know if we still use parts of the filter list stuff in EP (the classes maybe)?

@pwpatton Actually, not so sure, but looking at it it's more relying on list-detail for its toggle mechanism. For its look, it is mostly accordion with some css style overrides.

>@nbcp I think the first thing we should do is implement it by forcing the stands-lone pager over with css and managing the chevron collapsing ourselves since we have our own lm-drawer implementation for the list-detail pattern. If we discover a need for a larger collapse pattern in EP we could add it to their backlog. But first I think we should implement it and demo to Tim.

Sounds good, I'll try to work on this on landmark first and see how well it would work even when theme changes.

**Comment by vonnyw** [comment]
@tmcconechy Which sprint will this be scheduled for?

**Comment by tmcconechy** [comment]
@nbcp were you working on this (its assigned to you). If not we can add it in August sprint and do it? Unless @nbcp is already working on something?

**Comment by nbcp** [comment]
Yup I already started working on this in landmark. And since this feature is not going to be used elsewhere (at least for now), going to close this ticket as longer needed.
