### ISSUE TITLE
Datagrid: Browser context menu is also shown upon right click 

### ISSUE THREAD

**Issue by sheilamaejornadal** [infor-design/enterprise-ng#817]
**Describe the bug**
Upon right click on the datagrid, the browser context menu is being displayed on top of the datagrid context menu.

**To Reproduce**
1. Run enterprise-ng project
2. Open Datagrid - Dynamic component
3. Right click on the datagrid
4. See issue

**Expected behavior**
The browser context menu should not be displayed.

**Version**
- ids-enterprise: 7.2.0-dev.20200505
- ids-enterprise-ng: 7.1.0 

**Platform**
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: Version 81.0.4044.138 (Official Build) (64-bit)

**Additional context**
See attached gif for the actual issue: 
![datagrid-contextmenu-issue](https://user-images.githubusercontent.com/52568990/82048296-0264e580-96e7-11ea-8f8e-2c624c27292d.gif)

**Comment by tmcconechy** [comment]
This is probably just an issue in the example that can be corrected by doing `event.stopPropagation()` in the context menu handler. You could try that.

The example in general is working in EP https://master-enterprise.demo.design.infor.com/components/datagrid/test-contextmenu.html

**Comment by sheilamaejornadal** [comment]
I already tried using `event.stopPropagation()` and `event.preventDefault()` but it didn't work.

Our project currently transitioned to angular 9 version. That's when we encountered the issue.

In your example, is it already using angular 9?

**Comment by tmcconechy** [comment]
That example is using the underlying component library underneath the angular wrappers. So that part is working just the angular example isnt. Giving it a quick look...

**Comment by tmcconechy** [comment]
Took a look and the fix was to add this https://github.com/infor-design/enterprise-ng/pull/819/files#diff-26611e4207bfbfbefce6997927da91d6R99 to the example. Which you can do on on your end. Note: Need to call preventDefault on "orginalEvent"
