### ISSUE TITLE
Datagrid: Treegrid, value returned to tooltip function not accurate

### ISSUE THREAD

**Issue by waltersh790824** [infor-design/enterprise-ng#827]
**Describe the bug**
When using a Datagrid with the treegrid flag set to true, and with a tooltip function for a given column, the value received by the function does not match the actual value of the cell being hovered over.

**To Reproduce**
1. Create a datagrid and set treegrid = true
2. For any column, add a tooltip function that returns the value of the highlighted cell
3. Note if the tooltip text being shown matches the cell being hovered over.

**Expected behavior**
When I have a tooltip function set up on a column, and I hover over a cell in that column, I expect the value provided to my tooltip via function arguments to match the value displayed in the cell being hovered over.  In other words, the value argument below should match the text being displayed in the cell being hovered over.

`        tooltip: function(row, cell, value) {
          return value;
        },`

**Version**
- ids-enterprise-ng: 6.6.4

**Screenshots**
![image](https://user-images.githubusercontent.com/25912716/83157388-89479400-a0d1-11ea-8cb6-c8800bcb6e0a.png)

**Platform**
 - OS Version: Windows 10 Enterprise, build 1909
 - Browser Name 
Chrome Version 81.0.4044.138 (Official Build) (64-bit)
Firefox 76.0.1 (64-bit)

**Here are my datagrid and column definitions**
`      this._columns.push({id: 'ProductDisplayName', name: 'Product', field: 'ProductDisplayName', expanded: 'collapsed', filterType: 'text', sortable: false, width: '80%', 
        formatter: Soho.Formatters.Tree
      });
      this._columns.push({id: 'Status', name: 'Status', field: 'Status', sortable: false, align: 'center', width: '20%', 
        formatter: this.getCustomStatusFormatter, 
        click: (event, args) => {
          if (args[0] && args[0].item.ProductName) {
            if (this.isPublicView) {
              this.openRegionAndProductStatusDetailsModal(this.publicViewRegion.Name, args[0].item.ProductName);
            } else {
              this.openProductStatusDetailsModal(args[0].item.ProductName);
            }
          }
        },
        tooltip: function(row, cell, value) {
          return value;
        },
      });`

`            <div soho-datagrid 
                [data]="dataForGrid | async"
                [columns]="this.getColumns"
                selectable="single"
                treeGrid="true"
                filterable="true"
                filterWhenTyping="true"
                enableTooltips="true">
            </div>`

**Comment by tmcconechy** [comment]
Please use the bug reporting template https://github.com/infor-design/enterprise-ng/issues/new/choose

i think that the problem here is simply that the tooltip function isnt getting the proper depth context of the tree. Perhaps also attach the datagrid settings and data so we can reproduce this.

In addition what do you want the tooltip to say?

**Comment by waltersh790824** [comment]
Hey, thanks for the template!  I've updated the original post with much more information.  Please let me know if I can clarify anything or provide any more information.

**Comment by jbrcna** [comment]
**QA Passed**
v4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-tooltip.html
![image](https://user-images.githubusercontent.com/56722184/87401796-37a98900-c5ed-11ea-988a-1a8e524b5b85.png)
![image](https://user-images.githubusercontent.com/56722184/87401827-41cb8780-c5ed-11ea-9e43-694f5ece5f0c.png)
![image](https://user-images.githubusercontent.com/56722184/87401724-1ba5e780-c5ed-11ea-8f87-e46c1cc4b952.png)
