### ISSUE TITLE
Datagrid: the api for setDirtyIndicator is missing the optional fourth argument

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#829]
Describe the bug
The fourth optional argument to setDirtyIndicator isn't exposed in enterprise-ng.

It's defined as:
setDirtyIndicator(row: number, cell: number, toggle: boolean): void;

When it should be defined as:
setDirtyIndicator(row: number, cell: number, toggle: boolean, data?: any): void;
 
datagrid.js defines the API to be
  /**
   *  Set a cell to dirty and add the dirty icon visually.
   * @param {number} row The row index
   * @param {number} cell The cell index
   * @param {boolean} toggle True to set it and false to remove it
   * @param {object} data Adds dirty data to the internal tracker
   */
  setDirtyIndicator(row, cell, toggle, data)

**Comment by tmcconechy** [comment]
I think i was thinking no one would need that parameter as its internally called. Do you need it? Wanna try a PR?

**Comment by claudenbach** [comment]
Here's the background on what I'm trying to accomplish.  Perhaps you have a better idea?

In Landmark we have a concept of a copy row.  The user selects a row and a new row is added, copying cell values from the selected row.  This all works great but the expectation is that the newly created copied row is dirty.  When using dirtyRows() the newly created copied row is not dirty.

The only way I could find to make the copied row dirty is to use 
        const data = { originalVal: 0, value: targetRow.price, isDirty: true };
        gridApi.setDirtyIndicator(0, 3, true, data);

I've created a sample to illustrate.

**Comment by claudenbach** [comment]
[GitNT-829.zip](https://github.com/infor-design/enterprise-ng/files/4730547/GitNT-829.zip)

**Comment by tmcconechy** [comment]
That might be a valid case for it. Sounds like it to me. Sort of what we used it for internally. Well if you intend to use it lets add it then? Not harm having it.

What do you think about her use case @deep7102 ? Any other ideas?

**Comment by deep7102** [comment]
Yeah, that is looks fine to me and good way to go for this case.

**Comment by vonnyw** [comment]
@tmcconechy Which sprint is this scheduled for?

**Comment by tmcconechy** [comment]
Think we can fit this in 4.31 as it is small

**Comment by pwpatton** [comment]
@tmcconechy I can make this change for ng that goes out against 4.30. What version is that atm, is that on master or a branch?

**Comment by tmcconechy** [comment]
Master of https://github.com/infor-design/enterprise-ng will be out with 4.30 should do it

**Comment by pwpatton** [comment]
sounds good, I'll get that in this week.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
