### ISSUE TITLE
SohoBlockGrid: Missing Paging, Pagesize types and example

### ISSUE THREAD

**Issue by Jagannath-hub** [infor-design/enterprise-ng#836]
**Describe the bug**
SohoBlockGrid doesnot have Paging, Pagesize features like the SohoDataGrid. We noticed the types in the block grid EP componant for paging have not been added to angular. 

**To Reproduce**
Please resync the types for block grid
Make sure its zone enabled
Add an example like https://master-enterprise.demo.design.infor.com/components/blockgrid/example-paging.html -> perhaps using an NG loop to add the data

**Expected behavior**
SohoBlockGrid should have Paging, Pagesize like the EP Component

**Version**
- ids-enterprise-ng: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by pwpatton** [comment]
Highly recommend using

**Comment by pwpatton** [comment]
sorry, clicked something wrong. didn't mean to close.

**Comment by pwpatton** [comment]
I would like to see the pager bar be used stand alone and not be part of any other component. The implementer would hook up the events and settings and manage a more simple version of the pager ( a slave component so to speak). This is what landmark is doing right now with block grid and stand alone pager and it works great. I think the issue right now is that this only works with standalone pager and it's not fully implemented for page number, etc... it only has next/prev/first/last and pagesizechooser.

**Comment by tmcconechy** [comment]
Problem is it already is part of it. But you have a point @Jagannath-hub can maybe try and work with the standalone pager example and handle the paging logic manually.

**Comment by EdwardCoyle** [comment]
Raised infor-design/enterprise#4204 for a small bug in detection of which records to display in the Blockgrid.

**Comment by janahintal** [comment]
Hello, the paging now exist in https://master-enterprise.demo.design.infor.com/components/blockgrid/example-paging.html?theme=uplift&variant=dark&colors=0066D4. However the first & last button is not working. 
![image](https://user-images.githubusercontent.com/45757016/88912976-b3b0fb80-d292-11ea-9b0b-d06db1039667.png)
