### ISSUE TITLE
Datagrid: depricated pager exists in the soho-datagrid.d.ts

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise-ng#841]
**Is your feature request related to a problem? Please describe.**
should depricated properties still exist in the components definition?

  /**
   * Reference to pager.
   *  @deprecated use pagerAPI
   */
  pager: SohoPagerStatic;

**Describe the solution you'd like**
The component types assist in the writing of the typescript, so if a depricated property is still on the component it is possible to compile the code but only find the deprication on the client side.

**Comment by tmcconechy** [comment]
So what’s the suggestion? Actually remove anything deprecated? Usually what we have done is give notice on them. I’m not certain this one is used much.

See also #222

**Comment by marknolaninfor** [comment]
@tmcconechy 

The pager was depricated about a year, replace with pagerAPI, and the correct warning was displayed for a period informing that it will be removed but now it is nolonger depricated as it has been removed.

**Comment by marknolaninfor** [comment]
Something like the following should work while an item is being deprecated 
  /**
   * Reference to pager.
   *  @deprecated use pagerAPI
   */
    pager: SohoPagerStatic | null;

This can then be overridden in a solution, to stop devs from attempting to reuse depricated item.

interface SohoDataGridStatic {
   pager: null;
}

You could even use an interface called SohoDepricated so that the type is clear instead of null.

**Comment by tmcconechy** [comment]
OK, also we are adding strict types https://github.com/infor-design/enterprise-ng/issues/755 which would do what you saying.
