### ISSUE TITLE
Datepicker: Unable to reselect the previously selected date after clearing value in ngModel

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise-ng#853]
**Describe the bug**
Unable to reselect the previously selected date after clearing the value in ngModel. 

[datepicker.zip](https://github.com/infor-design/enterprise-ng/files/4815210/datepicker.zip)

**To Reproduce**
1. Unzip the above datepicker.zip file and apply the datepicker.demo.html and datepicker.demo.ts to the demo application
2. Run the demo application
3. Navigate to the Date Picker demo
4. Click on the Show Model button to display the model values; the State Change field and the standard model value should have the same value
5. For the State Change field, open the date picker and select Today
6. The State Change field and the standard model value should have the same value
7. Click the Save button to set the standard model value to an empty string
8. The State Change field and the standard model value should have the same value (empty string)
9.  For the State Change field, open the date picker and select Today again
10. Issue > the component displays today's date, but the standard model value remains an empty string

**Expected behavior**
The standard model value should be updated with the value.

**Version**
- ids-enterprise-ng: 7.1.3

**Screenshots**
![datepicker](https://user-images.githubusercontent.com/20212079/85328415-52795980-b496-11ea-9e1e-0984be848755.gif)

**Platform**
 - All

**Additional context**
If a different date is selected, the model value is updated correctly, and if the original date is selected again afterwards, the model is updated correctly.

**Comment by vonnyw** [comment]
@tmcconechy Can you please include this in June sprint? Thanks

**Comment by tmcconechy** [comment]
Do you have a fix? We are finishing this sprint in a day or two.

**Comment by tmcconechy** [comment]
Tracked this down. More simply the change event is not firing when the value is blank.

1. go to http://localhost:4000/components/datepicker/test-change-event.html
2. blank out the field
3. open the picker and press today -> no change is firing

**Comment by jbrcna** [comment]
**QA Passed**
https://4300-beta0-enterprise.demo.design.infor.com/components/datepicker/test-change-event.html
![image](https://user-images.githubusercontent.com/56722184/86122745-e5576b00-bb0a-11ea-8a11-b3bf45f0ddfd.png)

https://4300-beta0-enterprise.demo.design.infor.com/components/datepicker/example-range.html
![image](https://user-images.githubusercontent.com/56722184/86122992-4da64c80-bb0b-11ea-82a0-ca3e0122a2ed.png)
