### ISSUE TITLE
DataGrid: Horizontal scroll bar does not move automatically when reordering columns

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#854]
**Describe the bug**

Open a data grid example, e.g. XXXX in the **ids-enterprise-ng** demo app and add all columns via Personalize Column, there is horizontal scroll bar in the grid. 

Select one grid header to reorder, the horizontal scroll bar does not move to right or left automatically to complete the reorder is the target is outside the viewport.

**To Reproduce**
_Configuration Prerequisites_
Clone, compile and run `ids-enterprise-ng`

_Steps_
1. Navigate to the datagrid demo XXXX
2. Add all columns via Personalize Column, with the horizontal scroll bar is in the left of the grid
2. Select one header to reorder and attempt to move after a header that is not visible - i.e. off the right of the window.

_Actual Result_
The horizontal scroll bar does not move to right or left automatically and user cannot complete reorder in one operation

**Expected behavior**

The horizontal scroll bar can move to right or left automatically when user drag the column to the rightmost or leftmost of the screen

**Version**
- ids-enterprise-ng: 7.2.4

**Screenshots**

**Platform**
 - Chrome (latest)

**Additional context**
 N/A

**Comment by bthharper** [comment]
I noticed that if the datagrid does not fill the window (which normally it would) then drop locator icons (?) appear outside the datagrid.

**Comment by bthharper** [comment]
[IDS Enterprise - Angular Components - Work - Microsoft​ Edge 2020-06-23 09-38-17.zip](https://github.com/infor-design/enterprise-ng/files/4818210/IDS.Enterprise.-.Angular.Components.-.Work.-.Microsoft.Edge.2020-06-23.09-38-17.zip)

**Comment by tmcconechy** [comment]
Can this be reproduce on any of the EP examples?

**Comment by tmcconechy** [comment]
Descoping this issue unable to fix right now
