### ISSUE TITLE
Soho Input cannot be disabled using FormGroup

### ISSUE THREAD

**Issue by tomjohn9** [infor-design/enterprise-ng#86]
Steps to reproduce:
* Have Component with template with input `<input formControlName="count" soho-input>`
* Use following body of component .ts  
```
formGroup: FormGroup;
model: {
    count: number
  } = {
    count: 10
  };

  constructor(private formBuilder: FormBuilder) {
    this.formGroup = this.createForm();
    this.formGroup.disable();
  }

  private createForm() {
    return this.formBuilder.group({
      count: [this.model.count]
    });
  }
```

**Expected result**:
  input component is disabled

**Actual result:**
  input component is enabled

**Guidelines:**
got from channel chat - can help
The hook between an angular component and the jQuery widget does not handle disable requests.  Specifically, the components needs to override the following ControlValueAccessor method:

```
/**
 * This function is called when the control status changes to or from "DISABLED".
 * Depending on the value, it will enable or disable the appropriate DOM element.
 *
 * @param isDisabled
 */
 setDisabledState(isDisabled: boolean): void {
   // NOP
 }
```

**Comment by bthharper** [comment]
I have a fix for this on my fork, however all other controls that implement the ControlValueAccessor need to be updated so will take a little longer.

**Comment by tmcconechy** [comment]
This seems ok to me if noted in the changelog.

**Comment by bthharper** [comment]
@tmcconechy do we assign these for QA?

**Comment by tmcconechy** [comment]
We dont have a way for functional QA to QA any of the angular stuff at the moment. QA is crowd sourced among our teams for this part. But working on that. So just close the issue for now.
