### ISSUE TITLE
Tabs: Does not respond to element resize

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-ng#860]
**Describe the bug**
The tabs component does not detect when the element has been resized, causing the "more" menu, separator and gradient to appear even when all the tabs can clearly fit.

**To Reproduce**
1. Go to https://anhallbe.github.io/ids-repro/tabs
2. Resize the tabs container
3. See error

Code here: https://github.com/anhallbe/ids-repro/blob/master/src/app/tabs/tabs.component.html

**Expected behavior**
The tabs should respond to element resize, not just window resize.

**Version**
- ids-enterprise-ng: 7.2.4

**Screenshots**
![ids-tabs-demo](https://user-images.githubusercontent.com/4991954/86338587-cb28a480-bc52-11ea-9f99-285474a75c19.gif)

**Platform**
Chrome, Safari, Firefox on Windows & MacOS

**Additional context**
The repro code uses the CSS `resize` property to set the container size. But the problem is seen in other areas such as widgets, dialogs, JQuery `resizable` containers etc.

**Comment by tmcconechy** [comment]
Perhaps you just call https://github.com/infor-design/enterprise/blob/master/src/components/tabs/tabs.js#L730 on the enddrga event of the resize thing that you added?

We dont plan on making things resizable in that way. But have one ticket for modals.

**Comment by EdwardCoyle** [comment]
For what it's worth, we do something similar in the Enterprise test for this:  https://master-enterprise.demo.design.infor.com/components/tabs/test-container-resize.html

On the Slider component's `change` event, we [trigger the global IDS `resize` custom event](https://github.com/infor-design/enterprise/blob/master/app/views/components/tabs/test-container-resize.html#L114) on the [body tag](https://github.com/infor-design/enterprise/blob/master/src/components/tabs/tabs.js#L729).  This is the event-driven way to call `handleResize()` on Tabs.  However, the benefit of triggering the event is that other components are also looking at the body for a similarly-named event, and will also resize themselves if it occurs.

@anhallbe it might even be enough to switch [these lines](https://github.com/anhallbe/ids-repro/blob/master/src/app/tabs/tabs.component.ts#L10-L12) out to listen for the jQuery `resize` event coming from `body`.

**Comment by jbrcna** [comment]
**QA Passed**
v4.32.0-dev
https://master-enterprise.demo.design.infor.com/components/tabs/test-container-resize-homepages.html
![image](https://user-images.githubusercontent.com/56722184/90012064-43b06580-dcd5-11ea-97b2-239ef14dc268.png)
