### ISSUE TITLE
Icon: Want All icons available in span elements

### ISSUE THREAD

**Issue by LucasLund** [infor-design/enterprise-ng#866]
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem, but the possibility of being able to use icons in a span element would be a great addition, as it unlocks the use of them for a lot more different scenarios.

**Describe the solution you'd like**
I'd like to be able to use any icons in a span, instead of being restricted to the few that have been made for span elements.
This is used a lot when creating custom navigation or any form of custom drop down etc..

**Describe alternatives you've considered**
I've tried simply just using the buttons with the icons in them, but the restrictive CSS rules setup around it, makes it more of a hassle to scale it properly than simply just having them in a span, and not having to worry about ripple effects or scaling of button with SVG inside.

**Additional context**
I haven't been able to find any documentation that shows the ability to do so, majority of the documentation (even on the non angular IDS) displays the ability to use the icons in buttons, and only very few in span elements.
Specifically I would like to use the caret-down, caret-left etc.. icons, but having accessibility to all would be great.

**Comment by tmcconechy** [comment]
Not sure about  this one? I tried on https://master-enterprise.demo.design.infor.com/components/icons/example-index.html ject editing inline and wrapping and nothing is stoping you from putting them in a span.

But the states and effect below on buttons when they are interactive.

```
<span>
   <svg class="icon" focusable="false" aria-hidden="true" role="presentation">
     <use href="#icon-alert"></use>
  </svg>
</span>
```

**Comment by LucasLund** [comment]
Aaah I haven't seen this is any examples, I've checked out the examples on IDS' website, but the example file just includes
`{{{iconHtml}}}`
And haven't though about inspecting the element on the example page.

Thanks a lot! 
I don't see the need to make any specific changes to accomidate an 'easier' use, only nice-to-have change would 
to make the example on GitHub include this as an example.
