### ISSUE TITLE
Datagrid: In filter row missing icon for a filterable date column

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise-ng#876]
Describe the bug
A date column hat is filterable is missing the icon on the filter row. 

1. Go to DataGrid - DataGrid - Fixed Header or http://localhost:4200/ids-enterprise-ng-demo/datagrid-fixedheader
2. Ensure that the filter row is visible
3. Notice that the Order Date column in the filter row is missing the date icon

Timestamp icon seems to available when testing using DataGrid - Dynamic?
Also please confirm that the icon is present when a date cell is editable.

Expected behavior
A filterable date column would show the date icon on the filter row.

Version
- ids-enterprise: v4.31.0-dev 

Screenshots
![image](https://user-images.githubusercontent.com/39804038/88558631-6b26e300-cff1-11ea-87fb-4234cb4fb271.png)

**Comment by tmcconechy** [comment]
This is fixed on https://github.com/infor-design/enterprise/pull/4185 and https://github.com/infor-design/enterprise/issues/4151 (already reported duplicate)

Has a patch in 4.30.1 and will be ok in 4.31.0

**Comment by pwpatton** [comment]
4.30.1 is part of ng 7.4.1, @claudenbach  update to that to verify fix.

**Comment by tmcconechy** [comment]
I also updated master to 4.31 dev confirm and its working now on dev master.

**Comment by claudenbach** [comment]
Confirming that the fix works.  Thanks!
