### ISSUE TITLE
Soho Lookup issue with Dataset

### ISSUE THREAD

**Issue by GauravJags** [infor-design/enterprise-ng#882]
**Describe the bug**
When the lookup is clicked for second time there is no data.
However it works fine at the first click

**To Reproduce**

**Expected behavior**
The data inside the look should get displayed

**Version**
- ids-enterprise-ng: [5.0.0]

**Screenshots**
First click 
![First click](https://user-images.githubusercontent.com/43963281/88935915-e1e90800-d29f-11ea-904d-61ecddab6e1d.JPG)
second click
![second click](https://user-images.githubusercontent.com/43963281/88935998-f7f6c880-d29f-11ea-81a7-3bdca27575e1.JPG)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@GauravJags This issue only uses the issue template and has no code to debug or steps to reproduce. So we probably can't do much with that to help you

**Comment by tmcconechy** [comment]
Closing for now as probably a developer issue and we have a meeting to look at it. Nothing we can do with this issue as it is.
