### ISSUE TITLE
Dropdown: "Submit"/"Save" button in modal window remains disabled with data-validate="required"

### ISSUE THREAD

**Issue by hemantg05** [infor-design/enterprise-ng#884]
**Describe the bug**
"Submit"/"Save" button in modal window remains disabled, when a value is programmatically set for a dropdown with data-validate="required"
 
**To Reproduce**

Paste following code in enterprise-ng/src/app/modal-dialog/example-fullsize-modal.component.html
```<div class="row form-responsive no-indent">
  <div class="full-width column">
    <div class="field">
      <label for="context-name" class="required">Name</label>
      <input id="context-name"  aria-required="true" name="context-name" type="text" value="John"/>
    </div>

    <div class="field">
      <label for="context-type" class="required label">Type</label>
      <select soho-dropdown id="context-type" name="type" data-validate="required">
        <option value=""></option>
        <option value="1" selected>Context 01</option>
        <option value="2">Context 02</option>
        <option value="3">Context 03</option>
        <option value="4">Context 04</option>
        <option value="5">Context 05</option>
      </select>
    </div>


    <div class="field">
     <label for="context-desc" class="required">Page Title</label>
     <textarea id="context-desc" aria-required="true" name="context-desc" maxlength="50">Test Desc</textarea>
    </div>
  </div>
</div>
```

1. Go to http://localhost:4200/ids-enterprise-ng-demo/modal-dialog
2. Click on 'Full On Tablet' button
3. Observe the "Submit" button in modal window

**Expected behavior**
Submit button should be enabled as all required fields are filled

**Version**
- ids-enterprise-ng: [e.g. v6.1.1 onwards]

**Screenshots**
![2020-07-31 16 58 16](https://user-images.githubusercontent.com/1594815/89051174-2209c280-d354-11ea-88ac-b462ae1bbd67.gif)

**Additional context**

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to Done column.
