### ISSUE TITLE
SohoModalDialogService: Regarding deprecation of parent argument

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise-ng#889]
**Is your feature request related to a problem? Please describe.**
In recent versions of the components, the `parent` argument is marked as deprecated in the following API:
`public modal<T>(component: ComponentType<T>, parent?: ViewContainerRef, options?: SohoModalOptions)`

We would like to make sure that existing usages of `SohoModalDialogService.modal` continue to work, without having to change to a new call signature. Around 80 Homepages widgets are using this API in its current form, e.g. passing a ComponentType and a ViewContainerRef parent, as was required up until recently. If the parent argument is removed, as the deprecation states, it will probably break somewhere since the second argument would be treated as a SohoModalOptions object instead. 

**Describe the solution you'd like**
Some alternatives that could be considered
* Don't remove the parent argument, keep it optional
    * The few (?) cases in which options are being passed, null could simply be provided as second argument. For others, ComponentType is sufficient 
* If it has to be removed, make sure to check if the second argument (if provided) is of type SohoModalOptions, not ViewContainerRef, before using as options.
    * The few cases in which options are being passed will "fail", since the options would not be used as there's no third argument anymore. Small code change required in the widget to make it work as before.

It's OK if TS compilation fails for the old syntax, just want to make sure that existing runtime JS will continue to work. 

**Additional context**
In `SohoContextualActionPanelService`, parent argument is not yet deprecated

**Comment by tmcconechy** [comment]
The reason for the change is to better be able to close references and avoid DOM and memory leaks. As noted https://github.com/infor-design/enterprise-ng/pull/784

But we don't have plans to actively remove this anytime soon. If we remove the deprecated message would this be solved for now?

Caveat being doing it this way may leave elements in the DOM and/ or memory leak.

**Comment by volante007** [comment]
The change itself is great, e.g. not having to pass a ViewContainerRef anymore! Just worried it will take a lot of time before all adopters change their code to the new syntax. So we're definitely not asking to revert to _using_ a parent for the component creation, just worried about a changed call signature :) 

Removing the deprecation message/log would be appreciated!

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
