### ISSUE TITLE
Timepicker: Update typings and Inputs to match ep component

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise-ng#890]
**Describe the bug**
The timepicker typings and Inputs are out of sync with the underlying soho component. Missing are secondInterval, locale, language, parentElement, and returnFocus.

**Version**
- ids-enterprise-ng: v4.31.0-rc.0

**Comment by tmcconechy** [comment]
@fitzorama are you doing this or need us to?

**Comment by fitzorama** [comment]
@tmcconechy what is the timeline? I can do the update.

**Comment by tmcconechy** [comment]
Expect to be done testing EOD. But i can wait for it to maybe tomorrow? If so that would be great PR it into branch 7.5.x please?

**Comment by pwpatton** [comment]
Yes, we'd need this in 7.5.x

**Comment by tmcconechy** [comment]
Thanks @fitzorama will get this merged into next 7.5 build when i make it (tomorrow)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
