### ISSUE TITLE
Homepage columns don't reset after using the maximize button.

### ISSUE THREAD

**Issue by crlang44** [infor-design/enterprise-ng#894]
**Describe the bug**
When you make the homepage smaller by resizing the window (from 3 column default to 2 or 1 column size) and then resize the window by using the maximize button, the homepage columns do not reset to 3 columns. As a side note, it also seems to happen if you resize the window quickly to significantly larger than the 3 column width as seen in the gif below.

**To Reproduce**
1. Go to ids-enterprise-ng-demo/homepage example
2. Resize the page to make it smaller so that the page uses less columns.
3. Use the browser's maximize button.

**Expected behavior**
Columns should reset as needed after any resize.

**Version**
- ids-enterprise-ng: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![homepage-resize](https://user-images.githubusercontent.com/4143306/90168287-bb23da80-dd51-11ea-9d8a-5808bacc997a.gif)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome, Edge, Firefox

**Additional context**

**Comment by tmcconechy** [comment]
Seems like i can reproduce this.. But only in NG which is a bit unexpected. Cc @deep7102

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Used URL: https://master-enterprise.demo.design.infor.com/components/homepage/example-four-column.html to test this issue.
