### ISSUE TITLE
Homepage with 4 columns won't go back to 4 columns after resize to smaller than 4 columns

### ISSUE THREAD

**Issue by crlang44** [infor-design/enterprise-ng#895]
**Describe the bug**
For a homepage which has the columns set to 4, the page loads fine initially. You can see 4 columns are being used.
But if you resize the page smaller so that it becomes 3, 2, or 1 column width, then resize the page larger again so that it should be 4 columns, it only goes up to 3 columns and not back up to 4.

**To Reproduce**
1. In src\app\homepage\homepage.demo.html, set [columns]="4" on the homepage component.
2. Run the demo, open a browser to http://localhost:4200/ids-enterprise-ng-demo/homepage
3. Verify the page initially loads with 4 columns.
4. Resize the page to be smaller so that it becomes 3, 2, or 1 column.
5. Resize the page larger so that it is the initial width and should become 4 columns.
6. It does not resize back to 4 columns, only 3 max.

**Expected behavior**
The page should be able to go back to 4 columns after resizing.

**Version**
- ids-enterprise-ng: 7.5.0

**Screenshots**
![ids-enterprise-ng-4-columns-resize-issue](https://user-images.githubusercontent.com/4143306/90180255-8de02800-dd63-11ea-9bcf-7a5ed87a7611.gif)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome, Edge, Firefox

**Additional context**

**Comment by tmcconechy** [comment]
Seems like it might be the same fix as https://github.com/infor-design/enterprise-ng/issues/894

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Use URL: https://master-enterprise.demo.design.infor.com/components/homepage/example-four-column.html to test this ticket.
