### ISSUE TITLE
Lookup: Component's "beforeShow" only triggers one time

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-ng#899]
**Describe the bug**
Lookup component's `beforeShow` only triggers one time if I pass `false` to the callback method.
Which is described how you cancel the lookup dialog to open. Though it disables the lookup dialog entirely as well.

**To Reproduce**
1. Go to http://localhost:4200/ids-enterprise-ng-demo/lookup
2. Click on the lookup in Products (Cancel Before Open) -> toast shows
3. Repeat 2 -> wont fire anymore

**Expected behavior**
Should be able to repetitively click on the icon and beforeShow should fire

**Version**
- master branch

**Comment by jbrcna** [comment]
**QA Passed**
v4.33.0-dev
https://master-enterprise.demo.design.infor.com/components/lookup/test-beforeshow-cancel.html
![image](https://user-images.githubusercontent.com/56722184/93204002-edc55680-f787-11ea-82c4-012125dc2ba8.png)
