### ISSUE TITLE
Datagrid: Activated row on second page is not highlighted in datagrid mixed mode

### ISSUE THREAD

**Issue by crlang44** [infor-design/enterprise-ng#900]
**Describe the bug**
If the paging datagrid is in "mixed" mode, on first page, when clicking a row, it becomes highlighted.
now open second page or any subsequent page, when clicking a row, it does not become highlighted.

**To Reproduce**
1.  Open src\app\datagrid\datagrid-paging-service.demo.ts
2. Change selectable to 'mixed'.
3. Run and open the app in the browser, go to http://localhost:4200/ids-enterprise-ng-demo/datagrid-paging-service
4. Click a row on the first page, it applies the blue background color to the row correctly.
5. Go to the second page and click a row. It does not apply the blue background to the row.

**Expected behavior**
The row should show as selected (blue background)

**Version**
- ids-enterprise-ng: 7.5.0

**Screenshots**
![ids-enterprise-ng-paging-row-activated](https://user-images.githubusercontent.com/4143306/90939485-b2ba4800-e3c0-11ea-937c-bffc686c03ac.gif)

**Comment by jbrcna** [comment]
**QA Passed**
v4.33.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/test-paging-select-serverside-mixed.html
![Large GIF (1302x586)](https://user-images.githubusercontent.com/56722184/93460301-9523c400-f915-11ea-8b00-72f79fe5d422.gif)
