### ISSUE TITLE
Autocomplete: Cannot select with 'enter' when there is a custom template

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-ng#901]
**Describe the bug**
A `soho-autocomplete` does not trigger the `(selected)` even when the 'enter' key is used for selection. This only appears to happen when the `[template]` input is used.

**To Reproduce**
1. Go to 'https://anhallbe.github.io/ids-repro/autocomplete-selected'
2. Click on the autocomplete field
3. Enter 'A' to open the autocomplete dropdown, select a result with 'Enter'
4. Nothing happens

**Expected behavior**
The 'selected' event should trigger, which should reset the counter in the field label.

**Version**
- ids-enterprise-ng: 7.5.2

**Screenshots**
![autocomplete-select](https://user-images.githubusercontent.com/4991954/91021648-550e4180-e5f4-11ea-9d3b-120645b0e498.gif)

**Platform**
 - OS Version: Windows
 - Browser Name: Chrome
 - Browser Version: 84, 85, 86, 87

**Additional context**
https://jira.infor.com/browse/LIME-6312

Repro code here: https://github.com/anhallbe/ids-repro/tree/master/src/app/autoomplete-selected

**Comment by jbrcna** [comment]
**QA Passed**
v4.33.0-dev
https://master-enterprise.demo.design.infor.com/components/autocomplete/example-templates.html
![Large GIF (868x420)](https://user-images.githubusercontent.com/56722184/93339345-09029580-f85e-11ea-9df5-26ecd02a689b.gif)
