### ISSUE TITLE
SohoCirclepager: Button pagers aren't rendering dynamic number of pages

### ISSUE THREAD

**Issue by eaenriquez** [infor-design/enterprise-ng#902]
**Describe the bug**
The initial render of the soho-circlepager dynamically loads 'x' number of images, which is correct. But upon removing/adding pages, the button-pages are not increasing/decreasing.

**To Reproduce**
1. Go to circlepager component
2. Try to add/remove pages through code
4. See that the circlepager's buttons to navigate the pages aren't reacting

**Expected behavior**
The soho-circlepager's button-pagers count should render depending on how many pages the circlepager has

**Version**
- ids-enterprise-ng: v7.4^

**Screenshots**
![image](https://user-images.githubusercontent.com/68070868/91950621-03bc2b80-ed33-11ea-93e4-9af1a006acee.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name chrome
 - Browser Version Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
The pager does not actively watch the DOM for changes. So you might try calling `updated()` when the new DOM nodes are appended.
