### ISSUE TITLE
Datagrid: How do I filter a single column for multiple values and return the result

### ISSUE THREAD

**Issue by FranklinAf** [infor-design/enterprise-ng#903]
When using a multiselect with a soho datagrid filter, cannot filter more than one result. I am not sure if this is possible at the moment.

Filtering on a single column, for the multiple values 'test', 'test2', and 'test3'.

const filter: SohoDataGridFilterCondition[] = [ { columnId: 'col-sup', operator: 'contains', value: ('test' || 'test2' || 'test3') }, ];

If the column has any of those values, return all rows in the filtered result.

Thanks

**Comment by tmcconechy** [comment]
Hi @FranklinAf for next time please use the issue template https://github.com/infor-design/enterprise-ng/issues/new/choose

We do support this in a way but you need to select the ones you want. So as an example
1. go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
1. in the activity (multi) column, open the filter multiselect and select the two types

You can select any combination? is this what you mean ?

**Comment by FranklinAf** [comment]
Apologies, will remember to use the issue template for new issues. That is correct. If I chose the selections 'test', 'test2', 'test3 in the multiselect, then show all the rows when any of the 3 values. 
With the example-filter.html, the datagrid object itself that is exactly what I am looking for but In my case I am trying to programmatically pass in a specific filter from a separate multiselect object. Not a multiselect object built into the grid.

So for example on select of a separate multiselect object test, test2, test3. Pass these selected values to a new datagrid filter condition, then apply them to the datagrid.

Is the multiselect dropdown in https://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html using a SohoDataGridFilterCondition to apply the filter?
Or is there documentation on how that filtering is being done? Because it is exactly what I am looking for, just using filtering criteria from a separate multiselect object.

**Comment by tmcconechy** [comment]
```
columns.push({ id: 'activity', name: 'Activity', field: 'activity', formatter: Formatters.Dropdown, filterType: 'multiselect', options: activities, editorOptions: {showSelectAll: true}});
```

So filterType: 'multiselect' and options -> you might need to build these out with values for example:

```
         var activities = [{id: 'Assemble Paint', value:'Assemble Paint', label: 'Assemble Paint'},
                               {id: 'Inspect and Repair', value:'Inspect and Repair', label: 'Inspect and Repair'}];
```

**Comment by FranklinAf** [comment]
That looks to be working great. Do you know if there is a property to make them selected by default? Or a method to select a specific value from the multiselect instead of relying on user input?

Like below
         var activities = [{id: 'Assemble Paint', value:'Assemble Paint', label: 'Assemble Paint', selected: true},
                               {id: 'Inspect and Repair', value:'Inspect and Repair', label: 'Inspect and Repair', selected: false}];

Or 
columns.push({ id: 'activity', name: 'Activity', field: 'activity', formatter: Formatters.Dropdown, filterType: 'multiselect', options: activities, editorOptions: {showSelectAll: true, selectedByDefault: true}});

Appreciate all the help.

**Comment by tmcconechy** [comment]
Sure No problem. So to pass them in by default you need to run applyFilter then pass in a conditions object similar to what you get in the 'filtered' event when you type in a condition. So for multiselect this would be something like:

```
  grid.applyFilter([{columnId: "activity", operator: "equals", value: ["Assemble Paint", "Inspect and Repair"]}]);
```

**Comment by tmcconechy** [comment]
Closing but ask if any more follow up questions...
