### ISSUE TITLE
Charts: Expose updated API for all the available charts

### ISSUE THREAD

**Issue by DivyaParepally** [infor-design/enterprise-ng#905]
Currently we observed the chart (Bar Chart, Pie chart, Donut, Bullet chart) not rendering properly, as there is no option for updated API while the widget is activated.

https://teams.microsoft.com/l/message/19:ff24d87598a142b2aaa36d31f4703589@thread.skype/1595249664076?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=541e584f-dd52-42e4-83d6-81adc36b6a62&parentMessageId=1595249664076&teamName=Homepages%20Widget%20Development&channelName=General&createdTime=1595249664076

Video is present in the above mentioned teams link.

Expected behavior:
Provide updated API so that, charts and legends get rendered properly.

**Version**
- ids-enterprise-ng: v7.1.0

**Platform**
 - OS Version:  Windows 10
 - Browser Name: chrome
 - Browser Version: 85.0.4183.83 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
@DivyaParepally I'm not following this request.

1) What "API" is missing/not exposed?
1) Can't find that video - you can zip it and attach it. Or better if you can type the steps to reproduce out.

Feel free to do a pull request if you can and we can review the additions

**Comment by DivyaParepally** [comment]
@tmcconechy 

1. Expose an updated API for all their chart variants, as you do for the generic soho-chart component.
2. We faced this issue in Homepage Widgets. 

Steps to reproduce:
1. Add the homepage widget
2. Before the chart is loaded, edit/move to other page/view, then the chart is not rendered properly

PFA sample video
[chart.zip](https://github.com/infor-design/enterprise-ng/files/5199549/chart.zip)

**Comment by tmcconechy** [comment]
Note that soho-chart is deprecated you should use the individual charts now like soho-pie or soho-line. I think these should have everything in the API now. If not let me know specifically whats missing?

Im not totally following the idea of the video? Seems like you are referring to something in the data events? 

I think we need some clarification here.

**Comment by DivyaParepally** [comment]
In soho-chart, soho-chart.component.d.ts there is "updated()", but for example in soho-bar chart, soho-pie chart, soho-bullet chart, in soho-bar.component.d.ts, soho-pie.component.d.ts, soho-bullet.component.d.ts, there is no "updated()"

**Comment by tmcconechy** [comment]
Ok, i see. We can add that type for the method. Also a good candidate for a pull request if you want to try 👍
