### ISSUE TITLE
Popupmenu: Expose is-selectable, is-multiselectable, and multi-selectable-section

### ISSUE THREAD

**Issue by crlang44** [infor-design/enterprise-ng#907]
**Is your feature request related to a problem? Please describe.**
Popupmenu does not currently expose is-selectable, is-multiselectable, and multi-selectable-section.

**Describe the solution you'd like**
Expose is-selectable, is-multiselectable, and multi-selectable-section as input properties.

**Comment by crlang44** [comment]
Can you assign this to me and Schedule for this months release. I'll submit a PR in a few min.

**Comment by EdwardCoyle** [comment]
Sounds good!  Thanks for the contribution. :beers:

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
