### ISSUE TITLE
Datagrid: row selection not working when using datagrid with immutable data

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise-ng#909]
**Describe the bug**
We are using `@ngxs/store` for state management with `developmentMode: true`, which will make data selecting from state immutable. However, this cause data grid row selection not working correctly anymore.

**To Reproduce**
1. Clone repo https://github.com/ahnpnl/soho-bug-repo
2. Install dependencies with `yarn`
3. Start the app via `ng serve`
4. Open Chrome Dev Tools, stay on Console tab
5. Check the checkbox of any rows, then check the checkbox to select all rows
6. Observe the error in the console and not all rows are selected
7. Check the checkbox to deselect all rows, observe that nothing happens.
8. Open `AppModule`, change `developmentMode` of `NgxsModule` to false
9. Wait for page refresh, performs step 5, 6, 7 again and row selection works well.

**Expected behavior**
Row selection should work normally with immutable data

**Version**
- ids-enterprise-ng: **7.5.3/7.6.0**

**Screenshots**
Error in the console
![image](https://user-images.githubusercontent.com/27772165/93107116-74f3cb00-f6b1-11ea-942d-5835463aadb1.png)

**Platform**
 - Device (if applicable) **N.A.**
 - OS Version: MacOS/Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 85.0.4183.102 (Official Build) (64-bit)

**Additional context**
With `developmentMode: true` from `@ngxs/store`, it guarantees that our application follows correctly state management coding standard. Datagrid doesn't work with immutable data which hurt our development quality.

**Comment by ahnpnl** [comment]
The error seems to be more related to `ids-enterprise` rather than NG wrapper.

**Comment by tmcconechy** [comment]
We are doing some rework on the components and i can do this there. See #1463 but it's going to require a pretty substantial partial rewrite. But it was planned and noted in the past

**Comment by tmcconechy** [comment]
This is too difficult to fix at the present time. However for the rework i made sure we only work on copies of the array. Will be in version 5.0.0
