### ISSUE TITLE
Breadcrumb: component breaks template interpolation

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#926]
**Describe the bug**

Adding string interpolation to an element inside a breadcrumb does not work when using `soho-breadcrumb`.

For example:

```
html
<nav soho-breadcrumb>
    <li>
      <span>{{someData}}</span>
    </li>
</nav>
```

Does not display updates to the **someData** property.  Changing to use simple markup does:

```html
<nav class="breadcrumb">
  <ol class="breadcrumb-list">
    <li>
      <span>{{someData}}</span>
     </li>
   </ol>
 </nav>
 <button soho-button (click)="increment()">Increment</button>
```

```typescript
private _i = 1;

public get someData() {
  return this._i;
}

public increment() {
  console.log(`Incrementing ${this._i++}`);
}
```

**To Reproduce**
1. Check out the latest repo for `ids-enterprise-ng`.
2. Apply the attached GIT patch [breadcrumb.patch.zip](https://github.com/infor-design/enterprise-ng/files/5401311/breadcrumb.patch.zip)
3. Build (`npm run build`)
4. Run (`npm run start`)
5. Navigate (`http://localhost:4200/ids-enterprise-ng-demo/breadcrumb`)

Clicking the "Increment" button does not update the first breadcrumb but does the second.

**Expected behavior**

Both breadcrumbs should be updated.

**Version**
- ids-enterprise-ng: 8.0.2

**Screenshots**

**Platform**
 - Device (if applicable) Desktop
 - OS Version: Windows 10 and macOS 10.15.7
 - Browser Name: Edge Chromium and Safari
 - Browser Version: Latest

**Additional context**

I believe this is due to underlying widget adding a `button` under the `nav` element. 

Also, I tried adding a soho-breadcrumb-list component which sets the class for the order list to make sure the markup is HTML compliant.  This did not fix the issue, so assume it might be related to the button.

Using the component without these calls in the `AfterViewInit` resolved the issue:

```typescript
ngAfterViewInit() {
    this.ngZone.runOutsideAngular(() => {
      this.jQueryElement = jQuery(this.element.nativeElement);
      // this.jQueryElement.breadcrumb(this.options);
      //  this.breadcrumbAPI = this.jQueryElement.data('breadcrumb');
    });
  }
```

This leads me to believe there is something occurring in the underlying widget which is breaking angular links to the  page elements.

**Comment by bthharper** [comment]
Also - the EP widget seems to be converting all the list item's content into anchors, e.g.
```html
<span>{{someData}}</span>
```
is becoming
```html
<a id="" class="hyperlink hide-focus" tabindex="0">1</a>
```

**Comment by bthharper** [comment]
It looks like angular is loosing track of its templates as the EP widget is deleting the generated markup, 

> // If breadcrumbs are present, they are processed for settings and removed.

**Comment by tmcconechy** [comment]
So is the suggest to just update our examples to use the full markup approach?

**Comment by bthharper** [comment]
@tmcconechy - not sure - effectively there are two problems:

1. The soho-breadcrumb does not integrate with angular due to the dynamic creation of the html (which angular does not see) - similar to the problems we had with data grid and custom editors and formatters not working with angular concepts.
2.The EP widget turns all list items into hyper links when some are not.

In my application at the moment, I have reverted to the standard markup without any component or EP widget integration.  I wonder if there is a case leave the original HTML in place (if it exists) and just manipulate it rather than generating breadcrumb models?

**Comment by tmcconechy** [comment]
I think perhaps for the angular case we just need to

a) let the original markup work
b) let a full expanded markup work (as this wont "correct" the DOM)

Probably an issue for @EdwardCoyle when he can get to it

**Comment by bthharper** [comment]
For now I am using the following markup:

```html
<soho-toolbar-flex-section [isTitle]="true">
  <nav class="breadcrumb">
    <ol class="breadcrumb-list">
      <li class="breadcrumb-item">
        <a soho-hyperlink (click)="navigateToUsers($event)">{{'UserFormUsersNavigationLabel' | sohoTranslate}}</a>
      </li>
      <li class="breadcrumb-item current">
        <a soho-hyperlink id="new-user-breadcrumb">{{name}}</a>
      </li>
    </ol>
  </nav>
</soho-toolbar-flex-section>
```

This mostly works okay, and gives the same styling as the breadcrumb widget.  

Is there an option to have a non hyperlink with the same text styling but without the hover?  the disabled option looks too greyed out.

**Comment by tmcconechy** [comment]
Yes, just replace the `<a>` tag with a `<span>` and it will work.

**Comment by bthharper** [comment]
If I do that the styling is all out.

**Comment by tmcconechy** [comment]
Works in EP when i try it.

**Comment by bthharper** [comment]
Ummmm .... same in NG.  Must be some quirky styling in our app.  Let me check it out.

**Comment by bthharper** [comment]
Maybe it's the flex-toolbar, but a min-height is being added:

![image](https://user-images.githubusercontent.com/8340092/96620890-e9003f00-12ff-11eb-9e76-77cf8a5e91e9.png)

**Comment by bthharper** [comment]
Which causes:

![image](https://user-images.githubusercontent.com/8340092/96620978-f61d2e00-12ff-11eb-804d-d460d1226fbf.png)

**Comment by bthharper** [comment]
Using a hyperlink I get:

![image](https://user-images.githubusercontent.com/8340092/96621085-177e1a00-1300-11eb-8fde-b99299304af4.png)

**Comment by tmcconechy** [comment]
Ok, i bet the layout bug is to do with it being in a toolbar with spans moving around there. Might need some css to counter it when its in a toolbar

**Comment by bthharper** [comment]
Yeah - maybe a flex-toolbar thing.

**Comment by tmcconechy** [comment]
Will try and get to it next sprint

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
