### ISSUE TITLE
Autocomplete: Selection of first item in list with the same value returns a different object

### ISSUE THREAD

**Issue by rvilleno** [infor-design/enterprise-ng#933]
**Describe the bug**
When the list of object returned from an autocomplete lookup contains the same value as the first object, if the user select the first value in the list of result, the select event will return the last instance of the list containing the same value 

**To Reproduce**
You have to update first the source object similar to the below image where they all contain the same value.
![image](https://user-images.githubusercontent.com/10869544/98338389-13166880-2045-11eb-92ff-cb1b902438f7.png)

1. In the ng enterprise demo go to 'A > Autocomplete'
2. Type in the "Selected event fires" the search parameter
3. Select the first result

**Expected behavior**
It should return the first item that was selected

**Version**
- ids-enterprise-ng: 7.7.1

**Screenshots**
![Auto-complete-error](https://user-images.githubusercontent.com/10869544/98338118-a00cf200-2044-11eb-8438-e83a91683841.gif)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version 86.0.4240.183 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Can you paste the code in you changed? I'm not sure exactly what you changed since its only part of a screen shot?
I think that the values should be unique, but would like to test it further.

What is the use case here where there is a whole bunch of the same thing?

**Comment by rvilleno** [comment]
Hi @tmcconechy 

I have updated autocomplete.demo.html starting at line 16 with this code

`    <div class="field">
      <label for="autocomplete-selected-event">Selected event fires</label>
      <input id="autocomplete-selected-event" soho-autocomplete [source]="statesUrl" filterMode="contains" (selected)="onSelected($event)" type="text" [(ngModel)]="selectedItemEvent">
    {{selectedItemEvent}}
    </div>`

and defined the new ngModelProperty in the .ts code

`selectedItemEvent: string;`

and updated the function _onSelected_

`public onSelected(event: any) {
    console.log(event);

    this.selectedItemEvent = event[2].label;
    console.log(`Selected item: ${event[2].label}`);

  }`

also, I updated states.demo.json with the below values.
`
[
    { "index":0, "label": "Alabama", "value": "TEXT" },
    { "index":1, "label": "Alaska", "value": "TEXT" },
    { "index":2, "label": "Arizona", "value": "TEXT" },
    { "index":3, "label": "Arkansas", "value": "TEXT" },
    { "index":4, "label": "California", "value": "TEXT" },
    { "index":5, "label": "Colorado", "value": "TEXT" },
    { "index":6, "label": "Connecticut", "value": "TEXT" },
    { "index":7, "label": "Delaware", "value": "TEXT" },
    { "index":8, "label": "Florida", "value": "TEXT" }
  ]
`

The use case for this is if we have a set of data that has could have the same value, but differs in label, when I tried to select the first item in that list in the autocomplete component, it will return the last item in that list that has the same value.

**Comment by tmcconechy** [comment]
Ok, I think the workaround is to make the values all unique. I'm not 100% sure we can fix this but i'm thinking we can.

**Comment by EdwardCoyle** [comment]
I'm not sure we can change this.  `value` is used internally in the [EP side of Autocomplete](https://github.com/infor-design/enterprise/blob/master/src/components/autocomplete/autocomplete.js) to differentiate results.

**Comment by tmcconechy** [comment]
Closing this as Stale
