### ISSUE TITLE
Attributes: Add NG types for new attributes options

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise-ng#934]
**Is your feature request related to a problem? Please describe.**
A new option was added to the colorpicker control, e.g. ` { attributes: { name: 'id', value: 'background-color' } }`, but there is no way to set that for `soho-colorpicker`. 

**Describe the solution you'd like**
The SohoColorpickerComponent needs a new `@Input()` for setting the attributes option. With that, also typings I assume.
```
@Input() set attributes(value: object) {
    this.attributes = value;
    this.options.attributes = value;

    if (this.colorpicker) {
      this.colorpicker.settings.attributes= value;
      this.markForRefresh();
    }
  }
```

**Additional context**
It's also missing for the `SohoToastService`, but that one just needs updated `SohoToastOptions` to allow passing attributes to `show()`

**Comment by tmcconechy** [comment]
Its actually missing for all of them. I forget to check the type additions before the release.

**Comment by volante007** [comment]
Hi @tmcconechy, seems to be missing for `soho-dropdown` still. I can perhaps add it manually for now, but do you want to reopen this one for it?

**Comment by tmcconechy** [comment]
ok imust have missed that one. Is it ok if i just push it to master for next time?

**Comment by tmcconechy** [comment]
I just pushed them here https://github.com/infor-design/enterprise-ng/commit/c762398a85c47f1119a40c36e16e04ee79193d11 for next version. I think you can use `(settings.attributes as any)` for now?
