### ISSUE TITLE
DataGrid: Content of custom components is not visible when frozen columns are set

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise-ng#947]
**Describe the bug**
Content of custom components is not visible when frozen columns are set

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-enterprise-ng-8-1-0-ya1f1w?file=src/app/app.component.html
2. observe column 'captions'
3. remove lines with frozen columns settings #223-225 in src/app/grid-frozen/grid.constants.ts
4. See column 'captions' now contains text

**Expected behavior**
Custom components should be usable when frozen columns are set

**Version**
- ids-enterprise-ng: 8.1.0

**Screenshots**
![Screenshot from 2020-11-24 16-37-03](https://user-images.githubusercontent.com/11279863/100116096-a20fe700-2e73-11eb-9eb3-f80d199b3ebf.png)
![Screenshot from 2020-11-24 16-40-02](https://user-images.githubusercontent.com/11279863/100116276-d71c3980-2e73-11eb-9298-9efb0ab55deb.png)

**Comment by tmcconechy** [comment]
I see the fix and its quick, so adding it now

**Comment by jbrcna** [comment]
**QA Passed**
4.35.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/test-post-renderer.html
