### ISSUE TITLE
Lookup: When used in a form array the lookup only works for the last row in the array

### ISSUE THREAD

**Issue by ablomq** [infor-design/enterprise-ng#948]
**Describe the bug**
When using an input field with lookup in a [reactive form array](https://netbasal.com/angular-reactive-forms-the-ultimate-guide-to-formarray-3adbe6b0b61a) the lookup only work for the last row in the array.

**To Reproduce**
1. I have a reactive form array with one input field with a lookup.
2. When adding a new row in the array the lookup only works for the last row but not for the preceding rows.

**Expected behavior**
The same lookup should be displayed for all lookup fields in the form array regardless if it's the last row or not.

**Version**
- ids-enterprise: 4.32.0
- ids-enterprise-ng: 7.6.0

**Screenshots**
My dynamic form array with a lookup field:
![Screenshot 2020-11-25 at 17 10 37](https://user-images.githubusercontent.com/42343009/100253856-eb2e6c80-2f41-11eb-8e0e-383b46dd0f48.png)

I press the lookup button and the lookup is displayed:
![Screenshot 2020-11-25 at 17 11 37](https://user-images.githubusercontent.com/42343009/100253969-0dc08580-2f42-11eb-9f79-89fef5002b72.png)
I then add a new row:
![Screenshot 2020-11-25 at 17 12 06](https://user-images.githubusercontent.com/42343009/100254056-24ff7300-2f42-11eb-92f9-5cf917d491c6.png)
After that I press the lookup button on the same row as before:
![Screenshot 2020-11-25 at 17 13 11](https://user-images.githubusercontent.com/42343009/100254166-406a7e00-2f42-11eb-8555-c5b05426f137.png)
But this time the lookup contains this:
![Screenshot 2020-11-25 at 17 13 48](https://user-images.githubusercontent.com/42343009/100254267-5ed07980-2f42-11eb-8bd4-a2f4a684e1e3.png)
But if I press on the lookup button on the last row in the array it works, but not for the preceding rows:
![Screenshot 2020-11-25 at 17 20 47](https://user-images.githubusercontent.com/42343009/100254500-ae16aa00-2f42-11eb-9966-5f722f76b61e.png)
![Screenshot 2020-11-25 at 17 21 22](https://user-images.githubusercontent.com/42343009/100254513-b373f480-2f42-11eb-8067-fdd12087b82e.png)

This is how the generated html looks like if that can be to any help:
![Screenshot 2020-11-25 at 17 26 02](https://user-images.githubusercontent.com/42343009/100255121-6cd2ca00-2f43-11eb-83c4-23a730cfae9a.png)

**Comment by tmcconechy** [comment]
Can you make / attach a replication (stackblitz?) as im not sure we would be able to solve this given the current info.

**Comment by ablomq** [comment]
Do we have an existing stackblitz workspace I can use? Would be nice if we could have i.e. IdsEnterpriseNgQuickstart available on stackblitz to ease the burden of setting up a new project.

**Comment by tmcconechy** [comment]
Yes i made one off the quickstart as mentioned you can fork from here https://stackblitz.com/edit/ids-quick-start

**Comment by ablomq** [comment]
The issue was with passing the value to the lookup component. I solved the issue in my code so no further action is required.
