### ISSUE TITLE
Reactive Dropdown: Selected option label is not updated when underlying label is updated or when the selected option is removed + sohoDropDown.selectValue() API and formControl.setValue() API are not reflected in the soho dropdown

### ISSUE THREAD

**Issue by hemantg05** [infor-design/enterprise-ng#959]
**Describe the bug**
Reactive Dropdown: Selected option label is not updated when underlying label is updated or when the selection option is removed.

In addition,  sohoDropDown.selectValue() API and formControl.setValue() API are not reflected in the soho dropdown.

**Case 1 - Remove Option which is currently selected:**
**To Reproduce**
1. Run the demo app 'Reactive Dropdown' that I sent above.
2. Select Pennsilvania in the dropdown.
3.Click on "Remove Pennsilvania"

**Expected behavior**
Pennsilvania should not be shown as selected as it is removed.

**Actual behavior**
Actual:  Pennsilvania is shown as selected dropdown. When i open the dropdown list, the list doesn't show Pennsilvania which is expected.

**Case 2 - Update Option label which is currently selected:**
**To Reproduce**
1. Run the demo app 'Reactive Dropdown' that I sent above.
2. Select Arizona in the dropdown.
3.Click on "Update Arizona"

**Expected behavior**
The dropdown should show the selected option as 'Updated Arizona'.  If you open the dropdown list, the list shows updated value for Arizona which is expected.

**Actual behavior**
The old value 'Arizona' is still shown.

Code enterprise-ng/src/app/dropdown/dropdown-reactive.demo.ts:
```
import {Component, ViewChild} from '@angular/core';
import {FormControl, FormGroup} from '@angular/forms';
// @ts-ignore
import { SohoDropDownComponent } from 'ids-enterprise-ng';

@Component({
  selector: 'app-dropdown-reactive-demo',
  template: `
  <div class="example-section">
  <form>
    <div class="row">
      <h1>Reactive Dropdown</h1>
      <span class="code-tag">Live Example</span>
      <div class="row">
        <div class="field">
          <label for="states" class="label">States</label>
          <form [formGroup]="form">
            <select soho-dropdown formControlName="state" >
              <option *ngFor="let state of states" [value]="state.value">
                {{ state.label }}
              </option>
            </select>
          </form>
        </div>
      </div>
    </div>
  </form>
  <button soho-button (click)="toggleModel()">{{showModel ? 'Hide' : 'Show'}} Model</button>
  <button soho-button (click)="remove()">Remove Pennsylvania</button>
  <button soho-button (click)="updateArizona()">Update Arizona</button>
  <div *ngIf="showModel">
    <hr>
    <h3>{{ form.value | json }}</h3>
  </div>
</div>

  `,
})
export class DropdownReactiveDemoComponent {

  @ViewChild(SohoDropDownComponent, { static: true }) dropdown?: any;
  states = [
    {label: 'Arizona', value: 'AZ'},
    {label: 'California', value: 'CA'},
    {label: 'Colorado', value: 'CO'},
    {label: 'New York', value: 'NY'},
    {label: 'Pennsylvania', value: 'PA'},
  ];

  form = new FormGroup({
    state: new FormControl(this.states[4]),
  });

  showModel?: boolean;

  toggleModel() {
    this.showModel = !this.showModel;
  }

  remove() {
    this.states = this.states.filter(state => state.value !== 'PA');
  }

  updateArizona() {
    this.states = this.states.map( state => { if (state.value === 'AZ') { state.label = 'Updated Arizona'; } return state; });
  }
}

```

**Version**
- ids-enterprise-ng: latest from master at the time of bug creation

**Screenshots**

**Platform**
 - Browser Name Chrome
 - Browser Version Latest

**Additional context**
@karinthulin

**Comment by tmcconechy** [comment]
cc @bthharper @pwpatton - i tried to look at this one but not sure what's going on 100%. When you have some time would you take a look.

**Comment by tmcconechy** [comment]
Descoping this issue unable to fix right now
