### ISSUE TITLE
soho- 6877 Loading Shimmer

### ISSUE THREAD

**Issue by theakatz** [infor-design/enterprise-ng#96]
Add the soho loading shim to replace the current busy indicator on app load.

https://codepen.io/kevlarthrowintreesatya/pen/GZYRwY

**Comment by bthharper** [comment]
Is this a new "standard" for all IDS apps now?

**Comment by tmcconechy** [comment]
Maybe this should go in design issues? https://github.com/infor-design/design-system as i understand this was being discussed? Or is it finalized now.

**Comment by theakatz** [comment]
It was tagged as an angular issue in JIRA, so that's why I put it in this repo.

**Comment by tmcconechy** [comment]
Hmm i think this would not be an angular issue - would be an enterprise issue. Did design approve this to replace the busy indicator?
