### ISSUE TITLE
Need enterprise v4.35.4 for v9 (Ng11)

### ISSUE THREAD

**Issue by nbcp** [infor-design/enterprise-ng#961]
**Is your feature request related to a problem? Please describe.**
Currently ep-ng v9 only includes up to enterprise v4.35.0, we need to get the latest as enterprise in this version as well.

**Describe the solution you'd like**
Bump up version 9 that includes enterprise v4.35.4

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by tmcconechy** [comment]
Ok its there now. https://www.npmjs.com/package/ids-enterprise-ng/v/7.9.0
This is with 4.35.4 and using NG 9.

We are up on Ng 11 now so wont be doing it automatically on Ng 9 unless asked anymore, so hopefully not too many more builds for NG 9

**Comment by nbcp** [comment]
Hi @tmcconechy, as discussed offline, this is for enterprise-ng v9.0.1 (Ng11) with enterprise v4.35.4. Thank you

**Comment by tmcconechy** [comment]
Yes my mistake will release tomorrow:

enterprise-ep v 9.0.1 -> with enterprise 4.35.5 and uses Angular 11

later in a few weeks we will have:
enterprise-ep v 9.1.0 -> with enterprise 4.36.0 and uses Angular 11

**Comment by tmcconechy** [comment]
Ok @nbcp https://github.com/infor-design/enterprise-ng/releases/tag/9.0.1 is ready it is on NG 11 and contains 4.35.4
