### ISSUE TITLE
Datagrid - Allow for multiline column header text

### ISSUE THREAD

**Issue by FranklinAf** [infor-design/enterprise-ng#965]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Possibility to have \n in header column text values or equivalent functionality.

**Describe alternatives you've considered**
Allow auto sizing on the grid api is how we are using this today. But that only expands the headers and columns horizontally.

**Additional context**
NA

**Comment by tmcconechy** [comment]
Yes you can do this already here is an example https://master-enterprise.demo.design.infor.com/components/datagrid/test-two-line-header.html

You just do it by putting a line break in the name in the column..

```
name: 'Contstrained <br /> Max Order'
```

**Comment by FranklinAf** [comment]
That works great! Appreciate the assistance.
