### ISSUE TITLE
Datagrid: Cannot remove row without triggering sync

### ISSUE THREAD

**Issue by Carlfjord** [infor-design/enterprise-ng#966]
**Describe the bug**
I have a datagrid with server side pagination and when I remove a row the datagrid will sync the available records and thus resetting the "pages" and "total records" data that was set when initially loading the current set of records. Resulting in total count only recognizing currently showed records and pagination only recognizing 1 page. This could in my case be avoided if I was able to supply the "noSync" parameter that is available in enterprise. But unfortunately the enterprise-ng function does not support multiple arguments.

**To Reproduce**
Not sure this applies, and there are no current examples in the enterprise-ng app that does removeRow() as far as I can tell. So perhaps no example app is required?
But you can see the functions in question here: 
https://github.com/infor-design/enterprise-ng/blob/1767fa92e0ed091fc5645787f4f18841a45e73a5/projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.component.ts#L1457
https://github.com/infor-design/enterprise/blob/d0917b4302a92cec663d1e43a2c2ecdd9989866e/src/components/datagrid/datagrid.js#L632

Note how in enterprise-ng it only takes one argument. While the removeRow() in enterprise allows for three arguments.

**Expected behavior**
I would like to be able to supply the noSync parameter to a removeRow() call in enterprise-ng.

**Version**
- ids-enterprise-ng: 9.0.2

**Screenshots**
![image](https://user-images.githubusercontent.com/9215760/104232307-7317f980-5450-11eb-8382-7979eab08675.png)

**Additional context**
Infor PIM

**Comment by tmcconechy** [comment]
Yeah its missing the types. I can add them in quick. For now what you can try as a workaround is using this trick...

```
  (this.dataGrid as any).removeRow(1, true);
```

**Comment by tmcconechy** [comment]
Pushed the types for next release https://github.com/infor-design/enterprise-ng/commit/70fc3062a9d3b0e7c959482e79eef7f7f05033db

**Comment by Carlfjord** [comment]
> Yeah its missing the types. I can add them in quick. For now what you can try as a workaround is using this trick...
> 
> ```
>   (this.dataGrid as any).removeRow(1, true);
> ```

Thanks :) @tmcconechy You mean to replace the code in the enterprise-ng code? Or in my component? 
Unfortunately we are reading the library directly from the dependency so can't change there. And trying this in the component seems to make no difference.. Perhaps I'm missing something.

This is essentially how i do it in the component:

```
import { SohoDataGridComponent } from 'ids-enterprise-ng';
@ViewChild(SohoDataGridComponent) sohoDataGridComponent: SohoDataGridComponent;

 removeDeletedEntitiesFromDatagrid(rowIndex) {
      (this.sohoDataGridComponent as any).removeRow(rowIndex, true);
  }
```

**Comment by tmcconechy** [comment]
i meant in your code...My bad your right it needs to be fixed in the function. I missed that. But here is the extra part of the fix

https://github.com/infor-design/enterprise-ng/commit/e18a4f484ffddbcc3d49d0bea087e269a3d9cfe7#diff-b2b1882060e197eee5954735d123d17ecb5bda140c4a53e82118d553e2c6817dR1460

So for a workaround i wonder if you can get at the underlying datagrid object something like...

```
(this.sohoDataGridComponent as any). datagrid.removeRow(rowIndex, true);
```

**Comment by Carlfjord** [comment]
@tmcconechy Looks good 👍 
Aaah right, now I get it! Yes executing the removeRow() on the underlying datagrid works. Will do that for now. Thanks!
