### ISSUE TITLE
Datagrid: Nested datagrid only opens one time

### ISSUE THREAD

**Issue by dmcodrum** [infor-design/enterprise-ng#967]
**Describe the bug**
With a nested datagrid, the first time you click the expander the nested grid shows correctly. If you click the expander to close the nested grid then click it again (to re-expand), the nested grid doesn't appear. 

**To Reproduce**
1. Go to IDS NG demo.
2. Open the 'Datagrid - Expandable Row (nested)' demo.
3. Click the expander icon on one of the rows, note the nested grid appears.
4. Click the expander icon again, note the nested grid closes.
5. Click the same expander again, note the nested does not appear.
6. Note the browser console shows an error (see screenshot below).

**Expected behavior**
At step 5 the nested grid should appear.

**Version**
- ids-enterprise-ng: 9.1.0

**Screenshots**
![image](https://user-images.githubusercontent.com/39279254/104346749-c67c5d00-54cd-11eb-8236-dffe6731309d.png)

**Platform**
 - Device 
 - OS Version: Windows 10
 - Browser Name Chrome
 - Browser Version latest

**Additional context**

**Comment by tmcconechy** [comment]
Looks like an issue on this logic..

```
        const idx = this.rowTemplateComponents.findIndex((c) => event.row === c.row);
        if (idx > -1) {
            this.rowTemplateComponents[idx].component.destroy();
            this.rowTemplateComponents.splice(idx, 1);
        }
```

Its taking the row details away in the wrong manner

**Comment by dmcodrum** [comment]
Any chance for this fix to get into IDS NG 8.x? Version 9.x/NG 11 is somewhat off in the horizon for us right now. Thanks!

**Comment by tmcconechy** [comment]
i can do that once the PR is merged.
