### ISSUE TITLE
Add production build as a PR check

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#97]
**Describe the bug**

When making a change, it is important that is compiles when used in a production build, this will impact teams using AOT when building.  Primarily this is caused by the fact we don't bundle the angular library yet, but require teams to compile it locally.  However, the component library code should compile using these options anyway.

**To Reproduce**

`ng build --prod`

**Expected behavior**

No error.

**Screenshots**

![image](https://user-images.githubusercontent.com/8340092/41399953-990cb498-6fb3-11e8-96a7-197146385fc4.png)

**Platform**

All

**Additional context**

**Comment by bthharper** [comment]
@clepore this should be an easy one to add?

**Comment by tmcconechy** [comment]
When we setup the build i did mentioned this. However, we found if you run `ng build --prod` then `ng test` the tests all fail , presumably due to tree shaking. I suggest we do as i had suggested at one point and run both (even though its slower)..

`ng build --prod` // tests that prod build works
`ng build ` // build again for testing
`ng test` // run tests

**Comment by bthharper** [comment]
I'm surprised that running `ng build --prod` then `ng test` fails as running a test recompiles.  I've tried locally and it works for me.

**Comment by clepore** [comment]
Well when you run `--prod` it does the build and minifies/compiles it, but the tests don't really run against minified code.

**Comment by bthharper** [comment]
That's correct - if we add the `ng build --prod` step it will ensure we don't break other teams using that option but "should not" affect the unit testing (we obviously want that too).

**Comment by bthharper** [comment]
We can close this now #143 has been completed.
