### ISSUE TITLE
Swaplist: wrong id on the root element

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise-ng#970]
**Describe the bug**
I've tried to add the id to a swaplist component, but it wasn't applied to the root element

**To Reproduce**
1. Go to http://localhost:4200/ids-enterprise-ng-demo/swaplist
2. Open dev tools and locate the swaplist element
-> why does the root have soho-swaplist-0 ? Doesnt make sense

**Expected behavior**
It should be based on the input id same as the others and probably be id="<input id>-swaplist"

**Version**
- ids-enterprise-ng: 9.1.x

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/104483404-60283500-55c8-11eb-80fe-1bc375cd4944.png)
**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/swaplist/example-index.html
![image](https://user-images.githubusercontent.com/45757016/105687595-9acc8e80-5f33-11eb-9ca6-4df163b129bd.png)
