### ISSUE TITLE
SohoLookupComponent processValue() Regression

### ISSUE THREAD

**Issue by nbcp** [infor-design/enterprise-ng#972]
**Describe the bug**
A regression on processing object lookup value was introduced in this commit 5eec1d7
![image](https://user-images.githubusercontent.com/11013464/104671190-48f85d00-5718-11eb-812b-e7db9de49ed0.png)
This causes a problem when setting value in the lookup because any value will always be converted to an empty string.

**To Reproduce**
1. Go to any lookup demo
2. Call setValue() with SohoLookupChangeEvent with data as object 

**Expected behavior**
Value must be parsed properly from the event.

**Version**
- ids-enterprise-ng: latest

**Platform**
All

**Comment by volante007** [comment]
Not sure if related, but if the connected `[(ngModel)]` isn't set, the lookups will display `undefined` in the field as well.
![image](https://user-images.githubusercontent.com/1101770/104710999-143cd380-5721-11eb-978d-d0254ddc6968.png)
Should just be empty, right?

**Comment by pwpatton** [comment]
Well need this patched in 9.1.x

**Comment by tmcconechy** [comment]
Once the errors are fixed and i merge i'll copy it back there.
