### ISSUE TITLE
Rating: expose the val() method

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise-ng#981]
**Is your feature request related to a problem? Please describe.**
With the change to rating to allow stars to be unselected (https://github.com/infor-design/enterprise/issues/4571), we need a way to get the current value of the control. Exposing the val() method will allow this, and allow programmatic setting of the control as well.

**Describe the solution you'd like**
Expose the val() method from enterprise controls.

**Comment by vonnyw** [comment]
@tmcconechy Can this be patched in 4.36?

**Comment by tmcconechy** [comment]
ok it would be in 9.1.3 if it was to be patched since its just an NG change. But this almost seems like a feature

**Comment by vonnyw** [comment]
Yes, just an NG change, appreciate it if it can be in 9.1.3.

**Comment by tmcconechy** [comment]
OK 9.1.3 is done https://www.npmjs.com/package/ids-enterprise-ng/v/9.1.3
