### ISSUE TITLE
General: Project doesn't work for a certain set of configurations

### ISSUE THREAD

**Issue by Amiin29** [infor-design/enterprise-ng#995]
I have tried several times to run this project but still get an error, I have installed all the packages you published give me the detail steps for running this project  I want your help please

**Comment by tmcconechy** [comment]
Sure ping me on MS Teams with the info (Tim McConechy in there). Would be easier going back and forth there. 
Can also joing this channel https://teams.microsoft.com/l/team/19%3a2b0c9ce520b0481a9ce115f0ca4a326f%40thread.skype/conversations?groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&tenantId=457d5685-0467-4d05-b23b-8f817adda47c

See also https://github.com/infor-design/enterprise-ng/blob/master/docs/DEVELOPER.md#enterprise-components-for-angular-development-environment

The usual most common problem is at the moment everything (all dependencies) only work with node 12. So make sure you are running node 12 as a version.

**Comment by tmcconechy** [comment]
Closing this support issue reach out on teams if you still need help there.. Or go ahead and ask

**Comment by Amiin29** [comment]
Thanks i fixed this issue
