### ISSUE TITLE
Multiselectable: Popup Toggle Issue

### ISSUE THREAD

**Issue by crlang44** [infor-design/enterprise-ng#998]
**Describe the bug**
Clicking the checkbox in a multi-select popup menu stops working after a couple times toggling it.

**To Reproduce**
1. Go to ids-enterprise-ng-demo/popupmenu
2. Right click on the input field under "Label"
3. Hover over the multiselectable option.
4. Toggle one of the options multiple times making sure to click on the actual checkbox and not the word.
5. After about 3 times, clicking the checkbox will no longer toggle the option.

**Expected behavior**
Clicking the checkbox should always toggle the option.

**Version**
- ids-enterprise-ng: 7.7.1 and 9.2.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/4143306/108782953-62fc3b00-7521-11eb-9388-018c0ed66f95.png)

![image](https://user-images.githubusercontent.com/4143306/108782963-668fc200-7521-11eb-8f99-e006a255a1de.png)

**Platform**
 - OS Version:Windows 10
 - Browser Name Chrome
 - Browser Version Version 88.0.4324.150 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
@crlang44 did you try a newer version? this issue is perhaps familiar

**Comment by crlang44** [comment]
Yep, tried it with the master branch. Version is 9.2.0-dev

**Comment by crlang44** [comment]
It works fine if you click the word portion of the option, but not the actual checkbox after a couple toggles.

**Comment by tmcconechy** [comment]
ok maybe an event handler in the wrong place?
